### ISSUE TITLE
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet:

### ISSUE THREAD

**Issue by damey2011** [carltongibson/django-filter#1001]
When we have a model that is extending another class for example:

`class ExtraMixin:`
`     is_head = models.BooleanField(default=False)`

`class Account(AbstractUser, ExtraMixin):`
`    email = models.EmailField(unique=True)`
`    date_of_birth = models.DateField(null=True, blank=True)`
`    sex = models.CharField(max_length=3, blank=True, null=True, choices=SEX)
`
This error is returned when 'is_head; is added to the Filterset class as a field

`TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: is_head`

But once you add 'is_head' to the main Account model, all works as expected

**Comment by rpkilby** [comment]
Hi @damey2011. I'm not 100% sure, but I don't think the `ExtraMixin` is valid. I believe you need to make it an abstract model like so:

```python
class ExtraMixin(models.Model):
    is_head = models.BooleanField(default=False)

    class Meta:
        abstract = True


class Account(AbstractUser, ExtraMixin):
    email = models.EmailField(unique=True)
    date_of_birth = models.DateField(null=True, blank=True)
    sex = models.CharField(max_length=3, blank=True, null=True, choices=SEX)
```

As an aside, use triple back ticks to block format your code. e.g., 


````
```python
class Foo(Bar):
    ...
```
````

**Comment by damey2011** [comment]
Haha.. @rpkilby Thanks for the heads up.
