### ISSUE TITLE
Use a certain lookup by default?

### ISSUE THREAD

**Issue by tiloc** [carltongibson/django-filter#1006]
Hi,

I have a field called 'code' in my model. Due to its semantics it makes sense to always use the 'istartswith' lookup on it. When I declare my FilterSet like this:
```python
class ObservationFilter(FilterSet):
    """Custom filters for observations"""
    class Meta:
        model = Observation
        fields = {
            'code': ['istartswith']
        }
```

I get a request parameter ```code__istartswith``` in DRF. Can I somehow tweak this thus that the name of the parameter is just ```code```, but it still uses ```istartswith``` semantics?

Thanks!

**Comment by rpkilby** [comment]
Hi @tiloc. I would recommend overriding `FilterSet.get_filter_name()`.

https://github.com/carltongibson/django-filter/blob/b813813b3d4f370de89c430b024342c03d0e4982/django_filters/filterset.py#L297-L311

**Comment by n2ygk** [comment]
Perhaps:

class ObservationFilter(FilterSet):
    """Custom filters for observations"""

    code = CharFilter(field_name=‘code’,lookup_expr=‘istartswith’)
    class Meta:
        model = Observation

**Comment by tiloc** [comment]
Thank you @rpkilby, that does exactly what I was looking for.
@n2ygk that was actually the route I originally tried, but I couldn't get it to work.

My code now looks like this:
```python
class ObservationFilter(FilterSet):
    """Custom filters for observations"""
    @classmethod 
    def get_filter_name(cls, field_name, lookup_expr):
        if field_name == 'code':
            return 'code'
        if field_name == 'interpretation':
            return 'interpretation'
        
        return super().get_filter_name(field_name, lookup_expr)


    class Meta:
        model = Observation
        fields = {
            'code': ['istartswith'],
            'effective_datetime': ['gte', 'lte', 'gt', 'lt'],
            'value_quantity_value': ['gte', 'lte', 'gt', 'lt'],
            'interpretation': ['icontains'], 
            'subject': ['exact']
        }
```

**Comment by n2ygk** [comment]
@tiloc Huh, I wonder what the problem is with my approach. I'm using it [here](https://github.com/columbia-it/django-jsonapi-training/blob/8a153689c0aa3fda3cb5ed8e68d6d933378a2412/myapp/views.py#L118-L138) and it seems to work:
```python
class InstructorFilterSet(filters.FilterSet):
    """
    :py:class:`django_filters.rest_framework.FilterSet` for the Instructor model
    """
    # A filter "alias" for a chained search from instructor->course_term->course:
    # There does not appear to be a way to supply a list of `lookup_expr`'s as is allowed with the `fields` dict.
    #: `course_name` is an alias for the path `course_terms.course.course_name`
    course_name = filters.CharFilter(field_name="course_terms__course__course_name", lookup_expr="iexact")
    course_name__gt = filters.CharFilter(field_name="course_terms__course__course_name", lookup_expr="gt")
    course_name__gte = filters.CharFilter(field_name="course_terms__course__course_name", lookup_expr="gte")
    course_name__lt = filters.CharFilter(field_name="course_terms__course__course_name", lookup_expr="lt")
    course_name__lte = filters.CharFilter(field_name="course_terms__course__course_name", lookup_expr="lte")

    class Meta:
        usual_rels = ('exact', 'lt', 'gt', 'gte', 'lte')
        model = Instructor
        fields = {
            'id': usual_rels,
            'name': usual_rels,
        }
```

**Comment by tiloc** [comment]
@n2ygk I honestly don't know why I couldn't get it to work. I don't think there is anything wrong with your approach. I tried it before posting my Issue here and I failed. I tried overriding the get_filter_name and it worked. I might give it another shot, as I think yours has less code and is more declarative.
