### ISSUE TITLE
No warnings shown when using deprecated functionality

### ISSUE THREAD

**Issue by OskarPersson** [carltongibson/django-filter#1008]
I've setup a simple project based on the example described by Django Rest Framework (DRF) where I've added a `filter_class` and `detail_route` to the viewset:

```
# djangofilterwarn/urls.py

from django.conf.urls import url, include
from django.contrib.auth.models import User
from django_filters import rest_framework as filters
from rest_framework import decorators, serializers, viewsets, routers


class UserFilter(filters.FilterSet):
    class Meta:
        model = User
        fields = ['username']


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_class = UserFilter

    @decorators.detail_route()
    def foo(self, request, pk=None):
        pass

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]
```

When running `python -W once manage.py test` this should print a message warning me about `filter_class` being replaced by `filterset_class` but the only message I get is the DRF deprecation of `detail_route` being replaced by `action`:

```
python -W once manage.py test
Creating test database for alias 'default'...
/Users/Oskar/git/djangofilterwarn/djangofilterwarn/urls.py:26: PendingDeprecationWarning: `detail_route` is pending deprecation and will be removed in 3.10 in favor of `action`, which accepts a `detail` bool. Use `@action(detail=True)` instead.
  @decorators.detail_route()
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
```

I'm using Python 3.6.6 and the output of `pip freeze` is:
```
Django==1.11.16
django-filter==2.0.0
djangorestframework==3.8.2
pytz==2018.7
```

**Comment by carltongibson** [comment]
HI @OskarPersson. Yep. 

But it looks like such warnings should be raised: 

https://github.com/carltongibson/django-filter/blob/99ced9ce401f8e08f4ee89a4e1246253640e5b2f/tests/rest_framework/test_backends.py#L365-L382

Fancy digging in to see what's not quite as expected?

**Comment by OskarPersson** [comment]
I just investigated this some more and noticed that I had forgotten to add `filter_backends = (filters.DjangoFilterBackend,)` to my example (see the edit).

The warning now appear when that ViewSet is accessed but not like the warning from DRF which is generated during startup of either the server or test suite. I'm guessing this is because the `detail_route` decorator runs when the module is loaded by Python while the `ViewSet` is not.

**Comment by carltongibson** [comment]
Yes, the FilterSet is generated dynamically, so there's no real way to catch this. (Declare your FilterSets explicitly...) 

Thanks for the follow-up.
