### ISSUE TITLE
`[invalid_name]` displaying when not filtering on a model field

### ISSUE THREAD

**Issue by knyghty** [carltongibson/django-filter#1009]
I'm not sure if this is a bug report or a feature request.

If I have a field that doesn't correspond to a field on the model (filters multiple fields, etc.), the label defaults to `[invalid_name]`. It seems like it'd be nicer if it defaulted to the field name or something similar?

Works fine:
```python
status = django_filters.ChoiceFilter(
    label='Status',
    method='filter_status',
    choices=STATUS_CHOICES,
)
```

`[invalid_name]`:
```python
status = django_filters.ChoiceFilter(method='filter_status', choices=STATUS_CHOICES)
```

Also `[invalid_name]`:
```python
status = django_filters.ChoiceFilter(
    field_name='status',
    method='filter_status',
    choices=STATUS_CHOICES,
)
```

**Comment by rpkilby** [comment]
Hi @knyghty. Thanks for raising the issue. Form labels are automatically generated from the model field name. However, if the filter doesn't point to a valid model field, it complains about not being able to generate a name. 

That said, there should probably be two changes here:
- `[invalid_name]` doesn't really tell the user anything other than "something is wrong". There might be a better value that provides more context.
- We could try to use the attribute name for declared filters. Not sure if this is possible - we would need to distinguish declared vs generated filters.

**Comment by rpkilby** [comment]
Yes, if you explicitly provide the label for your declared filter, then there shouldn't be an issue.

**Comment by danihodovic** [comment]
That solves my problem. Thanks @rpkilby !
