### ISSUE TITLE
ImportError: cannot import name 'STRICTNESS'

### ISSUE THREAD

**Issue by dorokhin** [carltongibson/django-filter#1015]
There is mistake on [doc page ](https://django-filter.readthedocs.io/en/stable/ref/filterset.html#handling-validation-errors-with-strict) 

Section: **Handling validation errors with strict**

ImportError: cannot import name 'STRICTNESS' from 'django_filters'

**Comment by rpkilby** [comment]
Hi @dorokhin, the stable docs are out of date and aren't even listed in the RTD versions. I've noticed people linking to these docs. How did you get there? You should be looking at the master or 1.1.0 docs instead.

**Comment by dorokhin** [comment]
Ok, thank's @rpkilby 
This links from Google
