### ISSUE TITLE
Search Inside the jsonField

### ISSUE THREAD

**Issue by nikolas310** [carltongibson/django-filter#1032]
I've a jsonfield with data like {"amount": 20000}. 

```
class ApplicationFilter(filters.FilterSet):
    FILTER_DEFAULTS = deepcopy(filterset.FILTER_FOR_DBFIELD_DEFAULTS)
    FILTER_DEFAULTS.update({
        JSONField: {
            'filter_class': CharFilter,
            'extra': lambda f: {'lookup_choices': ['icontains']},
        },
    })
```
works fine with exact amount. But problem is when I use gte, gt, lte or lt. How to query inside json object

**Comment by mgaby25** [comment]
You cannot use gte, gt, lte or lt with json field unless you cast those values before and annotate the queryset. You'll need a custom method to do the filtering, try the following:


    from django.contrib.postgres.fields.jsonb import KeyTextTransform
    from django.db.models import IntegerField
    from django.db.models.functions import Cast

    class ApplicationFilter(FilterSet):
        ammount__gte = filters.NumberFilter(field_name='your_json_field', method='filter_ammount__gte')
        
        class Meta:
            model = YourModel
            fields = ['ammount__gte']

    def filter_ammount__gte(self, queryset, name, value):
        if value:
            queryset = queryset.annotate(ammount=Cast(KeyTextTransform('ammount', 'your_json_field'), IntegerField()))
            return queryset.filter(ammount__gte=value)
        return queryset

**Comment by nikolas310** [comment]
Thanks. Working
