### ISSUE TITLE
Add DateTimeFromToRangeFilter to Migration Guide

### ISSUE THREAD

**Issue by Uxio0** [carltongibson/django-filter#1037]
I went through the migration guide to update `django-filters` from v1 to v2, but the case of `DateTimeFromToRangeFilter` was not documented, lucky I found that during testing.

I realized that previously in the query strings the datetimes were expected to end on `_0` and `_1`, while on the new version `_after` and `_before` was expected.

I know that there's a hint that says `MultiWidget replaced by SuffixedMultiWidget`, but I think it doesn't make obvious that some fields were affected.

Thanks for the amazing work you do with this library

**Comment by carltongibson** [comment]
Hey @Uxio0. Fancy making a quick PR for that change whilst it's fresh in your mind? Ta.

**Comment by Uxio0** [comment]
@carltongibson Done :wink:
