### ISSUE TITLE
LookupChoiceFilter lookup missing from API schema

### ISSUE THREAD

**Issue by dms-cat** [carltongibson/django-filter#1040]
## How to reproduce

Create a filter class with *either* a filter like `code = filters.LookupChoiceFilter(field_name='code', lookup_choices=[('exact', 'Equals'), ('contains', 'Contains')])` *or* declare `Meta.fields` as a `dict` containing `'code': ['exact', 'contains']`.

## What should happen?

The generated API schema should contain the relevant fields for requesting either an exact or substring match.

## What happens instead?

Only the `code` field (no suffix or `code_lookup`) is in the generated API schema. I therefore don't see this parameter in the drf-yasg API explorer, and I get the following error message when trying to GET with `code`:

```json
{
  "code": [
    "Select a lookup."
  ]
}
```

## Additional information

Constructing the filter class with `data={'code': 'some code'}` or  `data={'code__contains': 'some substring'}` (without `code_lookup`) work fine and return the expected object. Which indicates that testing the filter class directly may not be viable, because additional validation of the input happens somewhere else.

Using django-filter 2.1.0 from PyPI.

**Comment by dms-cat** [comment]
There must have been something else at play, because after cleaning up all the filters I now get `__contains` filters in the API explorer.

**Comment by rpkilby** [comment]
Hi @dms-cat. `Meta.fields` has a different result from `LookupChoiceFilter`. The former generates individual filters per lookup (in your case, you will have distinct `code` and `code__contains` filters, and both of these will show up in the API explorer. The latter is a just *single* filter that expects both a value and lookup expression to be provided. e.g., its querystring would look like:
```
?code=foo&code__lookup=contains
```

The reason `code__lookup` doesn't show up in the API explorer is that there is a general incompatibility between Core API schemas and the `MultiWidget`-based filters. I've detailed it more in #819, but the gist is that a single filter logically maps to a single Core API field, however `LookupChoiceFilter` uses multiple query params, and Core API has no mechanism to support this. Mapping to multiple Core API fields seems like it could work, however there are unresolvable issues with validation errors. e.g., an error for `code__lookup` would actually be raised for `code`, which would be confusing to the user.
