### ISSUE TITLE
Inconsistent behavior of filter_overrides - it's not possible to override ChoiceFilter

### ISSUE THREAD

**Issue by ckrybus** [carltongibson/django-filter#1046]
In the filter_for_lookup method one can use a custom filter_class by specifying [filter_overrides](https://django-filter.readthedocs.io/en/master/ref/filterset.html\#filter-overrides), this works for most fields. But when one tries to override a field which uses choices and has a lookup_type=exact the custom filter_class read from filter_overrides is never being used, instead filter_for_lookup() always returns ChoiceFilter.

```
    @classmethod
    def filter_for_lookup(cls, field, lookup_type):
        DEFAULTS = dict(cls.FILTER_DEFAULTS)
        if hasattr(cls, '_meta'):
            DEFAULTS.update(cls._meta.filter_overrides)

        data = try_dbfield(DEFAULTS.get, field.__class__) or {}
        filter_class = data.get('filter_class')
        params = data.get('extra', lambda field: {})(field)

       # (...)

        # perform lookup specific checks
        if lookup_type == 'exact' and getattr(field, 'choices', None):  # ---> filter_class is not being used here
            return ChoiceFilter, {'choices': field.choices}

        if lookup_type == 'isnull':
            data = try_dbfield(DEFAULTS.get, models.BooleanField)
            filter_class = data.get('filter_class')
            params = data.get('extra', lambda field: {})(field)
            return filter_class, params

```
I know it is possible to overwrite filter_for_lookup(), the docs even [say so](https://django-filter.readthedocs.io/en/master/ref/filterset.html#filter-for-lookup), but I think the filter override functionality should behave consistently. Also silently ignoring the override is probably not the best user experience.

Any thoughts? I would create a pull request, but in this case I'm not sure if the code behavior is intended or not and what the correct solution is. I personally tend to think that making the override behavior consistent is the best option.

**Comment by carltongibson** [comment]
Meh... this code has been the same in essence for many years... it’s almost certain that whatever complication you want to add to other filters to handle choices isn’t worth the effort. I.e just override filter_for_lookup() as you say. 

But... you’re welcome to present a proposal. 🙂

At this moment I can’t quite see what you’re wanting to do but can’t. So I’d start there. Then I’d show the proposed changes.

**Comment by ckrybus** [comment]
This is definitely a bug, albeit small and maybe insignificant one. Since I don't have a use case right now I'll drop it. I looked a little into it and as you said fixing it would add additional complexity and it's probably not worth it.
