### ISSUE TITLE
QueryArrayWidget mutates passed data

### ISSUE THREAD

**Issue by agateblue** [carltongibson/django-filter#1047]
I think I've faced a small issue with the `QueryArrayWidget`, especially with this line: https://github.com/carltongibson/django-filter/blob/master/django_filters/widgets.py#L242, as described below:

```python
class QueryArrayWidget(BaseCSVWidget, forms.TextInput):

    def value_from_datadict(self, data, files, name):
        if not isinstance(data, MultiValueDict):
            for key, value in data.items():
                # treat value as csv string: ?foo=1,2
                if isinstance(value, str):
                    data[key] = [x.strip() for x in value.rstrip(',').split(',') if x]
```

The last line of this snippet will mutate the initial QueryDict, which can have unforeseen consequences. An easy fix could be to simply create a new dict and I can provide a PR with that if we agree on a fix :)

Edit: temporary workaround in my project is to subclass like that:

```python
class QueryArrayWidget(widgets.QueryArrayWidget):
    """
    Until https://github.com/carltongibson/django-filter/issues/1047 is fixed
    """

    def value_from_datadict(self, data, files, name):
        data = data.copy()
        return super().value_from_datadict(data, files, name)
```

**Comment by carltongibson** [comment]
OK, quickest possible scan, but yes, that looks right. `data` here is `request.GET` yes?

**Comment by EliotBerriot** [comment]
Yes, that's basically what's passed when instanciating a django form, so typically `request.GET` or `request.POST` if I understand correctly :)

**Comment by carltongibson** [comment]
OK. I can't quite swing my head round instantly to thinking what happens if you try and mutate those, but, regardless, it doesn't sound like a good idea, so yes PR sounds good. 

Thanks. 👍

**Comment by rpkilby** [comment]
I'm confused by the `if not isinstance(data, MultiValueDict):` line. `request.GET`/`request.POST` are `QueryDict`s, which inherit `MultiValueDict`. When would this condition ever be triggered?

**Comment by EliotBerriot** [comment]
> OK. I can't quite swing my head round instantly to thinking what happens if you try and mutate those, but, regardless, it doesn't sound like a good idea, so yes PR sounds good.

basically, if you're using this widget in a form (or filterset) and this method is called before other widget's `value_from_datadict`, they will end up with lists of values instead of simple values to clean, which cause all kinds of unexpected crashes.

I'll submit a PR then :)

**Comment by AMontagu** [comment]
@carltongibson can we help on this one with a merge request or something?

**Comment by carltongibson** [comment]
@AMontagu Yes, thanks.

**Comment by AMontagu** [comment]
@carltongibson someone in my team took it and made a PR.

**Comment by carltongibson** [comment]
@AMontagu Great thanks. It's in my queue! 🎁
