### ISSUE TITLE
KeyError exception for every field which is not in the fields list

### ISSUE THREAD

**Issue by ksantr** [carltongibson/django-filter#1057]
This is a simple example.
My model has three fields: login, group and name. Any field that is not in the fields list raises the KeyError exception.

class MyFilter(FilterSet):
    class Meta:
        model = Mymodel
        fields = ['group', 'name']

WARNING:root:Could not resolve form field 'login'.
Traceback (most recent call last):
  File "/home/venv/lib/python3.6/site-packages/django/forms/forms.py", line 163, in __getitem__
    field = self.fields[name]
KeyError: "Key 'login' not found in 'MyFilterForm'. Choices are: 'group', 'name'"

**Comment by ksantr** [comment]
Version 2.1.0

**Comment by ksantr** [comment]
Also there is a problem to retrieve related models. ex, manufacturer__name

**Comment by rpkilby** [comment]
Hi @ksantr - can you provide a more complete example/test case? django-filter is tested pretty extensively, and theses are common uses that would likely have been caught by the test suite.

**Comment by Deus-Rex** [comment]
Unsure if this warrants a new issue, but I've come across this as well. I'll briefly explain my use case.

I am replacing an existing view with a FilterView, and using its form to render the filters on my template. I'm also implementing it with pagination, and require allowing the user to have the option of changing the number of items displayed on the page.

It made sense to just add it as a field to the form I have defined in the filterset, and handle the forms pagination input in Django's list view helper method. However, this is where the keyerror is raised.

Thankfully it can be resolved by overriding the  `BaseFilterSet.filter_queryset` method and change `self.filters[name]` to use `.get(name)` instead with a case of continuing if it doesn't exist.

It would be nice if it was as simple as setting a flag, though I think I've been spoiled by the simpleness of Django's generic views too much and feel it tough to separate them.
