### ISSUE TITLE
DRF: document that filterset_class is now filter_class

### ISSUE THREAD

**Issue by fpghost** [carltongibson/django-filter#1067]
Could you please document that for DRF `filterset_class` is actually now called `filter_class`.

Currently [the docs](https://django-filter.readthedocs.io/en/master/guide/rest_framework.html#adding-a-filterset-with-filterset-class) suggest `filterset_class`, but actually 

```
from django_filters import rest_framework as filters

class AgentListViewSet(viewsets.ModelViewSet):
    filter_backends = (filters.DjangoFilterBackend, )
    filter_class = UserFilter
```

is what works.

**Comment by carltongibson** [comment]
It really is `filterset_class`. 

https://github.com/carltongibson/django-filter/blob/81ad70d6dd6f0e427ffc0a99633ef9024d04e277/django_filters/rest_framework/backends.py#L38-L57

Those TODOs and the shims probably need removing by now.

**Comment by carltongibson** [comment]
See #867.

**Comment by rpkilby** [comment]
I don't understand why this issue keeps coming up. DRF used to have the outdated attribute names, but those docs have been updated.

**Comment by tysonclugg** [comment]
@rpkilby 
> I don't understand why this issue keeps coming up. DRF used to have the outdated attribute names, but those docs have been updated.

This issue keeps coming up because there are still references to `filter_class` in the 3.3.1 and 3.3.2 release notes with no deprecation notice given in the same document.  This may lead some to believe that `filter_class` has not actually been deprecated:
https://www.django-rest-framework.org/community/release-notes/

Many of us make reference the relevant section of the release notes when submitting pull requests to make the switch in dependent code, if the deprecation isn't "official" (ie: specifically mentioned in the release notes) it can be hard to have the PR accepted.

**Comment by RomainFayolle** [comment]
Upgraded recently from :

- Django `3.2.9` to `4.2.5`
- `djangorestframework` `3.12.4` to `3.14.0` 
- `django-filter` `21.3` to `23.3`

There was no warning about `filter_class` becoming `filterset_class` (I used the command `python3 -Wa manage.py test`) and no errors in the views. I agree that I should have had a test on the filters but still. Easy to find, easy to fix but a bit annoying to discover !

**Comment by alenpaulvarghese** [comment]
Done some migrations for our Django app (drf 3.11.2 -> 3.14.* )

I haven't seen any mention of the change in the release notes, so it broke the filtering logic.

Did I miss something or is it worth mentioning?

**Comment by Yassine-Latreche** [comment]
> Done some migrations for our Django app (drf 3.11.2 -> 3.14.* )
> 
> I haven't seen any mention of the change in the release notes, so it broke the filtering logic.
> 
> Did I miss something or is it worth mentioning?

same here

**Comment by ivall** [comment]
I migrated to the new Django & DRF version, and the entire filter system broke down, causing significant system interruptions. I believe this should definitely be mentioned in the release notes.
