### ISSUE TITLE
ModelChoiceFilter doesn't support empty value

### ISSUE THREAD

**Issue by arielpontes** [carltongibson/django-filter#1068]
Let's say I have the following models:

```
class User(models.Model):
    name = models.CharField()

class Post(models.Model):
    text = models.TextField()
    author = models.ForeignKey(User)

class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey(User, related_name='comments')
    post = models.ForeignKey(Post, related_name='comments')
```

If I want to filter the user list so that I can see all users that commented on a given post, I can do:

    post = filters.ModelChoiceFilter(
        field_name='comments__post',
        queryset=Post.objects.all()
    )

However, if I want to filter the user list to get all users who have NOT commented on ANY post, passing `null` or empty string doesn't work. I couldn't find any solution in the documentation. Am I missing something? If this really isn't possible, it would be a nice feature to have. For the moment the only solution I see is to use a custom method and renounce on the `ModelChoiceFilter` altogether.

**Comment by rpkilby** [comment]
Hi @arielpontes. `ModelChoiceFilter` extends `ChoiceFilter`, which has options that enable filtering by null values. You can either enable this feature globally for all choice filters via settings, or you can enable it for a specific filter through its own arguments (see: [filter reference](https://django-filter.readthedocs.io/en/master/ref/filters.html#choicefilter)).

**Comment by rpkilby** [comment]
That said, you might also consider using a boolean filter with a custom filter method. e.g., 

```python
class UserFilter(FilterSet):
    has_commented = filters.BooleanFilter(method='filter_has_commented')

    def filter_has_commented(self, qs, name, value):
        return qs.filter(comments__isnull=not value)
```

aside - it shouldn't be necessary to filter through the post relation, since it looks like a user can't create a comment without it being related to a post.

**Comment by arielpontes** [comment]
Hi, I tried using the `null_value` parameter but it simply didn't work. It had no effect at all. The `BooleanFilter` doesn't solve my problem because, as I've mentioned, I want to make a request like: 

    /users/?has_commented_on_post=12

And I want as a result a list of all users who have commented on the post with id 12, and I want to be able to do a request like:

    /users/?has_commented_on_post=null

I tried this:

```
has_commented_on_post = filters.ModelChoiceFilter(
    field_name='comments__post',
    null_value='null',
    queryset=Post.objects.all()
)
```

But it didn't work. As for your comment about it being unnecessary to go through the post relationship, that is just not true. I need to filter users by post id _via comments_. If I filter the user by post id directly I'll get a list with a single user: the author of the post. But I want a list of users who commented on that post. I probably wasn't very clear when I first described the issue. I hope it's clearer now :)

**Comment by rpkilby** [comment]
Maybe the docs could be more clear, but you need to set `null_label` (`null_value` already defaults to `null`). `empty_label` and `null_label` control whether their respective empty/null choices are made available.

**Comment by rpkilby** [comment]
> As for your comment about it being unnecessary to go through the post relationship, that is just not true.

Sorry -  was focusing on solving this:

> However, if I want to filter the user list to get all users who have NOT commented on ANY post

My suggestion for a boolean filter was for filtering for users that hadn't commented. In this case, it isn't necessary to go through the post relationship. Obviously, if you're trying to find if a user has commented on a specific post, you'll need to join on the post relationship.
