### ISSUE TITLE
rename fields' name

### ISSUE THREAD

**Issue by kiarashplusplus** [carltongibson/django-filter#107]
I couldn't find a way to rename a field inside the Filterset. I'd rather not to change my original models and I don't want the user to the see the original name. I have something like 'file__pretty_upload_time' which I want to replace with say 'time'

Any thoughts?

**Comment by eduardocalil** [comment]
But, what if I didn't want to set this in form field. I've declared my filters only in Meta fields, for optimization. How can I change these labels?

**Comment by rpkilby** [comment]
@eduardocalil - there aren't any Meta options for modifying the attributes of the generated filters. However, the FilterSet behaves similarly to model forms and should be modifiable in similar ways. Some possibilities:

modify the class's `base_filters`
```py
class ArticleFilter(FilterSet):
    class Meta:
        model = models.Article
        fields = {'author': ['exact', 'in', 'isnull']}

ArticleFilter.base_filters['author'].label = 'Author Exact Lookup'
ArticleFilter.base_filters['author__in'].label = 'Author In Lookup'
```

Customize via `__init__`
```py
class ArticleFilter(FilterSet):
    def __init__(self, *args, **kwargs):
        super(ArticleFilter, self).__init__(*args, **kwargs)
        self.filters['author'].label = 'Author Exact Lookup'
        self.filters['author__in'].label = 'Author In Lookup'

    class Meta:
        model = models.Article
        fields = {'author': ['exact', 'in', 'isnull']}


```

**Comment by carltongibson** [comment]
... By which time you'd be better off using the explicit declaration... :-)

**Comment by rpkilby** [comment]
@carltongibson should there be `label`, `help_text`, etc... meta options, similar to `ModelForm`s?

**Comment by ad-m** [comment]
@rpkilby , why? ```self.filters['author__in'].field.help_text``` etc. you can use I believe.

**Comment by rpkilby** [comment]
For the same reason Django added the meta options to their model forms - it's a cleaner way to customize auto-generated filters without having to override inside the `__init__`.

It doesn't particularly matter to me either way, since I don't typically display the form.

**Comment by carltongibson** [comment]
> @carltongibson should there be label, help_text, etc... meta options, similar to ModelForms?

No. 

> There should be one-- and preferably only one --obvious way to do it.

That way is to explicit declare the filter attributes, where extra kwargs will be passed to the form field. 

The whole meta fields thing is just a shortcut. As soon as it's not enough for you, switch.

**Comment by eduardocalil** [comment]
Thank you very much, @carltongibson and @rpkilby for the fast answer! You've just saved my work :D

**Comment by eduardocalil** [comment]
Giving real examples is a great way to help .
