### ISSUE TITLE
through m2m filter

### ISSUE THREAD

**Issue by Zverushko** [carltongibson/django-filter#1073]
hi!
i have models:

    class Product(model.Model):
        attributes = models.ManyToManyField(Attribute, through='ProductAttribute')`

    class ProductAttribute(Base):
        product = models.ForeignKey(Product, on_delete=models.CASCADE)
        attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
        value = models.CharField(max_length=255)

and filter class:

    class ProductFilter(django_filters.FilterSet):
       class Meta:
            model = Product
            fields = ['attributes_set_value']`

i have error:
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: attributes_set__value

how i can use ProductAttribute__value for filter?
thx!

**Comment by rpkilby** [comment]
`attributes_set` is not the name of the model field. It should be `attributes__value`. Also, note the use of the double underscore.
