### ISSUE TITLE
Adding generic filter to DRF pre-filtered queryset

### ISSUE THREAD

**Issue by ggjersund** [carltongibson/django-filter#1091]
For some weird reason I can't pre-filter my queryset in the `get_queryset(self)` function. `DjangoFilterBackend` seemes to only accept in my case `return Project.objects.all()` instead of some `return Project.objects.filter(company='<some company>')`.

Is this documented somehow or is it a bug?

**UPDATE**:
It seemes that filters directly related to the model, such as `return Project.objects.filter(number=1)` works, but `return Project.objects.filter(company__owner=self.request.user)` does not.

**UPDATE 2**:
Boiled the problem down to using `self.request.user`as `return Project.objects.filter(company__owner=1)` works. Any ideas?

**UPDATE 3**:
Yupp, somehow `django-filter` hates `self.request.user`.
```
user = self.request.user
return Project.objects.filter(company__administrators__user=1)
```
wont work, however this (commenting out) will
```
#user = self.request.user
return Project.objects.filter(company__administrators__user=1)
```

**Comment by ggjersund** [comment]
Found out it works, but is not properly generated in the automatic schemas.

**Comment by rpkilby** [comment]
The [schema generation docs](https://django-filter.readthedocs.io/en/master/guide/rest_framework.html#schema-generation-with-core-api) kind of hint at this in regards to args/kwargs, but they don't explain what this means for the request object. Also, I assume you're getting a warning in your log ouput?

https://github.com/carltongibson/django-filter/blob/7c08deea132686f456df8a646a9c65654cee2712/django_filters/rest_framework/backends.py#L127-L129

**Comment by ggjersund** [comment]
I got no warning or output. It simply didn't appear in the schema. Decided to roll with my own custom filter in the end.
