### ISSUE TITLE
Dynammic lookup dropdown filters

### ISSUE THREAD

**Issue by dan-developer** [carltongibson/django-filter#1094]
It is possible to render forms with lookups in a dropdown for the user to select as in the attached example?
If it is not possible, please tell me where I can customize how form is rendered that I will send a pull request with this feature.
This is very important for business applications.
![B4A59363-1AA9-4B74-8E10-177A512FC620](https://user-images.githubusercontent.com/10473169/60751948-e3f57000-9f94-11e9-8e1d-ccf6a03fd657.png)
![2E91793A-DD43-4EC3-ABBE-A0A6F0AC91E2](https://user-images.githubusercontent.com/10473169/60751949-e3f57000-9f94-11e9-8342-f3f213d53327.jpeg)

**Comment by rpkilby** [comment]
Hi @AndersonDan, you're probably looking for the [`LookupChoiceFilter`](https://django-filter.readthedocs.io/en/master/ref/filters.html#lookupchoicefilter). It renders two inputs - one for the value, one for the lookup. As to customizing the form, there is the [`Meta.form`](https://django-filter.readthedocs.io/en/master/ref/filterset.html#form) options which accepts a `Form` subclass.

**Comment by AndersonDan** [comment]
Obrigado pela resposta rápida, senhor.

Realmente me passou despercebido isso.
