### ISSUE TITLE
_meta error with DRF package.

### ISSUE THREAD

**Issue by VasiliyRusin** [carltongibson/django-filter#1099]
### UPD. I have an error even if I use filters.FilterSet (for DRF).
Remove Meta class is only one way to solve this problem.
___

So if I have a class with two inheritance it will raise an error: 
`AttributeError: 'tuple' object has no attribute '_meta'`

filters.py

```
class IdFilter(filters.FilterSet):
    class Meta:
        fields = ['id']

    id = filters.NumberFilter()


class NameFilter(filters.FilterSet):
    class Meta:
        fields = ['name']

    name = filters.CharFilter(lookup_expr='icontains')


class GenreFilter(IdFilter, NameFilter):
    class Meta:
        model = Genre,
        fields = ['id', 'name']
```

As far as I remember non-DRF version works correctly.

**Comment by rpkilby** [comment]
Hi @VasiliyRusin. The issue is in your `GenreFilter` declaration.

```python
class GenreFilter(IdFilter, NameFilter):
    class Meta:
        model = Genre,    # <---- the comma turns this into a one element tuple
        fields = ['id', 'name']
```

**Comment by VasiliyRusin** [comment]
@rpkilby Oh... I'm really sorry for this issue. It was really stupid.

**Comment by rpkilby** [comment]
No worries. It's a very easy mistake to make.
