### ISSUE TITLE
choices for BooleanFilter fields

### ISSUE THREAD

**Issue by amenasse** [carltongibson/django-filter#11]
Hi Alex,

I am trying to assign custom choices to a BooleanNullFilter, by default the options displayed on the form field are Yes,No and Unknown however this doesn't suit my application.

Heres my model and filter:

Model

<pre><code>
class Feedback(models.Model):
  
  feedback = models.TextField(blank=True)
  addressed = models.BooleanField(default=False)
</code></pre>

Filter

<pre><code>
# uses the BooleanNullFilter by default 

class FeedbackFilter(filter.FilterSet):
  
  class Meta:
    model = Feedback
    fields = ['addressed']
</code></pre>

I tried changing the widget to one that would allow me to specify choices , this displays fine but doesn't perform the filtering :

<pre><code>
ADDRESSED_CHOICES = (
    (True,'Adressed'),
    (False,'Not Addressed'),
    (None,'Any'),
)

class FeedbackFilter(filter.FilterSet):
  
  addressed =  filter.ChoiceFilter(choices=ADDRESSED_CHOICES,label='Status')

  class Meta:
    model = Feedback
    fields = ['addressed']
</code></pre>

I also tried using a different widget, however this throws an exception:

<pre><code>
class FeedbackFilter(filter.FilterSet):
  
  addressed = filter.BooleanFilter(widget=forms.Select,choices=ADDRESSED_CHOICES,label='Status')
.
.
</code></pre>

Result:

<pre><code>
Traceback:
File "/home/anthony/lib/python2.5/django/core/handlers/base.py" in get_response
  92.                 response = callback(request, *callback_args, **callback_kwargs)
File "/home/anthony/src/ams/trunk/src/ams/browse/views.py" in common_detail
  23.     feedback_list = feedback_set.qs
File "/home/anthony/src/django-filter/filter/filterset.py" in qs
  196.                     val = self.form.fields[name].clean(self.form[name].data)
File "/home/anthony/src/django-filter/filter/filterset.py" in form
  213.             fields = SortedDict([(name, filter_.field) for name, filter_ in self.filters.iteritems()])
File "/home/anthony/src/django-filter/filter/filters.py" in field
  50.                     widget=self.widget, **self.extra)

Exception Type: TypeError at /browse/shots/1/
Exception Value: __init__() got an unexpected keyword argument 'choices'
</code></pre>

I expected this to work since the Select widget requires a choices argument.

I was wondering if you could offer any advice on how to get this behaviour to work without having to change my model.

Thanks
Anthony

**Comment by wimfeijen** [comment]
Adding a reference to: https://code.djangoproject.com/ticket/23681#comment:5 ,

which addresses this issue as well, and explains where the Unknown, Yes and No come from, and gives another method to overwrite the widget (which will be easier when a patch for the ticket has been made and integrated into django)
