### ISSUE TITLE
The filter seems dosen't work on the queryset generated by union operation

### ISSUE THREAD

**Issue by rootgrandfather** [carltongibson/django-filter#1102]
1. What's the ORM query you want to perform?

  ```python
  # views.py
  class ArticlesListViewSet(viewsets.GenericViewSet, mixins.ListModelMixin):
      filter_backends = (DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter)
      filter_class = ArticlesFilter
  
      def get_queryset(self):
          docs,blogs=get_articles_objects()
          if self.request.user.is_superuser:
              return docs.union(blogs).all()
          else:
              filter_docs = docs.filter(Q(docsinfo__status__in=[DocsStatus.normal.value, DocsStatus.convert_fail.value]))
              filter_blogs = blogs.filter(Q(blogsinfo__status__in=[BlogsStatus.normal.value]))
              return filter_docs.union(filter_blogs).all()
  ```

  ```python
  # filters.py
  class ArticlesFilter(django_filters.rest_framework.FilterSet):
      category=django_filters.NumberFilter(method='category_filter')
      def category_filter(self, queryset, name, value):
       	return queryset.filter(category__id=value)
  ```

  I want to apply the filter on the queryset generated by get_queryset()

2. What have you tried?

   I tried to apply the category_filter on the queryset,but it dosen't work.

3. What result do you see?

   It dosen't work,I want the filtered queryset.

**Comment by carltongibson** [comment]
> It dosen't work...

But what actually happens? (If you want help you have to give us a chance...) 

This is a usage question, not an issue, so I'm going to close it. Please don't open a new issue. Just reply here. 🙂

**Comment by rootgrandfather** [comment]
Ok,I know.But could you give me sone suggestions on how to apply django-filter on the union queryset?Thank you.😸

**Comment by carltongibson** [comment]
You filter querysets exactly as you would otherwise. There's nothing special about `union()`. That's why I want to see the result you're getting. (A traceback maybe...) 

(What's the `name` parameter? What is `value` when your `method` is called? ...)

**Comment by rootgrandfather** [comment]
Ok,when I go back,I'll show you the details.In django,filter() function dosen't work after a union() like this situation:a.union(b).all().filter().And that even dosen't raise an exception,the filter() just return the original union queryset.So in the django-filter,the filter receives the union queryset and use filter() to handle the queryset further ,but also return the original union queryset,the filter condition can't work.So is there a solution of django-filter to solve the problem?

**Comment by rootgrandfather** [comment]
**### The name and value parameter**:
![Snipaste_2019-07-12_19-34-06](https://user-images.githubusercontent.com/30030633/61125594-cc5e4000-a4dc-11e9-8b64-007f29f8f957.png)
**### The final SQL command**:
![Snipaste_2019-07-12_19-35-02](https://user-images.githubusercontent.com/30030633/61125630-eac43b80-a4dc-11e9-8516-0eb6fe8836d4.png)
**### The result:**
![Snipaste_2019-07-12_19-32-17](https://user-images.githubusercontent.com/30030633/61125664-ffa0cf00-a4dc-11e9-892f-271e88528562.png)

**Comment by carltongibson** [comment]
Ah, sorry, I understand. This is a limitation on `union()`. Nothing to do with django-filter. 

[From the docs](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.union): 

> In addition, only LIMIT, OFFSET, COUNT(*), ORDER BY, and specifying columns (i.e. slicing, count(), order_by(), and values()/values_list()) are allowed on the resulting QuerySet.

i.e. `filter()` isn't supported. 

([There's a suggestion to raise a suitable error message](https://code.djangoproject.com/ticket/27995). )

**Comment by rootgrandfather** [comment]
Ok,that may be a drawback of django.I finally can't find a suitable solution.

**Comment by carltongibson** [comment]
I'm guess you could generate the same QuerySet without using `union()`. (They're both _types_ of `Article` it looks like...

```
Article.objecs.filter(Q(type='blog') | Q(type='doc')...
```

But you'll need to work it out yourself. Good luck.

**Comment by rootgrandfather** [comment]
Thanks,but actually doc and blog are different tables,they have different fields,when I union the two table,I use annotate() to add extra columns to make them the same column types.I do so just for the extensibility of the system.Then in such condition,what better solution can I try?😭

**Comment by rootgrandfather** [comment]
Ok,thanks.I'll try that.
