### ISSUE TITLE
Improve introspection of models in `DjangoFilterBackend.get_coreschema_field`

### ISSUE THREAD

**Issue by thismatters** [carltongibson/django-filter#1104]
Hi, I'm new to using `django-filter` (2.1.0) and so far I really like it and find it quite flexible; thank you for writing it! I have run into a small problem though. I'm following the documentation about integrating with DRF. I'm using a `FilterSet` as so:

```python
class CIAttributeDefinitionFilter(filters.FilterSet):
    ci_type_name = filters.CharFilter(field_name="ci_type", lookup_expr='name')
    ci_type_id = filters.NumberFilter(field_name="ci_type", lookup_expr='pk')

    class Meta:
        model = CIAttributeDefinition
        fields = [
            'name', 'data_type', 'multiple', 'required',
            'ci_type_name', 'ci_type_id', ]
```
The model looks like this:

```python
class CIAttributeDefinition(models.Model):
    name = models.CharField('Attribute Name', max_length=64, unique=True)
    ci_type = models.ForeignKey(
        CIType, related_name='_native_attributes', on_delete=models.CASCADE)
    data_type = models.CharField(
        'Attribute Data Type', max_length=8,
        choices=CIAttributeTypeEnum.choices())
    description = models.CharField('Attribute Description', max_length=140)
    default_value = models.ForeignKey(
        'CIAttribute', on_delete=models.SET_NULL, null=True, blank=True)
    multiple = models.BooleanField('Allow multiple values?', default=False)
    required = models.BooleanField(default=False)
```

This results in the following swagger documentation which shows all the named fields; however all but the `ci_type_id` parameter are listed as string parameters. The `coreschema` package has fields for [boolean](https://github.com/core-api/python-coreschema/blob/master/coreschema/schemas.py#L369) and [enum](https://github.com/core-api/python-coreschema/blob/master/coreschema/schemas.py#L369) data (among others). Has broader introspection for the purposes of documentation generation been considered and rejected in the past?

**Comment by Beatris** [comment]
+1 for this one. I have added the fields with the drf_yasg manual_parameters option but it would have been great to have them automatically detected.

**Comment by carltongibson** [comment]
As it stands the CoreSchema based stuff is unmaintained/deprecated. So there's no real chance of an addition. 

You could easily enough subclass the backend and override the relevant methods to produce richer introspection: 

https://github.com/carltongibson/django-filter/blob/79b4ea7535b5d6760afad736361dff08bfd1fda9/django_filters/rest_framework/backends.py#L107-L140


**But** it's not something I want to put time into. 

If there's life in the dry_yasg/CoreSchema ecosystem, happy to link to where the action is, or even take PRs but I'm not sure if there is or not...?

I'll close this as I don't see it actionable for here.
