### ISSUE TITLE
simple ManyToMany filter

### ISSUE THREAD

**Issue by dbinetti** [carltongibson/django-filter#1105]
I have read the documentation and issues and it would seem that django-filter supports this kind of filterset declaration for use with DRF:

```
class GroupFilterset(FilterSet):
    class Meta:
        model = Group
        fields = {
            'owners': [
                'in',
            ],
       }
```

where the `owners` refers to ManyToMany field pointing at the User model.  However, it does not work, throwing a `AttributeError: 'list' object has no attribute 'split'` error.   (I have searched for this error and the answers appear to be unrelated to this particular issue.)

I should mention that the mere inclusion of the above breaks the filter entirely, including for other simpler known-to-work requests.  So perhaps the `in` filter is not support for M2M?  If so, it would be worthwhile to say that in the documentation and perhaps have a more descriptive error.  If not, then perhaps I've stumbled on a bug.

Django 2.2.3
django-filter 2.1.0
drf 3.9.4

and FWIW, also using drf-jsonapi and dry-rest -permissions

thanks

**Comment by rpkilby** [comment]
Yes, this is a bug (see: https://github.com/carltongibson/django-filter/issues/1084). The generated `in` lookup produces a CSV-based filter, however the CSV mixin behavior is not compatible with multiple choice filters.

**Comment by dbinetti** [comment]
Sorry -- I did see that issue, but was confused by some of the language since it didn't specifically refer to a M2M field.  Closing in favor or #184 thanks
