### ISSUE TITLE
Filter JSONCharField from Django jsonfield

### ISSUE THREAD

**Issue by frozen-yogurt** [carltongibson/django-filter#1107]
Hello Is there any example on how to set up django-filter to search a specific field in JSON. 

For example, I have a model: Exploration and it has a JSONCharField named location. Location looks like `{'name': 'aa'}`.  This JSONCharField is imported from Django jsonfield, it is a generic textfield that serializes/deserializes JSON objects, stored in the database like a CharField, which enables it to be used.

As for my Filter class, following the idea from #768, it is defined as below:
```python
from copy import deepcopy
from jsonfield import JSONCharField
from django_filters import filterset

class ExplorationFilter(FilterSet):
    FILTER_DEFAULTS = deepcopy(filterset.FILTER_FOR_DBFIELD_DEFAULTS)
    FILTER_DEFAULTS.update({
        JSONCharField: {
            'filter_class': filters.CharFilter,
            'extra': lambda f: {'lookup_expr': ['icontains']},
        },
    })

    location = filters.CharFilter(name='location', method='filter_location')

    def filter_location(self, qs, name, value):
        return qs.filter(location__name=value)

    class Meta:
        model = Exploration
```

I want to find all `Exploration` with `location.name == 'aa'`. 
However, when I GET `http://localhost:8000/api/v1/explorations?location=aa`, I get the following error: 
```
Exception Type:  FieldError
Unsupported lookup 'name' for JSONCharField or join on the field not permitted.
```

I think there must be some places that I did incorrectly. Is there any example that I could follow, to fix this? Thank you!!

**Comment by rpkilby** [comment]
It is not possible to use key lookups with django-jsonfield. The app doesn't actually use JSON db types, instead just serializing the data as json before stuffing it in a char/text field. The advantage of django-jsonfield is that it's database agnostic, but of course the drawback is that you don't get query support. It's usually most useful for arbitrary config data that you *know* won't need to be queried. If you want to query individual keys, you'll need to use Django's postgres [`JSONField`](https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#jsonfield).

**Comment by frozen-yogurt** [comment]
Thank you a lot @rpkilby
