### ISSUE TITLE
Using django-filter with DetailView

### ISSUE THREAD

**Issue by Damar225** [carltongibson/django-filter#1108]
I posted this problem on stackoverflow [here](https://stackoverflow.com/questions/57085070/using-django-filter-with-class-detailview)
I know that i have just posted this problem on stackoverflow and it didn't take it is time, but i just want to know from you guys ... is this something that can be done with dango-filter or it is very hard/impossible ?
i just want to link the filter form to django DetailView class.
you can see the link above for code details thanks.

**Comment by carltongibson** [comment]
StackOverflow is the correct forum for this kind of question.
