### ISSUE TITLE
assert isinstance() call

### ISSUE THREAD

**Issue by sirdodger** [carltongibson/django-filter#1111]
There is a loose assertion in filterset.py:225 that checks that the `queryset` argument is a models.QuerySet.  The problem with that is that it makes mocking the queryset difficult (especially since querysets tend to be chained).  It also violates the spirit of allowing duck typing in Python.

Can it be removed?

**Comment by sirdodger** [comment]
https://github.com/carltongibson/django-filter/pull/1112

**Comment by carltongibson** [comment]
Can’t you just set the [mock’s `spec` ](https://docs.python.org/3/library/unittest.mock.html)?

I’m not really inclined to pull his out. It helps people make sure they’ve implemented things right...

**Comment by sirdodger** [comment]
You can spec the queryset, but because you can chain querysets, it gets annoying to spec the mock that will actually be passed to this filter.  e.g., you end up needing to track the exact chain of calls on the queryset prior to the filter_queryset() method and mock something like:

mock_qs.all.return_value.filter.return_value = Mock(spec=QuerySet)

It's not impossible, but it is fragile.

Could the assert be changed to a logging.error instead, or implemented as a type hint?

**Comment by rpkilby** [comment]
Why do you need to mock the queryset at the `FilterSet` level? Usually, mocking is done for testing individual filters, not for testing the entire process.

**Comment by sirdodger** [comment]
I'm not sure I understand.  Sure, individual filters should be tested with mocks.  But why should entire custom FilterSets have to be tested with live querysets?  Or are you suggesting that they don't need to be under test at all?

**Comment by rpkilby** [comment]
I'm suggesting that testing the filterset with mocks is particularly fragile and should probably be avoided. I would look at `tests.test_filtering` as a base example of how filtersets can be tested.

**Comment by rpkilby** [comment]
Closing per https://github.com/carltongibson/django-filter/pull/1112#pullrequestreview-369055675
