### ISSUE TITLE
Integration with djangorestframework-camel-case

### ISSUE THREAD

**Issue by Reyvel** [carltongibson/django-filter#1114]
Most javascript programmers in my team use camelCase. So I am wondering if I can integrate django-filter with djangorestframework-camel-case to make front end developers feel at home. I am thinking about using middleware to underscoreize the query params, but I don't know how to camelize the browseable api. Any idea?

**Comment by carltongibson** [comment]
Start with what you can do. Then when you have code to show it's worth thinking about the more difficult cases.
