### ISSUE TITLE
Did not work request based filter (doc is outdated)?

### ISSUE THREAD

**Issue by yn-coder** [carltongibson/django-filter#1117]
Did not work request based filter (doc is outdated)?

``request`` is not sended to callable object

https://github.com/carltongibson/django-filter/blob/master/docs/guide/usage.txt#L224

My code is:

    def user_projects(request):
        if request is None:
            return Project.objects.filter(id=3)
    
        return GetMemberedProjectList( request.user ) # GetMemberedProjectList - get projects for user

    class TaskFilter(django_filters.FilterSet):
        project = django_filters.ModelChoiceFilter(  queryset=user_projects )

        class Meta:
            model = Task
            fields = ['project' ]

    task_filter = TaskFilter( request.GET, queryset= Task.objects.all() )

```request``` is always None

**Comment by yn-coder** [comment]
Your docs sample looks outdated

class EmployeeFilter(**filters**.FilterSet):
        department = **filters**.ModelChoiceFilter(queryset=departments)

**Comment by yn-coder** [comment]
Possible solution is

    task_filter = TaskFilter( data = request.GET, request=request, queryset= Task.objects.all())

**Comment by carltongibson** [comment]
You're not passing the `request` when instantiating the `FilterSet`. (The docs you linked demonstrate how to configure a a `ModelChoiceFilter`, as part of a `FilterSet`.)
