### ISSUE TITLE
FilterSet with custom form doesn't filter correctly.

### ISSUE THREAD

**Issue by lorenzodantonio** [carltongibson/django-filter#1123]
I need a filter with a custom form (I want to specify the widgets for each field).
From the documentation there seems to be the possibility to specify a form attribute in the meta class of the FilterSet.

```
class TestForm(ModelForm):

    class Meta:
        model = Model1
        fields = ['field_1', 'field_2', 'field_3']
        widgets = {
            'field_1': ModelSelect2(url='url'))
        }


class TestFilterset(FilterSet):

    class Meta:
        form = TestForm
```

The form renders correctly (with the widgets I chose) but when I try to filter the queryset the behaviour of the FilterSet is aberrant: if the filtered queryset would normally be empty I receive a KeyError else I get an empty result.

![key_error](https://user-images.githubusercontent.com/39066537/65337411-5ce58a80-dbc8-11e9-926b-0a8b3e7deaca.PNG)

Trying to debug the problem I noticed that the content of self.filters is an empty OrderedDict in the KeyError case.

I also tried to specify the Model and the fields in the Meta of the FilterSet but my custom form
is overwritten.

**Comment by carltongibson** [comment]
What's the `KeyError`? I'd guess you'd need to specify `fields` on the `FilterSet`. (But there's not enough to really go on here.)
