### ISSUE TITLE
adding FilterSet slows down, don't know why

### ISSUE THREAD

**Issue by littlehome-eugene** [carltongibson/django-filter#1133]
I added pretty basic setting as below, and the ViewSet's view endpoints are somehow really slow (CPU 200ms => 40000ms in django-debug-toolbar .. SQL query time remains the same)

```
 class ReviewThreadFilterSet(filters.FilterSet):

     class Meta:
         model = ReviewThread
         fields = {
             'user_id': ['exact']
         }

```
and adding
```
 class ReviewThreadViewSet(serializers.ModelViewSet): 
     filterset_class = ReviewThreadFilterSet
     filter_backends = [filters.DjangoFilterBackend]
```

Underlying models looks like the following..  

```
class Thread(models.Model):

    user = ForeignKey(User) 
   

class ReviewThread(Thread):
   pass
```

**Comment by rpkilby** [comment]
Hi @littlehome-eugene. This is pretty severe performance issue that would likely have been raised before now. My guess is that something else is at play here. I created a quick reproduction locally and the response time was near instantaneous.

**Comment by littlehome-eugene** [comment]
I tracked down 

`template.render(context, request)` in backends.py `to_html` with template being `'django_filters/rest_framework/crispy_form.html'`


I didin't know it was rending forms for me.. (I am only returning json for api request)
I suspect it's rendering the entire `queryset` and takes a long time.


How can I stop this behavior?
