### ISSUE TITLE
Can I pass two query sets?

### ISSUE THREAD

**Issue by avanibhatnagar** [carltongibson/django-filter#1140]
Django doesn't let me pass two query sets for filtering. 

In my app, join wasn't working so my final result is generated using two query sets. How can I use two query sets?

**Comment by rpkilby** [comment]
Hi @avanibhatnagar. I'm not entirely sure what you're trying to achieve, but a `FilterSet` operates on a single `QuerySet`. You can filter across joins, just like you would do in a queryset. e.g.,

```python
class MyFilterSet(FilterSet):
    related_field = filters.CharFilter(field_name='related_model__related_field', lookup_expr='icontains')
```

However, if you want to manually join two querysets, you are able to use multiple filterset forms on the same page. You need to use the [`prefix`](https://docs.djangoproject.com/en/2.2/ref/forms/api/#django.forms.Form.prefix) argument, which is passed to the filterset's underlying form. This namespaces the fields so that names from each filterset form don't conflict. e.g.,

```python
class AFilterSet(FilterSet):
    name = filters.CharFilter()

    class Meta:
        model = ModelA
        fields = [...] 

class BFilterSet(FilterSet):
    name = filters.CharFilter()

    class Meta:
        model = ModelB
        fields = [...] 

# prefix changes the form input names to (e.g., `a-name` and `b-name`), so they don't conflict
f1 = AFilterSet(request.data, prefix='a')
f2 = BFilterSet(request.data, prefix='b')

result = do_something_to_join(f1.qs, f2.qs)
```

You'll also need to render both filterset forms in your template.

**Comment by avanibhatnagar** [comment]
Thanks a lot for the response. I want to filter using two tables in the same model. I am unable to see the result after the join because I'm working with a legacy database and the table I'm working with doesn't have a Foreign Key. I haven't been able to find a good workaround for that. Hence trying to join the two query sets to pass to the filter and then display results on HTML. Would I need two FilterSets even though both the tables I need are in the same model?

**Comment by avanibhatnagar** [comment]
What I have is:  
```raw_sql="""SQL QUERY"""  
a_list = aRecords.objects.raw(raw_sql)  
b_list = bRecords.objects.raw(raw_sql)
return render_to_response("template.html", {'a':a_list, 'b' = b_list})```

Then in the template I either do a.title or b.number according to what I need to display. Both aRecords and bRecords are in the same model. I want to be able to filter using the fields of a and b.

Thanks in advance!

**Comment by rpkilby** [comment]
> I want to filter using two tables in the same model.

I don't really follow. A Django model typically maps to a single database table. 

> I'm working with a legacy database and the table I'm working with doesn't have a Foreign Key.

You can still use `ForeignKey`s on models to join the tables, even if their isn't a constraint.

```python
class ModelA(models.Model):
    pass

class ModelB(models.Model):
    a_id = models.ForeignKey('ModelA', db_constraint=False, ...)
```

**Comment by avanibhatnagar** [comment]
Sorry, I stated it incorrectly. It is two different models in the same app and the two tables are in the same database. 
I tried doing that. It gives me the following error
```
 ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'a_id_id'. (207) (SQLExecDirectW)")
```
 How I’m using it-
    models.py:
```
    class ModelA(models.Model):
    number = ...

    class ModelB(models.Model):
    a_id = models.ForeignKey('ModelA', on_delete=models.CASCADE, db_constraint=False)
    name = ...
```
views.py:
```
    b_list = b.objects.all()
    return render_to_response(“template.html", {'items’:b_list})
```
template.html:
```
{%for item in items%} 
{b.name}
{b.a_id.number}
{% endfor %}
```
  Doing this gives me the above mentioned Invalid column name error.

**Comment by avanibhatnagar** [comment]
Yes, sorry about that. But I was unable to use the filters due to the join issue so far! Now my JOIN works!! So now I only have one queryset to pass to the filter in views.py. For the fields since I am using a foreign key(a) to refer to one of the models, would I do the following to use that field(a.number) in the filter?
```
class ItemFilter(django_filters.FilterSet):
    class Meta:
        model = Itemrecords
        fields = ['a.number','name']
```
Thanks a lot for the help so far!

**Comment by avanibhatnagar** [comment]
I was able to resolve that error by changing ```a.number``` to ```a__number```
But I'm not sure the filter is working as desired since I'm not getting the desired results, but results still show up so it's not nothing.

**Comment by rpkilby** [comment]
> I was able to resolve that error by changing `a.number` to `a__number`

Yep, in DRF field relations are `.`-notated, but in django-filter, the ORM `__` seperator is used.
I can't give you any specific advice, but my general advice is to make sure that the underlying ORM query works, then try to implement that in the `FilterSet`. e.g., if you have 
```python
class ModelA(models.Model):
    pass

class ModelB(models.Model):
    a = models.ForeignKey(
        'ModelA', 
        on_delete=models.CASCADE, 
        db_constraint=False, 
        db_column='whatever',
    )
```

ensure that this works first

```python
example_qs = ModelB.objects.filter(a='<some known/valid ID>')
print(example_qs)
```

If that works, see if you get the same query from the filterset. e.g.,

```python
class BFilter(FilterSet):
    a = filters.ModelChoiceFilter(field_name='a')

f = BFilter(data={'a': '<some known/valid ID>'}, queryset=B.objects.all())
print(f.qs)
```

If that doesn't work you can always print out the SQL to make sure you're getting sensible results. 
```python
print(str(example_qs.query))
print(str(f.qs.query))
```

**Comment by avanibhatnagar** [comment]
So when I do something like ``` print(example_qs.query)``` I can see my query and it looks right. Similarly with ```print(str(f.qs.query))```, my query looks fine.

But when I do ```print(str(f.qs))``` or ``` print(example_qs)``` then I get this ProgrammingError:
```django.db.utils.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'aRecordID'. (207) (SQLExecDirectW)")```

aRecordID is my db_column in ForeignKey in models.py:
```
 a = models.ForeignKey(
        'ModelA', 
        on_delete=models.CASCADE, 
        db_constraint=False, 
        db_column='aRecordID',
    )
```

**Comment by rpkilby** [comment]
Hm. SQL Server is telling you that the column name is invalid, so I'd check the table schema to ensure that you don't have a typo. You can also run `python manage.py inspectdb` to see what Django thinks the column name should be (`inspectdb` generates models based on the table schemas).

**Comment by rpkilby** [comment]
Either way, it sounds like django-filter is doing the correct thing here, so this is more an issue with ensuring your models are compatible with their underlying tables.

**Comment by avanibhatnagar** [comment]
Yeah, I did ```inspectdb``` and it's literally the same thing. I even copied it just cause I thought maybe I can't see what it is, but still doesn't work. It works as a raw sql query.. raw_sql ="""SELECT A.aRecordID, .... """ works just fine, and produces the desired results.
Yes it's not related to django-filter.. I don't know what's happening.

**Comment by rpkilby** [comment]
Are you sure you're querying against the correct `db_table`?f

**Comment by avanibhatnagar** [comment]
Yep. Just made sure again. I do have multiple databases, but I'm querying against the default database so I wouldn't have to mention that anywhere right?

**Comment by rpkilby** [comment]
Maybe try to determine the differences between your raw query and the query generated by the ORM. Beyond that, I can't really help you debug this. Best of luck.

**Comment by avanibhatnagar** [comment]
I was finally able to debug it! Thanks a lot for the help! django_filter now works! 
Can I change the name of how it appears on the browser though? For example my filters.py has:
```record__title = django_filters.CharFilter(lookup_expr='icontains')``` and this appears on my browser as "Recordid title contains" right next to the text box. Could I change that?
Also, the database I'm working with is huge, how can I get a splice? I tried ```[:5]``` to get 5 entries but I get an error:
```cannot filter a query once a slice has been taken```

**Comment by rpkilby** [comment]
>  this appears on my browser as "Recordid title contains" right next to the text box. Could I change that?
 
Yes. Any [additional keyword arguments](https://django-filter.readthedocs.io/en/master/ref/filters.html#kwargs) that are not attributable to the filter class, are passed to its underlying form field. This includes the form `label`.

> how can I get a splice?

It depends on what you're trying to do, but if you're trying to limit the number of results at the end, try using DRF's pagination classes.

**Comment by avanibhatnagar** [comment]
Thanks! Just the last question is if there is a ```lookup_expr``` for "not in" or "not equal to"

If someone enters their branch number in a text box and clicks search, I want it to return all fields except the ones with their own branch number (the branch number they entered)

**Comment by rpkilby** [comment]
`lookup_expr` corresponds to the lookups in the Django ORM. As such, there isn't a "not in" or "not equal to" `lookup_expr`.  However, the ORM allows you to invert a `filter()` by using `exclude()` instead. In django-filter, this is controlled with the [`exclude`](https://django-filter.readthedocs.io/en/master/ref/filters.html#exclude) argument.

**Comment by avanibhatnagar** [comment]
But I'm unable to use filter() to take in user input. I'm able to do the following:
```
Arecords.objects.select_related('bid').filter(~Q(id=5)).values(..)
```
But instead of the 5, I need to take in user input..

**Comment by rpkilby** [comment]
A `Filter` instance will generate the underlying ORM `.filter()` call. e.g., given this filterset:

```python
class MyFilterset(FilterSet):
    my_field = filters.CharFilter()

    class Meta:
        model = MyModel
```

You would get a query like:
```
MyModel.objects.filter(my_field='<input>')
```

However, if you provide the exclude argument:

```python
class MyFilterset(FilterSet):
    my_field = filters.CharFilter(exclude=True)
    ...
```
you would invert the call:
```python
MyModel.objects.exclude(my_field='<input>')
```

**Comment by avanibhatnagar** [comment]
Thanks a lot for the help. It worked :)
Is there an equivalent of form.save() to save the user input to the database available in the form(filter.form) made by django_filter?

**Comment by rpkilby** [comment]
As in stored queries? No.

**Comment by avanibhatnagar** [comment]
No, not the stored queries.

Just whatever the user inputs in the fields to filter..
I have two buttons: Search and Save. Search will just filter according to what user entered in the field. I want "Save" to save what the user entered in the fields to a different database.
If i have a filter using the field "Name".
And this is the filter form on the html page-
Name: 
User enters "Sam" in the textbox.
Then clicking on the Search button would filter the results where Name is/contains "Sam"
And clicking on Save would save the name Sam to another database.

**Comment by rpkilby** [comment]
> Just whatever the user inputs in the fields to filter..

Sorry, hadn't had coffee yet. That's what I meant. Regardless, no - that's something you'd need to build. I'd recommend something generic that saves the raw query string/form data as a `TextField` or the parse query params as an `HStoreField` or equivalent, instead of saving the individual fields for the filter.
