### ISSUE TITLE
AttributeError on startup when the foreign model is not resolved yet by Django

### ISSUE THREAD

**Issue by mlorant** [carltongibson/django-filter#1157]
I have been splitting a models.py file into distincts files in order to clarify my codebase. When I'm referencing my model [using its name instead of its references, due to circular imports](https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.ForeignKey), it breaks on the runserver startup.  Let's suppose I had the following structure before the refactoring:

    class Group(models.Model):
        some_field = models.ForeignKey(ExternalEntity)

    class Item(models.Model):
        group = models.ForeignKey(Group)

    # in some viewsets file
    class ItemFilterSet(FilterSetBase):
        class Meta:
            model = Item
            fields = ['group__some_field',]

This was working great. Replacing ForeignKey(Group) by ForeignKey('Group') gives me:

    File "my_project/api/urls.py", line 7, in <module>
      from orfeo.api import views
    File "my_project/api/views.py", line 88, in <module>
      class ItemFilterSet(FilterSetBase):
    File ".venv/MY_PROJECT/lib/python3.7/site-packages/django_filters/filterset.py", line 71, in __new__
      new_class.base_filters = new_class.get_filters()
    File ".venv/MY_PROJECT/lib/python3.7/site-packages/django_filters/filterset.py", line 330, in get_filters
      field = get_model_field(cls._meta.model, field_name)
    File ".venv/MY_PROJECT/lib/python3.7/site-packages/django_filters/utils.py", line 141, in get_model_field
      fields = get_field_parts(model, field_name)
    File ".venv/MY_PROJECT/lib/python3.7/site-packages/django_filters/utils.py", line 170, in get_field_parts
      opts = field.remote_field.model._meta
    AttributeError: 'str' object has no attribute '_meta'

Indeed, the model _may_ not be loaded yet, depending on how Django import the models on the launch of the server.

I can hopefully fix my problem hopefully by tweaking my structure to allow the import of the Group model in the Item file, but I guess `get_field_parts` might need to handle this case.

**Comment by carltongibson** [comment]
This is a problem in your code structure. Project URLs shouldn’t be imported until after the apps registry is populated, normally via `django.setup()`.

**Comment by eytanschulman** [comment]
> This is a problem in your code structure. Project URLs shouldn’t be imported until after the apps registry is populated, normally via `django.setup()`.

How is this not a lack of a feature in `Django Filters` to support referencing a model by its name?
