### ISSUE TITLE
Document use with Django's Paginator

### ISSUE THREAD

**Issue by adamchainz** [carltongibson/django-filter#1159]
https://stackoverflow.com/questions/48546864/django-filter-with-pagination seems to be the de facto documentation source and it's very complicated. I think it would be good to have a small example in the official django-filter docs.

**Comment by carltongibson** [comment]
Okay... 

So, how is this different from just, say, Django’s pagination docs? (Like you filter the QuerySet then you paginate it...)

Happy to add whatever really but...

**Comment by adamchainz** [comment]
On second glance I think you're right. A student just struggled to grasp it but perhaps that's a lesson in *filter*ing out low quality SO answers more than anything. There is already a paragraph in "the view" section of the django-filter docs:

> If you want to access the filtered objects in your views, for example if you want to paginate them, you can do that. They are in f.qs

**Comment by carltongibson** [comment]
OK... — well, if you have a concrete idea, come back. 👍
