### ISSUE TITLE
Distinct seems missing on ordering filter

### ISSUE THREAD

**Issue by PokeTheCiTy** [carltongibson/django-filter#1162]
Hi,

I am using ordering filter on M2M Relationship and got deduplication issue.

Let's work with this example:
```py
class Track(Model):
    title = Charfield..
    # stuff

class Artist(Model):
    name = Charfield()
    tracks = ManyToManyField(Track)
```

I used OrderingFilter on Track view like this:
```py
    ordering = OrderingFilter(
        fields=(
            ("title", "title"),
            ("artists__name", "artist"),
    )
```

However, for songs with more than 1 artist, I got X copy of it where X is the number of artists when I do `?ordering=artist`

Inspecting the code, I found that OrderingFilter inherit ChoiceFilter but reimplement `filter` method.
Thus, it does not have `return qs.distinct() if self.distinct else qs` which I think could fix the issue.

If I am wrong, can you please provide me a solution because adding kwarg `distinct=True` did not fix it.

Thank you

**Comment by loganknecht** [comment]
@PokeTheCiTy Did you find a solution for this? I'm currently having an issue in #1255 and I don't really know a work around for the issue of using `distinct` with a filter.
