### ISSUE TITLE
I can not  paginate the results in django-filter

### ISSUE THREAD

**Issue by Lifechess** [carltongibson/django-filter#1166]
### my view

```python
def post_list(request):
    qs = Post.published.filter(location_id__lte=23225 ).order_by('-created')
    past = timezone.datetime.today() - timezone.timedelta(days=30)
    Post.objects.filter(created__lte=past).delete()
    posts = PostFilter(request.GET, queryset=qs)
    paginator = Paginator(posts.qs, 1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    f = PostFilter(request.GET, queryset=qs) 
    context = {
    'filter': f,
    'posts': posts,
    'page': page,
    }
    return render(request, 'ads_on_cafe/post_list.html', context)
```

### my templates

`<div class="pagination mt-3">

    {% with request.get_full_path as querystring %}
        <ul class="pagination">

            
            {% if posts.has_previous %}
                {% if 'title' in querystring %}
                    {% if 'p' in querystring %}
                        <li class="page-item {% if posts.number == p %}active{% endif %}">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ posts.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if posts.number == p %}active{% endif %}">
                            <a class="page-link" href="{{ querystring }}&p={{ posts.previous_page_number }}">&laquo;</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if posts.number == p %}active{% endif %}">
                        <a class="page-link" href="?page={{ posts.previous_p_number }}">&laquo;</a>
                    </li>
                {% endif %}
            {% endif %}

            
            {% for p in posts.paginator.page_range|slice:":9"  %}
                {% if 'title' in querystring %}
                    {% if 'p' in querystring %}
                        <li class="page-item {% if posts.number == p %}active{% endif %}">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ p }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if posts.number == p %}active{% endif %}">
                            <a class="page-link" href="{{ querystring }}&page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if posts.number == p %}active{% endif %}">
                        <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            
            {% if posts.has_next %}
                {% if 'title' in querystring %}
                    {% if 'p' in querystring %}
                        <li class="page-item {% if posts.number == p %}active{% endif %}">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ posts.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if posts.number == p %}active{% endif %}">
                            <a class="page-link" href="{{ querystring }}&page={{ posts.next_page_number }}">&raquo;</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if posts.number == p %}active{% endif %}">
                        <a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a>
                    </li>
                {% endif %}
            {% endif %}

        </ul>
    {% endwith %}

</div>
`
Maybe my code is in the wrong approach but the documentation doesn't explain pagination

**Comment by rpkilby** [comment]
Hi @Lifechess. django-filter does not directly affect pagination. Make sure you've implemented pagination first, then add in filtering.

**Comment by Lifechess** [comment]
Yes, It is affecting my resulte, because i don't want to paginate my normal queryset but the filter queryset so i must integrete django-filter in my panination. When i get a result filter, i got someting like this as my link:

>  http://127.0.0.1:8000/?csrfmiddlewaretoken=0gusJToXCgcyknuXQz8xrP0vlcnWbhQ8nzrGuw8a8jh2Ivm52ncWDB4UynJKaGZd&location=&choose_the_gender=woman&in_call=&out_call=&fa-kiss-wink-heart=Filter

when i click next_page, my link come back to someting like this:

>  http://127.0.0.1:8000/?page=2
and all the result come back again

**Comment by rpkilby** [comment]
This is an issue with your template. Your prev/next links only contain the `page` number, however you should also be passing the rest of the querystring (`choose_the_gender`, `in_call`, `out_call`, etc...)

**Comment by Lifechess** [comment]
Thank for the help rpkilby , finaly i succeed with the exmple from  stackoverflow of José L. Patiño from this link:  [https://stackoverflow.com/questions/2047622/how-to-paginate-django-with-other-get-variables](url)
