### ISSUE TITLE
lookup_type not respecting list or tuple

### ISSUE THREAD

**Issue by rosscdh** [carltongibson/django-filter#117]
Hi there, 

Firstly thanks for your work on this project. Neat addition to rest_framework.

A small problem Im running into is:

https://django-filter.readthedocs.org/en/latest/ref/filters.html#lookup_type

**"If a list or tuple is provided, then the user can select from those options."**

When providing a list or tuple:

```
email = django_filters.CharFilter(lookup_type=('startswith', 'icontains'))
```

you end up with a:

```
IndexError: list index out of range
```

**Comment by divkis01** [comment]
Is this issue fixed? I am using django-filter-0.9.2 and I still see that passing list or tuple to lookup_type does not work.

**Comment by dekoza** [comment]
same here - passing list or tuple does not work

**Comment by carltongibson** [comment]
If you can provide a falling test-case showing your problem that would help.
