### ISSUE TITLE
New release to update PyPI metadata for Django 3.0.

### ISSUE THREAD

**Issue by AndreyMZ** [carltongibson/django-filter#1173]
Does `django-filter` support Django 3.0?

If no, then let this issue be used for tracking the state/progress.

If yes, then the page <https://pypi.org/project/django-filter/> should be updated:
- add "Django :: 3.0" in the list of _Frameworks_;
- add "3.0" in the _Requirements_ section of  _Project description_.

**Comment by carltongibson** [comment]
The current version is compatible. The metadata is all in place on master. I guess we just need a release.

**Comment by pqmertz** [comment]
Sorry, but I'm confused by this.
Trying to get this to work with Django 3.0,  if I use the function view nothing happens on submit, if I use the classview I get a blank white screen.   I've tried copying the files here into my venv but that didn't appear to make any difference either.   Any ideas, when the 3.0 will be released to PyPi?  Or simple instructions for using it from here.  Thanks much!

**Comment by WayneLambert** [comment]
I would also be keen to know when the updates will be released to PyPI. I think I only have two packages left to be updated before I can hopefully bump my project to Django 3.0.x

Thank you!

**Comment by carltongibson** [comment]
This is not blocking your updating. It’s just a meta data tweak.

**Comment by WayneLambert** [comment]
OK, thanks for confirming.

**Comment by carltongibson** [comment]
Closed by #1231, on PyPI today.
