### ISSUE TITLE
Regression: DateFilter in combination with lookup_expr fails for models.DateTimeField

### ISSUE THREAD

**Issue by gabn88** [carltongibson/django-filter#1179]
When using a DateFilter, for example:

```
class ModelStatusFilter(django_filters.FilterSet):
    '''
    This filter is used in the views
    '''

    timestamp__gte = django_filters.DateFilter(
        field_name='timestamp', lookup_expr='gte', widget=CustomDatePicker())
    timestamp__lte = django_filters.DateFilter(
        field_name='timestamp', lookup_expr='lte', widget=CustomDatePicker())

    class Meta:
        model = ModelStatus
        fields = {
           'timestamp',
            'status'
        }
```

it used to work before, but since version 2.0 the filter will render fine, but when entering a date you'll get the error: 

```
RuntimeWarning at /yourserver/
DateTimeField ModelStatus.timestamp received a naive datetime (2020-02-25 00:00:00) while time zone support is active.
```

This might have to do with the way we migrated from pre-2.0 to the post-2.0 version of this package, but I just expected it to work and I'm not sure how to go forward. 

We tried the DateRangeFilter, but then we could not get the custom widget in place.
Of course we could write a completely custom filter, but that seems quite a lot of work for something so simple, or am I missing something?

**Comment by rpkilby** [comment]
Off the cuff response, but my guess is that this is ORM related, and nothing specific to django-filter. `DateFilter` itself is just a wrapper around `forms.DateField`.

https://github.com/carltongibson/django-filter/blob/bdb190b29cf4a1462da3ccf9fa7620596aeb777f/django_filters/filters.py#L269-L270

**Comment by gabn88** [comment]
You are right, just changing DateFilter to DateTimeFilter resolved the issue. So stupid, you wouldn't say I have tried a dozen things and spend 4+ hours on this. Thank you for your swift response!

**Comment by rpkilby** [comment]
No worries, 🥂

**Comment by gabn88** [comment]
Just one question, the timestamp__lte (a.k. 'end date') is still exclusive, probably due to the conversion of date to datetime. Is there a way to fix this?

**Comment by rpkilby** [comment]
Oh, you should probably use the `date` transform here. 

```python
class ModelStatusFilter(django_filters.FilterSet):
    timestamp__gte = django_filters.DateFilter(
        field_name='timestamp', lookup_expr='date__gte', widget=CustomDatePicker())
    timestamp__lte = django_filters.DateFilter(
        field_name='timestamp', lookup_expr='date__lte', widget=CustomDatePicker())
```

This will just compare the date portion so you don't have to worry about the trailing hours/minutes/etc.

**Comment by gabn88** [comment]
Works like a charm, thanks!
