### ISSUE TITLE
'property' object has no attribute '_iterable_class'

### ISSUE THREAD

**Issue by Ch41r0s** [carltongibson/django-filter#1188]
When trying to read queryset of filterset with django_pandas.io.read_frame, the error 'property' object has no attribute '_iterable_class' is thrown. I looked into django_filters source code to better address the issue, but couldn't find any lead. I also tried to override both .qs and it's __init__ in my code but couldn't get it to work.

Steps to reproduce:

Create Model as Models.Model
Create FilterSet as django_filters.FilterSet
Create a def View, django_pandas.io.read_frame(FilterSet.qs)

How can i get a workaround for this issue?

**Comment by rpkilby** [comment]
Hi @Ch41r0s. You need to first create a filterset subclass for your model, then instantiate it. The docs goes into more detail:

https://django-filter.readthedocs.io/en/master/guide/usage.html
