### ISSUE TITLE
How To Change Query Params Name in Filterset

### ISSUE THREAD

**Issue by mmohajer9** [carltongibson/django-filter#1192]
Hi everyone !

i'm using django-filter the latest version 2.2.0

and i'm using it with Django Rest Framework

my issue is when i'm using the meta class and fields attribute , then i'm selecting some fields even with relationship path for example :

```
class Member(Model):
     user = Foreignkeyfield(User)  # e.g


class Meta:
     model = Member
     fields = [
          "user__username"
     ]

```

to make a filter based on username 

and  now the `query param` is `user__username`

and it is worse for more complex relationships

for example

`post__member__user__username`

and it's annoying

please tell me how to fix this 

Tnx

**Comment by rpkilby** [comment]
Hi @mmohajer9. To customize filters, they should be declared manually. e.g., 

```python
class MemberFilter(FilterSet):
    username = filters.ModelChoiceFilter(...)
```

That said, you can also override the various class methods to customize how generation works. e.g., you could override [`get_filter_name`](https://github.com/carltongibson/django-filter/blob/f94d104b63d4b837363a354e7cdac4f6bcd5c6b1/django_filters/filterset.py#L303-L317) to return values for specific (field_name, lookup_expr) pairs. You could also alter the `MemberFilter.base_filters` dict.
