### ISSUE TITLE
CameraModelFilterSet resolved field 'tags' with 'exact' lookup to an unrecognized field type TaggableManager

### ISSUE THREAD

**Issue by djjudas21** [carltongibson/django-filter#1200]
I've been using `django-filter` for a while but I just added `django-taggit` to my project with minimal config as in these two commits, basically just adding a `tags` field to the model `CameraModel`:
* https://github.com/djjudas21/camerahub/commit/fd322cb730dc9146cca366ef41dcc01efeabfcc9
* https://github.com/djjudas21/camerahub/commit/9547319e200d4fc8751e54b7d399ae5989a47753

Straight away I started getting this error about filters:

```
CameraModelFilterSet resolved field 'tags' with 'exact' lookup to an unrecognized field type TaggableManager. Try adding an override to 'Meta.filter_overrides'. See: https://django-filter.readthedocs.io/en/master/ref/filterset.html#customise-filter-generation-with-filter-overrides
```

I followed the advice in the URL in the error and specified `filter_overrides` in the pre-existing FilterSet as below, but this hasn't changed the error. Am I missing something? Thanks

```py
class CameraModelFilter(FilterSet):
    class Meta:
        model = CameraModel
        fields = [
            'manufacturer',
            'mount',
            'format',
            'negative_size',
            'body_type',
        ]
        exclude = ['tags']
        filter_overrides = {
            TaggableManager: {
                'filter_class': CharFilter,
                'extra': lambda f: {
                    'lookup_expr': 'icontains',
                },
            },
        }
```

**Comment by rpkilby** [comment]
Hi @djjudas21.

> I followed the advice in the URL in the error and specified `filter_overrides` in the pre-existing FilterSet as below, but this hasn't changed the error.

Hm.. something doesn't seem right with the example. The `tags` field is in `Meta.exclude`, so the `FilterSet` explicitly won't attempt filter generation. It should not be possible for the error to  occur in this case. Also, I created the following model and filter, and didn't have any issue.

```python
# model
class Taggable(models.Model):
    name = models.CharField(max_length=80)
    tags = TaggableManager()

# filter
class TaggableFilter(FilterSet):
    class Meta:
        model = Taggable
        fields = ['name', 'tags']
        filter_overrides = {
            TaggableManager: {'filter_class': CharFilter},
        }
```

`TaggableFilter.base_filters` yields

```python
OrderedDict([
    ('name', <django_filters.filters.CharFilter object at 0x10a202e10>), 
    ('tags', <django_filters.filters.CharFilter object at 0x10a209a90>),
])
```

Possibly there was a typo, or `filter_overrides` was set on the class instead of the `Meta` class?

**Comment by djjudas21** [comment]
Thanks for your response. I've checked my FilterSet and `filter_overrides` is definitely inside the `Meta` class. This is verbatim what my filter looks like:

```py
class CameraModelFilter(FilterSet):
    class Meta:
        model = CameraModel
        fields = [
            'manufacturer',
            'mount',
            'format',
            'negative_size',
            'body_type',
        ]
        exclude = ['tags']
        filter_overrides = {
            TaggableManager: {
                'filter_class': CharFilter,
            },
        }
```

I'm new to Python/Django so I'm not really sure how to troubleshoot this further. All my code is public, so would it be possible for you to check out my repo and try to get the same error?

```sh
git clone git@github.com:djjudas21/camerahub.git
cd camerahub
git checkout 284b_tags
sourve venv/bin/activate
pip install .
python manage.py runserver
```

Browse to http://localhost:8000/cameramodel/ as this is the view that triggers the error (the only one with a `tags` field in the model.

**Comment by rpkilby** [comment]
I'm wondering if this is an environment issue - I installed your application and ran the following in `python manage.py shell`:

```python
>>> from schema.filters import CameraModelFilter
>>> CameraModelFilter.base_filters['tags']
Traceback (most recent call last):
  File "<console>", line 1, in <module>
KeyError: 'tags'
```

As expected, because `tags` is in the `Meta.exclude` list, the filterset doesn't attempt to generate a filter. I edited the code and added `tags` to `Meta.fields` and reran the above.

```python
>>> from schema.filters import CameraModelFilter
>>> CameraModelFilter.base_filters['tags']
<django_filters.filters.CharFilter object at 0x10b0cf490>
>>> CameraModelFilter.base_filters['tags'].lookup_expr
'icontains'
```

I'm going to go ahead and close, since this doesn't seem like an issue in django-filter, but happy to continue discussing.

**Comment by djjudas21** [comment]
Thanks, I agree that this doesn't look like a bug in `django-filter`. I've filed a very similar issue against `django-taggit` and we'll see if the developer has any useful advice. I'm not sure how to debug this on my own.

https://github.com/jazzband/django-taggit/issues/670

**Comment by rpkilby** [comment]
Everything worked as expected for me, so best I can tell is that something is broken in your environment. I might recreate your virtualenv and see if that fixes your issue.

**Comment by djjudas21** [comment]
Thanks. I'm not an experienced virtualenv user but I did the following to blow it away and start over, and I'm having the same problem.

```
[jonathan@poseidon camerahub]$ rm -rf venv
[jonathan@poseidon camerahub]$ python3 -m venv venv
[jonathan@poseidon camerahub]$ source venv/bin/activate
(venv) [jonathan@poseidon camerahub]$ pip install .
```

If it's relevant, here's the output of `pip freeze`
```
astroid==2.3.3
awesome-slugify==1.6.5
CameraHub==0.7.1.dev1
confusable-homoglyphs==3.2.0
Django==2.2.12
django-autosequence==0.7.0
django-choices==1.7.1
django-crispy-forms==1.9.0
django-currentuser==0.5.0
django-favicon==0.1.3
django-filter==2.2.0
django-fullurl==1.0
django-getenv==1.3.2
django-model-utils==4.0.0
django-moderation==0.7.0
django-money==0.15.1
django-redis==4.11.0
django-registration==3.1
django-sendgrid-v5==0.8.1
django-tables2==2.3.1
django-taggit==1.2.0
django-watson==1.5.5
future==0.18.2
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
pbr==5.4.5
psycopg2-binary==2.8.5
py-moneyed==0.8.0
pylint==2.4.4
pylint-django==2.0.15
pylint-plugin-utils==0.6
PyMySQL==0.9.3
python-http-client==3.2.7
pytz==2019.3
redis==3.4.1
regex==2020.4.4
sendgrid==6.2.2
six==1.14.0
sqlparse==0.3.1
typed-ast==1.4.1
Unidecode==0.4.21
uWSGI==2.0.18
wrapt==1.11.2
```

**Comment by rpkilby** [comment]
Ah. I just figured it out. The views have set `filter_class`, when they should be setting `filterset_class`. Because of this, the view is generating the filterset via a factory method, which doesn't have the override. You can see this in the stack trace:

<img width="760" alt="Screen Shot 2020-04-24 at 10 20 04 AM" src="https://user-images.githubusercontent.com/2370209/80239550-4a777780-8615-11ea-87bf-6ea4302aecbe.png">

**Comment by djjudas21** [comment]
Ah great, thanks. Sorry for my late response - my email has been down for a few days and somehow I didn't realise I wasn't getting notifications for stuff.

So is this a bug in `django-filter` or the class-based views in Django itself?

**Comment by rpkilby** [comment]
No, this is a bug in your code. `filter_class` has never been a valid attribute for `FilterView`.

**Comment by djjudas21** [comment]
Oh, thanks, that's excellent. I've fixed my views and everything looks great now. Thanks for your help :+1:
