### ISSUE TITLE
Correct Way to Use CSVWidget with CharFilter

### ISSUE THREAD

**Issue by banagale** [carltongibson/django-filter#1201]
I got this working, but am not sure I'm doing this in the most efficient way.

**Problem:** How do you return a join of query filters based on multiple comma-separated strings passed in via the url coming from a related object's Charfield?

i.e.  `/api/facilities/county=Talbot+County%2C+Baltimore+County,%20Howard%20County`

Prior discussion on this: [in drf](https://github.com/encode/django-rest-framework/pull/2529) and here in #259 and #344.

My solution was to add the [CSVWidget](https://django-filter.readthedocs.io/en/master/ref/widgets.html#csvwidget) to the CharFilter, then create a custom class, `MultiValueCharFilter` which inherits `BaseCSVFilter`.

Then I overrode the base class `Filter`'s [filter()](https://github.com/carltongibson/django-filter/blob/fbb67b6d8d8a8114c69c16b8eaba81cea68e839e/django_filters/filters.py#L139) to join the arbitrary number of querysets resulting from applying the char filter multiple times.

This works, but is there a better way to do this? Is this behavior documented already in a helpful way that I missed?

`api/filters.py`
```
from django_filters.widgets import CSVWidget
from django_filters.constants import EMPTY_VALUES

class MultiValueCharFilter(filters.BaseCSVFilter, filters.CharFilter):
    """
    Custom filter to accept multiple CharFilter strings provided using CSVWidget
    """
    def filter(self, qs, value):
        values = value or []
        queryset = None
        for value in values:
            if value in EMPTY_VALUES:
                return qs
            if self.distinct:
                qs = qs.distinct()
            lookup = '%s__%s' % (self.field_name, self.lookup_expr)
            if not queryset:
                queryset = self.get_method(qs)(**{lookup: value})
            else:
                queryset = queryset | self.get_method(qs)(**{lookup: value})
        if not queryset:
            queryset = qs.all()
        return queryset

class FacilityFilter(filters.FilterSet):
...
    county = MultiValueCharFilter(
        field_name='county__name',
        label='county', widget=CSVWidget,
        help_text="A list of county names, comma separated",
    )
...
```
`models.py`
```
class Facility(TimeStampedModel, AuthorStampedModel):
...
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True)
...

class County(TimeStampedModel):
    name = models.CharField(max_length=100, blank=True, unique=True)
````

**Comment by rpkilby** [comment]
Hi @banagale. `in` lookups support table joins, so it should be sufficient to just use the `BaseInFilter` mixin without needing to override any methods.

```python
class CharInFilter(filters.BaseInFilter, filters.CharFilter):
    pass

class FacilityFilter(filters.FilterSet):
    county = CharInFilter(
        field_name='county__name', label='county',
        help_text="A list of county names, comma separated",
    )
```

Although a more verbose param, these filters can also be generated. e.g.,

```python
class FacilityFilter(FilterSet):
    class Meta:
        model = Facility
        fields = {'county__name': ['in']}
```
