### ISSUE TITLE
Reusing a FilterSet in 2 different but similar models

### ISSUE THREAD

**Issue by marco-silva0000** [carltongibson/django-filter#1207]
I'm using django-filter together with django-simple-history which will create a "HistoryModel" based on a "MainModel".

On a DRF list view I'm using Django filter, and on a particular case I want to list the history versions of the data. To do this I changed the queryset to have correct data, but then django-filter raises an exception on DjangoFilterBackend, line 64

```python
class DjangoFilterBackend(metaclass=RenameAttributes):
    def get_filterset_class(self, view, queryset=None):
        #
        #
        if filterset_class:
            filterset_model = filterset_class._meta.model

            # FilterSets do not need to specify a Meta class
            if filterset_model and queryset is not None:
                assert issubclass(queryset.model, filterset_model), \
                    'FilterSet model %s does not match queryset model %s' % \
                    (filterset_model, queryset.model)

            return filterset_class
```

I get why this check is in place, but I would like to have a way to override it, or to add a set of models to be valid on this filter.

To get around this I can duplicate the filter, set the model to the generated history model, and set self.filter_class to the copied model on the view code where I change querysets. I also did it another way that I'll leave here for anyone that needs.

```python
# this was done in a view's get_queryset method
MainClassHistoryFilter = MainClassFilter
MainClassHistoryFilter._meta.model = MainClassHistoryModel
self.filter_class = MainClassHistoryFilter
```

So I write this to ask if this is an appropriate way of hacking this, and if support for this use case would be a nice feature to add.

**Comment by rpkilby** [comment]
Hi @marco-silva0000. The easiest thing to do would be to use a custom backend for that endpoint. Most of that code is either handling deprecations, or generating a `filterset_class` based on `filterset_fields`. If you already have the class, then you could do something like:

```python
class HistoryBackend(DjangoFilterBackend):
    def get_filterset_class(self, view, queryset=None):
        # ignore model type checking
        return self.filterset_class


class MyView(ViewSet):
    filter_backends = [HistoryBackend]
```

**Comment by marco-silva0000** [comment]
hello,

I used @rpkilby suggestion, for anyone else looking note that it should be `return getattr(view, 'filterset_class', None)` on the Backend class.
Also note that by setting the filter_backends explicitly you will override the default backends from `settings.py`, so add them as well if you have any.
