### ISSUE TITLE
CharFilter lookup_expr='icontains' lower/upper case for regional characters

### ISSUE THREAD

**Issue by moreplavec** [carltongibson/django-filter#1209]
Is it possible to search and ignore upper/lower case for regional characters? For example:

one of my django_filters.FilterSet:

surname = django_filters.CharFilter(lookup_expr='icontains')

but when i try to search "št", no surname starting "Št" (capital) is found. 

I prefer search to be not case sensitive even for regional characters. Or is it possible to define substitutions for my language somehow?

**Comment by rpkilby** [comment]
Hi @moreplavec. Are you using sqlite?

https://docs.djangoproject.com/en/3.0/ref/databases/#substring-matching-and-case-sensitivity

**Comment by moreplavec** [comment]
Yes. So my problem can be solved by changing db backend? Do i get it right?

**Comment by rpkilby** [comment]
It looks like there are workarounds, but going with mysql or postgres is probably a better option.

**Comment by moreplavec** [comment]
I copied whole project to the new virtual and imported data to PostgreSQL. But the problem stays the same. Any hint what i have wrong? Or my problem is not DB related?

**Comment by rpkilby** [comment]
Just a sanity check - did you update your settings to point to the postgres database, or are you still querying sqlite?
