### ISSUE TITLE
Callable value for queryset on ModelChoiceField not working

### ISSUE THREAD

**Issue by liquidscorpio** [carltongibson/django-filter#1210]
### Version and environment
- Python 3.7
- Ubuntu 18 LTS
```
Django==3.0.5
django-filter==2.2.0
djangorestframework==3.10.3
```

### Steps to reproduce
Create a filterset as below - the important part is a callable value for queryset other aspects can be adapted.

```python
def bar_qs(request):
    return Bar.objects.filter(user=request.user)

class FooFilterSet(FilterSet):
    bar = filters.ModelChoiceField(
        to_field_name='uid', queryset=bar_qs)

    class Meta:
        model = Foo
        fields = ('bar',)
```

### Expected output
As per the [docs](https://django-filter.readthedocs.io/en/master/ref/filters.html#modelchoicefilter):
> The queryset argument also supports callable behavior. If a callable is passed, it will be invoked with Filterset.request as its only argument. This allows you to easily filter by properties on the request object without having to override the FilterSet.__init__.

The code is consistent with the docs.

### Actual output
The django `runserver` command crashes with stack trace. 
See the relevant parts of the stack-trace:

```
  File "/app/.venv/lib/python3.7/site-packages/django_filters/fields.py", line 265, in __init__
    super().__init__(*args, **kwargs)
  File "/app/.venv/lib/python3.7/site-packages/django/forms/models.py", line 1181, in __init__
    self.queryset = queryset
  File "/app/.venv/lib/python3.7/site-packages/django/forms/models.py", line 1206, in _set_queryset
    self._queryset = None if queryset is None else queryset.all()
AttributeError: 'function' object has no attribute 'all'
```

### Hints
I had a cursory look at the code and, it seems, handling of `queryset` param is delegated to django-forms and it is not handling callable (I may be wrong here). The relevant code from django package (forms/models.py) below:
```python
    def _set_queryset(self, queryset):
        self._queryset = None if queryset is None else queryset.all()
        self.widget.choices = self.choices
```

**Comment by rpkilby** [comment]
Hi @liquidscorpio. You've accidentally created the filterset with a form field instead of the filter. Instead of using `ModelChoiceField`, you should be using `ModelChoiceFilter`.

**Comment by liquidscorpio** [comment]
@rpkilby Thanks!
Apologies, should have been more diligent :man_facepalming:.
