### ISSUE TITLE
Required BaseInFilters aren't required

### ISSUE THREAD

**Issue by knyghty** [carltongibson/django-filter#1213]
I'm not sure if this also applies to forms or not, I only tested in DRF.

```python
class StringInFilter(filters.BaseInFilter, filters.CharFilter):
    pass

class ThingFilterSet(filters.FilterSet):
    foo = StringInFilter(field_name="foo", required=True)
    ...
```

If I just use a regular `CharFilter` it works, and will show an error when accessing the view. But using `BaseInFilter`, it doesn't seem to care if it's missing.

**Comment by knyghty** [comment]
Woops, this is a duplicate of https://github.com/carltongibson/django-filter/issues/869 which I'll reopen instead.

**Comment by rpkilby** [comment]
Thanks @knyghty. Opened #1215.
