### ISSUE TITLE
Docs include unreleased features

### ISSUE THREAD

**Issue by Mist3ry** [carltongibson/django-filter#1214]
Hello everyone,
im trying to change default lookup expr behavior and i found in official documentation, that this can be done by defining an environment in `settings.py` to do that:
```
FILTERS_DEFAULT_LOOKUP_EXPR = 'contains'
``` 
but this did not bring the expected result, his behavior is still `exact`.  I also noticed that in my `django-filters/conf.py` [that line](https://github.com/carltongibson/django-filter/blob/fbb67b6d8d8a8114c69c16b8eaba81cea68e839e/django_filters/conf.py#L10) is missing.

Versions that I installed with pip
```
django-filter==2.2.0
djangorestframework==3.11.0
python==3.7.5
```

**Comment by rpkilby** [comment]
Hi @Mist3ry. It looks like the docs have been pushed before that feature has been released. We either need to revert the docs or issue a new release.

**Comment by Mist3ry** [comment]
Hi @rpkilby Thank you, looking forward to release

**Comment by carltongibson** [comment]
I've re-enabled the `stable` docs version, which currently points to v2.2, and in theory updates to the latest tag.

**Comment by rpkilby** [comment]
Closing as it looks like this has been resolved? Default docs point to stable, which don't include the unreleased features.
