### ISSUE TITLE
[Filter DRF browsable API filterchoices]

### ISSUE THREAD

**Issue by gabn88** [carltongibson/django-filter#1223]
I'm not sure where to place this issue, so I hope this is the correct place.

When I have filters on foreignkeys, the filter button at the top of the page of the browsable API will show ALL possible choices for the foreign key. With 2,5m rows the loading becomes very slow. But it is also a potential security risk (imagine having names of persons to filter for).

In the past I have disabled the browsable API completely because of this, but I would like to start using it again. 
When I look into filterset.py, the function `remote_queryset(f)` is responsible for creating the queryset. It would be nice if there was an easy way to override this. For example in DRFs serializers I use a SecureSerializerMixin to make sure that nobody creates an object with a related instance they should not be able to view, and also to limit the choices in the browsable API at the same time.

I think the current way the FilterSet is setup does not allow an easy Mixin-based approach to limit the choices, or am I wrong?

**Comment by rpkilby** [comment]
> When I look into filterset.py, the function `remote_queryset(f)` is responsible for creating the queryset.

`remote_queryset` is a default helper that is only used for generated relationship filters (i.e.,  `Meta.fields`). If you have a generic helper that provides more complex/secure behavior, then you could override the defaults on your filterset's `FILTER_DEFAULTS`. Something like..

```python
class MyMixin:
    FILTER_DEFAULTS = deepcopy(FilterSet.FILTER_DEFAULTS)
    FILTER_DEFAULTS[models.ForeignKey]['extra'] = lambda f: {
        'queryset': my_queryset_helper(f),
    }
    FILTER_DEFAULTS[...] = ...

class MyFilterset(MyMixin, FilterSet):
    class Meta:
        model = MyModel
        fields = ['my_relationship']
```

Alternatively you could just override the `filter_for_field` or `filter_for_lookup` methods. e.g.,

```python
class MyMixin:
    @classmethod
    def filter_for_lookup(cls, field, lookup_type):
        filter_class, params = super().filter_for_lookup(field, lookup_type)

        if 'queryset' in params:
            params['queryset'] = my_queryset_helper(field)

        return filterset_class, params
```

Also note that querysets accept a callable as described [here](https://django-filter.readthedocs.io/en/stable/guide/usage.html#filtering-the-related-queryset-for-modelchoicefilter), which you'll probably need to leverage to get per-user filtering.

**Comment by gabn88** [comment]
Ah that's great!
I have now overwritten the queryset on a case-by-case way, but this is much cleaner and much easier to not forget.

**Comment by gabn88** [comment]
Okay, I might have overlooked something.

```
class SecureFilterMixin:
    '''
    Makes sure that the 'secure_queryset' method on related fields is called
    '''
    @classmethod
    def filter_for_lookup(cls, field, lookup_type):
        filterset_class, params = super().filter_for_lookup(field, lookup_type)
        if 'queryset' in params:
            params['queryset'] = secure_queryset

        return filterset_class, params
```
Let's say I want to use this Mixin. now the only thing that is passed on to the secure_queryset method is the request. Nothing else. So how can I filter the queryset dynamically? 

I know I could do "MyModel.objects.filter_secure()", but I don't know from the request what MyModel is. On the other hand, if I doe secure_queryset(field) in the Mixin, it gets called on initialization and with only the field, and without request...

**Comment by rpkilby** [comment]
So, `remote_queryset` is producing default querysets that are suitable for a given field. Similarly, your implementation would need to generate a per-field queryset/callable.

One option is to have a wrapper function that accepts the model field. 

```python
def generate_secure_queryset_fn(field):
    model = field.related_model

   def secure_queryset(request):
        return do_something_with(model)

class SecureFilterMixin:
    @classmethod
    def filter_for_lookup(cls, field, lookup_type):
        filterset_class, params = super().filter_for_lookup(field, lookup_type)
        if 'queryset' in params:
            params['queryset'] = generate_secure_queryset_fn(field)

        return filterset_class, params
```

Alternatively, you can bind the field to a generic function using `parial`.

```python
from functools import partial

def secure_queryset(request, field):
    model = field.related_model
    return do_something_with(model)

class SecureFilterMixin:
    @classmethod
    def filter_for_lookup(cls, field, lookup_type):
        filterset_class, params = super().filter_for_lookup(field, lookup_type)
        if 'queryset' in params:
            params['queryset'] = partial(secure_queryset, field=field)

        return filterset_class, params

**Comment by gabn88** [comment]
Thank your for taking the time to learn me something new! I will try both methods!
