### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by TheMcGoose** [carltongibson/django-filter#1224]
It looks like there have been a number of changes since the last release https://github.com/carltongibson/django-filter/compare/2.2.0...master

One of these is https://github.com/carltongibson/django-filter/pull/1127 without which this library does not work with the latest versions of Django.

@carltongibson would it be possible to release the current version out to PyPi? Thanks!

**Comment by carltongibson** [comment]
Yes, it's coming. Would be there but we've been delayed by the pandemic. 

If you're desperate I suggest using [pip's VCS support to install master directly](https://pip.pypa.io/en/stable/reference/pip_install/#git).

**Comment by danihodovic** [comment]
Any update on this @carltongibson ?

**Comment by carltongibson** [comment]
@danihodovic If there were any update it would appear here.
