### ISSUE TITLE
How to simply add a class (CSS) to django-filter? 

### ISSUE THREAD

**Issue by alnikolaj** [carltongibson/django-filter#1228]
I wish to add CSS classes to my django_filters filter form, nonetheless, I do not manage to get it working and I do somehow try something I either get an error (see below) or it messes with the HTML tag, e.g. a dropdown (select tag) gets converted to a text field, which is not good. 

```
#filters.py
class OrderFilter(django_filters.FilterSet):

class Meta:
    model = Order
    fields = ['order', 'customer', 'status']
    exclude = ['delivery_date']

#THIS BELOW IS HOW I DO IT IN FORMS.PY - ANY EQUIVALENT FOR DJANGO-FORMS? 
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        #apply css to all fields
        for visible in self.visible_fields():
            visible.field.widget.attrs['class']  = 'w-full p-2 bg-gray-100 border border-gray-100'

        #apply css to individual fields     
        self.fields['order_date'].widget.attrs['class'] = 'flatpickr w-full bg-gray-100'
```

Is there somehow a possibility to easily add CSS classes to the filter fields as in the above example for the forms.py?

**Comment by rpkilby** [comment]
Hi @alnikolaj. You can provide a custom form class via the [FilterSet options](https://django-filter.readthedocs.io/en/stable/ref/filterset.html#form). e.g.,

```python
class MyForm(Form):
    def __init__(self, *args, **kwargs):
        # custom form logic
        ...

class MyFilterset(FilterSet):
    class Meta:
        model = MyModel
        fields = [...]
        form = MyForm
```

Note that you will want to inherit the regular `Form` class here, not `ModelForm`.

Alternatively, if you have a one-off case, you could pass the widget as part of a filter's arguments. Any arguments not consumed by the filter class will be used to construct its underlying form field.

```python
class MyFilterset(FilterSet):
    my_field = CharFilter(widget=TextInput(attrs={'class': 'myfieldclass'}))
    ...
```
