### ISSUE TITLE
django-filters and MPTT

### ISSUE THREAD

**Issue by ckarrie** [carltongibson/django-filter#123]
Hi, I want to get all underlying Items in all sub-waregroups in a selected waregroup.

I.e.:

WareGroup 1
--- WareGroup 1.1
------ Item A
------ Item B
------ WareGroup 1.1.1
--------- Item C
--------- Item D
--- WareGroup 1.2
------ Item E
------ Item F

If I filter for **WareGroup 1** I want to get Item A to Item F.
If I filter for **WareGroup 1.1** I want to get Item A to Item D.

In MPTT its possible with filtering the tree_id.

I.e. getting all Items for one Waregroup **WareGroup 1.1** (including in subwaregroups):

``` python
# Edit: This is wrong!!!!
waregroup = WareGroup.objects.get(pk=1)
return Item.objects.filter(waregroup__tree_id=waregroup.tree_id)
# Edit: This is correct!!!!
waregroup = WareGroup.objects.get(pk=1)
return Item.objects.filter(waregroup__in=self.get_descendants(include_self=True))
```

Could you please help me?

**Comment by robalar** [comment]
Hi all,

I know this is a very old issue, but it is the first (and only) Google result for this behaviour. I managed to get a working implementation for the desired behaviour, however being a novice contributor I imagine it can be improved greatly. Plus as mentioned above I'm not sure this is even the right repo to submit a pull request to.

    from mptt.forms import TreeNodeChoiceField
    import django_filters

    class TreeNodeChoiceFilter(django_filters.ModelChoiceFilter):
        field_class = TreeNodeChoiceField

        def filter(self, qs, value):
            if value != self.null_value:
                return self.get_method(qs)(**{f'{self.field_name}__in': value.get_descendants(include_self=True)})

            qs = self.get_method(qs)(**{'%s__%s' % (self.field_name, self.lookup_expr): None})
            return qs.distinct() if self.distinct else qs

Feedback greatly appreciated :)

**Comment by carltongibson** [comment]
Hi @robalar --- I guess I'd take a PR on the docs showing the Filter implementation in the Tips and Tricks section. (It's not a filter I'd include in the package itself.)
