### ISSUE TITLE
Filter field rename in FilterSet class no longer works in 2.3

### ISSUE THREAD

**Issue by Bel-Shazzar** [carltongibson/django-filter#1232]
Hello,
I have a filter that looks something like this:
```python
class AwesomeFilter(django_filters.FilterSet):
    shorter_name = django_filters.CharFilter(
        field_name='way_too_long_name__what_were_you_even_thinking')

    class Meta:
        model = AwesomeModel
        fields = {'shorter_name':['exact']}
```
Since today (as in, update to django-filter 2.3.0) this throws the following error on first import:
`TypeError: 'Meta.fields' must not contain non-model field names: shorter_name`

Is there a new way to do this or might this be a bug?

**Comment by rpkilby** [comment]
Hi @Bel-Shazzar. This was changed in #1061, and declared filters are no longer allowed in a `Meta.fields` dict. All you need to do is remove `shorter_name`. The PR goes into more detail, but the short version is that the old behavior would break quietly. e.g., if you had

```python
    class Meta:
        model = AwesomeModel
        fields = {'shorter_name':['exact', 'contains']}
```

then you might expect a `shorter_name__contains` filter to be generated. However this never worked, and due to a bug, the filterset failed to raise an appropriate exception. That exception is now raised.

**Comment by Bel-Shazzar** [comment]
Thank you @rpkilby . I wasn't even considering this since I am so used to putting everything in the Meta.fields

**Comment by ron8mcr** [comment]
Can note about this change (#1061) be added to Changelog (https://github.com/carltongibson/django-filter/blob/master/CHANGES.rst#version-230-2020-6-5)? This looks like breaking change, and there is no mention of it in changelog

**Comment by carltongibson** [comment]
@ron8mcr Happy to merge that in yes.

**Comment by ayushin** [comment]
This certainly *IS* a breaking change.

My question is how do I ensure that the non-field filters that are no longer in the Meta.fields are called in the correct sequence?

@carltongibson I think it is too early to close this issue.

**Comment by ayushin** [comment]
And then of course this should go too?

` AssertionError: Setting 'Meta.model' without either 'Meta.fields' or 'Meta.exclude' has been deprecated since 0.15.0 and is now disallowed. Add an explicit 'Meta.fields' or 'Meta.exclude' to the OfferFilterSet class.`

**Comment by MortenKaae** [comment]
I just ran into this error when upgrading the package as well. It would help a lot to have this mentioned as a breaking change.
