### ISSUE TITLE
Error on non-model field with version 2.3.0

### ISSUE THREAD

**Issue by Ansa89** [carltongibson/django-filter#1236]
When using django-filter 2.3.0 I get `TypeError: 'Meta.fields' must not contain non-model field names: <NAMES_HERE>`
for my non-model fields even if they are correctly declared as variables inside my filter (as per official documentation).
The same code works fine with 2.2.0, so I bisected the problem to carltongibson/django-filter@62e621d64c1cefe2f2ebda806674777e5587a09e (file `django_filters/filterset.py`).
Please note that my `fields` variable is of type `dict`.

If you need more info, just ask me.
If I missed/misunderstood something, I apologize and I kindly ask you to post some reference/link to proper documentation.

**Comment by carltongibson** [comment]
Same issue as was reported in #1232. 

In principle the change was fixing the issue in  #1013, but I wonder if we're blocking a legitimate usage...? @Ansa89: how exactly did you hit this?

**Comment by Ansa89** [comment]
Thanks for the reply, I hit this updating a project that was using `django-filter==2.0.0` (then upgraded to 2.2.0 without issues).

Basically I have a lot of filters like this:
```python
class TestModel(models.Model):
    foo = models.CharField()
    # no bar field


class TestFilter(django_filters.FilterSet):
    bar = django_filters.CharFilter(field_name='bar', method='filter_bar')
    bar__contains = django_filters.CharFilter(field_name='bar__contains', method='filter_bar')

    class Meta:
        model = TestModel
        fields = {
            'foo': ['exact', 'iexact', 'icontains'],
            'bar': ['exact', 'contains']
        }

    def filter_bar(self, queryset, name, value):
        # actual code here
        pass
```

Looking at carltongibson/django-filter#1061, I see you removed the possibility to use declared filters with the `Meta.fields` dict.
Honestly, I would prefer to use a `dict` instead of a `list` to declare my filters, since it looks more clear to me; also please note that I do **not** expect the library to auto-generate the "bar__contains" filter (or any other non-model field).

IMHO it was clear since the beginning I started using this library (and read some documentation) that **every** non-model field must be declared and the programmer has to explicitly manage it, but apparently it was only me.

Do you think it is possible to bring back the old behavior?

**Comment by carltongibson** [comment]
@rpkilby Can I get your thoughts here? Why is this not a regression? (Ta!)

**Comment by Alir3z4** [comment]
We have the exact problem and use case.
Had to downgrade back to `2.2.0`

**Comment by Ansa89** [comment]
@carltongibson @rpkilby any news on this?

**Comment by devinnasar** [comment]
I am experiencing this issue as well. It's keeping me from using field names that I've renamed in the serializer:

```
# models.py

class Tenant(models.Model):
    # ...
    def __str__(self):
        return self.name

    name = models.CharField(max_length=200)
    environment = models.ForeignKey(
        Environment,
        on_delete=models.SET_NULL,
        null=True
    )

```
```
# serializers.py
class TenantSerializer(WritableNestedModelSerializer):

    tenant_name = serializers.CharField(source='name', read_only=False)
    tenant_environment = EnvironmentSerializer(source='environment', many=False, read_only=False, partial=True)

    class Meta:
        model = Tenant
        fields = ('id', 'tenant_name', 'tenant_environment')

```

```
# views.py

class TenantFilter(filters.FilterSet):

    tenant_name = filters.CharFilter(field_name='name')
    tenant_environment = filters.NumberFilter(field_name='environment')
    tenant_environment__name = filters.CharFilter(field_name='environment__name')

    # I need a way of renaming the fields here.
    class Meta:
        model = Tenant
        fields = {
            'tenant_name': ['exact', 'in', 'startswith'],
            'tenant_environment': ['exact'],
            'tenant_environment__name': ['exact', 'in', 'startswith']
        }
```

And the error:
```
app_1    |   File "/env/lib/python3.8/site-packages/django_filters/filterset.py", line 71, in __new__
app_1    |     new_class.base_filters = new_class.get_filters()
app_1    |   File "/env/lib/python3.8/site-packages/django_filters/filterset.py", line 358, in get_filters
app_1    |     raise TypeError(
app_1    | TypeError: 'Meta.fields' must not contain non-model field names: tenant_name, tenant_environment, tenant_environment__name
```

**Comment by carltongibson** [comment]
So... re-reading #1061... You should remove the declared filters from `fields`. It doesn't make sense to declare the filter and then try to add extra lookups via a dict in `fields`.

**Comment by devinnasar** [comment]
@carltongibson but how am I expected to give the filters multiple lookups? It errors out when I try:
```
tenant_name = filters.CharFilter(field_name='name', lookup_expr=['exact', 'in', 'startswith])
```

**Comment by devinnasar** [comment]
Thanks for the pointer @carltongibson, however, now the behavior is inconsistent from lookups I specify in the fields. When using LookupChoiceFilter, now I'm required to pass in a lookup parameter to my querystring. I don't want that, I want it to behave exactly as it does when specifying the lookups for fields.

```
    tenant_name = filters.LookupChoiceFilter(
        field_name='name',
        label='Tenant name',
        field_class=forms.CharField,
        lookup_choices=[
            ('exact', 'Equals'),
            ('in', 'In'),
            ('startswith', 'Starts with')
        ]
    )
```

- Scenario 1
Input: `https://host/api/tenants/?tenant_name=my-target-object-name`
Expectation: Returns one object with the target tenant name

Result:
```
{
    "tenant_name": [
        "Select a lookup."
    ]
}
```

- Scenario 2
Input: `https://host/api/tenants/?tenant_name__exact=my-target-object-name`
Expectation: Returns one object with the target tenant name

Result:
```
[
    {
        "id": 3,
        "tenant_name": "my-target-object-name",
        ...
    },
    {
        "id": 1,
        "tenant_name": "not-my-target-at-all-1",
        ...
    },
    {
        "id": 2,
        "tenant_name": "not-my-target-at-all-2",
        ...
    }
]
```

- Scenario 3
Input:
`https://host/api/tenants/?tenant_name=my-target-object-name&tenant_name_lookup=exact`
Expectation: Returns one object with the target tenant name without requiring `tenant_name_lookup` param

Result:
```
[
    {
        "id": 3,
        "tenant_name": "my-target-object-name",
        ...
    }
]
```
Is it just not possible to specify a list of acceptable lookups to a renamed field?

**Comment by carltongibson** [comment]
> I want it to behave exactly as it does when specifying the lookups for fields

If you manually declare one filter, you must manually declare them all. 

**Note**: this **never worked** how you’re thinking it should/did: Only the manually declared filter was ever created. (The other lookups for the key in the `fields` dict were just silently passed over.

**Comment by devinnasar** [comment]
@carltongibson Ahh I see. Apologies if I could have come to that sooner. One thing I'd like to mention before concluding is that it looks like it does indeed work when both manually declared filters and lookups in the fields dict are working. I'm noticing it in the HTML view of my api. I've got it working the way I need now. Thanks!
