### ISSUE TITLE
ValidationError using parameters with invalid UUID 

### ISSUE THREAD

**Issue by CleitonDeLima** [carltongibson/django-filter#1241]
When I have a model where the id is UUID, using `ModelMultipleChoiceFilter` or `ModelChoiceFilter`, making a request with an invalid UUID happens the error, example: 

```
GET: ...path/?related_field=xxxxxxx
```

```python
ValidationError: '“xxxxxxx” is not a valid UUID.'
```

Is this behavior expected?

**Comment by rpkilby** [comment]
Hi @CleitonDeLima. Yes - filtering API results via query string will result in validation errors if the input is invalid. You should be getting an HTTP 400 response.

**Comment by CleitonDeLima** [comment]
Ok @rpkilby 

When it comes to the browser, doing the get, shouldn't this error be a form error?

**Comment by rpkilby** [comment]
Sorry - I assumed you were using DRF here. The response will depend on your view. Internally, the `FilterSet` will raise the `ValidationError`, however the view can  handle errors  in a variety of ways. If using the DRF filter backend, validation errors will be re-raised as DRF's own `ValidationError` class, resulting in a 400 response with a body containing the error dict. If using the generic CBV mixin, the view will return a 200 respons with the errors rendered to the template.

**Comment by CleitonDeLima** [comment]
> Sorry - I assumed you were using DRF here. The response will depend on your view. Internally, the `FilterSet` will raise the `ValidationError`, however the view can handle errors in a variety of ways. If using the DRF filter backend, validation errors will be re-raised as DRF's own `ValidationError` class, resulting in a 400 response with a body containing the error dict. If using the generic CBV mixin, the view will return a 200 respons with the errors rendered to the template.

Right,  
I'm using `FilterView` but I'm getting error 500 and not 200 with the error rendered by the form.

![image](https://user-images.githubusercontent.com/4956372/90014138-f56f7800-dc7c-11ea-9006-4ab2748ce739.png)

I found the error, I'm using a `django-select2` widget, it is not handling form errors.

My filterset_class:  
```python
class MyFilterSet(django_filters.FilterSet):
    field = django_filters.ModelMultipleChoiceFilter(
        queryset=FieldSelect2MultipleWidget.queryset,
        widget=FieldSelect2MultipleWidget
    )
```

I'll see what it can be, thanks for the help @rpkilby

**Comment by rpkilby** [comment]
The widget should only be responsible for parsing the field value and rendering its HTML widget. It shouldn't be raising a `ValidationError`. 

> I'm using `FilterView` but I'm getting error 500 and not 200 with the error rendered by the form.

Can you post your view code? The issue is most likely there.

**Comment by CleitonDeLima** [comment]
> Can you post your view code? The issue is most likely there.

My view code:  
```python
class MyReportView(ExportViewFormMixin, FilterView):
    template_name = 'app/mymodel_filter.html'
    queryset = MyModel.objects.all()
    filterset_class = MyFilterSet
    paginate_by = 30
    model = MyModel
    formats = [base_formats.CSV, base_formats.XLSX]
    resource_class = MyResource
```
If removing the `FieldSelect2MultipleWidget` works as expected.  
`ExportViewFormMixin` only works on post.

**Comment by rpkilby** [comment]
Hm. I'm not sure what's going on here. What's providing `FieldSelect2MultipleWidget`? It's not in django-select2.

**Comment by CleitonDeLima** [comment]
> Hm. I'm not sure what's going on here. What's providing `FieldSelect2MultipleWidget`? It's not in django-select2.

It seems that the problem is [here](https://github.com/codingjoe/django-select2/blob/master/django_select2/forms.py#L458). The form has errors but in the render where the error happens.  
I'll check what can be done in django-select2.

**Comment by codingjoe** [comment]
Joe here, from `django-select2`. After reviewing this and the other discussion you opened, I believe a stacktrace would go a very long way here. Can you please past it here and ping me? Best, Joe
