### ISSUE TITLE
get_schema_fields doesn't provide a way to add descriptions for filters

### ISSUE THREAD

**Issue by lpulley** [carltongibson/django-filter#1242]
I'm using DRF to generate a schema for my API. Several of my views have filters on them, but there seems to be no way for me to define a description for each field. Thus, I'm left with documentation like this:

![image](https://user-images.githubusercontent.com/7193187/87713393-bb8b7e80-c76f-11ea-8ee2-9e062c09be0d.png)

(The `mission` parameter is a filter, but the docs don't indicate that in any way. "mission" is not a good description of the parameter `mission`.)

Other things in the schema generation seem to use docstrings as descriptions for fields. But I'm not sure what the best way is. Unless there *is* already a way to set schema descriptions on filters and I'm missing it somehow?

**Comment by carltongibson** [comment]
Hi @lpulley — no, not really it doesn't. 

I guess, you subclass the backend and add the logic you need there. I'd be very happy to look at PRs adding extra functionality here: the schema generation is currently _minimal_. (I guess we don't need a lot, but a little more would be good...)

**Comment by lpulley** [comment]
I'm looking further into this, and it seems like there is more implementation of this than I thought; I didn't realize the `description` item of `Field` had been deprecated and moved into the `schema` item, which django-filter *does* define. I found this line indicating I need to set some value for `'help_text'` in the `extra` field of the filter:

https://github.com/carltongibson/django-filter/blob/434dfabdf59e6c6bba01aac7c47b07ab38e20ade/django_filters/rest_framework/backends.py#L113

and it turns out that the base `Filter` class does dump all `kwargs` into `self.extra`:

https://github.com/carltongibson/django-filter/blob/434dfabdf59e6c6bba01aac7c47b07ab38e20ade/django_filters/filters.py#L80

which in theory should mean that I could do `foo = filters.ModelChoiceFilter(queryset=Foo.objects.all(), help_text='THIS IS HELP TEXT')`, for example, and have "THIS IS A HELP TEXT" show up in the docs for that filter. But it doesn't, so I must be missing something.

I know the filter is getting `'help_text'` set in its `extra`; I've tested that, and it's working. As far as I can tell, the schema returned in this line should contain "THIS IS A HELP TEXT" in `description`:

https://github.com/carltongibson/django-filter/blob/434dfabdf59e6c6bba01aac7c47b07ab38e20ade/django_filters/rest_framework/backends.py#L138

But it doesn't show up in the schema. Any idea where the disconnect is?

**Comment by lpulley** [comment]
It also does appear that Django REST Framework is using the function.

https://github.com/encode/django-rest-framework/blob/4b06e0a5a114b7631bd237e29e2d6d22412a50bd/rest_framework/schemas/coreapi.py#L526

**Comment by lpulley** [comment]
I'm getting this result inspecting my `FilterSet` in the Django shell:

```py
>>> import api.models
>>> list(api.models.Foo.FilterSet.base_filters.items())[0][1].extra.get('help_text')
'BAR FILTER HELP TEXT'
```

which is mirroring what happens in `get_schema_fields` and `get_coreschema_field` in `DjangoFilterBackend`.

https://github.com/carltongibson/django-filter/blob/434dfabdf59e6c6bba01aac7c47b07ab38e20ade/django_filters/rest_framework/backends.py#L113

And yet, my docs don't show my help text. I've been digging at this for an hour today and I still don't see why `help_text` doesn't result in anything showing up in the docs. If anyone knows anything about this I'd love to hear it.

**Comment by carltongibson** [comment]
Hmmm. Possibly the HTML template is just not using the value...? Sorry I'm not sure. This doesn't really look like an issue with django-filter... 😬

**Comment by lpulley** [comment]
I'm definitely starting to agree with you. I'll create an issue where I think it's relevant and link it back here for context later.

**Comment by carltongibson** [comment]
Ok thanks @lpulley. I'll close here. Happy to reopen if it's an issue on our end. 👍
