### ISSUE TITLE
Unclear error when configuring filters 

### ISSUE THREAD

**Issue by affonsobrian** [carltongibson/django-filter#1245]
This is not really a bug, but it is something that makes a programming error to be a little bit unclear.
When creating a Filter class such as the following:                             
```python                                                                       
class EngineFilter(filters.FilterSet):                                          
    class Meta:                                                                 
        model = Engine                                                          
        fields = {"model": ["exact"], "brand": ["exact"]}                      
```                                                                             
                                                                                
if for some reason you forget to use a tuple, set, or a list and leave it as a string like the following example:
                                                                                
```python                                                                       
class EngineFilter(filters.FilterSet):                                          
    class Meta:                                                                 
        model = Engine                                                          
        fields = {"model": ["exact"], "brand": "exact"}                        
```                                                                             
                                                                                
It will raise an error saying that the _brand_ attribute cannot be searched by 'e'.
                                                                                
This happens because the library tries to iterate through the string and the first element is _e_ which is not valid.
                                                                                
A solution for this would be a validation that raises an exception if the value is a incorrect type and explains that you must pass one of those valid types instead of the used type (in this example string).

**Comment by affonsobrian** [comment]
I created this Pull Request to show the possible solution.

**Comment by rpkilby** [comment]
Hi @affonsobrian. Thanks for raising the issue, but I'm going to close this as a probable wontfix. The error is raised  during the filterset's class creation (not after the fact in some obscured location), and the message is already fairly explanatory:

```
FieldLookupError: Unsupported lookup 'e' for field 'vehicles.Engine.brand'.
```
