### ISSUE TITLE
docs declaring filters (update request)

### ISSUE THREAD

**Issue by onno-timmerman** [carltongibson/django-filter#1249]
The docs show how declare filters with model Meta:
 https://django-filter.readthedocs.io/en/master/guide/usage.html#declaring-filters

If you follow the docs you will get an error. 

`AssertionError: Setting 'Meta.model' without either 'Meta.fields' or 'Meta.exclude' has been deprecated since 0.15.0 and is now disallowed. Add an explicit 'Meta.fields' or 'Meta.exclude' to the`

You need to set fields or it will not work. Although it look obvious what needs to be done. Still this might confuse somebody thats starting out with django-filters.

**Comment by carltongibson** [comment]
Hi @onno-timmerman. Super, OK, yes! Thanks for the suggestion. 

Fancy making a PR with the change?
