### ISSUE TITLE
NullBooleanField is Deprecated in Django 3.1 Removed in Django 4.0

### ISSUE THREAD

**Issue by smithdc1** [carltongibson/django-filter#1250]
Following the fix for `url()` there is one remaining Warning showing in [Travis.](https://travis-ci.org/github/carltongibson/django-filter/jobs/710248454)

```
WARNINGS:
tests.User.is_employed: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use BooleanField(null=True) instead.
```
It's being generated by this line here

https://github.com/carltongibson/django-filter/blob/52eece7b3b89109232669697c53e1b3001a9879b/tests/models.py#L50

As previous versions of Django will need to be supported for some time I investigated trying to [Temporarily suppress warnings](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings). But fell short of a solution that worked. Sorry I've not been able to find a solution for this. 

More than happy to look further if someone can point me in the right direction as I'm missing something.

**Comment by carltongibson** [comment]
`BooleanField(null=True)` has been allowed since Django 2.1. We support Django 2.2+, so can we just change the model declaration to use `BooleanField(null=True, default=False)`?
