### ISSUE TITLE
Package Version compatible with Django 3.1

### ISSUE THREAD

**Issue by domdinicola** [carltongibson/django-filter#1253]
@carltongibson do you have any idea of when next version would be released?
Thanks!!

**Comment by rpkilby** [comment]
Hi @domdinicola. django-filter 2.3 _should_ be  compatible with Django 3.1. #1252 added 3.1 to the test matrix without any additional changes.

**Comment by carltongibson** [comment]
Yes, as @rpkilby says, I'm not expecting any issues... did you encounter any?

To answer the question: 

I'm working on Channels at the moment. 

Once that's updated DRF is next on my list. 

**Then** a round of smaller maintenance releases for django-filter and friends. 

That's the plan anyway. As I say, if there's an actual issue I can review that.

**Comment by domdinicola** [comment]
@rpkilby @carltongibson my bad..
issue was DRF which just released 3.11.1

closing this
