### ISSUE TITLE
Django_Filters :no need to show all items using object.all() at the first load

### ISSUE THREAD

**Issue by technqvi** [carltongibson/django-filter#1256]
I am new for Django_Filter

As I notice, django_filter always loads all objects on the firs loading despite not filtered yet. Due to a large amount of data in the table in the database. So it results in poor performance for loading all objects unnecessarily.

### **_it is rather unreasonable in my view. Thus the better way it should filter a result whenever click button only._**

How to set Django_Filter in order to show the result when only click the search button(I don't want to list all items by using objects.all()).

[
<img width="438" alt="search-poor" src="https://user-images.githubusercontent.com/38780060/90382558-1b47b300-e0a9-11ea-95f7-59dbcd505203.png">
](url)

[You can click this like for more detail in stack flow (it is the same question as this issue)](https://stackoverflow.com/questions/63448278/django-filters-no-need-to-show-all-items-using-object-all-at-the-first-load)

Thank you in advance.
Pongthorn

**Comment by rpkilby** [comment]
Hi @technqvi. The `FilterSet` filters the input queryset based on the request's query params. It is not responsible for making a determination as to whether the result set is too large for rendering purposes. 

Looking at your SO post, your view function should filter the `inventories` list further.
