### ISSUE TITLE
import error on django 3.1

### ISSUE THREAD

**Issue by MJoshua25** [carltongibson/django-filter#1261]
I have this error with Django 3.1 and django-filter 2.3.0

ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.fields'

**Comment by rpkilby** [comment]
Hi @MJoshua25. You might have had an env or installation issue, as 2.3 specifically fixes this bug. Please ensure that you have the latest version installed.

v2.3.0:
https://github.com/carltongibson/django-filter/blob/56eaae15e4fab97483e1353080a0c320f18c1014/django_filters/utils.py#L5

v2.2.0:
https://github.com/carltongibson/django-filter/blob/da4b64ea8dde19304b552592a32b343e9aefe9da/django_filters/utils.py#L10

**Comment by MJoshua25** [comment]
It was an env issue
