### ISSUE TITLE
Improper search when rendering drf filter button in browsable api

### ISSUE THREAD

**Issue by CoffeeExpress** [carltongibson/django-filter#1263]
I am running django-filter with django-rest-framework.

If I have a `<foreign_key>_id` filter field, when the filter button is rendered in the django-rest-framework browsable api template, a query of `<foreign_key_model>.objects.all()` is triggered. For tables where <foreign_key_model> is exceptionally large, this effectively breaks that page of the browsable api. Is there a way to restrict that lookup from being executed?

**Comment by AviKKi** [comment]
@CoffeeExpress Can you share some code?
If you can create a repo with minimum reproducible code that would be really great.

**Comment by carltongibson** [comment]
@CoffeeExpress The filter form is using a ModelChoiceField. You can provide a better queryset there (using `select_related` say, provide precalculated `choices` or else switch to a integer field that won't offer the select UI but will act like a `raw_id` field. 

See https://django-filter.readthedocs.io/en/stable/ref/filterset.html#filter-overrides
