### ISSUE TITLE
Performance of Queries

### ISSUE THREAD

**Issue by king-11** [carltongibson/django-filter#1264]
In was profiling the SQL queries made using django_debug_toolbar even though I wasn't providing any query_param, the SQL queries are taking up a lot of time.

- with filter and no query params
```zsh
time: 10.28ms
queries: 7
```

- with no filter at the same endpoint
```zsh
time: 0.71ms
queries: 3
```

So to improve time when not filtering I implemented two separate views, I think those SQL queries are redundant and can really improve the filter performance when not filtering so how can I do that or is it part of django_filter only.

```python
class ImageFilterView(generics.ListAPIView):
    queryset = images.objects.prefetch_related('tag').select_related(
        'person__user').filter(verified=True).order_by('-likes')
    serializer_class = ImageSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    filter_backends = [DjangoFilterBackend]
    filterset_class = ImageFilter
    pagination_class = ImageListPagination

class ImageFilter(filterset.FilterSet):
    photographer = filters.CharFilter(
        field_name="instaHandle", lookup_expr="icontains")
    place = filters.CharFilter(field_name="place", lookup_expr="icontains")
    likes = filters.NumericRangeFilter(field_name="likes")

    class Meta:
        model = images
        fields = ('place', 'photographer', 'likes', 'person')
```

**Comment by AviKKi** [comment]
@king-11 Can you post the screenshots of your django_debug_toolbar ? Looking at the SQL queries would help.

I guess django-filter doesn't change queryset for blank query filters.

**Comment by carltongibson** [comment]
@king-11 See my https://github.com/carltongibson/django-filter/issues/1263#issuecomment-694064894 — it's essentially the same issue. If you can provide a better queryset to the filterset's form you can greatly reduce the number of queries you need to make.

**Comment by king-11** [comment]
@carltongibson as such am already using the most optimised queryset using prefect_related and select_related options

**Comment by king-11** [comment]
### with filterset class and no query parameters
![Screenshot_20200917_133602](https://user-images.githubusercontent.com/52061363/93439478-3e55c480-f8ec-11ea-9f60-d862e4818d5e.png)
### with no filterset class and no additional filtering
![Screenshot_20200917_133643](https://user-images.githubusercontent.com/52061363/93439573-5b8a9300-f8ec-11ea-99f8-2a874f135e5f.png)

**Comment by carltongibson** [comment]
Check that those are actually duplicate queries first (There's an issue in debug toolbar https://github.com/jazzband/django-debug-toolbar/issues/1239) It's likely only the one is real. (Do they have the exact same trace?) 

Also, check the time disabling SQL tracing, as that's pretty slow. You'll likely find it's **MUCH** faster. 

If your SELECT FROM image_store_photographer is already using the best queryset then there's not much else you'll be able to do (indexes maybe) — ultimately it HAS to fetch the values sometime. 

(If it's static you can cache...)

Hopefully some of that helps.

**Comment by king-11** [comment]
Ohh thanks for looking up that issue @carltongibson. Yeah I will lookup caching thanks for your advice :))
