### ISSUE TITLE
Filter a list of dicts

### ISSUE THREAD

**Issue by ebdavison** [carltongibson/django-filter#1277]
I have a table that I am displaying that comes from a list of dicts and the fields are not always the same.  So, I cannot use a Model-based filterset.

I did find a way to create a filterset dynamically, as such:

```
def FilterFactoryList(field_list, class_name):
    class_vars = {}

    for field in field_list:

        field_name = field
        class_vars[field_name] = django_filters.AllValuesFilter(
            field_name=field_name
        )

    class_vars["Meta"] = type("Meta", (object,), {"fields": "__all__"})

    klass = type(class_name, (django_filters.FilterSet,), class_vars)
    return klass

...

data = [{"a": 1, "b": 1, "c": 1},{"a": 1, "b": 1, "c": 1},{"a": 1, "b": 1, "c": 1}] 
col_list = ["a", "b", "c"]
filterset = FilterFactoryList(col_list, "queryFilter")
```

This gives me a filterset that is of type `<class 'django_filters.filterset.FilterSetMetaclass'>`.

So far, so good.

But now is where it gets tricky and where I get lost.  My data is a list of lists as you can see above.  

Doing the following obviously will not work as the data is not a queryset:

```
filter = query_filter(request.GET, queryset=data)
```

The result is the error `'list' object has no attribute 'model'` and I have also gotten an error about a missing `_default_manager`.

Any pointers or references would be appreciated.

**Comment by carltongibson** [comment]
This is out of scope for here. We're about filtering query sets as you've noticed. 

You'd have to write the Python to filter the list.
