### ISSUE TITLE
DjangoFilterBackend.filterset.qs in filter_queryset method is very expensive for large dataset

### ISSUE THREAD

**Issue by xmnlab** [carltongibson/django-filter#1278]
hi everyone! 

I have an application with `django-restframework`, `django-filter` and `elasticsearch`, and `django-filter` executes `filterset.qs` (https://github.com/carltongibson/django-filter/blob/master/django_filters/rest_framework/backends.py#L96) before any pagination and that makes elasticsearch load all data ... and, for a large database, it becomes very slow and throws an error in `elasticsearch` because the amount of data is higher than the limit. 

Any idea about how to work around this problem? thanks!!

**Comment by carltongibson** [comment]
>... and that makes elasticsearch load all data ...

🤔 django-filter is for the Django ORM. Elasticsearch isn't supported I'm afraid.
