### ISSUE TITLE
How can i render form for filter based on user login?

### ISSUE THREAD

**Issue by AhmedSalam22** [carltongibson/django-filter#1281]
sorry for bothering i spend all day to try figure out how I can filter files that shows on a form based on the current user
the dropdown has all value for all user!
 for example
  book= models.ForeignKey(owner, on_delete=models.CASCADE)
i want to filter this field to show only the data for the login user not all data

another problem Django-filter doesn't work well with pagination

hope you understand me

**Comment by carltongibson** [comment]
Hi. 

1. Make your form accept the user and set querysets based on that: 

```
class YourForm(forms.Form):
  def __init__(self, ..., user=None, ...):
    super().__init__(...)
    self.fields["model_choice_field"].queryset = ... .filter(user=user)
```

2. For pagination, get filterset.qs and pass that to your paginator.

**Comment by AhmedSalam22** [comment]
thank's but it doesn't work 
AttributeError: 'JournalFilter' object has no attribute 'fields'
```python

class JournalFilter( django_filters.FilterSet):
    class Meta:
        model = Journal
        fields = ['account', 'date' , 'balance' , "transaction_type"]

    def __init__(self,  user=None, **kwargs):
        super().__init__(**kwargs)
        self.fields["account"].queryset = Journal.objects.filter(owner=user)
```

**Comment by carltongibson** [comment]
You need to edit the `filterset.form`. https://django-filter.readthedocs.io/en/stable/ref/filterset.html#custom-forms-using-form

**Comment by AhmedSalam22** [comment]
Thank you so much for your time

**Comment by AhmedSalam22** [comment]
@carltongibson last question sir if you don't mind when i try
```python
class JournalListView(ListView):
    paginate_by = 10
    model = Journal

     def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context["filter"] = JournalFilter(data=self.request.GET , queryset = super().get_queryset(**kwargs) , user=self.request.user)
            print("-----------------")
            self.object_list =  context["filter"].qs```
 filterset.qs and pass that to your paginator. Doesn't work
