### ISSUE TITLE
Question: How to get the selected choices from ModelChoiceFilter

### ISSUE THREAD

**Issue by hkokko** [carltongibson/django-filter#1285]
I would like to set the selected choice from ModelChoiceFilter to a session variable and use it in other queries within the app. 

For example: 

class CultureCareerFilter(django_filters.FilterSet):
    culture = ModelChoiceFilter(queryset=Culture.objects.all())

    
    class Meta:
        model = CultureCareers
        fields = ['culture']

This works really well - I can select the cultures and the filter pics the careers for a culture

I would like to retain the selection of the culture and later on use it in other places during the user session - for example you have chosen "City" culture and I would like to use that in UI and other selections.  

How would I do that... 

I am a first time Django user at this point.

**Comment by hkokko** [comment]
Found a way to retain the selection of the culture above (just dig it from the rendering result). 

But how would I be able to set it as default choice the following time I come to filter page AND get this as the initial result of the page. 

So user would first time around select choice "Italian" from the list of cultures and get the list of related careers of Italian culture. This selection "Italian" culture is the saved to session variable

Next time you come to the page during the session I would like to have "Italian" selected as the choice and the list of careers populated with Italian careers. User should then be able to change it to "Spanish" careers by selecting from the ModelChoiceFilter. How could I accomplish that. 

Still very new with Django at this point.

**Comment by carltongibson** [comment]
Simplest way is to update the URL: `?culture=1` (where `1` is the ID for Italian). 

You can adjust the dict you pass as `data` to the FilterSet. (Copy `GET`, use `setdefault()`, and use that as `data`, rather than just `GET`)

Also see https://django-filter.readthedocs.io/en/stable/guide/tips.html#using-initial-values-as-defaults

**Comment by hkokko** [comment]
Thank you - worked perfectly.
