### ISSUE TITLE
Multiple query params will only return the last element

### ISSUE THREAD

**Issue by RyanSiu1995** [carltongibson/django-filter#1293]
Here is the list of my dependencies.
```
django-filter==2.4.0
djangorestframework==3.12.1
Django==3.1.3
```
I have an error with the filters under multiple values in query params.
The query params given by Django 3 is sth like this.
```
(Pdb) request.query_params
<QueryDict: {'target': ['a', 'b', 'c']}>
```
It will pass the `request.query_params` to `FilterSet` class as `data` here, https://github.com/carltongibson/django-filter/blob/master/django_filters/rest_framework/backends.py#L82-L87.
The `QueryDict` has a different behavior compared to `dict`.
Here, https://github.com/carltongibson/django-filter/blob/master/django_filters/filterset.py#L196, the code regards the `QueryDict` as `dict` directly.
The main difference between them is here.
```
> request.query_params['tagret']
'c'
> dict(request.query_params)['tagret']
 ['a', 'b', 'c']
```
This is not the bug on Django but the feature.
You could check it out the issue here, https://code.djangoproject.com/ticket/1130.

**Comment by robertsutherland** [comment]
Has anyone found a workaround for this?

**Comment by carltongibson** [comment]
This is working as expected. The query dict gets passed to the filter set, which uses a form to extract values. The form will fetch a single item or a list depending on the widget being used. e.g. an **multiple** select will expect a list. 

See the docs for [QueryDict.getList()](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.QueryDict.getlist) and e.g. [ChoiceWidget.value_from_datadict()](https://github.com/django/django/blob/0c42cdf0d2422f4c080e93594d5d15381d6e955e/django/forms/widgets.py#L654-L661) for examples. 

Good luck!

**Comment by Przemek625** [comment]
Have you found the solution?

**Comment by sylvaingable** [comment]
Depending on your use case, [MultipleChoiceFilter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#multiplechoicefilter) or [ModelMultipleChoiceFilter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#modelmultiplechoicefilter) might be a good fit.

It seems to me the OP problem can be solved by using a `QueryArrayWidget` (from the `django_filters.widgets` module).

Let's say you want to filter a `foo` `Charfield` with multiple values by performing an `__in` lookup then you could do it like this:

```python
from django_filters import rest_framework as filters
from django_filters.widgets import QueryArrayWidget

class CharInFilter(filters.BaseInFilter, filters.CharFilter):
    pass

class MutlipleValuesFilter(filters.FilterSet):
    foo = CharInFilter(widget=QueryArrayWidget)
```

NB: as per the source code comments, `foo` query params values can be formatted as:
* `?foo=bar,baz`
* `?foo[]=bar&foo[]=baz`
* `?foo=bar&foo=baz`
