### ISSUE TITLE
PostgreSQL's unaccent support

### ISSUE THREAD

**Issue by Pablo849** [carltongibson/django-filter#1299]
It would be interesting to have native support for PostgreSQL's unaccent filter. Both individually and chained for example with icontains

**Comment by carltongibson** [comment]
What does this look like at the ORM level? (A `Filter` is just wrapper around that.)

**Comment by Pablo849** [comment]
I use this solution in my filters, because in Spanish accents are a big problem with filters. It may not be the best option to carry it out. I just wanted to propose the functionality in case it was possible to integrate it into the core of the package. Sorry I can't give better information, I'm still inexperienced working with Django.

```
    def filter_for_field(cls, field, field_name, lookup_expr=None):
        if lookup_expr == 'icontains':
            if settings.DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql_psycopg2':
                lookup_expr = 'unaccent__icontains'
        return super().filter_for_field(field, field_name, lookup_expr)
```

**Comment by carltongibson** [comment]
OK, thanks for the extra info. I’ll have a think about it. 

Your approach looks fine.

**Comment by timnyborg** [comment]
I'd argue that it's better to be explicit, and leave it up to the developer to choose 'unaccent__icontains' for individual filters.

Using MSSQL, I had to write my own `unaccent` filter:

```python
@models.CharField.register_lookup
class UnAccent(models.Transform):
    """A transform that allows us to do accent-insensitive text searching in MSSQL
       Allows filters like Modelname.objects.filter(title__unaccent__startswith='Joao')
    """
    lookup_name = 'unaccent'

    def as_sql(self, compiler, connection):
        lhs, params = compiler.compile(self.lhs)
        return '{} COLLATE Latin1_General_CI_AI'.format(lhs), params
```

and then use it when only when I need to:

```python
class SearchFilter(filters.FilterSet):
    def filter_firstname(self, queryset, field_name, value):
        """Filters on firstname or nickname, accent-insensitive"""
        return queryset.filter(
            models.Q(firstname__unaccent__startswith=value)
            | models.Q(nickname__unaccent__startswith=value)
        )

    firstname = filters.CharFilter(
        label='First name',
        method='filter_firstname'
    )

    surname = filters.CharFilter(
        label='Surname',
        field_name='surname',
        lookup_expr='unaccent__startswith',
    )
   ...
```

Having django-filter apply an `unaccent` by default would be a bit magic, might have performance impacts on big query (maybe affect the use of indexes? not sure).

If you want to unaccent filters across a whole application, subclassing FilterSet with Pablo489's method would an easy solution.

**Comment by carltongibson** [comment]
Yes, I agree. Thanks @timnyborg
