### ISSUE TITLE
Easier method for customizing labels on filter forms

### ISSUE THREAD

**Issue by paulschreiber** [carltongibson/django-filter#1308]
It would be nice if there was an easier method to customize the labels on filters. Per [a StackExchange answer](https://stackoverflow.com/a/52477028/135850), I was able to do this by overriding `__init__()`.

It would be preferable if setting `labels` in the `Meta` subclass worked.

`views.py`
```python
class AssignmentList(FilterView):
	model = Assignment
	filterset_class = AssignmentFilter
```

`filters.py`
```python
class AssignmentFilter(django_filters.FilterSet):
	class Meta:
		model = Assignment
		fields = [ 'user' ]

	def __init__(self, *args, **kwargs):
		super(AssignmentFilter, self).__init__(*args, **kwargs)
		self.filters['user'].label='Assignee'
````

**Comment by carltongibson** [comment]
Hi @paulschreiber — Yes... but no. 😀 I don't want to add meta options here — it would lead to duplicating the entire `Form` API on `FilterSet`, which isn't a road we're going to go down. Overriding `__init__` is fine.

**Comment by paulschreiber** [comment]
@carltongibson Can you make this clearer in the docs? I had to find the example on StackOverflow.

**Comment by mohoo** [comment]
The example above does not work for `django_filters.rest_framework` in conjunction with `drf-spectacular` since the `__init__` is never called.

Here's what worked for me:
```python
from django_filters import rest_framework as filters

class AssignmentFilter(filters.FilterSet):
    class Meta:
        model = Assignment
        fields = ['user']
        
    @classmethod
    def get_filters(cls):
        filters = super().get_filters()
        filters['user'].label=  'Assignee'
        return filters


```
