### ISSUE TITLE
BooleanFilter cleaned_data problem

### ISSUE THREAD

**Issue by pipanchik** [carltongibson/django-filter#1312]
Hi!
I use django-filter 2.4.0

```
class TestFilter(django_filters.FilterSet):
    is_ignore = django_filters.BooleanFilter(
        label=_("is ignore"),
        help_text=False)

test_instance1 = TestFilter(data={"is_ignore": "False"})
test_instance1.qs
test_instance1.form.cleaned_data.get("is_ignore")       // False

test_instance2 = TestFilter(data={"is_ignore": False})
test_instance2.qs
test_instance2.form.cleaned_data.get("is_ignore")       // None

```

Why in the second example (test_instance2, when is_ignore value without quotes) return None?

How to fix it?

**Comment by carltongibson** [comment]
@pipanchik 

I'm not sure what's going on there. `BooleanFilter` uses a `NullBooleanField` under the hood, which uses `NullBooleanSelect`: 

```python
>>> from django.forms import NullBooleanSelect
>>> w = NullBooleanSelect()
>>> w.value_from_datadict({"is_ignore":False}, None, "is_ignore")
False
```

Can you put a full example together, preferably in a test case, and I can have a look?

**Comment by pipanchik** [comment]
The problem was in my application, not in django-filter. Thanks for the answer.
