### ISSUE TITLE
Filter by @property

### ISSUE THREAD

**Issue by esseti** [carltongibson/django-filter#1321]
Hi all, 
is it possible to filter by a model property?

```
class MyModel(Model):

    @property
    def is_active(self):
        return True
```

if I add for example 

```
    class Meta:
        model = MyModel
        fields = { 'is_active': ['exact'], }
```

but says

`'Meta.fields' must not contain non-model field names: is_active`

how can I do it?

**Comment by carltongibson** [comment]
You'll want to use a BooleanFilter specifying `method`. See https://django-filter.readthedocs.io/en/stable/ref/filters.html#method. Good luck.
