### ISSUE TITLE
Using django-filter with class-based views

### ISSUE THREAD

**Issue by perlun** [carltongibson/django-filter#1368]
Hi,

The docs are pretty clear on how to use this library with traditional Django views:

```python
def product_list(request):
    filter = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request, 'my_app/template.html', {'filter': filter})
```

_However_, we are not using function-based views in our application but [class-based views](https://docs.djangoproject.com/en/3.2/topics/class-based-views/intro/). I have tried various approaches on trying to get this working but I really don't get it.

Here's my last attempt:

```python
class CustomersView(LoginRequiredMixin):
    queryset = Customer.objects.all()

    filter = CustomerFilter(self.request, queryset=self.queryset)
```

Obviously, this can't work since `filter = CustomerFilter(request, queryset=queryset)` relies on things from `self` which isn't available when declaring properties like that... :slightly_smiling_face: 

I've also tried various approaches which involved overriding `get_queryset`, like this:

```python
    def get_queryset(self):
        filter = CustomerFilter(self.request, queryset=self.queryset)
        return self.queryset.filter(filter)
```

But with this I'm getting an error `cannot unpack non-iterable CustomerFilter object`. There's probably something obvious I'm missing out here... please let me know what it is. :smile:

**Comment by carltongibson** [comment]
Take a look at the bundled generic view implementation: 

https://github.com/carltongibson/django-filter/blob/2b2c13dbd65ed0f794a06b343b7c4793042caf13/django_filters/views.py#L76-L88

It should give you the guidance you need. 

In general you access the filtered QuerySet via `filter.qs`.
