### ISSUE TITLE
Website in GitHub project pointing to incorrect URL

### ISSUE THREAD

**Issue by craiga** [carltongibson/django-filter#1373]
Heya! Real quick one—the website configured in the GitHub project still points to the old `master` URL; it should be updated to `main`.

<img width="1563" alt="Screenshot 2021-05-03 at 17 14 18" src="https://user-images.githubusercontent.com/76330/116902512-1e80d000-ac33-11eb-965d-a0eb682124d0.png">

💖

**Comment by carltongibson** [comment]
Good one, thank you! Fixed.
