### ISSUE TITLE
Link of the documentation in pypi not working

### ISSUE THREAD

**Issue by rodneymandap** [carltongibson/django-filter#1375]
Hi,

The link of the docs in the pypi description for django-filter is not working. I made some troubleshooting and looks like the link in pypi is different from the link provided in the repo.

The cause of the issue occur after the branch master was changed to main.

**Comment by rodneymandap** [comment]
Link for the docs here is working. I guess the link on the repo is not updated yet.

**Comment by carltongibson** [comment]
Hi @rodneymandap. OK, yes, thanks for the report. This will be updated at the next release, which is slowly making it's way up my job list. :+1:

**Comment by AndrewGuenther** [comment]
@carltongibson I have a PR to fix a bunch of documentation links on #1382
