### ISSUE TITLE
collections.abc python 3.9 deprecation warning

### ISSUE THREAD

**Issue by neostimul** [carltongibson/django-filter#1395]
warnings.warn("Using or importing the ABCs from 'collections' instead "
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

_Originally posted by @neostimul in https://github.com/carltongibson/django-filter/issues/988#issuecomment-878319060_

**Comment by carltongibson** [comment]
Where exactly is this being raised? What version of django-filter are you using? This should have resolved in https://github.com/carltongibson/django-filter/commit/1f47e36b614724a8735e0457fa511dcaf5448481 I think. 🤔

**Comment by neostimul** [comment]
Python version 3.8.2 django_filter version is 2.4.0

I think python want, that we import `from collections` not `from collections.abc`
