### ISSUE TITLE
Release the package with Django 3.2 support

### ISSUE THREAD

**Issue by Jawayria** [carltongibson/django-filter#1404]
Hey, we are working on upgrading edX codebase to Django 3.2. This package is being used in the codebase but it isn't yet released with Django 3.2 support. Kindly consider releasing it with Django 3.2 support.
Thanks

**Comment by carltongibson** [comment]
Is there an actual incompatibility?

**Comment by carltongibson** [comment]
I can't see anything [between 2.4.0 and main](https://github.com/carltongibson/django-filter/compare/2.4.0...main) that would/should cause any problem with Django 3.2. 🤔

Have you actually tried to update?

**Comment by Jawayria** [comment]
v2.4.0 was released in Sep, 2020 but Django 3.2 support was added around 4 months ago. The package available on pypi doesn't officially support Django 3.2.

**Comment by carltongibson** [comment]
You mean the Trove classifiers? (They don't actually affect anything you know.)

New release is in the pipeline, but it's not blocking you. 

Django-Filter, being so old, is hyper-stable. That's why the older release still works.

**Comment by carltongibson** [comment]
@Jawayria Can you install the latest version of django-filter with Django 3.2 on the EdX code base and run the test suite please? If there is a django-filter related failure I'm happy to address it, as a matter of importance. If not, then you're good to go, and the new version will come when it does. Thanks.

**Comment by ulgens** [comment]
Hey @carltongibson, I know it will be a bit out of topic but can you please give some details about that "pipeline" you mentioned? I couldn't find any pinned issue or sth like that, explaining the release process. Also, "the new version will come when it does" is not the best way to encourage potential contributors :) I'd like to get some solid info about the process of that release, if that's possible. Thanks a lot 🌷

**Comment by carltongibson** [comment]
HI @ulgens — pipeline is just me reviewing the open PRs and tickets to see what we can (or want to) get it, and then rolling the release. 

My point was simply that there's nothing major between the last release and now on `main`, and that if the only urgency is PyPI metadata, then there's no rush. It's on my list — next item actually — but nobody is blocked (AFAIK) so no false panic. 

I hope that makes sense.
