### ISSUE TITLE
__contains not working true

### ISSUE THREAD

**Issue by thanhtuyenpkk** [carltongibson/django-filter#1407]
Hi 
I'm working in django and i want to search like 
demo = Demo.object.fillter(name__contains=name) ......

I print(demo.query)
with name=us 
Select * from demo where name::text LIKE %us%

I data base Demo.name have record 'usertest@gmail.com'
it not found 
Any body can't help me with it

**Comment by carltongibson** [comment]
Sorry, this isn't an addressable issue report.
