### ISSUE TITLE
Disabling in retrieve action or any actions

### ISSUE THREAD

**Issue by hadi2d** [carltongibson/django-filter#1439]
I have this codes:
class AdviceFilter(FilterSet):
    crop_id = ModelChoiceFilter(required=True, queryset=Crop.objects.all())

    class Meta:
        model = Advice
        fields = ['category_id']

class AdvicesViewSet(DynamicFieldsMixin, viewsets.ModelViewSet):
    queryset = Advice.objects.all()
    pagination_class = CommonPagination
    serializer_class = AdviceSerializer
    filter_backends = (SearchFilter, DjangoFilterBackend,)
    filterset_class = AdviceFilter
    search_fields = ['title']

when action is retrieve, raise exception that crop_id is required.
how to disable filters by DjangoFilterBackend in any action of ModelViewSet ?

**Comment by carltongibson** [comment]
You have the `crop_id` declared as required. This then is the expected behaviour. Change the declaration if you don't want it to be required.

**Comment by hadi2d** [comment]
Using the filters in retrieve action!?, I think is wrong.
I just want the filters to be applied in `list` action.
And check the required fields when the data is list. (method: GET, action: LIST) 
drf

**Comment by hadi2d** [comment]
filterset_fields = ['crop_id', ...] attr is worked fine, but not required.
tnks
