### ISSUE TITLE
ChoiceFilter not working as expected with | crispy

### ISSUE THREAD

**Issue by gldecurtins** [carltongibson/django-filter#1498]
Hi all

I'm trying to combine [django-filter](https://github.com/carltongibson/django-filter) with [crispy-tailwind](https://github.com/django-crispy-forms/crispy-tailwind). The expected behavior is that the ChoiceFilter adds the _selected_ attribute so that the filtered value would be pre-selected. The records are filtered correctly.

This works fine with:
```
<form method="get">
  {{ filter.form.as_p }}
</form>
```

But doesn't work with:
```
<form method="get">
  {{ filter.form | crispy }}
</form>
```

With `| crispy` the ChoiceLists look beautiful, but the filtered value is not selected:

![image](https://user-images.githubusercontent.com/35364122/167867965-a01de71f-b10f-49ca-adf9-b4274a250258.png)

Any thoughts?

Below you'll find a few lines of code. I think I've extracted the relevant pieces. Full code is available in my [objector github repository](https://github.com/gldecurtins/objector/tree/main/maintenance).

models.py
```
from django.db import models
from django.utils.translation import gettext_lazy as _
from rules.contrib.models import RulesModel
from inventory.models import Object

class Task(RulesModel):
    class Statuses(models.IntegerChoices):
        OVERDUE = 10, _("Overdue")
        DUE = 20, _("Due")
        PENDING = 30, _("Pending")
        INACTIVE = 40, _("Inactive")

    name = models.CharField(_("name"), max_length=200)
    description = models.TextField(_("description"), blank=True)
    object = models.ForeignKey(
        Object,
        verbose_name=_("object"),
        related_name="task_object",
        on_delete=models.CASCADE,
    )
```

filters.py
```
from .models import Task
import django_filters


class TaskFilter(django_filters.FilterSet):
    class Meta:
        model = Task
        fields = ["status", "object"]
```

views.py
```

from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task
from .filters import TaskFilter


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    paginate_by = 10

    def get_queryset(self):
        # all groups for user
        groups = self.request.user.groups.values_list("pk", flat=True)
        groups_as_list = list(groups)
        queryset = Task.objects.filter(object__owner=self.request.user)
        filterset = TaskFilter(self.request.GET, queryset=queryset)
        return filterset.qs

    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        filterset = TaskFilter(self.request.GET, queryset=self.queryset)
        context["filter"] = filterset
        return context
```

**Comment by carltongibson** [comment]
Is the `selected` attribute being set on the choice? (I would expect so but have a dig into the rendered HTML)

**Comment by gldecurtins** [comment]
On the other hand I'm not sure if the issue is with crispy-tailwind, as there are other dropdown fields on other forms which work as expected. But these fields are on a plain form, not a filter. Thus I've raised the issue with django-filter and not crispy-tailwind.

**Comment by carltongibson** [comment]
The form is right, since the `as_p()` rendering is correct. So it's a missing element in the template pack I'd think.

**Comment by carltongibson** [comment]
@gldecurtins On the last I'd likely suggest installing from GitHub as the crispy-tailwind package is still beta, and there may not be a release imminent.

**Comment by carltongibson** [comment]
I'll close this as I don't think it's a Django-filter issue.
