### ISSUE TITLE
Docs pages still say 2.4.0 in the <title>

### ISSUE THREAD

**Issue by jaap3** [carltongibson/django-filter#1500]
The readthedocs pages make it appear as if django-filter 2.4.0 is the most recent version (https://django-filter.readthedocs.io/en/latest/).

I almost pinned a new project to that version, before noticing the current version is actually 21.1.

P.S. When opening this ticket there was a notice about "upgrading to version 2.0" which made me double check to make sure 21.1 is really the new version :-).

**Comment by carltongibson** [comment]
Hey @jaap3 — Thanks for the report. 

P.s. dealt with 😃 — RTD... Errr.... Argh... — let me go look. 🤔

**Comment by carltongibson** [comment]
OK, builds are failing because RTD uses PY37 by default. 

Need to move to the new config files... https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by carltongibson** [comment]
Fixed now https://django-filter.readthedocs.io/en/latest/ — Thanks for the report @jaap3.
