### ISSUE TITLE
Fix base class for correct typing support

### ISSUE THREAD

**Issue by last-partizan** [carltongibson/django-filter#1515]
Hi, we're using pyright to type-check our code, and `djangorestframework-types` as types for DRF.

Type for `filter_backends` is defined as 

```python
    filter_backends: Sequence[Type[BaseFilterBackend]]
```

So, all filter must be subclasses of BaseFilterBackend.

Could you please add it as base class to `DjangoFilterBackend`?

**Comment by carltongibson** [comment]
It might be that we can define a Protocol here, but adding a inheritance just to satisfy the type checker is not the right move.

**Comment by last-partizan** [comment]
yeah, we can definitely add protocol. Thanks.
