### ISSUE TITLE
When upgrading from 21.1 to 22.1 foreign key relation filters don't work anymore

### ISSUE THREAD

**Issue by t16n** [carltongibson/django-filter#1527]
We are trying to upgrade to the latest version which breaks foreign key relation number filters.

For example the following Filter would not work anymore:

```
class BookFilter(filters.FilterSet):
   country = django_filters.NumberFilter(field_name="author__country_id")

    class Meta:
        model = Book
```

with the following models:
```

class Country(models.Model):
  name = models.CharField(max_length=100, null=True, blank=True)
  
class Author(models.Model):
  name = models.CharField(max_length=100, null=True, blank=True)
  country = models.ForeignKey(
        Country, on_delete=models.CASCADE
    )
  
class Book(models.Model):
  author =  models.ForeignKey(
        Author, on_delete=models.CASCADE
            )

  
```

This used to work in the version before (21.1). Went thru the commits but couldn't see anything obvious.

**Comment by carltongibson** [comment]
Can you put together a failing test case showing the issue? (Or a minimal reproduce project? — There's a lot you've left out here.) 

See #1520 as well.

**Comment by t16n** [comment]
@carltongibson thank you we figured it out it was the `filter_class` rename to `filterset_class`
