### ISSUE TITLE
RangeWidget: the dash separtor is not centered

### ISSUE THREAD

**Issue by Benji81** [carltongibson/django-filter#1528]
Hello,

There is no space between the - and the second input
![image](https://user-images.githubusercontent.com/30288181/185969590-6ea0a049-da5e-460e-86fc-1c311c71cab4.png)

In multiwidget.html: 
`{% for widget in widget.subwidgets %}{% include widget.template_name %}{% if forloop.first %}-{% endif %}{% endfor %}
`
should be 
`{% for widget in widget.subwidgets %}{% include widget.template_name %}{% if forloop.first %} - {% endif %}{% endfor %}
`

And maybe put the separator in a <span> with a class to allow easy css modification

**Comment by carltongibson** [comment]
There is no space. See https://github.com/carltongibson/django-filter/blob/main/django_filters/templates/django_filters/widgets/multiwidget.html. 

Maybe you have some `margin-right` in play? 🤔
