### ISSUE TITLE
Range filters not deffined properly in swagger

### ISSUE THREAD

**Issue by eloi-martinez-qida** [carltongibson/django-filter#1534]
Range filters only show the base filter, not the _min _max or _before _affter suffixes 

I assume it's because the filter.base_filters only returns the base filter not the ones in the suffix.

I also assume this is the same cause as the cause the issue with django json:api (https://github.com/django-json-api/django-rest-framework-json-api/issues/938)

**Comment by carltongibson** [comment]
Hi @eloi-martinez-qida — I recommend checking out drf-spectacular if you're working with schemas. 

https://drf-spectacular.readthedocs.io/en/latest/readme.html

It's a lot better developed than other options, including the basic in-core support. 

I'm likely to deprecate the built-in support in favour of this in the 23.x series.

**Comment by carltongibson** [comment]
As per #1432 the in-built schema support is going to be deprecated in the next version. 

Rather, I recommend you migrate to use `drf-spectacular`, which is much more fully featured, and under active development. 

https://drf-spectacular.readthedocs.io/en/latest/readme.html

If for some reason you're not able to use `drf-spectacular` you can copy the `django_filters.rest_framework.backends.DjangoFilterBackend` into your own project to customise as needed. (But use `drf-spectacular`.)

Thanks.
