### ISSUE TITLE
Add custom filter field which is not model field

### ISSUE THREAD

**Issue by 0xSullivan** [carltongibson/django-filter#1536]
Hey
I was using an old version of django-filter and I added some non-model fields for filtering. for example for user I added a `name` filter with custom method which concats `first_name` and `last_name` and filter both of them but there is no `name` field in the `User` model.
After I updated to the latest version I faced this error:
```
TypeError: 'Meta.fields' must not contain non-model field names: name
```
I checked the codes and I found out this error happen [here](https://github.com/carltongibson/django-filter/blob/06472fc8959192da4533071db07b1845c3661792/django_filters/filterset.py#L327). in the comment it say `warn if the field doesn't exist.` but it actually raise a `TypeError` in line 349

I think it's better to make it a REAL warning instead a ERROR

**Comment by carltongibson** [comment]
Can you provide a minimal reproduce please, as it's not possible to see what's going on from the information given so far.

**Comment by gone** [comment]
A sample filter/model that replicates this:


```
class Profile(models.Model):
    location = models.CharField(_("location"), max_length=30)
    organization = models.CharField(_("organization"), max_length=30)
    title = models.CharField(_("title"), max_length=30)


class ProfileFilter(django_filters.FilterSet):
    search = django_filters.CharFilter(label="search", method="search")

    def search(self, queryset, name, value):
        return queryset

    class Meta:
        model = Profile
        fields = ("location", "organization", "title", "search")
```

The intent here would be that search isn't attached directly to the model, but appears in the fields list.

**Comment by gone** [comment]
Ug duplicate name error. Just name your filter something different than your method, durp.
