### ISSUE TITLE
DRF documentation curd method missing auto-generated description information, Even if help_text attribute is added.  in django-filter (2.4.0)

### ISSUE THREAD

**Issue by 0x00t0x7f** [carltongibson/django-filter#1538]

**Comment by carltongibson** [comment]
As per #1432 the in-built schema support is going to be deprecated in the next version. 

Rather, I recommend you migrate to use `drf-spectacular`, which is much more fully featured, and under active development. 

https://drf-spectacular.readthedocs.io/en/latest/readme.html

If for some reason you're not able to use `drf-spectacular` you can copy the `django_filters.rest_framework.backends.DjangoFilterBackend` into your own project to customise as needed. (But use `drf-spectacular`.)

Thanks.
