### ISSUE TITLE
Is fieldset support planned?

### ISSUE THREAD

**Issue by ivanscm** [carltongibson/django-filter#1544]
I want to group filters on the form by groups or categories.

**Comment by carltongibson** [comment]
You need to provide significantly more detail if you want an actual response. (I have no idea what you're requesting, or whether it's already possible.)

**Comment by carltongibson** [comment]
This is something you'd do at the template layer really, or just next to that (see the [wontfix Django ticket-6630](https://code.djangoproject.com/ticket/6630#comment:26) ) — django-crispy-forms have dynamic layouts for just this purpose https://django-crispy-forms.readthedocs.io/en/latest/layouts.html

// cc @smithdc1 just FYI. :)

**Comment by carltongibson** [comment]
To be clear: you provide a layout for the `form` used by your `FilterSet`.
