### ISSUE TITLE
persisting and restoring filter options

### ISSUE THREAD

**Issue by markfink** [carltongibson/django-filter#1549]
I want to persist and restore the user selection for multiple choice filters.  I could not find a way to initialise the user selection. Am I doing it wrong or is this just not in scope?
I asked multiple choice filters related questions before on SO but with no feedback.

The only reference I found is a very old issue here: https://github.com/carltongibson/django-filter/issues/160

**Comment by carltongibson** [comment]
Can't you just save the URL? 

(Query string params are passed as `request.GET` to the FilterSet)

**Comment by markfink** [comment]
right. I did not look into the url aspect yet.
that looks like a brillant idea and might come very useful later
Thank you so much!
