### ISSUE TITLE
Django-filters, search_fields not working fine with 40+fields in model. 10 x 20 x 30 this type of input giving wrong result.

### ISSUE THREAD

**Issue by MudassarSharifSandhu** [carltongibson/django-filter#1582]
Hey @carltongibson team!
i'm facing an issue regarding search_fields
`  django = "~=2.2.26"
djangorestframework = "~=3.13.1"
django-allauth = "~=0.50.0"
django-rest-auth = "~=0.9.5"
django-extensions = "~=3.1.5"
django-filter = "*" ` 
above all the requirements, which installed.

Include all fields having no relation
`search_fields = [i.name for i in ManageTFTData._meta.get_fields() if not i.is_relation]

serializer_class = ManageTFTDataSerializer

filter_backends = (filters.SearchFilter, DjangoFilterBackend)
`
Anyone can help me on this?
its just having issue for this just one field for specific above string.

**Comment by carltongibson** [comment]
This is not an addressable issue report.
