### ISSUE TITLE
coreapi dependancy in function get_schema_fields

### ISSUE THREAD

**Issue by Qadosch** [carltongibson/django-filter#1586]
`get_schema_fields()` should be not dependant on deprecated coreapi and updated to openapi

**Comment by scastlara** [comment]
drf-yasg removed that dependency in the latest release https://drf-yasg.readthedocs.io/en/stable/changelog.html#id1

**Comment by carltongibson** [comment]
The schema generating methods are deprecated, to be removed.

**Comment by Qadosch** [comment]
Its a "wont do" then. Ty for feedback. Did not realise, its a deprecated function.
