### ISSUE TITLE
Passing an initial value

### ISSUE THREAD

**Issue by chromakey** [carltongibson/django-filter#160]
I've tried to pass an initial value to the form by separately trying the following methods (yadda being a placeholder value):

```
#views.py
def operator_search(request):
    operators = Operator.objects.all()
    f = OperatorFilter(request.GET, initial={'operator_city':'yadda'}, queryset=Operator.objects.all())
    return render(request, 'vendors/operator_search.html', {'filter':f, 'operators':operators})
```

```
#forms.py
class OperatorFilter(django_filters.FilterSet):
     operator_city = django_filters.CharFilter(initial="yadda")
     class Meta:
         model = Operator
```

Neither seems to work.  How can I set an initial value for the form when using django-filters?

**Comment by jiangbotang** [comment]
I searched the mailing list but could not find a solution. Here is a workaround that I figured out (use at your own discretion):

     ####### WARNING: this is a hack to enable initial filter field selection in django-filters########
    # Create a mutable QueryDict object, default is immutable
    initial = QueryDict('active_study=True', mutable=True)
    # QueryDict update works different than normal dictionary update. Refer to docs.
    initial.update(request.GET)
    # Place the hacked, mutable QueryDict to the FilterSet.
    filter = StudyFilter(initial, queryset=Study.objects.all())

**Comment by depaolim** [comment]
in case of ChoiceField you can use:
`empty_label=None, null_value=<default-value>, null_label=<default-label>`
