### ISSUE TITLE
DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14

### ISSUE THREAD

**Issue by jose-reveni** [carltongibson/django-filter#1616]
DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
https://github.com/carltongibson/django-filter/blob/6fef056093524cec9b9f0959ca5b4e015e9f6244/django_filters/__init__.py#L9

**Comment by carltongibson** [comment]
Hey @jose-reveni — thanks for the report! Fancy making a PR with that change?
