### ISSUE TITLE
Allow passing a filterset class to `filterset_factory`

### ISSUE THREAD

**Issue by b1rger** [carltongibson/django-filter#1631]
It would be nice if it was possible to override the filterset class that the `filterset_factory` is basing the returned filterset on. A similar thing is done in the `table_factory` [in django-tables](https://github.com/jieter/django-tables2/blob/5700abfaaf75c7eef7b002644e85dd8d52f78344/django_tables2/tables.py#L696)

**Comment by carltongibson** [comment]
Yes, **maybe**... 🤔

I had a similar need myself the other day. (I can't instantly remember what I did; I'll look when I'm back at it.) 

One consideration is `Meta` inheritance...

**Comment by carltongibson** [comment]
Hi @b1rger. So, I ended up defining the filter set class inline in my case, but I still think this might be a useful addition. 

Is it something you'd like to work on?

**Comment by b1rger** [comment]
> Is it something you'd like to work on?

Sure!

**Comment by carltongibson** [comment]
Fixed in  #1644
