### ISSUE TITLE
Switch GHA to use py-cov-action / python-coverage-comment-action

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-filter#1647]
Codecov's action broke. https://github.com/codecov/codecov-action/blob/main/README.md

See e.g. https://github.com/carltongibson/django-filter/actions/runs/8235019910

We've been meaning to get off it for a while. 

Switch to @ewjoachim's https://github.com/py-cov-action/python-coverage-comment-action

**Comment by ewjoachim** [comment]
I'll be delighted to help if you folks need anything :)

**Comment by carltongibson** [comment]
@ewjoachim Input always welcomed 😜
