### ISSUE TITLE
Documentation shows v23.5 in the header

### ISSUE THREAD

**Issue by nils-van-zuijlen** [carltongibson/django-filter#1662]
Hello,

The docs at https://django-filter.readthedocs.io/en/main/ (those linked in the Readme and on PyPi) show version 23.5 in the header.

This may be related to old issues #1500 and #1610.

**Comment by carltongibson** [comment]
Thanks for the report. I'll have a poke around the RTD settings so see if something is amiss.

**Comment by carltongibson** [comment]
![Screenshot 2024-07-03 at 10 22 59](https://github.com/carltongibson/django-filter/assets/64686/eb404703-ee51-47dd-a2eb-f1ab2e028a5f)

OK, as far as I can tell that's not the case. Everything looks correct for all docs versions.
