### ISSUE TITLE
Filter by list of IDs

### ISSUE THREAD

**Issue by stefan6419846** [carltongibson/django-filter#1664]
I am currently trying to filter a by list of IDs, but it seems like this is limited to two values.

Let's say I have the following code:

```python3
class NumberInFilter(BaseInFilter, NumberFilter):
    pass


class MyModelFilter(FilterSet):
    pk__in = NumberInFilter(field_name='id', lookup_expr='in')

    class Meta:
        model = MyModel
        fields = {
            'name': ['exact', 'contains'],
        }
```

This will be rendered as:

```html
<input type="number" name="pk__in" step="any" class="form-control is-valid" placeholder="ID ist in" id="id_pk__in">
```

Additionally, I get the query parameter `pk__in=`.

Unfortunately, this does not behave in clean manner:

* In the UI, I can only enter up to two numbers due to the input field type, basically mapping to a floating point value (although getting the correct results). This is represented inside the URL as `pk__in=1.2` for example.
* Passing `pk__in=1,2,6,10` in the URL explicitly seems to work as well and disables the regular input field behavior, now allowing to enter more than two numbers.

The current state is not consistent and especially the default number-only input field does not really feel right. Did I miss something for the UI or is this just a limitation of the library?

**Comment by m1guer** [comment]
any update?

**Comment by carltongibson** [comment]
The CSV approach is intended for API use. For HTML you're better off using a [ModelMultipleChoiceFilter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#modelmultiplechoicefilter) with a select widget (or checkbox or ...)
