### ISSUE TITLE
"Filters" button not showing if required fields are not passed

### ISSUE THREAD

**Issue by dontic** [carltongibson/django-filter#1669]
Coming from https://github.com/carltongibson/django-filter/issues/330#issuecomment-2165900104

When debuging an API it's super useful to have the ![image](https://github.com/carltongibson/django-filter/assets/25914304/be0d7cfe-cc8c-40d0-b07d-5350d90ed5fe) button.

Problem is that the button disappears if you have any required fields:

```python
from django_filters.rest_framework import FilterSet
import django_filters
from .models import Message

class MessageFilter(FilterSet):
    user_email = django_filters.CharFilter(
        field_name="user__email", lookup_expr="exact", required=True
    )

```
![image](https://github.com/carltongibson/django-filter/assets/25914304/92c5dc72-3439-4cb5-aad0-409797a93cef)

It will come back again if you first pass the required fields via the URL.

Is there a way it can be shown even if the 400 error is there? Maybe also with a small red asterisk in the form fields that are required?

**Comment by carltongibson** [comment]
This is a DRF issue really. It's nothing really to do with the filter set. I haven't used DRF for a while, so I can't really say what the issue or workaround would be.

**Comment by dontic** [comment]
> This is a DRF issue really. It's nothing really to do with the filter set. I haven't used DRF for a while, so I can't really say what the issue or workaround would be.

Gotcha, thanks for clarifying! Closing the issue then.
