### ISSUE TITLE
Add Django REST Framework friendly base FilterSet class

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-filter#275]
There are recurring themes where automatically generated `FilterSet` subclasses aren't ideal when using Django REST Framework. The goal here is to create a DRF-friendly base class that resolves this. 

* Use new IsoDateTimeFilter by default. #264 
* Use a JavaScript friendly BooleanWidget, for query parameter parsing. #270.
* [...anything else...]
* Open a matching PR on DRF to include these changes.  

For an example of a user land implementation see this [thread on the mailing list](https://groups.google.com/forum/#!topic/django-filter/vbTttMhqH0I) and [gist](https://gist.github.com/dpetzel/d039fff0baf3f8e1639a).

**Comment by auvipy** [comment]
+1
