### ISSUE TITLE
Document (or change) `distinct=True` on default `MultipleChoiceFilter`

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-filter#277]
Looking to merge #217, we note it was necessary to have MultipleChoiceFilter default to `distinct=True` in order to preserve backwards compatibility. 

That's the norm. `distinct` is normally `False` by default, and is documented as such. 

Either change the code or document the exception. (Change the code is favourite, but make sure you call that out properly if/when you do it.)

**Comment by rpkilby** [comment]
The majority of to-many relationships need to be de-duplicated (which is only possible w/ distinct?). If we change this to false, the auto-generated to-many relationships will generally be rendered useless. Two possibilities:
- Leave it as is, documenting the exception (as stated above).
- Revert to the default, but explicitly set `distinct=True` when auto-generating to-many rels (and document this exception).

**Comment by carltongibson** [comment]
My original view was just to document it...

**Comment by carltongibson** [comment]
Although that's not what I said...
