### ISSUE TITLE
Have help text NOT added by default. 

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-filter#292]
See [discussion on #136](https://github.com/alex/django-filter/pull/136#issuecomment-135330762).

**Comment by eriktelepovsky** [comment]
+1

**Comment by ad-m** [comment]
@eriktelepovsky , pull requests are welcome. Do you can prepare one, please? 

@carltongibson said:
> Unless someone jumps in with a PR, that'll not be instantly.

**Comment by carltongibson** [comment]
Closed by #386
