### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by ad-m** [carltongibson/django-filter#352]
Hello,

I am would like suggest add autoupdate docs. According to https://readthedocs.org/projects/django-filter/ the docs was build a month ago last time.

Here is how to use webhooks to update them: http://read-the-docs.readthedocs.org/en/latest/webhooks.html . 

I hope I fixed Tex build (see https://readthedocs.org/projects/django-filter/builds/3534119/ tex fail) in #351.

Greetings,

**Comment by carltongibson** [comment]
Fixed.
