### ISSUE TITLE
allow overriding the `extra` lookup type naming convention with another lookup type

### ISSUE THREAD

**Issue by smcoll** [carltongibson/django-filter#356]
`filter_overrides` allows a user to change the default lookup for a model field from `exact` to, say, `iexact`.  But even with that new default, the query name constructed will be `myfield__iexact` rather than simply `myfield`.  (Whereas, any field using the `exact` lookup will not have `__exact` appended to the field name for the query param, regardless of whether `exact` is the default lookup specified by `filter_overrides[{db_field}]['extra']['lookup_type']`).  

Respecting the default lookup for a field type as specified in `filter_overrides[{db_field}]['extra']['lookup_type']` such that the lookup name would automatically be generated as `myfield` (while the db query filtered on `myfield__{lookup_type}`) would be desirable.

**Comment by rpkilby** [comment]
Hi - just trying to clarify:

#### Background:
Django performs an implicit 'exact' lookup whenever you filter by field name. For example, `User.objects.filter(username='bob')` is equivalent to `User.objects.filter(username__exact='bob')`. django-filter's declarative fields syntax mirrors this convention by creating `<field name>` filters that have an implicit exact lookup type. [relevant code](https://github.com/alex/django-filter/blob/0.12.0/django_filters/filterset.py#L100-L115). Using just the declarative syntax, it's not possible to generate a `<field name>` filter with a different implicit lookup type, nor is it possible to create a `<field name>_exact` filter name on the FilterSet. 

#### Fix:
@smcoll In the short term, you should be able to get around this by doing the following:
```py
class UserFilter(FilterSet):
    username = CharFilter(name='username', lookup_type='iexact')
    username__exact = CharFilter(name='username', lookup_type='exact')

    class Meta:
        model = User
        fields = {
            'username': ['startswith', 'endswith', ],  # other lookup types 
        }
```

#### Thoughts:
There isn't any technical reason to follow Django's convention here - it was probably coded this way for the sake of consistency. Either way, it would also be pretty trivial to add this as a feature (forwards compatible, just requires documentation). 

That said, I don't think that it makes sense to use `filter_overrides` to handle this behavior. `filter_overrides` hooks into filter generation based on the model field's **type**. A default, implicit lookup (and how naming is handled) is more related to the specific model field **instance**. (eg, it might make sense to use an implicit 'iexact' lookup for a user's name, but maybe not for their username.)

#### Proposal:
Add a `field_default_lookups` or `implicit_lookups` or `default_lookups` or whatever as an option to the FilterSet.Meta class. This would work with both the dict and list style field declarations. ex:

```py
class UserFilter(FilterSet):
    class Meta:
        model = User
        fields = {
            'username': ['exact', 'iexact', 'startswith', 'endswith', ...],
        }
        implicit_lookups = {
            'username': 'iexact',
        }
```

**Comment by carltongibson** [comment]
Err... To be honest, I'm not inclined to do anything here. I'm inclined to say that declaring the filter fields explicitly, and using the `name` argument gives you everything you need. 

I'm inclined to close as Out of Scope but I'll leave it open for now in case a clean, tested, documented PR turns up that looks worth the effort.

**Comment by smcoll** [comment]
@rpkilby @carltongibson thanks for the attention. i'm satisfied by the "short term fix" in the first comment.  i thought i'd have to define each variation individually.
