### ISSUE TITLE
django_filters.widgets.BooleanWidget does not implement render

### ISSUE THREAD

**Issue by blaze33** [carltongibson/django-filter#383]
So it raises a `NotImplementedError` when django tries to render it. I see that django-filter doesn't use BooleanWidget but django restframework filters does for its BooleanField and it breaks the browsable API of django restframework.

I use:
Django==1.8.9
django-filter==0.12.0
djangorestframework==3.3.2
djangorestframework-filters==0.7.0

**Comment by carltongibson** [comment]
Yep. PRs welcome. (Widget was create for DRF but it looks like the browsable API got missed...)

**Comment by blaze33** [comment]
I'll happily do a PR once I have a response from one of the maintainer of django-rest-framework-filters about https://github.com/philipn/django-rest-framework-filters/issues/71

Considering that the widget was introduced in the first place to fix an issue I cannot reproduce I'm not even sure if we need to keep it at all.

**Comment by carltongibson** [comment]
BooleanWidget was introduced because people like `?param=true&other_param=false` to Just Work™

**Comment by blaze33** [comment]
Yes, but the BooleanField default widget, which is CheckboxInput, works just fine for `?param=true&other_param=false`, am I missing something ?

**Comment by rpkilby** [comment]
@carltongibson - already taken a stab at this in #378.

**Comment by carltongibson** [comment]
@rpkilby Yep. I missed that. It's fine. If you rebase I'll merge it now.

**Comment by carltongibson** [comment]
@blaze33 Could be... :-) There were plenty of people having trouble with XYZ JavaScript library that wanted `BooleanWidget`... I think it's just a bit more friendly than Django's own.

**Comment by blaze33** [comment]
Ah thanks, my bad, I missed that existing PR !

**Comment by carltongibson** [comment]
@blaze33 No problem.
