### ISSUE TITLE
django.db.models.expression.Expression

### ISSUE THREAD

**Issue by sinwires** [carltongibson/django-filter#392]
File **django_filters/utils.py** have an import:
from django.db.models.expressions import Expression 
The **Expression** class does not exists in Django 1.7. Due to this, django_filter==0.13 not works in Django 1.7 and raising **Import Error**

**Comment by carltongibson** [comment]
Django 1.8 is the minimum supported version. 

Django 1.7 is EOL — it no longer receives even security patches — you should not use it. Upgrade Django as your first priority. https://www.djangoproject.com/download/#supported-versions
