### ISSUE TITLE
IN lookup

### ISSUE THREAD

**Issue by maxtepkeev** [carltongibson/django-filter#394]
Hi,

I'm using django-filter with django-rest-framework, this one doesn't work, it just returns nothing:

```python
import django_filters
from rest_framework import filters

from ..models import MyModel


class MyModelFilter(filters.FilterSet):
    my_field = django_filters.CharFilter(lookup_expr='in')

    class Meta:
        model = MyModel
```

But this one does and works as expected:

```python
from django_filters import filters as df_filters
from rest_framework import filters

from ..models import MyModel


class CharInFilter(df_filters.BaseInFilter, df_filters.CharFilter):
    pass


class MyModelFilter(filters.FilterSet):
    my_field = CharInFilter()

    class Meta:
        model = MyModel
```

Is this a normal and expected behaviour or am I doing something wrong here ? Thanks.

**Comment by rpkilby** [comment]
Hi @maxtepkeev. Yes - this is the expected behavior. Filters are not 'expression aware' and will not alter behavior according to their `lookup_expr`. 

You can either manually create the filter class as you've done in the second example, or you can automatically generate filters with the dictionary style syntax for `Meta.fields`. Internally, it does the [same thing](https://github.com/carltongibson/django-filter/blob/v0.13/django_filters/filterset.py#L471-L478) as in your example.

eg,
```py
class MyModelFilter(Filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {
            'my_field': ['exact', 'in', ...],
        }
```

**Comment by maxtepkeev** [comment]
Hi @rpkilby 

Thanks for reply.

IMHO that is not very obvious from the documentation, so maybe you can add some more information about that in the docs.

Also, the second example with ``Meta.fields`` doesn't work for me for some reason.

**Comment by carltongibson** [comment]
@maxtepkeev Any PRs on the docs are very welcome!

I think the underlying issue is the CharFilter is only expecting (receiving?) a single value, not a list; that comes from how the widget maps data from the `GET` `QueryDict` — All of _that_ is Django Forms internals, which isn't that clear to many people. We probably need to have some _background reading_ to explain the mechanics...

**Comment by rpkilby** [comment]
@carltongibson I'll try to work on this later tonight. Could rework [this](https://github.com/carltongibson/django-filter/blob/v0.13/docs/usage.txt#L82-L100) into a section on common problems and/or theory.

@maxtepkeev Here are the [docs](https://django-filter.readthedocs.org/en/latest/ref/filters.html#baseinfilter) on mixing the `BaseInFilter` with other filter types, however it's not exactly obvious on how to get there. eg, if you were to search the docs on how to correctly use `CharFilter` with `lookup_expr='in'`, you probably wouldn't find that section.
Are you still having problems with the `Meta.fields` syntax?

**Comment by maxtepkeev** [comment]
@rpkilby Yes, it was hard to find, but I've read [this](https://django-filter.readthedocs.org/en/latest/ref/filters.html#baseinfilter) section and after that I implemented my current working solution, i.e.:

```python
from django_filters import filters as df_filters
from rest_framework import filters

from ..models import MyModel


class CharInFilter(df_filters.BaseInFilter, df_filters.CharFilter):
    pass


class MyModelFilter(filters.FilterSet):
    my_field = CharInFilter()

    class Meta:
        model = MyModel
```

``Meta.fields`` still doesn't work for me, it doesn't produce any tracebacks, errors or anything else, it just returns empty result set, this is how I'm trying to use it:

```python
from rest_framework import filters

from ..models import MyModel


class MyModelFilter(filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {
            'my_field': ['in'],
        }
```

As I said earlier, I'm using django-filter with django-rest-framework, I'm using ``?my_field=Option1,Option2`` syntax in URL which correctly works with my current solution but doesn't work with ``Meta.fields``.

**Comment by rpkilby** [comment]
Ah, you should be filtering with `?my_field__in=Option1,Option2`. This makes more sense when you have multiple lookups. eg,

```py
class ProductFilter(filterset.Filter):
    class Meta:
        model = Product
        fields = {'price': ['exact', 'in', 'lt', 'gt'], }
```
Would generate `price`, `price__in`, `price__lt`, and `price__gt` filters.

**Comment by maxtepkeev** [comment]
Of course, my bad, it works now.

But if I don't like the ``__in`` part, the only option is to use the custom class like I'm doing at the moment, right ?

**Comment by rpkilby** [comment]
Yep, and that's fine if you only have the one filter for that field. If you have multiple filters for a field though, you'll need to use some naming strategy to differentiate between them. eg, `price__in`,  `price__lt`,  `price__gt`.

**Comment by maxtepkeev** [comment]
Yes, that makes sense. Thanks. I have no more questions.
