### ISSUE TITLE
Improve Documentation around use of MultipleChoiceFilter

### ISSUE THREAD

**Issue by andybak** [carltongibson/django-filter#397]
See #137 especially https://github.com/carltongibson/django-filter/issues/137#issuecomment-37820702

Not sure if this is purely a DRF issue but the minimum needed to get multiple choice filters working is something like:

    class MultipleField(MultipleChoiceField):
        def valid_value(self, value):
            return True    
    
    class MultipleFilter(django_filters.MultipleChoiceFilter):
        field_class = MultipleField    
    
    # Then use them:
    class FooFilter(filters.FilterSet):
        bar = MultipleFilter(lookup_type='in')
        class Meta:
            model = Foo
            fields = ['bar']

If it's not appropriate to fix this within django-filter then a mention in the docs would save others a stack of time.

**Comment by carltongibson** [comment]
@andybak I think you're holding it wrong... 

As per #137, can you provide a full example of what you expect to be working but isn't? I'm happy to fix issues if they exist —  but in the whole discussion around this **no-one** has submitted a failing test case. 

Why aren't you just using `ModelMultipleChoiceFilter`? Why isn't that working for you?

Look at this [test in `ModelMultipleChoiceFilterTests`](https://github.com/carltongibson/django-filter/blob/develop/tests/test_filtering.py#L449).

That's the behaviour you need right? So what's the bug? 

If it's a documentation issue then where's the PR with the change? 

Also, have you looked at the new CSV filter stuff?

I'm going to close this pending something I can actually action.
