### ISSUE TITLE
Is there a way to specify a default value for a filter field?

### ISSUE THREAD

**Issue by lydiagu** [carltongibson/django-filter#411]
For example, I want to allow filtering by min/max dates on a model, and I want a default value for the min date if the user doesn't pass a value.

**Comment by carltongibson** [comment]
@lydiagu Have a look here: https://github.com/carltongibson/django-filter/issues/160 — you can use a plain dict instead of a QueryDict most times. 

I'm going to assume that covers you. If not follow up there.
