### ISSUE TITLE
[bug] FilterSet._meta.fields does not work if 'limit_choices_to' uses function name

### ISSUE THREAD

**Issue by elbenfreund** [carltongibson/django-filter#413]
Affected version: ``django-filter==0.13.0``
Evironment:
* django 1.9
* python 3.4

## Steps to reproduce:

1. Have a ``ForeignKeyField`` with ``limit_choices_to=some_function_name``
2. Set up a ``FilterSet`` with ``fields =  [name_of_your_foreign_key_field]`` and ``model = your_model``  in its ``Meta`` class.
3. run devserver``

## Expected Result
Filter gets instantiated properly.

## Actual Result
devserver crashes

### Traceback

```
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django_filters/filterset.py", line 161, in __new__
|     new_class.filter_for_reverse_field)
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django_filters/filterset.py", line 98, in filters_for_model
|     filter_ = filter_for_field(field, f)
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django_filters/filterset.py", line 430, in filter_for_field
|     filter_class, params = cls.filter_for_lookup(f, lookup_type)
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django_filters/filterset.py", line 457, in filter_for_lookup
|     params = data.get('extra', lambda f: {})(f)
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django_filters/filterset.py", line 210, in <lambda>
|     remote_field(f).limit_choices_to),
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
|     return getattr(self.get_queryset(), name)(*args, **kwargs)
|   File "/home/elbenfreund/.virtualenvs/kmncms/lib/python3.4/site-packages/django/db/models/query.py", line 715, in complex_filter
|     return self._filter_or_exclude(None, **filter_obj)
| TypeError: _filter_or_exclude() argument after ** must be a mapping, not function
```

## General Context
Django allows FK-Fields to be passed a [limit_choices_to](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.limit_choices_to) kwarg. It explicitly allows for a function name to be provided. However, if ``django_filters.filterset.filters_from_model`` encounters such a field it seems to be unable to handle it properly. If one removes the ``limit_choices_to`` kwarg or assigns it a value/function**call** ``django-filters`` works as expected. Alternatively the problem can be avoided by not triggering ``filters_from_model``, see next. 

## Workaround
In my particular context it was possible to avoid the issue rather easily by not using ``fields`` but specifying the filters manually.

**Comment by rpkilby** [comment]
Yep - it looks like a simple lambda isn't sufficient here. In the below snippets, `limit_choices_to` is resolved before being passed to complex filter. 

Relevant snippets from django's src - [1](https://github.com/django/django/blob/32969c3931dea8488ee4ad2849eab43e31e5542e/django/db/models/fields/__init__.py#L822-L828), [2](https://github.com/django/django/blob/a5c8a6ce19eabd96bf3b8c7bb4fb487f53928f3b/django/forms/models.py#L303-L309), [3](https://github.com/django/django/blob/a5c8a6ce19eabd96bf3b8c7bb4fb487f53928f3b/django/forms/models.py#L1163-L1172)

**Comment by carltongibson** [comment]
OK. This would have been written expecting a dict (or such). Happy to look at a PR adding support for a callable.

**Comment by elbenfreund** [comment]
Whilst I think this is less a new feature but a bug with handling established django API you seem to differ, which is why I removed the "bug" reference from the issue title.

**Comment by carltongibson** [comment]
@elbenfreund Yeah, it's just semantics. For me, this is a bit of an edge case — I'm happy to accept a PR but it's not something I consider high priority — so "Improvement/Feature". Don't let that bother you; the labels are to help me manage the repo. :-)
