### ISSUE TITLE
Range filter does not support distinct

### ISSUE THREAD

**Issue by porschelau** [carltongibson/django-filter#416]
I dug thru the code. the RangeFilter class does not have the part that add the qs.distinct() in the Filter class

`
class RangeFilter(Filter):
    field_class = RangeField

    def filter(self, qs, value):
        if value:
            if value.start is not None and value.stop is not None:
                lookup = '%s__range' % self.name
                return self.get_method(qs)(**{lookup: (value.start, value.stop)})
            else:
                if value.start is not None:
                    qs = self.get_method(qs)(**{'%s__gte' % self.name: value.start})
                if value.stop is not None:
                    qs = self.get_method(qs)(**{'%s__lte' % self.name: value.stop})
        return qs
`

**Comment by rpkilby** [comment]
Should this be closed due to #417?
