### ISSUE TITLE
0.12.0 on PyPI does not have a tar.gz

### ISSUE THREAD

**Issue by smcoll** [carltongibson/django-filter#419]
It's the only version which only has a `.whl` and not a `.tar.gz` source: https://pypi.python.org/pypi/django-filter/0.12.0#support

As a consequence, one CI environment i am building to is failing when pip installing the requirement, and version 0.12.0 wasn't listed as one of the available versions:

```
[...]
Downloading/unpacking django-filter==0.12.0 (from -r requirements.txt (line 13))
  Could not find a version that satisfies the requirement django-filter==0.12.0 (from -r requirements.txt (line 13)) (from versions: 0.13.0, 0.5.1, 0.5.3, 0.1.0, 0.5.0, 0.7, 0.2.0, 0.10.0, 0.8, 0.5.2, 0.9.1, 0.9.2, 0.11.0, 0.6a1, 0.5.4, 0.9.0, 0.6)
Cleaning up...
No distributions matching the version for django-filter==0.12.0 (from -r requirements.txt (line 13))
Storing complete log in /home/ubuntu/.pip/pip.log

/usr/bin/env pip install --exists-action=w -r requirements.txt returned exit code 1

Action failed: /usr/bin/env pip install --exists-action=w -r requirements.txt
```

**Comment by rpkilby** [comment]
@carltongibson occasionally forgets to upload the source build :D
As an alternative, could you not just upgrade pip/setuptools as a build step in CI prior to running the tests? Newer versions of pip should favor wheels over src distributions iirc.

**Comment by smcoll** [comment]
@rpkilby thanks for your response.  That would work as a workaround, yes, but it does add to build time.

**Comment by ad-m** [comment]
@smcoll , it is out ouf this is issue, but pip caching (introduced in pip v6.0) can be interesting for you if you have any binary packages in your CI project and package speed installation issue. You need only share ```~/.cache/pip``` between builds. It works very well in TravisCI. As a result, you can probably compensate the time needed for installation pip.

**Comment by carltongibson** [comment]
The 0.12 release went wrong — don't know why. I've tried sorting it several times. PyPI seems unwilling to change the release. No doubt my lack of expertise. Not going to fix it now. Sorry if that's a pain. I'd say update.
