### ISSUE TITLE
Odd p tag

### ISSUE THREAD

**Issue by MichaelPavlov** [carltongibson/django-filter#422]
Can you guys hint me how can I remove unnecessary `p` tag with "Filter" text in it. I'm using crispy-forms and django-filter. I'm not 100% sure but I think this issue has to do with django-filter

![selection_008](https://cloud.githubusercontent.com/assets/17099703/15448361/c059290c-1f68-11e6-81bf-175db078027d.png)

**Comment by rpkilby** [comment]
Does [this](https://django-filter.readthedocs.io/en/latest/ref/settings.html) cover your issue?

**Comment by MichaelPavlov** [comment]
Yes, thank you so much. This one does what I need.
FILTERS_HELP_TEXT_FILTER = False
For some reason I didn't look into settings section.
