### ISSUE TITLE
regarding names to display in the filter options

### ISSUE THREAD

**Issue by Dauth** [carltongibson/django-filter#424]
For the example below taken in the documentation, is it possible to display the type of loopup_expr in the filter options?

currently in the filter options of the browserable api, it will show 2 prices label and not the type of lookup_expr it is performing. i know that one way of doing would be to declare the filter as follows `price__gt = django_filters.NumberFilter(name='price', lookup_expr='gt')` but is it possible to do it in the dict format?
```
import django_filters

class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Product
        fields = {
            'price': ['lt', 'gt'],
        }
```

**Comment by rpkilby** [comment]
Hi @Dauth, there isn't a `Meta.help_texts` option like you would see in Django's `ModelForm`s. This was [discussed](https://github.com/carltongibson/django-filter/issues/107#issuecomment-209033803) and is not currently a goal. Per the discussion, passing a `help_text` to the filter is kosher as additional filter kwargs are passed through to the underlying form field. However, this obviously doesn't work with `Meta.fields`.

You could try to subclass `FilterSet.filter_for_field` to automatically add in a `help_text` to the filter params. Something like,

```py
class MyFilterSet(Filterset):
    @classmethod
    def filter_for_field(cls, f, name, lookup_expr='exact'):
        filter_instance = super(MyFilterSet, cls).filter_for_lookup(f, name, lookup_expr)
        help_text = lookup_expr.replace('_', ' ').capitalize()
        filter_instance.extra.setdefault['help_text'] = '%s filter' % help_text

        return filter_instance
```

**Comment by carltongibson** [comment]
Yep. As @rpkilby says. If you want to add this to your own project fine, but it's not functionality that I want to add to the library.
