### ISSUE TITLE
Add custom MultiWidget for better field names

### ISSUE THREAD

**Issue by Varkal** [carltongibson/django-filter#425]
Hello,

I think it's more expressive and clean to expose min and max than 0 and 1 in my REST API

So, I want to know if it's possible to rename the generated "fields" and so have this :     

```
f = F({'published_min': '2016-01-01 8:00', 'published_max': '2016-01-01 10:00'})
```

instead of 

```
f = F({'published_0': '2016-01-01 8:00', 'published_1': '2016-01-01 10:00'})
```

**Comment by rpkilby** [comment]
Hi @Varkal - Without diving into details, this is an artifact of Django's builtin `MultiWidget`, which is several layers deep in terms of the... composition hierarchy? Not sure if that's the correct way to articulate that. The short version is there isn't an easy way to customize the field name postfix without swapping out the Widget. 

A couple of options:
- Use a custom Widget, which may or may not have complications, depending on your setup.
- There is a comma-separated range filter that you can use ([docs](https://django-filter.readthedocs.io/en/latest/ref/filters.html#baserangefilter)). Your queries would instead look like:

  ```
  ?published_range=2016-01-01 8:00,2016-01-01 10:00
  ```
- The range lookup is just a SQL BETWEEN query, which is just a shorthand for lte/gte. You could instead manually setup min/max filters.

  ```py
 class MyFilter(FilterSet):
      published_min = DateFilter(name='published', lookup_expr='gte')
      published_max = DateFilter(name='published', lookup_expr='lte')
  ```

**Comment by carltongibson** [comment]
This applies equally to the generated fields passing a list to `lookup_expr`. It would be nice to resolve this.

**Comment by rpkilby** [comment]
I took a brief look into this, and it seems doable... You would need to completely override a couple of methods, and modify the `get_context` result. Something like:

```python
class MinMaxMultiWidget(forms.MultiWidget):

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        assert len(context['widget']['subwidgets']) == 2

        context['widget']['subwidgets'][0]['name'] = name + '_min'
        context['widget']['subwidgets'][1]['name'] = name + '_max'
        return context

    def value_from_datadict(self, data, files, name):
        return [
            self.widgets[0].value_from_datadict(data, files, name + '_min'),
            self.widgets[1].value_from_datadict(data, files, name + '_max'),
        ]

    def value_omitted_from_data(self, data, files, name):
        return all(
            self.widgets[0].value_omitted_from_data(data, files, name + '_min'),
            self.widgets[1].value_omitted_from_data(data, files, name + '_max'),
        )
```

**Comment by carltongibson** [comment]
👍🏽. 

I this is both doable and probably a nice to have. If you want to take it on, excellent. If you want to open a PR I'm happy to help on that docs wise etc.
