### ISSUE TITLE
django-filter to work on post data 

### ISSUE THREAD

**Issue by Chitrank-Dixit** [carltongibson/django-filter#435]
Hello Developers,

We are using django-filter library for our work and finding it very useful to work with. Write now I am making the API and that is a post API with lots of data to search on and there are lots of nested structures. I wanted to confirm that does django-filters work with request.post ?

**Comment by rpkilby** [comment]
> does django-filters work with request.post ?

This depends. From the [docs](https://django-filter.readthedocs.io/en/latest/usage.html#the-view), the FilterSet typically works with `GET` params, which Django parses as a `QueryDict`. If your POST request's content type is `application/x-www-form-urlencoded`, then the POST data will also [be parsed as a `QueryDict`](https://github.com/django/django/blob/1.9/django/http/request.py#L299-L302) and is compatbile. If you're POSTing a different content type (such as `application/json`), then it is not directly compatible. (`request.POST` would not be usable as it would be an empty `QueryDict`).

For a json request, you could try to convert the request body into a dict

```py
def product_list(request):
    # f = ProductFilter(request.GET, queryset=Product.objects.all())
    f = ProductFilter(json.loads(request.body), queryset=Product.objects.all())
    return render(request, 'my_app/template.html', {'filter': f})
```

but...
- some filters may not work correctly (such as multiple choice filters)
- the JSON would have to be valid and parse as a dictionary (arrays would break).
- nested filter structures are non-sensical (not sure if this is what you meant with nested structures). eg, 
```json
{
    "username__startswith": "bob",
    "related_model": {
        "related_filter": "some_value",
    }
}
```
