### ISSUE TITLE
FilterView doesn't acknowledge url kwargs

### ISSUE THREAD

**Issue by msaysell** [carltongibson/django-filter#445]
```
url(r'^foo/$',
     FilterView.as_view(filterset_class=SomeFilter, template_name='foo.html'),
     {'bar': 'kwarg_a'},
     name='some_name')
```

When using the generic `FilterView` any kwargs you define on a url appear to be ignored and are never passed through to the template

**Comment by rpkilby** [comment]
I don't think that init kwargs are made directly available in the template by cbv's. Try `{{ view.bar }}` instead of `{{ bar }}`.

See:
https://github.com/django/django/blob/1.9/django/views/generic/base.py#L36-L44
https://github.com/django/django/blob/1.9/django/views/generic/base.py#L22-L25

**Comment by msaysell** [comment]
Ah I'd misread the [documentation](https://docs.djangoproject.com/en/1.9/topics/http/urls/#passing-extra-options-to-view-functions)... `view.bar` doesn't work either since its stored in the views kwargs but I think I'm just going to find other ways of doing what I was doing. Thanks though!
