### ISSUE TITLE
Any interested in nullable/is-not-set fields?

### ISSUE THREAD

**Issue by silviogutierrez** [carltongibson/django-filter#446]
Hi there,

Incredible library and super easy to use. Very Djangonic/Pythonic. 

One use case I have is filtering by date _or_ date **not** being set. Now, this can easily be done with the meta syntax:

``` python
    class Meta:
        model = models.Widget
        fields = {
            'approved_at': ['exact', 'gte', 'lte', 'isnull'],
        }
```

But that technically creates three filters. For doing that with one filter, you can currently use DateFromToRangeFilter, but you lose the "is not set" functionality. I find using one filter to be more idiomatic, specially if you are generating a UI from it and want just one widget.

So I wrote this crude first pass:

``` python
class NullableRangeWidget(django_filters.widgets.RangeWidget):
    def __init__(self, attrs=None):
        widgets = (forms.TextInput, forms.TextInput, forms.NullBooleanSelect)
        forms.MultiWidget.__init__(self, widgets, attrs)


class NullableDateRangeField(django_filters.fields.RangeField):
    widget = NullableRangeWidget

    def __init__(self, *args, **kwargs):
        fields = (
            forms.DateField(),
            forms.DateField(),
            forms.BooleanField())
        super(NullableDateRangeField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if data_list:
            start_date, stop_date, is_null = data_list

            if is_null:
                return 'MAGIC'
            else:
                return super(NullableDateRangeField, self).compress([start_date, stop_date])
        return None


class NullableDateRangeFilter(django_filters.filters.RangeFilter):
    field_class = NullableDateRangeField

    def filter(self, qs, value):
        if value == 'MAGIC':
            lookup = '%s__isnull' % self.name
            return self.get_method(qs)(**{lookup: True})
        return super(NullableDateRangeFilter, self).filter(qs, value)
```

Any interest in something like this? So now you can say "approved_at" is not set.

Let me know and I'd be happy to clean it up and make a PR. I'd also need some suggestions on how to use a magic value to trigger the null check (as None is not usable).

Best,

Silvio

**Comment by carltongibson** [comment]
Hi Silvio. 

`value == 'MAGIC'` — I've used exactly this kind of thing before. I'm not sure there's any other way around it. 

Other than that, yes — a clean Filter with docs and tests would be given a warn welcome. :-)

**Comment by carltongibson** [comment]
I'm going to close this in favour of #541. 

As it stands I don't see a generic solution, and I don't want to add a plethora of `Filter` subclasses to the main project for every possible use-case. (The custom filters are pretty easy to come up with yourself.)

Happy to take a PR with that generic solution. 🙂
