### ISSUE TITLE
Deprecate autogeneration of filters for empty Meta.fields in favor of '__all__'

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#450]
I was somewhat surprised to find that filters are automatically generated for all model fields for the following filterset:

```py
class UserFilter(FilterSet):
    username = filter.CharFilter(lookup_expr='iexact')

    class Meta:
        model = User

>>> UserFilter.base_filters.keys()
['username', 'first_name', 'last_name', 'status', 'is_active', 'favorite_books']
```

I would have expected just the one `username` filter. It makes sense to me to deprecate this behavior in favor of using `fields = '__all__'` - similar to DRF's serializers and Django's ModelForms.
- Aside from API consistency, there are all of the [stated reasons](https://docs.djangoproject.com/en/1.9/topics/forms/modelforms/#selecting-the-fields-to-use) for requiring a declared value. The security risk is smaller since filters can't alter data, but users could still unintentionally expose information about the data model or the data itself. e.g., you may not be able to view an employee's salary, but you could accidentally allow users to filter by it.
- The implementation to support `Meta.fields = None` requires ignoring unrecognized field types, such as `tests.models.SubnetMaskField`. This prevents us from providing meaningful errors to the user. e.g.,

  ```py
  class NetworkSettingFilter(FilterSet):
      class Meta:
          model = NetworkSetting
          fields = ['mask']
  ```

  We should be able to inform the user that the field type is unrecognized, and that they need to use `filter_overrides` or alter the `DEFAULTS`. Currently, users get:
  ```py
  AttributeError: 'NoneType' object has no attribute 'model'
  ```

Thoughts?

**Comment by carltongibson** [comment]
OK yes. I'm in favour of this at first glance. 

I've got a couple of API changed in mind. I also need to merge you outstanding PRs

I like the roadmap to a 1.0 we've discussed. Target for all of this is August, when I'll have the time to give. i.e. 1.0 before September. I guess this would go there.

**Comment by carltongibson** [comment]
Incidentally, avoiding automatic creation of (potentially dangerous) filters is why I'm not keen on the automatic relationship spanning of DRF filters.

**Comment by rpkilby** [comment]
> Incidentally, avoiding automatic creation of (potentially dangerous) filters is why I'm not keen on the automatic relationship spanning of DRF filters.

You're absolutely right. There's been some recent discussion on spanning to-many relationships that has had me thinking about this. The short version is that a viewset typically has a get_queryset implementation that will provide default view permissions filtering. eg, for a Post resource, you may allow the logged-in user to view all of his/her posts and any *published* posts for all other authors. With drf-filters, there's no access to the request context, so you can't do any meaningful filtering - most users will just use the default queryset. So, while I may not be able to view another author's unpublished posts, I could try to divine what they're talking about. eg,

```http
/api/authors?post__is_published=False&post__body__contains=juicy%20story%20details
```

Not *super* terrible, but eek :/ 
The Good News is that I've got some ideas on how to solve this in a dryish, user-friendly manner.
