### ISSUE TITLE
django-filter shows all fields instead of just the ones specified

### ISSUE THREAD

**Issue by voodoo-burger** [carltongibson/django-filter#456]
I'm trying to use django-filter to filter my auth.User table (and a single field from a 1-to-1 table called Profile) like so:

```
class MemberListFilter(django_filters.FilterSet):
    username = django_filters.CharFilter(lookup_expr=['icontains', 'exact'], label='Username contains', help_text='')
    date_joined = django_filters.DateFilter(lookup_expr=['lte', 'gte'], help_text='')
    last_login = django_filters.DateFilter(lookup_expr=['lte', 'gte'], help_text='')
    email = django_filters.CharFilter(lookup_expr='icontains', label='Email address contains', help_text='')
    profile__post_count = django_filters.NumberFilter(lookup_expr=['lte', 'gte'], label='Post count', help_text='')

    class Meta:
        model = User
```

The problem is that this gives me not only the 5 fields I defined, but every single field in the User table. Am I doing something wrong? Tested on Django 1.9.9 and 1.10 .

![django-filter1](https://cloud.githubusercontent.com/assets/11193663/17627269/ecc3d06c-60b0-11e6-96ea-1b417bae5d6f.PNG)

**Comment by voodoo-burger** [comment]
I guess this is similar to issue #450 . A workaround seems to be adding `fields = []` to the meta class.

**Comment by carltongibson** [comment]
@voodoo-burger Yep. Specify the fields you want, otherwise the default is _all fields_
