### ISSUE TITLE
Render lookup type selector before input field

### ISSUE THREAD

**Issue by voodoo-burger** [carltongibson/django-filter#457]
Is it possible to render the lookup type select box before the input field in the form? So that it reads more naturally: "<Field name> <Lookup expression select box> <Input box>" ?

For example: "Date joined greater than or equal to 08/01/2016 " instead of "Date joined 08/01/2016 greater than or equal to" .

Thanks :)

**Comment by carltongibson** [comment]
It's just a Django form. See [the docs on Working with Templates](https://docs.djangoproject.com/en/1.10/topics/forms/#working-with-form-templates)
