### ISSUE TITLE
Property overrides should be enforced before meta fields in FilterSet

### ISSUE THREAD

**Issue by jmacul2** [carltongibson/django-filter#461]
I'll try an explain this the best I can.  I have a filterset that uses a non standard form field MACAddressFormField that uses a non-standard model field MACAddressField.  

My code is like so: 

```
class MacAddressFilter(Filter):
    field_class = MACAddressFormField

class HostFilter(FilterSet):
    mac = MacAddressFilter(lookup_expr='istartswith')

    filter_overrides = {
        MACAddressField: {
            'filter_class': MacAddressFilter,
            'extra': lambda f: {
                'lookup_expr': 'istartswith',
            },
        },
    }

    class Meta:
        model = Host
        fields = ['mac', 'hostname']
```

The problem here is that in previous versions <= 0.13, I didn't have to use filter_overrides because I am explicitly declaring a property on the FilterSet that should override the model field "mac"  But with version >= 0.14, even when declaring this property, checks are run that throw an Assertion error telling me that it doesn't know what MacAddressField is until I use a filter_override.  This seems like overkill.  If I override the field using a property, then it shouldn't care.  Make sense?

**Comment by rpkilby** [comment]
Hi @jmacul2 - remove `mac` from `fields`. The `fields` option is used purely for filter generation, so it's unnecessary to include it when you've already created your filter declaratively. This is related to #450 - the error message should address this case too.

**Comment by jmacul2** [comment]
That works.  Thanks for clarifying.

**Comment by rpkilby** [comment]
btw, #550 is a potential fix for this issue. The filter generation would skip over already declared filters, so it would be safe to include `mac` in the fields list.
