### ISSUE TITLE
Add an EmptyValue/EmptyString filter

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#478]
Originally from philipn/django-rest-framework-filters#104

It's not currently possible to filter by an empty value. eg, 

``` http
GET http://localhost/api/my-model?myfield=
```

We should be able to handle this case similarly to how `isnull` is handled. Possible implementation:

``` py
from django.core.validators import EMPTY_VALUES

class EmptyStringFilter(filters.BooleanFilter):
    def filter(self, qs, value):
        if value in EMPTY_VALUES:
            return qs

        exclude = self.exclude ^ (value is False)
        method = qs.exclude if exclude else qs.filter

        return method(**{self.name: ""})


class MyFilterSet(filters.FilterSet):
    myfield__isempty = EmptyStringFilter(name='myfield')

    class Meta:
        model = MyModel
```

``` http
GET http://localhost/api/my-model?myfield__isempty=false
```

**Comment by carltongibson** [comment]
I'm going to close this in favour of #541. 

As it stands I don't see a generic solution, and I don't want to add a plethora of `Filter` subclasses to the main project for every possible use-case. (The custom filters are pretty easy to come up with yourself.)

Happy to take a PR with that generic solution. 🙂
