### ISSUE TITLE
get_order_by() deprecation in 0.15 links to nonexistent docs

### ISSUE THREAD

**Issue by edmcdonagh** [carltongibson/django-filter#495]
AssertionError links to the following URL, which doesn't exist:

https://django-filter.readthedocs.io/en/latest/migration.html

**Comment by rpkilby** [comment]
Hi @edmcdonagh. It looks like the docs aren't up-to-date with the most recent release. I have a temporary build of the docs [here](http://rpkilby.github.io/django-filter/migration.html). Additionally, the source file can be read [here](https://github.com/carltongibson/django-filter/blob/develop/docs/migration.txt).

**Comment by carltongibson** [comment]
Thanks for the report. Updated now.

**Comment by edmcdonagh** [comment]
Thanks both of you. Now I need to fix and rerelease OpenREM. Or at least peg to 0.14!

**Comment by carltongibson** [comment]
Do you have a breakage from the ordering changes?

**Comment by edmcdonagh** [comment]
Yes, I get a 500 server error with debug off, and the following message if debug is on:

```
AssertionError at /openrem/ct/
get_order_by() has been deprecated. Subclass OrderingFilter and override .filter() instead. See: https://django-filter.readthedocs.io/en/latest/migration.html"
Request Method: GET
Request URL:    http://192.168.56.102:8000/openrem/ct/?display_name=example&o=-study_date
Django Version: 1.8.14
Exception Type: AssertionError
Exception Value:    
get_order_by() has been deprecated. Subclass OrderingFilter and override .filter() instead. See: https://django-filter.readthedocs.io/en/latest/migration.html"
Exception Location: /home/rem/virtenv/local/lib/python2.7/site-packages/django_filters/filterset.py in __new__, line 200
```

To be fair I haven't modified my django-filter related code since I first started using it a few years ago, and I'm aware that I could be using it to much better effect as the functionality has evolved. Its just one of those 'it works, so lets concentrate on all the other things that I need to do' things!

**Comment by carltongibson** [comment]
OK. Fair enough. (I think if you just remove `get_order_by` you should be OK...)

**Comment by edmcdonagh** [comment]
Hi @carltongibson 

Am I right that OrderingFilter isn't introduced until release 0.15, yet order_by isn't allowed in 0.15?

**Comment by carltongibson** [comment]
@edmcdonagh: No. With the caveats mentioned in the migration docs, `order_by` and `order_by_field`, whilst deprecated, retain backwards compatibility.

**Comment by edmcdonagh** [comment]
So it's just the get_order_by function? I use that to modify the order by date to order be date and time. Can you point me to how to do that instead?

**Comment by carltongibson** [comment]
Well, there's the OrderingFilter docs... https://django-filter.readthedocs.io/en/latest/ref/filters.html#ordering-filter

> You can subclass OrderingFilter to migrate any custom logic.

Give it a go — it should be pretty simple. If you've got a concrete example of what's _not_ working then it'd be easier to say something (equally) concrete...
