### ISSUE TITLE
OrderingFilter with widget=forms.Select() not working

### ISSUE THREAD

**Issue by bluesurfer** [carltongibson/django-filter#496]
In 0.15.0, when I try to set the widget for `OrderingFilter`, then such filter does not work anymore. For instance:

```
    o = OrderingFilter(
        widget=forms.Select(),
        # tuple-mapping retains order
        fields=(
            ('created', 'Created'),
        ),
        # labels do not need to retain order
        field_labels={
            'created': 'Created',
        }
    )
```

The ordering field now is rendered as a select (I am using crispy-forms) but, instead of ordering, the filter returns no results and as field error it says `c is not a valid choice`.

**Comment by carltongibson** [comment]
I don't think you need to specify the widget here: 

`OrderingFilter` extends `ChoiceFilter` which uses Django's `ChoiceField`, which has a `Select` widget by default. 

You're also passing a widget instance, without the `choices` set, see the `Select()`, where you need to pass the class, i.e. just `Select`. 

I'm going to close this as it doesn't look like an issue. (Happy to re-open if there's more.)

**Comment by bluesurfer** [comment]
I checked it out and the default widget seems to be "CSVWidget" not "Select"

**Comment by carltongibson** [comment]
OK. Fine. Can you add the default HTML that's generated for me? I'll verify what's going on.

**Comment by bluesurfer** [comment]
```
<div id="div_id_o" class="form-group row"> 
    <label for="id_o" class="col-form-label col-lg-3"> Ordering</label> 
     <div class="col-lg-9"> 
         <input class="csvwidget form-control" id="id_o" name="o" type="text"> 
     </div> 
</div>
```
This is what crispy-forms render in HTML.

**Comment by carltongibson** [comment]
OK. And one more thing... what happens if you pass the `Select` class rather than an instance? 

```
...
        widget=forms.Select,  # No `()`
```

**Comment by andreage** [comment]
I had a similar problem. The displayed input form field for the OrderingField was set to a Text field. Setting `widget=forms.Select` for the OrderingField solved the issue.

**Comment by bluesurfer** [comment]
It render correctly as a Select but, the filter does not work. It gives me a field validation error:
`Select a valid choice. C is not one of the available choices.`
Seems like it is only getting the first letter of the field value i.e. "Created"

**Comment by andreage** [comment]
You are right, same problem here.

**Comment by bluesurfer** [comment]
Here's the rendered HTML:
```
<select class="select form-control form-control-danger" id="id_o" name="o">
     <option value="Created" selected="selected">Created</option>
     <option value="-Created">Created (descending)</option>
</select>
```

**Comment by carltongibson** [comment]
> Seems like it is only getting the first letter of the field value i.e. "Created"

That'll be CSVWidget doing it's thing...

**Comment by andreage** [comment]
`FilterClass().filters['o'].field.widget` returns:
<django_filters.widgets.CSVWidget object at 0x7f175250dc50>

**Comment by bluesurfer** [comment]
The problem may be here:
```
class BaseCSVFilter(Filter):
    """
    Base class for CSV type filters, such as IN and RANGE.
    """
    base_field_class = BaseCSVField

    def __init__(self, *args, **kwargs):
        super(BaseCSVFilter, self).__init__(*args, **kwargs)

        class ConcreteCSVField(self.base_field_class, self.field_class):
            pass
        ConcreteCSVField.__name__ = self._field_class_name(
            self.field_class, self.lookup_expr
        )

        self.field_class = ConcreteCSVField
```

I think that the call to `super` sets your widget but then `self.field_class = ConcreteCSVField` messes all up.

**Comment by carltongibson** [comment]
https://github.com/carltongibson/django-filter/pull/499 should give you a workaround. 

The final fix won't look like that — it's not the right fix, but it should get you going. 

DO feedback if you try it and hit issues!

**Comment by rpkilby** [comment]
Hi everyone - #501 is an updated version. You should be able to use `OrderingFilter` without having to provide a `Select` widget.

**Comment by damianoporta** [comment]
Hi everyone,
for the moment i am using the following code to create my filter:

```

class BacktestFilter(django_filters.FilterSet):
    sort = django_filters.OrderingFilter(
        fields=(
            ("profit", "profit"),
        ),
        choices=(
            ("-profit", "Total profit"),
        ),
        widget=forms.Select,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filters["sort"].field.widget.attrs = {
            "class": "form-control"         
        }

```
maybe it is not the clearest solution but it is working. 
For some reason the **widget** parameter does not accept an instance of _forms.Select_ so i added it inside **__init__**
