### ISSUE TITLE
Labelling GET parameters and empty fields

### ISSUE THREAD

**Issue by bluesurfer** [carltongibson/django-filter#502]
Suppose I have a `Student `model with `name`, `surname `and a `OneToOneField `relation with a `Profile`
model to store additional information (e.g. `address`).

Consider a filter form for the fields `name`, `surname`, `profile__address`. Then when I fill the form to look for student 'Joe' with address 'Street', django-filter sends the following request:

`example.com/students/?name=Joe&surname=&city=&profile__address=Street`

Two questions: 

1. Is it possible to assign a label to the fields name in the URL (e.g. profile__address = address)? 

2. Is it possible to prevent sending empty fields (i.e. surname)?

My desired URL would be something like this:

`example.com/students/?name=Joe&address=Street`

**Comment by rpkilby** [comment]
1. Yep - the parameter name of the filter on the filterset is used as the query param name. The filter's `name` argument is the actual model field name. A bit of a mouthful - an example makes more sense:

  ```py
  class StudentFilter(FilterSet):
      street_address = filters.CharFilter(name='profile__address', lookup_expr='iexact')
  ```
  which allows

  ```http
  GET https://example.com/students/?street_address=Street
  ```
2. Not without javascript. If your concern is filtering behavior, empty values are ignored so `?surname=` has no effect. If your concern is readability, then you would have to use javascript to do this. You could intercept the form submit, filter out empty inputs, then continue submitting the form.
