### ISSUE TITLE
Custom choice for OrderingFilter

### ISSUE THREAD

**Issue by bluesurfer** [carltongibson/django-filter#517]
I would like to implement a custom ordering filter to sort by relevance (which involves computing a score) some given objects. Following the `OrderingFilter`implementation this is what I come with.

```
class CustomOrderingFilter(django_filters.OrderingFilter):

    def filter(self, qs, value):
        qs = super(CustomOrderingFilter, self).filter(qs, value)
        if value == 'relevance':
            # sort queryset by relevance (score computing will be here)
            pass
        return qs
```

That seems to work. However when I define the filter choices I must provide a **valid** model field name. Therefore, if the model does not have the `relevance` field then the following code will raise a `NotValidFieldException`.

```
        sort_by = CustomOrderingFilter(
            choices=[
                ('-updated', 'Latest'),
                ('updated', 'Oldest'),
                ('relevance', 'Relevance')  # not valid field
            ],
            label='Sort by'
        )
```

So, is it possible to define a custom sort-by choice?

**Comment by rpkilby** [comment]
Hi @bluesurfer. [`OrderingFilter.filter`](https://github.com/carltongibson/django-filter/blob/0.15.0/django_filters/filters.py#L547-L552) simply reverses parameter names to model field names. You should be able to perform the check before the call to super, like so:

```py
class CustomOrderingFilter(django_filters.OrderingFilter):
    def filter(self, qs, value):
        if value == 'relevance':
            # sort queryset by relevance (score computing will be here)
            return ...
        return super(CustomOrderingFilter, self).filter(qs, value)
```

**Comment by carltongibson** [comment]
I'm going to assume this is resolved. Shout if not.

**Comment by rpkilby** [comment]
@carltongibson - would it be worth adding a documentation example for this. Is it a common enough use case?

**Comment by carltongibson** [comment]
Good idea!
