### ISSUE TITLE
OrderingFilter: how to get the old `order_by=True` behavior?

### ISSUE THREAD

**Issue by blueyed** [carltongibson/django-filter#518]
I came up with the following hack:

``` python
class BaseFilterSet(filters.FilterSet):
    ...

    def __new__(cls, *args, **kwargs):
        cls_ = super().__new__(cls)

        class opts:
            order_by = True
            fields = None  # just for the dict check.

        ordering = cls_.get_ordering_filter(opts, cls_.base_filters)
        cls_.base_filters['ordering'] = ordering
        cls_.declared_filters['ordering'] = ordering
        return cls_
```

I've also tried to add a new filter class like `AllFieldsOrderingFilter(OrderingFilter)`, but it does not have access to the filterset to get all fields.. only at the end of `BaseFilterSet.__init__` the `parent` reference is set - so at least it seems to not be possible during initialization currently?!

**Comment by rpkilby** [comment]
Replicating the `Meta.order_by` behavior is tricky, as it wasn't well defined. For example, take the following filterset:
```py
class UserFilter(FilterSet):
    account = filters.CharFilter(name='username', lookup_expr='exact')
    account_is_like = filters.CharFilter(name='username', lookup_expr='icontains')

    class Meta:
        model = User
        order_by = True
```

This resulted in the following ordering filter:

```html
<th><label for="id_o">Ordering:</label></th>
<td><select id="id_o" name="o">
    <option value="account">Account</option>
    <option value="-account">Account (descending)</option>
    <option value="account_is_like">Account_is_like</option>
    <option value="-account_is_like">Account_is_like (descending)</option>
</select></td>
```

As you can see, `Meta.order_by = True` only works well when:
- there is only one filter per model field (It did not discern duplicate filters for a model field).
- the filter is named like an `exact` filter (`account_is_like` doesn't translate). 

You might be able to get away with some of the original magic by supporting filters using *only* `exact` lookups. It's a bit of a hack, but you should be able to override the `field` property to generate your choices. At this point, the filter has access to the `parent`. Something like the following should work:

```py
class AllFieldsOrderingFilter(OrderingFilter):

    @property
    def field(self):
        fields = OrderedDict([
            (f.name, param) for param, f 
            in self.parent.filters.items()
            if f.lookup_expr == 'exact'
        ])
        field_labels = {
            f.name: f.label for f
            in self.parent.filters.values()
            if f.lookup_expr == 'exact'
        }

        # set param map so we can reverse param names to field names (ie, account => username)
        self.param_map = {v: k for k, v in fields.items()}

        # overwrite choices - more complicated handling may be necessary to support
        # additional choices/fields passed in through filter initialization.
        self.extra['choices'] = self.build_choices(fields, field_labels)

        return super(AllFieldsOrderingFilter, self).field
```

**Comment by rpkilby** [comment]
Alternatively, if you'd prefer to handle this as part of the filterset, you could override the `FilterSetMetaclass.__new__` or `FilterSet.__init__`  and add the OrderingFilter there.

**Comment by rpkilby** [comment]
Hi @blueyed - is there anything else that needs to be resolved here?

**Comment by blueyed** [comment]
@rpkilby 
I have not looked much into it yet.
But in general I think it is a feature worth supporting in an easy way, if only by documenting it.

**Comment by carltongibson** [comment]
What's the actual request here? Something like, "Can we add an OrderingFilter without actually having to declare it?"

**Comment by blueyed** [comment]
@carltongibson 
Yes.

**Comment by carltongibson** [comment]
OK. I'm not sure, though, that it gets much simpler than:

    o = OrderingFilter(fields=["name", "age", "nationality"])

(Or whatever for your case)

What's the UI you want look like?

**Comment by rpkilby** [comment]
It seems like there are two separate request:
1. Add an ordering filter without having to explicitly declare the filter itself.
2. Automagically enable filtering on all fields. 

For the first point, I'm kind of ambivalent. We could add back `Meta.order_by`, but how much more simple or efficient is 

```py
class MyFilterSet(filters.FilterSet):
    class Meta:
        model = MyModel
        order_by = [...]

# vs. 
```

**Comment by rpkilby** [comment]
It seems like there are two separate request:
1. Add an ordering filter without having to explicitly declare the filter itself.
2. Automagically enable filtering on all fields. 

For the first point, I'm kind of ambivalent. We could add back `Meta.order_by`, but how much more simple or efficient is 

```py
class MyFilterSet(filters.FilterSet):
    class Meta:
        model = MyModel
        order_by = [...]

# vs. 

class MyFilterSet(filters.FilterSet):
    o = filters.OrderingFilter(fields=[...])

    class Meta:
        model = MyModel
```

As to the second point, I don't think there's anything that can be added to the core that is generally correct in enough cases. Correctness has to account for labels (aliasing), duplicate fields, which fields should be filtered on, etc... 

Maybe add the `AllFieldsOrderingFilter` from above, but with the caveat that it's unsupported (a la crispy-forms integration).

**Comment by carltongibson** [comment]
> Maybe add the AllFieldsOrderingFilter from above, but with the caveat that it's unsupported...

I don't want to do this. 

I'm going to close this. It's not something I want to support as is.

**Comment by blueyed** [comment]
This is what I came up with:
```python
from django_filters import rest_framework as filters

class BaseFilterSet(filters.FilterSet):

    def __new__(cls, *args, **kwargs):
        """Use a default ordering filter (on all filters).

        This gets updated from override_ordering, if defined.
        """
        cls_ = super().__new__(cls)

        ordering = filters.OrderingFilter(fields=cls_.base_filters.keys())
        try:
            override_ordering = cls_.base_filters['override_ordering']
        except KeyError:
            pass
        else:
            ordering.param_map.update(override_ordering.param_map)
        cls_.base_filters['ordering'] = ordering
        cls_.declared_filters['ordering'] = ordering
        return cls_
```
