### ISSUE TITLE
how filter range with coma seaparated value or how create JS slider from RangeWidged

### ISSUE THREAD

**Issue by Megido6** [carltongibson/django-filter#527]
i create form with pretty sliders, but my sliders create url like param1=1,57&param2=2,67
django-filter not understand this format?
i create custom sliders without rangewidget because i dont want manually enter digits in two fields.
if this module have native range  slider widget on jquery it will be solve my problem.

**Comment by rpkilby** [comment]
Hi @Megido6 - you should try stackoverflow for usage questions.
