### ISSUE TITLE
How to "Serialize" a Filter for DRF?

### ISSUE THREAD

**Issue by awolfmann** [carltongibson/django-filter#529]
I'm using Django Rest Framework, and now i'm implementing some filters on my app.
I have defined a filter with fields, some of them are AllValuesMultipleFilter.
This works perfectly in the browsable API, but I would like to send through my API what are the available fields to filters, and the possibles choices to put on them, so the frontend can have the information about what are the filters to show and which options.. So i thought about  'serialize' the filter and send it in a json, but i don't know if is the right approach to deal with this?

Extra comment: AllValuesMultipleFilter is not available, django_filter.AllValuesMultipleFilter throws an attribute error, so i copied that part of your code into my app, and it works fine, is this intentional thinking about deprecate it or just a mistake?

Thanks!

**Comment by rpkilby** [comment]
You may want to take a look at DRF's [schema](http://www.django-rest-framework.org/api-guide/schemas/) abstraction. #492 added core-api integration. 

> Extra comment: AllValuesMultipleFilter is not available, django_filter.AllValuesMultipleFilter throws an attribute error, so i copied that part of your code into my app, and it works fine, is this intentional thinking about deprecate it or just a mistake?

That is a mistake. Fixed in  #531.

**Comment by awolfmann** [comment]
Hey @rpkilby Thanks for the tip!
Do you have an example of a use case? I couldn't find anyone.. I tried with:
`
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_class = UserFilter


class UserFilterSchemaView(APIView):
    renderer_classes = [CoreJSONRenderer]

    def get(self, request):
        generator = schemas.SchemaGenerator(title='User filters')
        uservws = UserViewSet()
        filters = generator.get_filter_fields(path='/users/', view=uservws.list(request), method=request.method)
        return Response(filters)`

But it doesn't work yet..

Sorry for continue bothering..

**Comment by rpkilby** [comment]
Sorry - I'm not familiar with core-api. #492 was based on work by DRF's author. 

That said, I would look at [`SchemaGenerator`](http://www.django-rest-framework.org/api-guide/schemas/#schemagenerator). It seems to handle exposing the various filter backends.
