### ISSUE TITLE
How to access the current user in MethodFilter?

### ISSUE THREAD

**Issue by Canicio** [carltongibson/django-filter#530]
For example:

    class MyFilter(filters.FilterSet):
        field = MethodFilter()
        def filter_field(self, queryset, value):
            if value:
                return queryset.filter(user=...)
            return queryset

'self.request.user' does not exist

**Comment by rpkilby** [comment]
#520 was recently merged and should be available in the next release. In the mean time, you would have to manually set the request on the filterset in order to access it in the filter method.

**Comment by Canicio** [comment]
Ok. Thank you very much.
