### ISSUE TITLE
Add an applied_filters attribute or method to a bound filter instance

### ISSUE THREAD

**Issue by epicserve** [carltongibson/django-filter#534]
It would be nice to have a method or attribute for the a `filter` instance so that you can list what filters have been applied to your query set. So in a template you could list what filters are being used and provide a link to remove them.

It would be nice it returned a list or iterable that's something like the following:

``` python
>>> filter.applied_filters
[
    {'field': 'music_artists', 'label': 'Music Artists', 'selected_value': 1, 'selected_option': 'Django Reinhardt'} 
]
```

**Comment by rpkilby** [comment]
This seems like something that should be handled by the filterset form. If the filter field has a bound value, then you can display the link to clear the field. If the field has no value, it will return `None`. 

```py
>>> f = MyFilterSet(data={'field1': 'value'})
>>> f.form['field1'].value()
'value'
>>> f.form['field2'].value()
None
```

**Comment by epicserve** [comment]
@rpkilby How would you get the option selected from a select type field like a Boolean field (e.g. Yes or No)?

**Comment by rpkilby** [comment]
Do you need the actual value or the display value? The actual value would be accessible w/ the `.value()` call. To get the display value, you would have to access the field's choices.

**Comment by epicserve** [comment]
However finding the choices isn't working at the moment.

```
ipdb> filter.form.fields['completed']
<django.forms.fields.NullBooleanField object at 0x10ff70400>
ipdb> filter.form.fields['completed'].choices
*** AttributeError: 'NullBooleanField' object has no attribute 'choices'
```

This is way it would be handy to have what I suggested so others could just easily use the data. Seemls logical to me anyway that if you have a filter library you would want data easily accessible to use for what filters have been applied.

**Comment by rpkilby** [comment]
Keep in mind that when the form is initialized, you're dealing with `BoundField`s. In order to access the underlying field class, you would need to do the following:
```py
filter.form.fields['completed'].field.choices
```

Either way, it's not entirely clear what you're trying to achieve.

> It would be nice to have a method or attribute for the a filter instance so that you can list what filters have been applied to your query set. So in a template you could list what filters are being used and provide a link to remove them.

- Why isn't the rendered form sufficient?
- Why can't the users just remove the value from the form field and resubmit the form?

**Comment by epicserve** [comment]
No joy:

```python
ipdb> filter.form.fields['completed'].field.choices
*** AttributeError: 'NullBooleanField' object has no attribute 'field'
```

> Why isn't the rendered form sufficient?

Because it's becoming a pain to get the data needed

> Why can't the users just remove the value from the form field and resubmit the form?

They can, but when you have a UI where the filter form isn't always visible and is shown or hidden by clicking a filter button, it's nice to display what has been applied with removable labels like the following screenshot found by doing a Google image search for "applied filters."

![16-3-risk-filter-applied](https://cloud.githubusercontent.com/assets/191620/19774844/03dec054-9c34-11e6-9f34-ee7b9198e1f5.png)

For example in a template when using bootstrap you might do something like this:

```html
{% if applied_filters %}
    <div class="applied-filters">
        {% for key, value in applied_filters %}
            <div class="btn-group" role="group" aria-label="...">
                <button type="button" class="btn btn-default" data-param="{{ key }}">{{ value }}</button>
                <a href="#" class="btn btn-default btn-remove">&times;</a>
            </div>
        {% endfor %}
    </div>
{% endif %}
```

And then add some Javascript to for removing a filter.

```javascript
$('.applied-filters button').each(function() {
    var $btn = $(this),
        param = $btn.data('param') + '=',
        re = new RegExp("([&?])(" + param + ")=([^&]$|[^&]*)", "i"),
        is_param_found = location.href.match(re),
        href = location.href;

    if (!is_param_found) {
        href += (location.href.indexOf('?') === -1) ? '?' : '&';
        href += param;
    } else {
        href = location.href.replace(re, "$1$2");
    }
    $btn.next('.btn-remove').attr('href', href);
});
```

**Comment by rpkilby** [comment]
There is a difference between 

```py
filter.form['completed']
```
and 
```py
filter.form.fields['completed']
```

The former is the bound field, the latter is the regular form field. 

You could do either of the following to get the choices.
```py
filter.form['completed'].field.choices
# or
filter.form.fields['completed'].choices
```

**Comment by epicserve** [comment]
I just don't think choices are available on a NullBooleanField. I've tried it all the ways you're talking about.

**Comment by rpkilby** [comment]
Ah - null boolean is slightly different in that it's the [`NullBooleanSelect`](https://github.com/django/django/blob/1.10/django/forms/widgets.py#L561-L589) widget that provides the choices.

**Comment by epicserve** [comment]
Anyway are you starting to understanding way having a method/attribute like `filter.applied_filters` with the data I suggested would be super nice?

**Comment by carltongibson** [comment]
> * Why isn't the rendered form sufficient? That should display all of the filter fields with their applied values.
> * Why can't the users just clear the value from the form field and resubmit the form?

OK, first pass, _this_. If you want to progressively enhance the form in any way you can but, that would be my first port of call. 

> Because it's becoming a pain to get the data needed
> ...
> They can, but when you have a UI where the filter form isn't always visible and is shown or hidden by clicking a filter button, it's nice to display what has been applied with removable labels like the following screenshot found by doing a Google image search for "applied filters."

I'm inclined to say this is something needs handing on the client side. (There are all sorts of libraries that take a vanilla HTML form and enhance it.)

_Maybe_ there's room for a utility to inspect a Django Form and output a nice JSON representation but I'd that's Out of Scope for Django Filter. (It wouldn't surprise me if something like that didn't already exist.)

I'm going to close this one.
