### ISSUE TITLE
Double Join

### ISSUE THREAD

**Issue by Aletz-Morales** [carltongibson/django-filter#537]
When set multiple filter related to parent table, query is generated with double join.

`SELECT `core_product`.`id`, `core_product`.`name`, `core_product`.`active`, `core_product`.`created_at`, `core_product`.`updated_at`, `core_product`.`nutrients_info`, `core_product`.`ingredients_info`, `core_product`.`nutri_data_info`, `core_product`.`brand_id`, `core_product`.`category_id`, `core_product`.`sub_category_id`, `core_product`.`type_id`, `core_product`.`division_id`, `core_product`.`reference_vale_id`, `product_category`.`id`, `product_category`.`name`, `product_category`.`active`, `product_category`.`created_at`, `product_category`.`updated_at`, `product_category`.`product_type_id`, `product_type`.`id`, `product_type`.`name`, `product_type`.`active`, `product_type`.`created_at`, `product_type`.`updated_at` FROM `core_product` INNER JOIN `product_category` ON (`core_product`.`category_id` = `product_category`.`id`) INNER JOIN `product_type` ON (`product_category`.`product_type_id` = `product_type`.`id`) INNER JOIN `core_product_nutrient` ON (`core_product`.`id` = `core_product_nutrient`.`product_id`) INNER JOIN `core_product_nutrient` T5 ON (`core_product`.`id` = T5.`product_id`) WHERE (`core_product_nutrient`.`name` LIKE %sodio% AND T5.`value` BETWEEN 14 AND 100) GROUP BY `core_product`.`id` ORDER BY NULL`

`core_product_nutrient` is join double time

**Comment by rpkilby** [comment]
Reformatted SQL:

```sql

SELECT core_product.id,
       core_product.name,
       core_product.active,
       core_product.created_at,
       core_product.updated_at,
       core_product.nutrients_info,
       core_product.ingredients_info,
       core_product.nutri_data_info,
       core_product.brand_id,
       core_product.category_id,
       core_product.sub_category_id,
       core_product.type_id,
       core_product.division_id,
       core_product.reference_vale_id,
       product_category.id,
       product_category.name,
       product_category.active,
       product_category.created_at,
       product_category.updated_at,
       product_category.product_type_id,
       product_type.id,
       product_type.name,
       product_type.active,
       product_type.created_at,
       product_type.updated_at
FROM core_product
INNER JOIN product_category ON (core_product.category_id = product_category.id)
INNER JOIN product_type ON (product_category.product_type_id = product_type.id)
INNER JOIN core_product_nutrient ON (core_product.id = core_product_nutrient.product_id)
INNER JOIN core_product_nutrient T5 ON (core_product.id = T5.product_id)
WHERE (core_product_nutrient.name LIKE %sodio%
       AND T5.value BETWEEN 14 AND 100)
GROUP BY core_product.id
ORDER BY NULL
```

**Comment by carltongibson** [comment]
This isn't a Django Filter issue. (_If_ it's an issue, it's an issue for the Django ORM.)
