### ISSUE TITLE
Improve Docs on Filtering for empty values

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-filter#541]
It's often needed to filter for items where a value **is not set**. 

It's a bit tricky because we need to distinguish between a `null` and a merely empty value. 

There are various approaches (add an extra filter, add a `MAGIC` value, ...). None are complicated, but none are such that we want to add every possible `Filter` subclass to the core library. 

(If a decent generic solution turns up, we'll have that. Until then...)  

* [ ] Better document existing approaches with examples of creating your own subclass. 
    * Using `isnull`
    * None/Any handling on `ChoiceFilter` #519
    * Suggested `EmptyStringFilter` #478 
    * Suggested `NullableDateRangeFilter` #446

**Comment by rpkilby** [comment]
So, a "Filtering by empty values" section in the docs that discusses existing approaches as well as home-brewed approaches? Where should this live? Usage guide would make the most sense right now, but that section is already fairly long.

**Comment by carltongibson** [comment]
> Usage guide would make the most sense right now, but that section is already fairly long.

Indeed. :-)

I'm secretly planning a docs re-organisation...

If you fancy taking this on, how about creating a new page, as a sub section of `Usage`? That would be a good temporary place, even if it moves.

**Comment by rpkilby** [comment]
Not a bad idea. That said, is it worth postponing the 1.0 release for a docs rework?

**Comment by carltongibson** [comment]
I'd like to close this issue. (And there's one or two little doc changes I want to add as well.) But I see the docs as an ongoing project, rather than _Version 2™_ — It won't block the 1.0
