### ISSUE TITLE
Custom data input format for MultipleChoiceFilter / TypedMultipleValueField

### ISSUE THREAD

**Issue by pySilver** [carltongibson/django-filter#544]
Hi!

I've added support for custom data input for MultipleChoiceFilter-like fields so it can accept data as:

```
1. Values can be provided as comma separated strings
2. Values can be provided in array style (foo[]=bar&foo[]=bar)
```

Its common format for some JS frameworks (like angular). If community is interested, I'll make a PR

**Comment by carltongibson** [comment]
Hi. I'm not sure I fully follow... Could you elaborate? (Why is what you're suggesting not covered by `CSVWidget`?)

Thanks.

**Comment by pySilver** [comment]
First of all CSVWidget won't consume `foo[]=bar&foo[]=bar` which is common for rails/php/jquery folks:

http://api.jquery.com/jquery.param/
https://coderwall.com/p/uh8kiw/pass-arrays-objects-via-querystring-the-rack-rails-way

I'm not sure this is something that should be supported by django-filter out of the box though. We've faced this issue while developing AngularJS based frontend for DRF API backend and made it work this way:

```python
class FilterSet(filterset.FilterSet):
    """
    This FilterSet adds syntax sugar for MultipleChoiceFilter's

    1. Values can be provided as comma separated strings
    2. Values can be provided in array style (foo[]=bar&foo[]=bar)
    """

    def __init__(self, *args, **kwargs):
        data = kwargs.get('data')

        if data:
            data = data.copy()
            for name, _filter in six.iteritems(self.filters):
                # Multiple values can be enabled using explicit filter or by
                # turing on feature via filter **kwargs
                if isinstance(_filter, MultipleChoiceFilter) or \
                   issubclass(_filter.field_class, TypedMultipleChoiceField):

                    extracted_data = set()
                    request_data = data.getlist(name, data.getlist('%s[]' % name))
                    for item in request_data:
                        extracted_data.update(
                            [x.strip() for x in item.rstrip(',').split(',') if x]
                        )

                    try:
                        del data[name]
                    except KeyError:
                        pass

                    data.update(MultiValueDict({
                        name: list(extracted_data)
                    }))

            kwargs['data'] = data

        super(FilterSet, self).__init__(*args, **kwargs)
```

I haven't tried CSVWidget, it partially covers use-case. Anyway, it would require to override MultipleChoiceFilter so it always uses CSVWidget, so we won't produce repetitive code, every time we need csv input support.

All of this is useful for DRF only, since it's not a django who renders frontend markup and have control how data will be submitted.

p.s. Is there any particular reason why there is no TypedMultipleChoiceFilter?

**Comment by carltongibson** [comment]
OK. I understand. 

This should be handled at the widget level... but yes, if a PR comes in I'd be happy to look at it. 

TypedMultipleChiiceFilter: happy to take a PR. See #493

**Comment by carltongibson** [comment]
I'm going to close this: it's not an active issue. 

As I say, happy to look at a PR — begin with the widget, look at field and filter from there — it may be that they live at the user project level.
