### ISSUE TITLE
use django-filters，Multi table joint query is very slow,help!!

### ISSUE THREAD

**Issue by shandy-li** [carltongibson/django-filter#557]
Is studying Django, encountered the following problems
django version：1.9.4
python：2.7.2
django-filters：0.15.3

use django-filters，Multi table joint query is very slow,help!!

[code.txt](https://github.com/carltongibson/django-filter/files/583024/code.txt)

**models.py:**
from django.db import models

class Publish(models.Model):
    publishid = models.IntegerFiled(primary_key=True)
    publishname = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self): 
        return self.publishname

class Author(models.Model):
    authorid = models.IntegerFiled(primary_key=True)
    authorname = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self): 
        return self.authorname

class Book(models.Model):
    bookid = models.IntegerFiled(primary_key=True)
	bookname = models.CharField(max_length=255)
    publishid_id = models.ForeignKey(Publish)
	authorid_id = models.ForeignKey(Author)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    n_comments = models.IntegerField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __str__(self):
        return self.bookname

**views.py**

from django.shortcuts import get_object_or_404, render_to_response
from all.models import Publish,Author,Book
from django.http import HttpResponse
import django_filters

class BookFilterSet(django_filters.FilterSet):
	class Meta:
	model = Book
	fields = ['bookid','bookname', 'publishid', 'authorid']

class PublishFilterSet(django_filters.FilterSet):
	class Meta:
	model = Publish
	fields = ['publishid','publishname']

class AuthorFilterSet(django_filters.FilterSet):
	class Meta:
	model = Author
	fields = ['authorid','authorname']

def server_list(request):
	author_filterset = AuthorFilterSet(request.GET or None)
	pub_filterset = PublishFilterSet(request.GET or None)
	book_filterset = ServerFilterSet(request.GET or None)	
	return render_to_response('templates/book_list.html',{'book_filterset': book_filterset,'author_filterset':author_filterset,'pub_filterset':pub_filterset})

**book_list.html**
	
<table width="800" border="1" align="center" cellpadding="5" cellspacing="0" bordercolor="#CCCCCC">
<form method="get"  action=".">
    <tr><td>author
        <select name="authorid" id="authorid">
            <option value="">---</option>
        {% for author in author_filterset %}
            <option value="{{ author.authorid }}">{{ author.authorname }}</option>
        {% endfor %}
        </select>
        </td>
        <td>publish
        <select name="publishid" id="publishid">
            <option value="">---</option>
        {% for pub in pub_filterset %}
            <option value="{{ pub.publishid }}">{{ pub.publishname }}</option>
        {% endfor %}
        </select>
        </td><td>&nbsp;</td><td>&nbsp;</td><td><input type="submit" value="Submit"></td>
    </tr>
</form>
    {% for book in book_filterset %}
    <tr>
    <td>{{ book.id }}</a></td>
    <td>{{ book.bookname }}</td>
    <td>{{ book.authorid }}</td> 
    <td>{{ book.publishid }}</td> 
    </tr>
    {% endfor %}
</table>	

access book_list very slow!!
Where is the problem？？

thanks!!

**Comment by carltongibson** [comment]
I'm sorry, I can't diagnose performance problems for you. 

I suggest you try [Django Debug Toolbar](http://django-debug-toolbar.readthedocs.io/en/stable/) and look at your SQL queries.
