### ISSUE TITLE
Potential issue using 'together' filterset

### ISSUE THREAD

**Issue by sanjredfield** [carltongibson/django-filter#561]
When using the 'together' filterset, I find that I cannot send a query with parameter value 0. For example, suppose my filter defines:

```python
class Meta:
    fields = ['balance', 'total']
    together = ['balance', 'total']
```

A request with params { 'balance': 0, 'total': 10 } will return empty, even if there is a valid match. The issue seems to be in the get_full_clean_override function within filterset.py, specifically this line: 

```python
count = len([i for i in fieldset if cleaned_data.get(i)])  # line 50 in the 'develop' branch
```

One possible fix is to change this line as follows: 

```python
count = len([i for i in fieldset if cleaned_data.get(i) is not None])
```

**Comment by carltongibson** [comment]
OK. Yes. There's always issues with _Falsey_ values... First thing is a test case on this but I'd happily review a patch.

**Comment by rpkilby** [comment]
Would `None` or `filters.EMPTY_VALUES` be a more appropriate check?

**Comment by sanjredfield** [comment]
Happy to submit a patch. Whether we should use `None` or `filters.EMPTY_VALUES` depends on the desired behaviour. For example, for a field which may be blank, is setting the filter value to '' sufficient for a togetherness check? In my opinion, a check against None is more appropriate, because it maps directly to the case where the filter is not specified at all.

**Comment by carltongibson** [comment]
> ...depends on the desired behaviour.

What happens if we combine `FieldX` with `FieldY`? What happens if we want to allow the `blank` value? Etc. 

First thing is to think through the obvious combinations and set up simple test cases for those. 

Then I suspect the fix will be easy enough. (Either that or impossible 😀)

**Comment by sanjredfield** [comment]
Thank you for the guidance, I will set up some test cases.

**Comment by carltongibson** [comment]
@sanjredfield Cool. Feel free to open a PR to solicit feedback
