### ISSUE TITLE
django_filter v1.0.0 incompatibility with models.ImageField

### ISSUE THREAD

**Issue by Sahloul** [carltongibson/django-filter#564]
To to django_filter v0.15.3 everything was fine, but once upgraded to django_filter v1.0.0, filtering models.ImageField started failing with error:

> AssertionError: AutoFilterSet resolved field 'field_name' with 'exact' lookup to an unrecognized field type ImageField. Try adding an override to 'filter_overrides'. See: https://django-filter.readthedocs.io/en/latest/usage.html#overriding-default-filters

Although I already have:
```
filter_overrides = {
	models.ImageField: {
		'filter_class': django_filters.CharFilter,
		'extra': lambda f: {
			'lookup_expr': 'exact',
		},
	},
}
```

**Comment by kevin-brown** [comment]
What is your expected behaviour for filtering on an `ImageField`?

**Comment by rpkilby** [comment]
Hi @Sahloul - where are your `filter_overrides` defined? The option has been moved from the `FilterSet` class to `FilterSet.Meta` (migrations [docs](https://django-filter.readthedocs.io/en/latest/migration.html#move-filterset-options-to-meta-class)).
