### ISSUE TITLE
Import of rest_framework backend can fail

### ISSUE THREAD

**Issue by tarkatronic** [carltongibson/django-filter#567]
In the DRF docs, they give an example which looks like:

```
import django_filters
# ...

class ProductFilter(django_filters.rest_framework.FilterSet):
    # ...
```

This does not work, however, with the way the `django_filters/__init__.py` is set up. Using this example, I get:

`AttributeError: 'module' object has no attribute 'rest_framework'`

I have found a fix for it, by adding the following to `django_filters/__init__.py`:

`from . import rest_framework`

**Comment by carltongibson** [comment]
Yeah. That's probably right. Fancy doing a PR?

**Comment by tarkatronic** [comment]
Sure thing, I'll have it to you shortly.

**Comment by rpkilby** [comment]
There is a problem in that the `rest_framework` sub-package has a dependency on DRF. If DRF isn't installed, then `django_filters` will not be importable. 

One possible way to get around this is to add a `compat.rest_framework` check, and then only import the `rest_framework` sub-package if it passes.

**Comment by rpkilby** [comment]
Alternatively, the docs could be updated to include the correct import

```py
import django_filters.rest_framework

class ProductFilter(django_filters.rest_framework.FilterSet):
    # ...
```

**Comment by carltongibson** [comment]
I think `import django_filters` is my preferred API. 

> One possible way to get around this is to add a compat.rest_framework check, and then only import the rest_framework sub-package if it passes.

Yes. This.

**Comment by marcinn** [comment]
Why django_filters have references to DRF and Crispy? Both aren't a dependecies. Adapter for DRF should be provided inside DRF or some DRF' plugin/extension. 

Why? AFAIK django_filter is not an DRF's extension and there are other REST frameworks/libraries.It is not reasonable to include their adapters here. Why DRF is an exception? Same notes for Crispy.

**Comment by carltongibson** [comment]
@marcinn Neither DRF nor Django-Filters **depend** on each other. There is an **optional** combined usage. 

That code used to live in DRF. It now lives in Django-Filters. That's all. 

Why move? Less surface-area for DRF and easier integration for Django-Filter related fixes. e.g. [`django_filters.rest_framework.filters.BooleanFilter`](https://github.com/carltongibson/django-filter/blob/develop/django_filters/rest_framework/filters.py#L6-L10) — this is code that has no place in DRF.

**Comment by decibyte** [comment]
I'm getting some unexpected behavior around this. I _do_ have DRF installed. But `rest_framework` gets set to `None` anyway. If I remove the `try...except`, things work as expected, without any `ImportError`s.

Anyone have an idea what is going on?

**Comment by carltongibson** [comment]
Hmm. No idea at all at first glance. 😐

Can you put a breakpoint in and examine the environment where the import is failing? (Hopefully that reveals more)

**Comment by decibyte** [comment]
Thanks for a quick response. I'm having a tight deadline right now, but I'll return to the issue when I find some time for this.

**Comment by oliver-zhou** [comment]
When trying to add django_filters to INSTALLED_APPS in a DRF based project, I get an import issue that doesn't exhibit itself when imported normally.  django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by carltongibson** [comment]
@oliver-zhou I guess that it's unlikely to be related to this issue. Most likely you're accessing some model attribute in your FilterSet definition — which is processed at import time **before** the AppRegistry is initialised. 

You'll get a traceback. Look through it. That will point to the exact place you're getting the error. Either move the offending line so that it's called at runtime or else (if that's really unavoidable) move the offending definition into your app's [`ready`](https://docs.djangoproject.com/en/1.10/ref/applications/#django.apps.AppConfig.ready) handler.

I hope that helps. If you're still stuck I suggest posting a question (with the traceback and offending definitions) on StackOverflow.

**Comment by osonwanne** [comment]
@tarkatronic That didn't work for me, still getting error:

`    DFBase = django_filters.rest_framework.DjangoFilterBackend
AttributeError: 'module' object has no attribute 'rest_framework'`

**Comment by osonwanne** [comment]
Changing django-filter in requirements.txt from 1.0.1 to 1.0.0 fixed it for me.

**Comment by rpkilby** [comment]
@osonwanne - That would make sense, since the import was added in the 1.0.1 release. Could you try installing the branch from #741? This shouldn't mask the import error and might give you a useful traceback.
