### ISSUE TITLE
Meta inheritance for FilterSet

### ISSUE THREAD

**Issue by seyhuns** [carltongibson/django-filter#571]
I wonder if it makes sense to be able to inherit from a base ```FilterSet``` because I want to be able to change the ```form``` that I'm using for validation.

Comparing to Django, it is something like this:
https://docs.djangoproject.com/en/1.10/topics/db/models/#meta-inheritance

**Comment by rpkilby** [comment]
Could you provide a usage example of what you're looking to do here? It's not entirely clear to me what is not currently possible w/ the `Meta` class. The following should work:

```py
class MyBaseFilterSet(django_filters.FilterSet):
    class Meta:
        form = ...

class MyFilter(MyBaseFilterSet):
    ...

# or

class MyFilter(MyBaseFilterSet):
    class Meta(MyBaseFilterSet.Meta):
        ...
```

**Comment by seyhuns** [comment]
Yes you example is working fine, sorry about it.
