### ISSUE TITLE
rest_framework.DjangoFilterBackend.to_html crashes with multiple DjangoTemplate backends

### ISSUE THREAD

**Issue by charettes** [carltongibson/django-filter#578]
When multiple `DjangoTemplate` backends are configured using the `TEMPLATES` setting Django isn't able to determine a default engine when [instantiating a `Template` engine without passing an `engine` kwarg](https://github.com/carltongibson/django-filter/blob/fb5f4d9e190eb46bc516a77b4961519eda8ee73c/django_filters/rest_framework/backends.py#L88).

I think this should be fixed by moving the content of `FILTER_TEMPLATE` and `CRISPY_TEMPLATE` to an existing file (`templates/django_filters/rest_framework/form.html`) to allow the apps discovery mechanism to find them like it use to be the case when this code was part of `django-rest-framework`.

**Comment by charettes** [comment]
I think this was overlooked when #500 was fixed.

**Comment by charettes** [comment]
Another alternative could be to define both the template files and keep the inlined versions around so the rare users with this issue could add `django_filter` to their `INSTALLED_APPS` and be done with it.

I'm not sure why you want to avoid having users put `'django_filter'` in their `INSTALLED_APPS` tho, it's a common requirement of third-party apps.

**Comment by carltongibson** [comment]
@charettes Any chance you could put together a failing test case for this? (It's not something we cover currently.)

**Comment by rpkilby** [comment]
> I'm not sure why you want to avoid having users put `'django_filter'` in their `INSTALLED_APPS` tho, it's a common requirement of third-party apps

Yeah, that was my doing :sweat:. It was in part trying to avoid what seemed like an unnecessary requirement (after all, it's just two small templates), but also to avoid packaging mishaps (the tests had previously passed, but the distributed package didn't include the template files). That said, I had completely forgotten that the package includes translations, which requires hooking into `INSTALLED_APPS` anyway. 

#580 should fix this by reverting back to template files. @charettes - If you have the time, could you install the branch and verify that it works?

**Comment by charettes** [comment]
@rpkilby thanks a lot for working on this. I was planning to come up with a test during the weekend but you beat me to it!

**Comment by carltongibson** [comment]
Closed by #580

**Comment by charettes** [comment]
Related [Django ticket](https://code.djangoproject.com/ticket/27359) that proposes to allow specifying a default DTL backend.
