### ISSUE TITLE
queryset.distinct() called before filtering.

### ISSUE THREAD

**Issue by Andrew-SK** [carltongibson/django-filter#579]
https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L173

It looks like `qs.distinct()` is called before the filter is applied. I've managed to get duplicate models in the returned queryset.  

I apologise if this is just me not understanding the code correctly. I will test properly once I get home from work.

**Comment by rpkilby** [comment]
Hi @Andrew-SK. The order of the `distinct()` and `filter()` calls should be irrelevant. Are you also ordering by a related field? See first note in thed [docs](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#distinct).

**Comment by Andrew-SK** [comment]
Hi @rpkilby. Thanks for the response. 

You are correct, I'm not ordering by a related field only filtering across a many to one relationship. Regardless I'll close this issue.
