### ISSUE TITLE
Using with JSONField

### ISSUE THREAD

**Issue by dezinfo** [carltongibson/django-filter#583]
How I can define fields that I can use as filter by  JSONField 

now I define in FilterSet
`MarkaMoto = django_filters.CharFilter(name='attributes__MarkaMoto__value',lookup_type='contains',distinct=True)`

but it doesn't work. Morethere if I use lookup_type='icontains' I get an error

```
operator does not exist: jsonb #> text
LINE 1: ...ansport' AND UPPER("callboard_goods"."attributes" #> ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
SQL

```
sql	
('SELECT COUNT(*) FROM (SELECT DISTINCT "callboard_goods"."id" AS Col1, '
 '"callboard_goods"."category_id" AS Col2, "callboard_goods"."subcategory_id" '
 'AS Col3, "callboard_goods"."name" AS Col4, "callboard_goods"."price" AS '
 'Col5, "callboard_goods"."description" AS Col6, '
 '"callboard_goods"."creation_date" AS Col7, "callboard_goods"."update_date" '
 'AS Col8, "callboard_goods"."user_id" AS Col9, "callboard_goods"."views" AS '
 'Col10, "callboard_goods"."is_salles" AS Col11, '
 '"callboard_goods"."salles_price" AS Col12, "callboard_goods"."is_active" AS '
 'Col13, "callboard_goods"."rate" AS Col14, "callboard_goods"."state_id" AS '
 'Col15, "callboard_goods"."city_id" AS Col16, "callboard_goods"."currency" AS '
 'Col17, "callboard_goods"."order_date" AS Col18, '
 '"callboard_goods"."attributes" AS Col19 FROM "callboard_goods" INNER JOIN '
 '"callboard_category" ON ("callboard_goods"."category_id" = '
 '"callboard_category"."id") INNER JOIN "callboard_subcategory" ON '
 '("callboard_goods"."subcategory_id" = "callboard_subcategory"."id") WHERE '
 '("callboard_goods"."is_active" = %s AND "callboard_category"."slug" = %s AND '
 '"callboard_subcategory"."slug" = %s AND UPPER("callboard_goods"."attributes" '
 '#> %s::text) LIKE UPPER(%s))) subquery')
```

In the same time if I try to get data from model directly there isn't any problem

`Goods.objects.filter(attributes__MarkaMoto__value = 4)`

return data

**Comment by rpkilby** [comment]
Hi @dezinfo - I'm not sure what's happening with your particular case, but here are a few pointers:
- `name` and `lookup_expr` are used to create the complete expression passed to `filter()`. The `name` should consist of field parts, while `lookup_expr` should contain transforms and a lookup (The first section in the [lookup API reference](https://docs.djangoproject.com/en/1.10/ref/models/lookups/#module-django.db.models.lookups) may help clarify).
- Given the above, your filter should probably look like the following (although it may not matter here):
  ```py
  MarkaMoto = django_filters.CharFilter(name='attributes', lookup_expr='MarkaMoto__value__contains')
  ```
- The equivalent `filter()` call is the following:
  ```py
  Goods.objects.filter(attributes__MarkaMoto__value__contains=4)
  ```
- I'm not incredibly familiar with the postgres `JSONField`, but it's possible that `icontains` may not be a valid lookup ([docs](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#containment-and-key-operations)).

**Comment by dezinfo** [comment]
Thanks. Your tips helped.
