### ISSUE TITLE
Impossible to overwrite filter attributes in child class

### ISSUE THREAD

**Issue by fkdeboer** [carltongibson/django-filter#590]
Maybe we are missing something, but why does this happen?

```
class FooBaseFilter(django_filters.FilterSet):
    key = django_filters.CharFilter(label='code')
    name = django_filters.CharFilter(label='name')

class FooFilter1(FooBaseFilter):
    pass

class FooFilter2(FooBaseFilter):
    key = None
```

Expected result:

* rendering a FooFilter1 does show a filter on key.
* rendering a FooFilter2 does not show a filter on key.

Result:

* both FooTable2 and FooTable2 show a filter key.

Are we doing something wrong? Is this a bug or just very unpythonic? Feedback welcome.

**Comment by rpkilby** [comment]
This doesn't seem unreasonable. A quick test shows that Django's forms support this behavior, although DRF's serializers do not.

**Comment by rpkilby** [comment]
btw, see #591.

**Comment by fkdeboer** [comment]
for the moment, this works for us as a temporal solution:

`
class FooFilter2(FooFilter):
    def __init__(self, *args, **kwargs):
        super(FooFilter2, self).__init__(*args, **kwargs)
        del self.filters['key']
    
`
