### ISSUE TITLE
How to do m2m AND filters?

### ISSUE THREAD

**Issue by mackeyja92** [carltongibson/django-filter#595]
I want to filter the `User` model by `groups`. Specifically, I want to find users that belong to multiple groups. I am using DRF and the default filter class there with the `groups` field as a filter field.  `?groups=3&groups=6` returns all the Users that are in group 3 OR group 6. How do I make it so I can do an AND there? I tried `?groups=3,6` and `?groups=[3,6]` but with no success.

**Comment by rpkilby** [comment]
`ModelMultipleChoiceFilter` have a `conjoined` property that enables AND filtering.

**Comment by mackeyja92** [comment]
Oh, I missed that in the docs! Thanks @rpkilby
