### ISSUE TITLE
Question about turn on warning during migration to 1.0

### ISSUE THREAD

**Issue by shapeng42** [carltongibson/django-filter#596]
Hi, there. I have this naive question but I'm new to Django, I cannot find the answer anywhere.

In the document, there is this statement: 

> A forwards-compatible 0.15 release has also been created to help with migration. It is compatible with both the existing and new APIs and will raise warnings for deprecated behavior.

My question is how can I turn on the warnings to see them on console?

Thanks
Shawn

**Comment by rpkilby** [comment]
You need to enable warnings. You can either do this with the `-W` flag ([docs](https://docs.python.org/3.6/using/cmdline.html#cmdoption-W)) or by setting the `PYTHONWARNINGS` environment variable. If you're trying to check for deprecation when running your test suite, you could do the following:

```sh
$ python -W once manage.py test
```

The above would print all warnings once when they first occur. This is useful to know what violations exist in your code (or occasionally in third party code). However, it only prints the last line of the stack trace. You can use the following to raise the full exception instead:

```sh
$ python -W error manage.py test
```

**Comment by shapeng42** [comment]
Thanks!

**Comment by lingxiaoyang** [comment]
Hello there,

I was having the same problem during an update of dependencies. It is not mentioned in the migration instructions, and I had to look into the code of v0.15 to infer the reason that `warnings.warn(msg)` showed a message while `warnings.warn(msg, DeprecatedWarning)` didn't.

Could you please add a note for this in the docs?
