### ISSUE TITLE
Ordering by non-model fields

### ISSUE THREAD

**Issue by RadoRado** [carltongibson/django-filter#599]
I was following the docs here - https://django-filter.readthedocs.io/en/latest/ref/filters.html#adding-custom-filter-choices trying to make some custom ordering by non-model field.

Sadly, got the following error: `AttributeError: 'SomeCustomOrdering object has no attribute 'choices'`

Am I missing something? Copy-pasted the example code.

**Comment by rpkilby** [comment]
Hi @RadoRado - could you post the complete stack trace? Also, I think this is a type in the docs. Try:

```py

    def __init__(self, *args, **kwargs):
        super(CustomOrderingFilter, self).__init__(*args, **kwargs)
        self.extra['choices'] += [
            ('relevance', 'Relevance'),
            ('-relevance', 'Relevance (descending)'),
        ]
```

**Comment by RadoRado** [comment]
@rpkilby `self.extra['choices']` did the trick.

Now, I have to resolve the `"Cannot resolve keyword 'relevance' into field"`

It would be great if there's a full example of this working :panda_face:

**Comment by RadoRado** [comment]
@rpkilby Actually my bad - had a property called `relevance` and custom queryset defining a column called `relevance`. Renamed it to `relevance_column`, and it started working. Thanks for the quick input! :+1:

**Comment by rpkilby** [comment]
@RadoRado - no problem. Just to recap, the only issue is `self.choices` => `self.extra['choices']`, right?

**Comment by RadoRado** [comment]
@rpkilby On `django-filter` side of things - yes!

Should I try to PR the docs with a complete example?

**Comment by rpkilby** [comment]
Don't worry about it - already submitted a patch.

**Comment by rpkilby** [comment]
Thanks for pointing out the docs issue!

**Comment by RadoRado** [comment]
@rpkilby Thanks for being maintainer of this awesome library! :beers:

**Comment by RadoRado** [comment]
@rpkilby Actually, one more thing:

```python
class SomeOrdering(django_filters.OrderingFilter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.extra['choices'] += [
            ('relevance', 'Relevance'),
            ('-relevance', 'Relevance (descending')
        ]

    def filter(self, qs, value):
        # value is ['relevance'] not 'relevance'
        if value in ['relevance', '-relevance']:
            return qs.order_by_relevance()

        return super().filter(qs, value)

```

In the code above, `value` is a list of one element, not a string. Again, I can be doing something wrong here.

**Comment by RadoRado** [comment]
@rpkilby @carltongibson Can you take a look at the example above? Is this the desired behaviour?

**Comment by RadoRado** [comment]
Here's the working example:

```python
class SomeOrdering(django_filters.OrderingFilter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.extra['choices'] += [
            ('relevance', 'Relevance'),
            ('-relevance', 'Relevance (descending')
        ]

    def filter(self, qs, values):
        # values is ['relevance'] not 'relevance'
        for value in values:
            if value in ['relevance', '-relevance']:
                return qs.order_by_relevance()

        return super().filter(qs, values)
```

**Comment by carltongibson** [comment]
@RadoRado [From the docs](https://django-filter.readthedocs.io/en/develop/ref/filters.html#orderingfilter):

> [OrderingFilter] filter is also CSV-based, and accepts multiple ordering params.

i.e. Yes, it's the desired behaviour. `value` is a list. In your case it just has the single element.

**Comment by RadoRado** [comment]
@carltongibson Maybe we should change the example from here then - https://django-filter.readthedocs.io/en/latest/ref/filters.html#adding-custom-filter-choices - since it relies on the fact that `value` is a single element.

**Comment by carltongibson** [comment]
Yep. Sounds right.
