### ISSUE TITLE
Tests are failing under Django 1.11

### ISSUE THREAD

**Issue by edmorley** [carltongibson/django-filter#607]
#606 is adding Django 1.11 to the testing matrix, but with the result ignored since the tests are currently failing:
https://travis-ci.org/carltongibson/django-filter/builds/193589440#L294

eg
```
FAIL: test_get_filtered_detail_view (tests.rest_framework.test_backends.IntegrationTestDetailFiltering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/carltongibson/django-filter/tests/rest_framework/test_backends.py", line 399, in test_get_filtered_detail_view
    self.assertEqual(response.data, data)
AssertionError: {u'id': 1, 'text': u'aaa', 'decimal': u'0.25', u'basefilterableitem_ptr': 1, 'date': '2012-10-08'} != {u'id': 1, u'text': u'aaa', u'decimal': '0.25', u'date': '2012-10-08'}
```

**Comment by edmorley** [comment]
Though it's worth noting that d-r-f master has Django 1.11 marked as "failures allowed" too, so this likely will need to wait until after they have added support.

**Comment by carltongibson** [comment]
Hey @edmorley. 

> ...  d-r-f master has Django 1.11 marked as "failures allowed" too...

Yep. The `..._ptr...` failures are a DRF issue. https://github.com/tomchristie/django-rest-framework/issues/4574

https://github.com/carltongibson/django-filter/pull/604 takes on the widget failures. 

Everything else has already been dealt with. 🤞🏽we shall be good to go shortly

**Comment by carltongibson** [comment]
Looks like [the test matrix will need updating](https://github.com/carltongibson/django-filter/blob/develop/tox.ini#L4):

Fix for https://github.com/tomchristie/django-rest-framework/issues/4574 is due for 3.5.4 and [Django 1.11 + DRF 3.4 & 3.5 are still failing](https://travis-ci.org/carltongibson/django-filter/builds/200094722#L624).
