### ISSUE TITLE
`filter_class` and `filter_fields` in rest framework backend

### ISSUE THREAD

**Issue by joetsoi** [carltongibson/django-filter#610]
Is there a use case for using both `filter_class` _and_ `filter_fields` when using the rest framework integration?

    class ProductList(generics.ListAPIView):
        queryset = Product.objects.all()
        filter_backends = (filters.DjangoFilterBackend,)
        filter_fields = ('category', 'in_stock')
        filter_class = ProductFilter

Someone might define both and I think in all cases, the programmer _really_ didn't mean that. I was thinking of adding a warning if both are defined in [`get_filter_class`](https://github.com/carltongibson/django-filter/blob/b714fd135d76ec5671442e0fb934deb6b94471ca/django_filters/rest_framework/backends.py#L24)

**Comment by orf** [comment]
I think this should throw an error, clearly both are not supported and the precedence is seemingly arbitrary.

**Comment by joetsoi** [comment]
I agree on error, but I worry about breaking everyone's code suddenly which is why I suggested warning.

**Comment by carltongibson** [comment]
`filter_class` trumps `filter_fields`. I'm happy with that. I'd take a warning on `filter_fields` if both were defined. (But I'm a bit _Meh_ TBH)

**Comment by rpkilby** [comment]
I'm kind of ambivalent about this. The [doc section](https://django-filter.readthedocs.io/en/develop/guide/rest_framework.html#using-the-filter-fields-shortcut) is terse, and I think it's pretty clear that `filter_fields` is a shortcut/alternative to `filter_class`.

> ### Using the `filter_fields` shortcut
> You may bypass creating a`FilterSet` by instead adding `filter_fields` to your view class. This is equivalent to creating a FilterSet with just [Meta.fields](https://django-filter.readthedocs.io/en/develop/ref/filterset.html#fields).
> ```
> from rest_framework import generics
> ...
> ```

**Comment by carltongibson** [comment]
This isn't something I'm going to allocate bandwidth to. As I said, I'd take a PR adding a warning but it's **marginal** and I don't consider it an active issue. 

In general I'd be happy to see some of these shortcuts pulled out into factory functions, so in this case you'd do something like: 

    filter_class = filter_factory(fields=[...])

... but that's not a request, just, rather, giving you the train of thought. (I'd happily see the fields dict syntax go the same way; again not a request)

**Comment by joetsoi** [comment]
no problem, I wasn't requesting you to make the change either, if I find the time i'll consider making a pr
