### ISSUE TITLE
BooleanFilter with LinkWidget

### ISSUE THREAD

**Issue by ygwain** [carltongibson/django-filter#611]
BooleanFilter with LinkWidget renders nothing:
```python
class ProjectFilter(django_filters.FilterSet):
    is_archived = django_filters.BooleanFilter(django_filters.widgets.LinkWidget())

    class Meta:
        model = Project
        fields = ['is_archived']
```

```html
<p><label for="id_is_archived">Is archived:</label> </p>
<ul id="id_is_archived">
</ul>
```

I use Django 1.10, DjangoFilter 1.0.1

**Comment by carltongibson** [comment]
`LinkWidget` needs some `choices`. Here it's not getting any. 

Possibly: 

* Improve usage docs
* Provide some way of automatically generating `choices` here
* ...

**Comment by ygwain** [comment]
Thanks for your input. IMO second option would be most intuitive.

**Comment by carltongibson** [comment]
@ygwain Cool. I'm always happy to review a Pull Request 👍

**Comment by rpkilby** [comment]
I don't think the automatic generation of choices is really possible here. The widget would need to generate different sets of choices for different fields (eg, `BooleanField` and `NullBooleanField`), however the widget is unaware of the model field so it has nothing to generate the choices from. 

Improving the docs is probably the way to go.

**Comment by carltongibson** [comment]
I was thinking a subclass for the specific case in userland code, but beyond that I agree there's not much to be done.
