### ISSUE TITLE
Rest Framework filterset & django.forms.ValidationError

### ISSUE THREAD

**Issue by egnartsms** [carltongibson/django-filter#613]
When using Django Rest Framework filterset (*django_filters.rest_framework.FilterSet*) with "strict = 'RAISE'" meta option, *django-filter* raises usual ValidationError from Django instead of DRF ValidationError. This has the effect that default DRF exception handler does not catch this exception, and it results in a 500 response.

```python
class KittenFilter(filters.FilterSet):
    class Meta:
        fields = ('color', 'name', 'weight')
        model = Kitten
        strict = 'RAISE'
```

**Comment by carltongibson** [comment]
Yeah it does. (That's because the exception is raised during the FilterSet's form validation.)

If you set `strict='RAISE'`you need to be prepared to handle the exception. [See here in the DRF docs for guidance](http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling).

**Comment by egnartsms** [comment]
Thanks for quick response!  Once there's a Rest Framework-specific filterset class, isn't that intuitive to expect it to conform to Rest Framework conventions? In principle, it is possible to do smth like that:
```python
class BaseFilterSet(object):
   ...
   validation_error_cls = django.exc.ValidationError
   ...
   @property
   def qs(self):
      ...
      raise self.validation_error_cls(self.form.errors)
      ...

# In a rest_framework.filterset
class FilterSet(filterset.FilterSet):
    validation_error_cls = rest_framework.exc.ValidationError
```

What do you think about such a change?

**Comment by carltongibson** [comment]
I'm happy for users to define such a class in their own projects. 

I'm not sure it should be the default. 

This kind of thing always comes up on DRF. "Handle all exceptions automatically". It's always rejected there. "We handle the common cases, it's up to the user to deal with the project specific edge cases". I tend to agree. 

I'd certainly take an example with discussion added to the Tips and Tricks section of the docs.

**Comment by egnartsms** [comment]
OK, thanks for your comments!

**Comment by carltongibson** [comment]
Right. I'm going to re-open this. 

I'll take a PR with change notes on `django_filters.rest_framework.filterset.FilterSet` overriding `qs` to convert the error. 

Something like: 

```python
    @property
    def qs(self):
        try:
            qs = super().qs
        except forms.ValidationError as e:
            raise DRFValidationError(e.error_dict)
        else:
            return qs
```

**Comment by rpkilby** [comment]
#677 ?

**Comment by carltongibson** [comment]
Yep. That looks about right! 👍
