### ISSUE TITLE
HiddenWidget for OrderingField result in empty result with bizarre default value

### ISSUE THREAD

**Issue by SebCorbin** [carltongibson/django-filter#615]
I defined an OrderingFilter with HiddenInput and when displaying this field once the form has been submitted, the field render as `<input id="id_o" name="o" type="hidden" value="[]">`

Which is problematic because when submitted once again, there won't be any result due to this default value of `[]`.

I believe this is due to the `BaseCSVWidget.value_from_datadict` method that does a little too much on the value:
```
class BaseCSVWidget(forms.Widget):
    def value_from_datadict(self, data, files, name):
        value = super(BaseCSVWidget, self).value_from_datadict(data, files, name)

        if value is not None:
            if value == '':  # empty value should parse as an empty list
                return []
            return value.split(',')
        return None
```

And here is my filterset for reference:
```
class DocumentListFilter(django_filters.FilterSet):
    text = django_filters.CharFilter(method='filter_text')

    # Ordering
    o = OrderingFilter(
        widget=forms.HiddenInput,
        fields=(
            ('indice', 'indice'),
            ('weight', 'weight'),
        ),
    )
```

**Comment by carltongibson** [comment]
`value_from_datadict` is not involved in rendering the widget. (It comes in when handing the GET parameter pulled from the query string.)

If you could produce a failing case for [`CSVWidgetTests`](https://github.com/carltongibson/django-filter/blob/develop/tests/test_widgets.py#L177-L197) that would help. 

I'm wondering if you don't need to create a `HiddenCSVWiget` subclass, in parallel to `CSVWidget`

**Comment by SebCorbin** [comment]
Added a pull request with the test. When debugging, I found out that `value_from_datadict` is called twice, once for retrieving the value for the _clean\_*_ process and a second time for the default value when rendering the field.

**Comment by dwasyl** [comment]
Just to note, I'm experiencing this same problem with 1.0.4. When I render the `OrderingFilter` as hidden it has a value of  `[]` which on re-submitting breaks things. Interestingly, it doesn't do this on initial load of a form, but only after being submitted (which is the same as above).

However, I am rendering the `OrderingFilter` with the standard widget and displaying it in the form with `.as_hidden`. 

As a side note, this happens whens there is no ordering value set at all which, at least for me, is rarely the case. It would be useful to be able to set a default value for `OrderingFilter` and/or remove the empty choice.

**Comment by rpkilby** [comment]
I don't think #620 actually fixed the original issue - it fixed a similar issue in `BaseCSVWidget`. That said, not sure if this needs to be reopened. What's the use case for hidden inputs? If you're trying to provide a default ordering, I think this can be covered via below.

> It would be useful to be able to set a default value for OrderingFilter and/or remove the empty choice.

You can remove the empty choice by passing `None` to the `empty_label` argument. This will force users to always select an order with the form input. Note that API usage could still just omit the parameter.

If you want to enforce a default ordering, I would apply a default ordering to the provided queryset. eg, 

```python
MyFilterSet(queryset=MyModel.objects.order_by('-my_field'), data=...)
```

**Comment by dwasyl** [comment]
In this case, I've built a filter form that uses a number of `LinkWidget` displays of `AllValuesFilter`, well slightly changed to have choices filtered based on the current `QuerySet`. In addition to the `LinkWidget` choices there are forms with a submit button for selecting the sort order and one free text filter. When you submit the form with sort order it erases any current url parameters, to work with this I include all of the current filters as hidden form fields in the forms.

Interestingly (kind of), when you submit a GET form with a value of `[]` the resulting value of `order` is `[[]]`, etc.

Thanks for the tip re empty choice, I had been enforcing ordering before (but wanted that choice selected). I'll just make sure that the default ordering is the first choice on the list and with no empty label that'll work.
