### ISSUE TITLE
Can't use mixin pattern

### ISSUE THREAD

**Issue by stephenfin** [carltongibson/django-filter#618]
This is probably something that needs a simple note in the doc, but I'll post it here before submitting a PR.

I wrote a number of `FilterSet`s that all defined a `before` and `since` parameters. To minimize duplication, I put these in a mixin.

```python
class TimestampMixin(object):

    before = IsoDateTimeFilter(name='date', lookup_expr='lt')
    since = IsoDateTimeFilter(name='date', lookup_expr='gte')


class SeriesFilter(TimestampMixin, FilterSet):

    class Meta:
        model = Series
        fields = ('submitter', 'project')


class CoverLetterFilter(TimestampMixin, FilterSet):

    class Meta:
        model = CoverLetter
        fields = ('project', 'series', 'submitter')

# ...
```

# Expected Result

I expected to be able to filter series using the `since` and `before` filters.

# Actual Result

To my surprise, these weren't detected and it was necessary to defined them on each `FilterSet` instead.

```python
class SeriesFilter(FilterSet):

    before = IsoDateTimeFilter(name='date', lookup_expr='lt')
    since = IsoDateTimeFilter(name='date', lookup_expr='gte')

    class Meta:
        model = Series
        fields = ('submitter', 'project')


class CoverLetterFilter(FilterSet):

    before = IsoDateTimeFilter(name='date', lookup_expr='lt')
    since = IsoDateTimeFilter(name='date', lookup_expr='gte')

    class Meta:
        model = CoverLetter
        fields = ('project', 'series', 'submitter')

# ...
```

I haven't looked into the reason this doesn't work so I can't say if there's been a conscious decision not to support this pattern. It does seem like something that *should* work, however. Perhaps we could fix this oversight, else provide some information on the pattern one should use to escape such duplication.

**Comment by rpkilby** [comment]
Hi @stephenfin - have you tried inheriting from `FilterSet` in your mixin instead of from `object`? This [test](https://github.com/carltongibson/django-filter/blob/1.0.1/tests/test_filterset.py#L487-L506) indicates that this should work, although maybe the test is broken? Either way, the expected behavior seems reasonable.

**Comment by stephenfin** [comment]
Thanks for the tip, @rpkilby - that works correctly when I subclass from `FilterSet` instead. I'm surprised this is necessary though. Is that a bug or a feature? :smile:

**Comment by rpkilby** [comment]
`FilterSet`s have comparable behavior to DRF's serializers and Django's models. I'm not sure if allow this kind of mixin behavior.

**Comment by rpkilby** [comment]
So, the current behavior is expected. The relevant code in django-filter is [here](https://github.com/carltongibson/django-filter/blob/b094c3f5a871f6635cfa81dbc30834bed14be1c6/django_filters/filterset.py#L105-L111), which is based on the same code from [DRF](https://github.com/tomchristie/django-rest-framework/blob/773b68e188bd83f5f005b47eacb83b3d6b22e77b/rest_framework/serializers.py#L306-L312), which is in turn similar to Django's [Form metaclass](https://github.com/django/django/blob/c651331/django/forms/forms.py#L41-L51).

**Comment by carltongibson** [comment]
> I'm surprised this is necessary though.

It's because you need the metaclass behaviour. It affects all these _declarative syntax framework_ types. 

Another example, similar to yours, [_Model Utils_' `TimeStampedModel`](https://github.com/carljm/django-model-utils/blob/master/model_utils/models.py#L18-L29). It's intended to be used as a mixin but must inherit from `models.Model` in order for the fields to be registered. 

(@rpkilby: Good links! I think the Django Filter code pre-dates DRF, but they definitely both rip-off Django Form.)

**Comment by rpkilby** [comment]
@carltongibson - yep. My understanding is that django-filter's metaclass was based on Django Forms, but some of this was changed in #550, which draws from DRF's serializers.

**Comment by carltongibson** [comment]
@rpkilby Sure. The `get_declared_filters` logic is unchanged. (It just moved.) They key point is that _that_ is how filters get passed to subclasses...

**Comment by mahruskh** [comment]
> Hi @stephenfin - have you tried inheriting from `FilterSet` in your mixin instead of from `object`? This [test](https://github.com/carltongibson/django-filter/blob/1.0.1/tests/test_filterset.py#L487-L506) indicates that this should work, although maybe the test is broken? Either way, the expected behavior seems reasonable.

This worked for me. Thanks.
