### ISSUE TITLE
When does django filter execute in relation to the get_queryset?

### ISSUE THREAD

**Issue by jmgamboa** [carltongibson/django-filter#619]
Hi team. Currently using django-filter on several of my apps. I've come to the point where I need to optimize but am having trouble determining whether my filter or the get_queryset is the issue.

Can anyone inform me of the pipeline in regards to django custom filter lookups? I suspect a django filter occurs after a get_queryset as it returns a queryset. Can someone confirm this?

**Comment by rpkilby** [comment]
> I suspect a django filter occurs after a get_queryset as it returns a queryset. Can someone confirm this?

Yes, the queryset returned from `get_queryset()` is generally passed to the filterset. When this happens will depend on the view code in question. 

> Can anyone inform me of the pipeline in regards to django custom filter lookups?

Can you provide more detail as to what you mean? If you're referring to custom lookup expressions, those are processed at the same time as the builtin lookup expressions.

**Comment by jmgamboa** [comment]
@rpkilby ok thanks. That is what i tested in my code and it seems to agree. In terms of the pipeline, I meant that I imagined the output of the get_queryset would be passed into the filterset, then that queryset would essentially be passed onto the next function or another operation would occur. Thanks for the quick response!

**Comment by rpkilby** [comment]
> then that queryset would essentially be passed onto the next function or another operation would occur.

This will depend on the view code. If you're using the builtin [`FilterView`](https://github.com/carltongibson/django-filter/blob/70e15487befbfe3adc051e7ccb8dc662c20a0231/django_filters/views.py#L61-L67), then this is immediately rendered as part of the template's context. If you're using DRF, then the resulting queryset may be processed by other filter backends.
