### ISSUE TITLE
Release work on Django 1.11 support

### ISSUE THREAD

**Issue by adamcharnock** [carltongibson/django-filter#636]
It would be great to see a release of the work on Django 1.11 support given that the first beta has just come out ( #606 / #607 / #624 ).

Apologies if this is considered a duplicate.

**Comment by carltongibson** [comment]
Hey @adamcharnock — Yes it's a duplicate 🙂

v1.0.2 is ready to go. It'll be released soon™.

Anyone testing on 1.11bX can install DF from the `develop` branch. (The ability to do one implies the ability to do the other I'd say) [Pip's VCS Support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)

**Comment by adamcharnock** [comment]
Amazing, thanks @carltongibson.

I did indeed proceed against the ``develop`` branch.
