### ISSUE TITLE
Reset filters

### ISSUE THREAD

**Issue by gthieleb** [carltongibson/django-filter#637]
I want to add a button with a GET action `reset-filter` that resets all filter values. I am using a generic view.

Currently I try this within the dispatch method but this does not work:

	def dispatch(self, request, *args, **kwargs):
		from django.http import QueryDict

		action = request.GET.get('action', [])
		if action == 'reset-filter':
		    request.GET = QueryDict()
		    request.META['QUERY_STRING'] = {}
		    self.request = request

		return super(DefaultFormView, self).dispatch(request, *args, **kwargs)

**Comment by carltongibson** [comment]
If that button was just a link to the current page without any filter params set you'd already have what you need.

**Comment by gthieleb** [comment]
Thanks, I was overlooking the obvious!
