### ISSUE TITLE
ListView -> get_context overrides filters

### ISSUE THREAD

**Issue by jhotujec** [carltongibson/django-filter#641]
I'm trying to implement `django-filters` in my project but I've hit a roadblock :/ Somehow `filter` instance is getting removed from context..

```
class ListReservations(LoginRequiredMixin, FilterView):
    template_name = 'reservations/homepage.html'
    paginate_by = 25
    model = Reservation
    filterset_class = ReservationFilter

    def get_context_data(self, **kwargs):
        ctx = super(ListReservations, self).get_context_data()
        ctx['today'] = datetime.datetime.now().strftime('%d/%m')
        return ctx

```

Results are still getting filtered, but don't have access to `{{filter.form}}`

Any ideas what's going on? :) thanks

**Comment by carltongibson** [comment]
Well, one thing is you're not passing kwargs to the super get_context_data call. Likely that.
