### ISSUE TITLE
Improve UX of global FILTERS_STRICTNESS setting

### ISSUE THREAD

**Issue by edmorley** [carltongibson/django-filter#646]
The `FILTERS_STRICTNESS` global setting docs ([here](https://django-filter.readthedocs.io/en/latest/ref/settings.html#filters-strictness)), say:
```
Default: `STRICTNESS.RETURN_NO_RESULTS`

Set the global default for FilterSet strictness.
```

This was confusing at first glance, since:
1) Initially I read the default value as a string, not an actual class, since Django settings convention is to use strings to refer to classes/constants.
2) I had to rummage in the source to find out where to import the class from, since an example isn't shown.
3) After reading the source, it turned out there was a string version that could be used instead (`"RAISE"`), though the dict containing it is named `_LEGACY`, so it's not clear if it will remain supported.

Please can "`FILTERS_STRICTNESS` as a string" support be made official, and added to the docs, to avoid the above? :-)

Many thanks!

**Comment by carltongibson** [comment]
Hey @edmorley, 

I'm moving towards having an `Enum` here, rather than back to (just) strings.

The docs aren't great. We can certainly elaborate there.

**Comment by rpkilby** [comment]
Per #650, just adding a note to document that `RAISE_VALIDATION_ERROR` is a more appropriate default.
