### ISSUE TITLE
Change strictness default to RAISE_VALIDATION_ERROR for DRF?

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#650]
Thoughts on doing this for a future major version?

**Comment by carltongibson** [comment]
I suspect this _shouldn't_ be the default. I suspect most new users would prefer an empty result set than an uncaught `ValidationError`. 

I could be wrong on that.

**Comment by ticosax** [comment]
Empty results always tricked me. I'd prefer to have RAISE_VALIDATION_ERROR as default. Easier for client applications, assuming django-filter is used to serve a Rest API.

**Comment by carltongibson** [comment]
> ...assuming django-filter is used to serve a Rest API.

Exactly. Graceful handling requires DRF's view level handing of `ValidationError`. Everywhere else you're going to get a `500` — normally from accessing `filterset.qs` in the template. That seems like a pretty user-hostile default to me.

**Comment by ticosax** [comment]
Can we reconcile those 2 kinds of usage ? and having a sensible default for each of them ?

**Comment by carltongibson** [comment]
Yes, surely. But is the code that tries to guess any better than just having the user toggle a switch?

**Comment by ticosax** [comment]
You have a point, then, a documentation effort would be beneficial. Explaining that behind DRF's views, `RAISE_VALIDATION_ERROR` is a better choice.

**Comment by carltongibson** [comment]
Yep. +1. See also #646 (which is "docs" IMO)

**Comment by rpkilby** [comment]
This all makes sense - added a note in #646, so closing in favor of that.
