### ISSUE TITLE
NumericRangeFilter uses startswith and endswith

### ISSUE THREAD

**Issue by lucas03** [carltongibson/django-filter#652]
Hi,
I have a question about NumerRangeFilter. I do not think it does what one would expect.  
It uses `startswith` and `endswith`, as can be found [here](https://github.com/carltongibson/django-filter/blob/4dd64e5783b0f0ae32d9a187defc85d91164235b/django_filters/filters.py#L401) and documented [here](http://django-filter.readthedocs.io/en/develop/ref/filters.html#numericrangefilter).  

My question is, why `startswith` and `endswith`. I would expect `gte` and `lte`.  

Lets say we have model with 100 objects with ids = [1..100].  
If I set 5 as `value.start`, I expect to get `[5..100]`. `startwith` returns ids [5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
What am I missing?

**Comment by rpkilby** [comment]
Not sure if this helps (Django [docs](https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#querying-using-the-bounds))

**Comment by lucas03** [comment]
It does, thanks! So NumericRangeField is for RangeFields and should not be used on IntergerField.
