### ISSUE TITLE
filter_overrides in the Meta are lost

### ISSUE THREAD

**Issue by bastamper** [carltongibson/django-filter#663]
python 3.4
django 1.10.5
django-filters 0.15.3 or 0.15.4

If you move filter_overrides into the Meta it doesn't get pulled into the AutoFilterSet.

We have a setup like this:

```
class MyFilterSet(FilterSet):
    filter_overrides = {
        ...
    }


class MyDjangoFilterBackend(DjangoFilterBackend):
    default_filter_set = MyFilterSet
```

It works. But when adjusting when upgrading (due to deprecation warning) to this:

```
class MyFilterSet(FilterSet):
    class Meta:
        filter_overrides = {
            ...
        }


class MyDjangoFilterBackend(DjangoFilterBackend):
    default_filter_set = MyFilterSet
```

Our filter_overrides are not applied. Debugging it, it's because the filter_overrides are lost when AutoFilterSet is used in DjangoFilterBackend.get_filter_class(). We've worked around it with the following, but obviously this should not be necessary:

```
class MyDjangoFilterBackend(DjangoFilterBackend):
    default_filter_set = MyFilterSet

    def get_filter_class(self, view, queryset=None):
        filterset = super().get_filter_class(view, queryset)
        if filterset and issubclass(filterset, self.default_filter_set):
            filterset.Meta.filter_overrides = (
                self.default_filter_set.Meta.filter_overrides)

        return filterset
```

**Comment by carltongibson** [comment]
> ...obviously this should not be necessary

Reminds me of the joke about the math professor: 

> — Obvious it follows...
> — Er..., sir..., is it obvious?
>
> Professor disappears into office, emerges 30 minutes later.
> — Yes, it's obvious.

Meta class inheritance is a tricky topic. In general I'm happy that users are involved in configuring their custom DRF filter backends. But yes, I can see how you might want `get_filter_class` to handle this automatically. 

First step is to narrow this down to a minimal test case. We can think about an adjustment from there.

**Comment by carltongibson** [comment]
c.f. https://github.com/djangonauts/django-rest-framework-gis/pull/117/files#diff-745c1a45c45145b58594c9c47bee0057L86

**Comment by rpkilby** [comment]
Something like the following should be sufficient to support Meta class inheritance. Seems reasonable to me. 

```python
    def get_filter_class(self, view, queryset=None):
        ...
        if filter_fields:
            MetaBase = getattr(self.default_filter_set, 'Meta', object)

            class AutoFilterSet(self.default_filter_set):
                class Meta(MetaBase):
                    model = queryset.model
                    fields = filter_fields

            return AutoFilterSet
```
