### ISSUE TITLE
Django filter 1.0.2 regressions (git merge error?) 

### ISSUE THREAD

**Issue by frankh** [carltongibson/django-filter#666]
It looks like the 1.0.2 merge came off an out of date branch, as it had over 100 commits in it.

In particular, it seems to have reverted https://github.com/philipn/django-rest-framework-filters/pull/129 - which is causing this issue for me: https://github.com/carltongibson/django-filter/issues/562

**Comment by carltongibson** [comment]
This looks fine as far as I can see: https://github.com/carltongibson/django-filter/compare/1.0.1...1.0.2

Check the Milestone: https://github.com/carltongibson/django-filter/milestone/12?closed=1 There's a lot of tickets, so a lot of commits. 

I don't know about other repos but I guess https://github.com/carltongibson/django-filter/pull/580 is what you're looking for.

**Comment by rpkilby** [comment]
You may not have added `'django_filters'` to `INSTALLED_APPS`, which would be required to find the template files. Relevant changes in #580.
