### ISSUE TITLE
datetime filter don't support datetime input formats from project settings file

### ISSUE THREAD

**Issue by KushGoyal** [carltongibson/django-filter#668]
I am facing 2 issues:

1. when using django filter with django rest framework (DRF) datetime filters don't accept iso-8601 formats. DRF renders datetime objects as iso-8061. This creates confusion.

2. I added iso-8061 to django's datetime input formats setting. But django-filter still did not support it.

**Comment by rpkilby** [comment]
Hi @KushGoyal - which filterset class are you using? `django_filters.FilterSet` or `django_filters.rest_framework.FilterSet`?

**Comment by KushGoyal** [comment]
@rpkilby I am using `django_filters.rest_framework.FilterSet`

**Comment by rpkilby** [comment]
@KushGoyal - That's odd - it's the only obvious answer that comes to mind. 

If you look at this line [here](https://github.com/carltongibson/django-filter/blob/1.0.2/django_filters/rest_framework/filterset.py#L15), you'll see that the DRF filterset specifically uses the `IsoDateTimeFilter` for datetimes, which should handle your case. This [test](https://github.com/carltongibson/django-filter/blob/develop/tests/rest_framework/test_filterset.py#L12-L16) should verify the behavior. 

Could you provide a more complete example of your filterset? An example test case would be even more helpful.

**Comment by KushGoyal** [comment]
DRF has its own datetime input [setting](http://www.django-rest-framework.org/api-guide/settings/#datetime_input_formats)
Django has it own datetime input [setting](https://docs.djangoproject.com/en/1.10/ref/settings/#datetime-input-formats)

I am using a DateTimeFromToRangeFilter which does not use IsoDateTimeField. Is there a way I can make DateTimeFromToRangeFilter use iso-8061.

**Comment by rpkilby** [comment]
The [`DateTimeFromToRangeFilter`](https://github.com/carltongibson/django-filter/blob/1.0.2/django_filters/fields.py#L58-L64) is ultimately just a collection of two `forms.DateTimeField` fields, which does [obey](https://github.com/django/django/blob/1.10/django/forms/fields.py#L454) the `DATETIME_INPUT_FORMATS` setting. That said, `DATETIME_INPUT_FORMATS` doesn't recognize the `'iso-8601'` string. That behavior is specific to DRF. 

An alternative is to mix `IsoDateTimeFilter` with [`BaseRangeFilter `](http://django-filter.readthedocs.io/en/develop/ref/filters.html#baserangefilter).

**Comment by carltongibson** [comment]
> An alternative is to mix IsoDateTimeFilter with BaseRangeFilter.

I don't want to be adding a whole `DateX...` hierarchy mirroring Django here. Either we need to find workarounds (like this suggested) in user land code or we need to push back on Django to handle ISO-8061 in core. (IMO: Django should probably do that by this point — but this isn't something I have bandwidth to advocate for – so if you want it, make noise, write code.)

**Comment by rpkilby** [comment]
Hi @lucas-bremond, the CSV filter bases are used as mixins. 

```python
class IsoDateTimeRangeFilter(BaseRangeFilter, IsoDateTimeFilter):
    pass


class EventFilter (filters.FilterSet):
    date__range = IsoDateTimeRangeFilter(name='date')
```

**Comment by rpkilby** [comment]
That would require custom html/js. The CSV range filter uses a single input and expects two values separated by a comma. The original `DateFromToRangeFilter` expects two values across two separate inputs, named `<name>_0` & `<name>_1` (in 2.0, the suffixes change to `after` & `before`). 

If you want to use two inputs, but submit as a single CSV, then you'd need to write custom form html that presents the two inputs, then JS that intercepts the form submit, combines them as a single input, then submits the altered data.
