### ISSUE TITLE
filter field title changes fields verbose_name 

### ISSUE THREAD

**Issue by gthieleb** [carltongibson/django-filter#685]
When defining model fields verbose_name I want exactly use this as part of the generated filter label.

e.g. model field:

    dns = models.ManyToManyField(ReverseDnsEntry, blank=True, verbose_name='DNS')
    cidr = models.ForeignKey(Network, to_field='cidr', null=True, blank=True, verbose_name='CIDR')
    function = models.CharField(max_length="10", blank=True, verbose_name='Function')

Currently django filters creates a filter label like `Dns cidr function contains` instead of `DNS CIDR Function contains`. 

How can I change that behavior?

**Comment by carltongibson** [comment]
`Filter` takes a `label` kwarg. https://django-filter.readthedocs.io/en/develop/ref/filters.html#label

**Comment by gthieleb** [comment]
Sorry if i expressed myself not completely enough. 

I still want to rely on django-filters `generated filter labels` because they are really shining for my use case. 

I am missing a way to override `FILTERS_VERBOSE_LOOKUPS` and override the field name part with the fields `verbose_name`.

**Comment by carltongibson** [comment]
Well, the behaviour comes from [`django_filters.utils. verbose_field_name`](https://github.com/carltongibson/django-filter/blob/fd6c9a70ab2c97a5037e742affa5ea979ea597dc/django_filters/utils.py#L158-L184) so the first point of call is a failing test case showing the behaviour you'd like to see.

**Comment by gthieleb** [comment]
That looks good in a shell but why is it titelized in the label?

	In [45]: utils.verbose_field_name(DnsEntry, 'dns__cidr__cidr')
	Out[45]: u'DNS CIDR CIDR'

>> Dns cidr cidr

**Comment by gthieleb** [comment]
Perhaps to note, as I am coming from Germany my expectation is that substantives are written in uppercase, also the app is missing i18n, yet ...

**Comment by carltongibson** [comment]
If you look at the code `label_for_filter` calls `django.forms.utils.pretty_name` which applies the capitalisation. 

The simplest way around that behaviour is to supply the `label` kwarg. It'd be an interesting question as to how to detect when to apply the capitalisation and when not. 

If you're looking to contribute to open source than PRs improving either this behaviour or the i18n of the labels here would be welcomed.

**Comment by gthieleb** [comment]
So perhaps pretty_name makes something in respect to Djangos language settings? I meant i18n of my app. If I have something related to django filters I'll post a PR.

Thanks for pointing that out and thanks for such a great extension!

**Comment by rpkilby** [comment]
This seems valid to me. Added tests+fix in 686.
