### ISSUE TITLE
Filter Overrides

### ISSUE THREAD

**Issue by Bernardoow** [carltongibson/django-filter#689]
Hi brothers !

It's possible to set filter_overrides in a global way at settings.py?

For example, I want that all charfields be icontains.

Like this:
filter_overrides_global = {
             models.CharField: {
                 'filter_class': filters.CharFilter,
                 'extra': lambda f: {
                     'lookup_expr': 'icontains',
                 },
             }
        }

**Comment by rpkilby** [comment]
There is no global setting, but you could create a custom `FilterSet` and inherit from that instead. [`django_filters.rest_framework.FilterSet`](https://github.com/carltongibson/django-filter/blob/1.0.2/django_filters/rest_framework/filterset.py#L13-L21) is a good example of how to do this.
