### ISSUE TITLE
v1.0.2 introduced some template files and `django_filters` is required in `INSTALLED_APPS`.

### ISSUE THREAD

**Issue by wonderbeyond** [carltongibson/django-filter#690]
Django 1.0.2 introduced some template files and django_filters is required in INSTALLED_APPS, However this hasn't been documented yet.

> $ tree lib/python3.5/site-packages/django_filters/templates/
> lib/python3.5/site-packages/django_filters/templates/
> └── django_filters
>     ├── rest_framework
>     │   ├── crispy_form.html
>     │   └── form.html
>     └── widgets
>         └── multiwidget.html

The [Installation Guide](https://django-filter.readthedocs.io/en/latest/guide/install.html) needs update.

**Comment by carltongibson** [comment]
LGTM: 

![screenshot 2017-04-18 11 36 24](https://cloud.githubusercontent.com/assets/64686/25124201/53b1d808-242b-11e7-9112-8f68d97cdb3c.png)
