### ISSUE TITLE
Docs clarification re: settings.INSTALLED_APPS when using DRF

### ISSUE THREAD

**Issue by sushifan** [carltongibson/django-filter#692]
When Using DRF, I'm following these tips:

http://django-filter.readthedocs.io/en/develop/guide/rest_framework.html

Of course, here are the general installation tips:

http://django-filter.readthedocs.io/en/develop/guide/install.html

It's not clear, when using DRF, whether settings.INSTALLED_APPS should contain 'django_filters' or not.  Can you please clarify?

**Comment by rpkilby** [comment]
yes it should.

**Comment by sushifan** [comment]
Thanks a lot, appreciate it!
