### ISSUE TITLE
Use the same filter on multiple model fields

### ISSUE THREAD

**Issue by OskarPersson** [carltongibson/django-filter#695]
I'm using the following solution to filter a field by a comma separated string (e.g. `'valueA,valueB'`):

```
import django_filters
from django_filters.fields import Lookup

class ListFilter(django_filters.Filter):
    def filter(self, qs, value):
        value_list = value.split(u',')
        return super(ListFilter, self).filter(qs, Lookup(value_list, 'in'))

first = ListFilter(name='first')
```

This basically results in the following queryset: `MyModel.objects.filter(first__in['valueA', 'valueB'])`

How can I apply this filter on multiple fields? I would like it to generate the following queryset:
```
from django.db.models import Q
MyModel.objects.filter(Q(first__in['valueA', 'valueB']) | Q(second__in['valueA', 'valueB']))
```

using something like `ListFilter(name='first,second')`

**Comment by rpkilby** [comment]
Hi @OskarPersson. Two thoughts:

- I'd recommend taking a look at [`BaseInFilter`](https://django-filter.readthedocs.io/en/develop/ref/filters.html#baseinfilter).
- There is no API for filtering by multiple fields (eg, `name=['a', 'b']`), but you can customize how filtering is performed with the [`method`](https://django-filter.readthedocs.io/en/develop/ref/filters.html#method) argument of your filter.

**Comment by dvl** [comment]
I did something like this today and I want to leave it here maybe can help someone.

```python
class MultiFieldFilter(django_filters.Filter):

    def filter(self, qs, value):
        if value in django_filters.constants.EMPTY_VALUES:
            return qs

        if self.distinct:
            qs = qs.distinct()

        filters = Q()

        for name in self.name:
            filters |= Q(**{f'{name}__{self.lookup_expr}': value})

        qs = self.get_method(qs)(filters)

        return qs
```

**Comment by ArtemBernatskyy** [comment]
@dvl it says 

`  File "/var/webapps/reactmusic/code/reactmusic/audio/views.py", line 20
    filters |= Q(**{f'{name}__{self.lookup_expr}': value})
                                                ^
SyntaxError: invalid syntax
`
:)

**Comment by rpkilby** [comment]
@ArtemBernatskyy - Which version of python are you using. fstrings are only available in python 3.6

**Comment by ArtemBernatskyy** [comment]
@rpkilby 3.5 , if it is necessary i can set up it under pyenv

**Comment by rpkilby** [comment]
@ArtemBernatskyy - You would have to use python 3.6, since fstrings are only available in python 3.6 and above. Alternatively, you can just change the format statement. 

from this:
```python
        for name in self.name:
            filters |= Q(**{f'{name}__{self.lookup_expr}': value})
```

to this:
```python
        for name in self.name:
            key = '{}__{}'.format(name, self.lookup_expr)
            filters |= Q(**{key: value})
```

**Comment by ArtemBernatskyy** [comment]
@rpkilby one more thing, it says 

`  File "/var/webapps/reactmusic/env/lib/python3.4/site-packages/django_filters/utils.py", line 170, in verbose_field_name
    parts = get_field_parts(model, field_name)
  File "/var/webapps/reactmusic/env/lib/python3.4/site-packages/django_filters/utils.py", line 83, in get_field_parts
    parts = field_name.split(LOOKUP_SEP)
AttributeError: 'list' object has no attribute 'split'
`

Source code is here 

`
    class MultiFieldFilter(filters.Filter):

        def filter(self, qs, value):
            if value in django_filters.constants.EMPTY_VALUES:
                return qs

            if self.distinct:
                qs = qs.distinct()

            filters = Q()

            for name in self.name:
                key = '{}__{}'.format(name, self.lookup_expr)
                filters |= Q(**{key: value})

            qs = self.get_method(qs)(filters)

            return qs


    class SongFilter(filters.FilterSet):
        song = MultiFieldFilter(
            name=['name', 'artist__name'],
            lookup_expr='icontains',
        )

        class Meta:
            model = Audio
            fields = ["song"]
`

url by which i am searching is here `?song=red`

**Comment by ArtemBernatskyy** [comment]
For anyone who comes here i ended up with this, NOTE it doesn't uses django-filter 

    class AudioListView(ListCreateAPIView):
        renderer_classes = [JSONRenderer]

        def get_queryset(self):
            """
            Optionally restricts the returned purchases to a given user,
            by filtering against a `username` query parameter in the URL.
            """
            queryset = Audio.objects.select_related("artist")
            song = self.request.query_params.get('song', None)
            if song is not None:
                queryset = queryset.filter(Q(name__icontains=song) | Q(artist__name__icontains=song)).distinct()
            return queryset

        def get_serializer_class(self):
            if self.request.method == "GET":
                return AudioListSerializer
            if self.request.method == "POST":
                return AudioCreateSerializer
