### ISSUE TITLE
Textinput widget for Foreingkey

### ISSUE THREAD

**Issue by arenasgt** [carltongibson/django-filter#705]
I want to add  a textInput for a foreign key:
```python 
  channel__name = django_filters.CharFilter(
        lookup_expr='icontains',
        widget = forms.TextInput()
    )
```

I found out that this does the job:
```python 
    channel = django_filters.CharFilter(method='get_channel')

    def get_channel(self, queryset, name, value):
        return queryset.filter(channel__name__icontains=value)

```
I just wonder if it is possible to do it like the first example without declaring a method.
thanks for the app !

**Comment by rpkilby** [comment]
You should be able to get by with 
```python
channel__name = django_filters.CharFilter(name='channel__name', lookup_expr='icontains')
```

`CharFilter`s should already use a text widget. Specifying the widget as such should be redundant.

**Comment by arenasgt** [comment]
Hi rpkilby I've tried as you suggest but I get a select instead of textinput in the form.
thanks for your time.

**Comment by rpkilby** [comment]
[`CharFilter`](https://github.com/carltongibson/django-filter/blob/1.0.2/django_filters/filters.py#L175-L176) is just a thin wrapper around `django.forms.ChoiceField`. It would be unusual for a select widget to be present. Could you provide the `FilterSet` code?

**Comment by carltongibson** [comment]
I'm going to assume this is resolved.
