### ISSUE TITLE
FilterSet fields should autogenerate schemas from help_text (for DRF generated documentation)

### ISSUE THREAD

**Issue by bradmerlin** [carltongibson/django-filter#706]
Although backends support specifying a schema explicity via `get_schema_fields`, it would be very useful if a filter's `help_text` field would automatically generate a schema entry per field. One use case: display field `help_text` in DRF autogenerated documentation.

**Comment by rpkilby** [comment]
What version are you using? `help_text` should be supported since 1.0
see https://github.com/carltongibson/django-filter/blob/1.0.0/django_filters/rest_framework/backends.py#L94-L105

**Comment by bradmerlin** [comment]
I'm on 1.0.2. 

I think the issue is that at [django_filters line 103](https://github.com/carltongibson/django-filter/blob/1.0.0/django_filters/rest_framework/backends.py#L103), no `schema` is specified, which leaves it at `None`. In the DRF doc template, it tries to display `field.schema.description`, which fails because `field.schema` is `None`.

Should I move this to DRF, or do you think there's something to be done here?

**Comment by rpkilby** [comment]
Ah - I think this is already fixed in the upcoming 1.0.3 release ([source](https://github.com/carltongibson/django-filter/blob/bb4322bdfb50a729b564cdcba95e77645ad346e1/django_filters/rest_framework/backends.py#L96-L104)). You could test this out by installing the `develop` branch.

**Comment by bradmerlin** [comment]
Works perfectly! Thanks.
