### ISSUE TITLE
Can I use this as "Search" feature?

### ISSUE THREAD

**Issue by alzearafat** [carltongibson/django-filter#708]
Hi there,

Really great app, and a livesaver!

This is not technical issue by the way. I'm just curious, can I use `django-filter` as my search form? What is the difference with other search app, like django-watson or similar app? Any pros/cons?

Thank you!

**Comment by carltongibson** [comment]
I'd use Django Watson... it's great.

Using the ORM for search is bad idea. You're basically using LIKE queries at the DB layers. There are better ways.

**Comment by alzearafat** [comment]
django-watson somehow doesnt work for me, I dont know. I open issue on its github but no response, so I search for alternative

Anyway, thank you @carltongibson :)
