### ISSUE TITLE
ChoiceFilter callable choices

### ISSUE THREAD

**Issue by teelee7133** [carltongibson/django-filter#710]
Hello,

For ChoiceFilter (and other related ones), is it possible, or will it make sense, to have the 'choices' callable to behave like the ChoiceField in django, where 'it is evaluated each time the field’s form is initialized'?

https://docs.djangoproject.com/en/1.11/ref/forms/fields/#choicefield

(I am happy to draft a PR if this sounds a reasonable feature request)

Thanks!

**Comment by carltongibson** [comment]
> ... or will it make sense...

That's the question isn't is? 🙂

Can you explain your use-case a bit so we can see? Thanks!

**Comment by teelee7133** [comment]
Indeed!  :slightly_smiling_face:

I think currently in `ChoiceFilter`, `choices` parameter accepts a callable.  But if datetime function or ORM functions are used within that callable, then, ideally, it would be best the `choices` data to be materialized when the `FilterSet` instance is created, instead of when the `FilterSet` class is created.

Some naive example:
Consider some reporting system with the following models (I have not tested the syntax):
```python
class AccountTransactionType(models.Model):
    name = models.CharField(max_length=100)

class AccountTransaction(models.Model):
    transaction_type=models.ForeighKey(AccountTransactionType)
    transaction_date=models.DateTimeField()
    #....

# ------------
def recent_type_choice_fn():
    # Lets get some more recent account type
    return AccountTransaction.objects.filter(
        transaction_date__gt=(timezone.now() - timezone.delta(days=30))
    ).values_list('transaction_type', 'transaction_type__name')

class AccountingTransactionFilter(django_filter.FilterSet):
    transaction_type = ChoiceFilter(
        choices=recent_type_choice_fn, 
        #....
    )
   
```
Here we want to show transaction type with recent entries e.g. last 30 days, in the filter.  However,  `choices` for `AccountingTransactionFilter` will be fixed when the class is created.  If we leave django server running for a month, the choices won't change.  In order to have refreshed choices, either ChoiceFilter have to be subclassed, or restart django server...

Let me know of your thoughts, thanks!

**Comment by rpkilby** [comment]
Yep. The problem is [choice](https://github.com/carltongibson/django-filter/blob/1.0.2/django_filters/filters.py#L186-L210) resolution during the field instantiation. Could you try installing the branch from #680? I believe that this incidentally fixes the issue you're describing here.

**Comment by rpkilby** [comment]
It might not also be a bad idea for me to add a test in 680 ensuring that choices are resolved during FilterSet form creation instead of during filter instantiation.

**Comment by teelee7133** [comment]
Yep rpkilby, I gave PR #680 a quick test, and it looks like the PR solves the issue.  :+1:  Thanks for the PR!

When will it likely be released?  :slightly_smiling_face:

**Comment by carltongibson** [comment]
> When will it likely be released? 🙂

It'll be a week or two (at least). I need to finish 1.0.3 and then look at the proposals for 1.1 (which includes this one.) If you need it before then I'd suggest [installing from the branch](https://pip.pypa.io/en/stable/reference/pip_install/#git)

**Comment by teelee7133** [comment]
version 1.1 sounds good, thanks!
