### ISSUE TITLE
Django 1.11 compatibility - named cursor error

### ISSUE THREAD

**Issue by mheppner** [carltongibson/django-filter#713]
After upgrading to Django 1.11, I get a `Programming Error: can't use a named cursor outside of transactions` whenever an API view set has a `filter_fields` set directly to a foreign key field. The traceback is happening on line 3, `filter.form.as_p`, but I think it's coming from somewhere else (similar issue when I turn crispy forms back on):

```
<h2>{% trans "Field filters" %}</h2>
<form class="form" action="" method="get">
    {{ filter.form.as_p }}
    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
</form>
```

- `django-filter==1.0.2`
- `djangorestframework==3.6.3`
- `django-crispy-forms==1.6.1`
- `psycopg2cffi==2.7.5`
- Pypy 5.7.1

Normal fields work fine, so I'm not sure if I was inadvertently using a foreign key prior to upgrading, but I at least wasn't getting this error. If using a foreign key for something like `__isnull` isn't allowed, then an assertion should be made.

**Comment by rpkilby** [comment]
It looks like this is an incompatibility with Django and psycopg2cffi.
See: https://github.com/chtd/psycopg2cffi/issues/82

**Comment by rpkilby** [comment]
Try switching to `psycopg2` from `psycopg2cffi`. I'd guess that the issue disappears.

**Comment by mheppner** [comment]
Thank you @rpkilby. I didn't even try debugging further since it seemed to be coming from here. I'm targeting pypy, so I need to stick with `psycopg2cffi`. I guess this issue can be closed, up to you guys.

**Comment by rpkilby** [comment]
I don't think there is anything to be done here since the interaction is incidental to django-filter.

**Comment by mheppner** [comment]
Ok thanks
