### ISSUE TITLE
Clean way to detect if filter is active

### ISSUE THREAD

**Issue by ygwain** [carltongibson/django-filter#717]
I have a coupe of questions.
1. Is there a clean way to detect is filter active (applied)? (for now I looking into `filter_instance.data` and `filter_instance.form.cleaned_data`)
2. Is there a clean way to get cleaned value for a filter?
Thanks.

**Comment by carltongibson** [comment]
In normal usage the filter is always applied. Obviously if `request.GET` is empty then it won't do anything, so I guess check that. 

`filter_instance.form.cleaned_data` would be the canonical access point for the cleaned data from the filter set form.

**Comment by ygwain** [comment]
If there are several filter set's on the page and want to know if particular filter set is active?

**Comment by carltongibson** [comment]
Errrr.... that'll depend... I don't we can cover the logic of your specific application. I'm sure you'll come up with something.

**Comment by ygwain** [comment]
IMHO method like that is not the logic of my specific app. I don't ask you to implement it, I'm just curious does it make sense :) Thanks anyway!

**Comment by ygwain** [comment]
> In normal usage the filter is always applied. Obviously if request.GET is empty then it won't do anything, so I guess check that.
What do you mean while saying:
> In normal usage the filter is always applied
If `request.GET` is not empty but its data is not related to filter (e.g. it has page number for pagination) - filter is not applied and this is normal situation.

**Comment by carltongibson** [comment]
Under normal usage, the `FilterSet` is always passed `request.GET`. This is passed to the form which validates the data (excluding irrelevant keys, such as `page` in that example). The `cleaned_data` is then passed to each `Filter` in turn. In general, if the field isn't present, or has an empty value, no filtering will occur.

**Comment by rpkilby** [comment]
btw, this reminds me of #534.

**Comment by carltongibson** [comment]
@rpkilby Yep. You're right. 

```
for k  in my_keys:
   if k in request.GET:
      # But was it valid? Was it non-empty? ...
```

I'm not sure I want to add that. (Obviously awesome, tested documented solutions welcome...)

**Comment by rpkilby** [comment]
In #534, I don't think it occurred to me to inspect the form's `cleaned_data`. I'd have to think about it more, but I think we could do the same thing here. 

```python
def is_active(self):
    return bool(self.form.cleaned_data)

@property
def active_filters(self):
    return self.form.cleaned_data.keys()

**Comment by carltongibson** [comment]
And if that's all it is then all the more for it to live in userland code...

**Comment by gabn88** [comment]
I would love to have an is_active method added to the source code for the filter.

I now do: 
`if contact_filter.form.is_valid() and any(contact_filter.form.cleaned_data.values()):`
as a way to check whether it is active and it works, but it is a pain to remember it every time.

**Comment by carltongibson** [comment]
@gabn88 Just add a method to your filterset if you want to, as per the example in the discussion

**Comment by kgunia** [comment]
I know, it's too late but if anyone have the same problem, `contact_filter.data`  is the solution. This dictionay is empty when filters not applied.

**Comment by jdejoode** [comment]
My two cents: this is a feature that could live in userland, but it seems fairly fundamental for a filter to be able to export the currently active filtering fields, so why *not* include it. If not, I hope people find this page (took 15 minutes if searching) and that this solution could be helpful:

	class SomeFilter(django_filters.FilterSet):
	    
	    def is_active(self):
		return bool(self.form.cleaned_data)

	    @property
	    def active_filters(self):
		if self.form.is_valid():       
		    return self.form.cleaned_data
		return None

	    class Meta:
		model = SomeModel
		fields = '__all__'`

Then use as 

	 my_filter = SomeFilter(request.GET, queryset=some_queryset)
	 active_fields = my_filter.active_filters`

**Comment by jdejoode** [comment]
The solution above doesn't provide the human readable values for a field (so it uses underscores) and it would need to have a way of tweaking how m2m's are represented.

**Comment by confuzeus** [comment]
I agree that there should be a method on all FilterSets that returns whether there's any filtering being done or not because in my current project, I have a dozen filters where I use this method:

```python
@property
def is_filtering(self):
    return self.form.is_valid() and any(self.form.cleaned_data.values()
```

Of course, I'm inheriting from my own subclass of FilterSet to avoid duplication, but I wouldn't have to if this was baked in. Having to subclass in order to have this one method is kind of a waste. I'll also have to remember to do that for every new project.

Unless there's a good reason why this shouldn't be included, it should be. I'm happy to submit a PR if need be.
