### ISSUE TITLE
How to use with SearchVectorField?

### ISSUE THREAD

**Issue by raiviskrumins** [carltongibson/django-filter#725]
Is it possible to use django-filter with SearchVectorField?
https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/search/#searchvectorfield

**Comment by rpkilby** [comment]
It's python - anything is possible 😉 

I'm assuming you're looking to using `Meta.fields` to generate filters. By default, django-filter is aware of a limited set of model [fields](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/filterset.py#L117-L160) that it knows how to create filters for. Beyond that, you need to tell django-filter what to do by adding a filter [override](https://django-filter.readthedocs.io/en/develop/ref/filterset.html#filter-overrides) (or modifying the class-wide [defaults](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/filterset.py#L163-L164)).

**Comment by raiviskrumins** [comment]
Thank you
