### ISSUE TITLE
Slow ModelChoiceFilter

### ISSUE THREAD

**Issue by italomaia** [carltongibson/django-filter#726]
It seems ModelChoiceFilter always evaluates the given queryset. Is it expected behavior? Shouldn't it only evaluate the queryset when it is absolutely required?

**Comment by rpkilby** [comment]
My understanding is that it evaluates only when rendering. Could you provide a more complete example?

**Comment by italomaia** [comment]
Well, here, it was evaluating even when the filter parameter for it was not provided. I'll setup a fiddle of sorts, but you can verify this behavior easely with django-debug-toolbar.

**Comment by carltongibson** [comment]
@italomaia Can you pass a callable that raises an exception when it's evaluated and add the traceback here?

This will confirm at exactly which point the queryset is being evaluated. From there we have a sensible basis for discussion.

**Comment by rpkilby** [comment]
This is related to #710. `ChoiceFilter` was resolving its `choices` during init, which then had the effect of resolving `ModelChoiceFilter.queryset`. I think this can be closed now that the related PR has been merged. @italomaia - you should be able to install the `develop` branch to have the desired behavior.
