### ISSUE TITLE
doc issue

### ISSUE THREAD

**Issue by hyusetiawan** [carltongibson/django-filter#728]
in overriding queryset based on request doc, linked here: http://django-filter.readthedocs.io/en/develop/guide/usage.html#filtering-the-primary-qs

is the request variable of global scope? I tried self.request and it's not there either

help?

**Comment by carltongibson** [comment]
It should be available as `self.request`

**Comment by hyusetiawan** [comment]
it might not be related to django-filter, I tried using it with django-graphene, it keeps complaining that request is not available, closing this issue because it might be caused by another library

**Comment by rpkilby** [comment]
Just as a note - the docs in question have been patched in #691. They may need to be rebuilt/pushed to readthedocs.
