### ISSUE TITLE
Remove the rest_framework sub-package import block

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#729]
So, the import was originally added for ease of use, but it also seems to be a minor source of confusion & bugs. For example, I've seen several instances of the following:

```python
import django_filters

class MyFilter(django_filters.rest_framework.FilterSet):
    my_filter = django_filters.BooleanFilter(...)
```

It's a subtle bug in that they've accidentally used the wrong filter class. I'd argue that we should remove the import and simply plaster the correct import all over the relevant docs. eg, 

```python
from django_filters import rest_framework as filters
```

~~Additionally, the rest_framework import has been a source of weird circular import issues in the past. The try/except block has a tendency to mask this too, since it doesn't discriminate between circular imports, and the "DRF is not installed" import.~~ this is still true, but can be fixed

**Comment by carltongibson** [comment]
Hmmm. 

My preference is for:

```
import django_filters
```

and then to go from there. 

```
class MyFilter(django_filters.rest_framework.FilterSet):
```

What's wrong with that? ☕️

**Comment by rpkilby** [comment]
ehh, the import causes the occasional hangup for newcomers. eg, 

```python
# this (incorrect)
class MyFilter(django_filters.rest_framework.FilterSet):
    my_filter = django_filters.BooleanFilter()

# instead of this (correct)
class MyFilter(django_filters.rest_framework.FilterSet):
    my_filter = django_filters.rest_framework.BooleanFilter()
```

Ultimately, I'm kind of ambivalent on changing the import, especially since it would be a breaking change.

**Comment by rpkilby** [comment]
The other reason I wanted to remove the block was to fix circular import error hiding. I've opened #741 instead.
