### ISSUE TITLE
Filter with no arguments

### ISSUE THREAD

**Issue by leonprou** [carltongibson/django-filter#733]
Using previous `0.13`` version we had the following filter:
```

class MyFilter(django_filters.FilterSet):
    active = django_filters.MethodFilter()

    class Meta:
        model = MyModel
        fields = {'active': ['exact']}
        ordering = MyModel._meta.ordering

    def filter_active(self, queryset, value):
        #filtering here, no using value at all

```
 The filter query url looked like: `?active`, I don't needed value so no need to specify it.

Moving to 1.02 version I converted the filter to:

```
class MyFilter(django_filters.FilterSet):
    active = django_filters.CharFilter(method='filter_active')

    class Meta:
        model = MyModel
        fields = {'active': ['exact']}
        ordering = MyModel._meta.ordering

    def filter_active(self, qs, name, value):
        #filtering here

```

 **The previous valueless filter url  (`?active`) is not getting called, and I have to specify  the value, e.g - `?active=x`. Can I get the previous behavior?**

**Comment by carltongibson** [comment]
@leonprou Examine your FilterSet's form data: presumably you're getting an `EMPTY_VALUE` out of that. In this case no filtering will occur. (Your `filter_active` will never get called.)

You actually want a `Bool` here. `active` is `True/False` right?

Mapping from the `QueryDict` is the widget's responsibility, so I think you need to look at `django_filters.widgets.BooleanWidget` and override `value_from_datadict` to return `True` if the key is present but without a value. 

(`Filter`s take ` widget kwarg.)
