### ISSUE TITLE
Issue vs Support ticket

### ISSUE THREAD

**Issue by eriktelepovsky** [carltongibson/django-filter#735]
This is related to locked issue #732 

Why is that issue supposed to be a support ticket? 

I quote you (@carltongibson):
> Individual filters can take additional kwargs which will be passed to the form field.

It is true, but it **doesn't work**. It throws exception ... so it is an issue, not a support ticket.

**Comment by carltongibson** [comment]
@eriktelepovsky Please try the other channels as requested. 

Unless you are able to narrow this down to something much more specific there is currently no reason to consider this a bug. 

If you persist I will block you from the repo.
