### ISSUE TITLE
release versions of the docs are not on readthedocs.org

### ISSUE THREAD

**Issue by fmoor** [carltongibson/django-filter#737]
The docs on readthedocs.org only have `latest`, `stable`, `master` and `develop` as version options. As a library user I don't trust any of these because it is not obvious how they relate to a particular release version of the library. I have to checkout the version that I am using and build the docs locally, or read restructured text on git hub to be sure I am reading relevant documentation. I can see how these branches would be relevant for people who are developing django-filter, but they are not helpful for users. Can we have all version version numbers available from pypi.python.org available on read the docs too?

As an aside, it is also not obvious from the names how the four branches relate to each other. latest and develop seem like they should be synonyms. Why are they both on readthedocs? master may as well be called default. It has no inherent meaning in relation to the other three names. Why is master on readthedocs at all? I'm confused...

**Comment by carltongibson** [comment]
I've removed `latest` and `stable`. `develop` and `master` correspond to the branches in the repo. `master` is always the latest release. 

I'd take a PR on the docs adding a note to that effect.
