### ISSUE TITLE
Unable to customize multiwidget.html

### ISSUE THREAD

**Issue by bluesurfer** [carltongibson/django-filter#746]
I would like to customize the HTML template in `django_filters/widgets/multiwidget.html` but it seems that `django-filter` ignores my changes (I want to remove the hyphen "-" between widgets).

I have recreated in my templates directory the same path `django_filters/widgets/multiwidget.html`. This should override the default `multiwidget.html`, but instead nothing changes.

**Comment by rpkilby** [comment]
Are you using a version of Django older than 1.11? 

https://docs.djangoproject.com/en/1.11/releases/1.11/#template-based-widget-rendering

**Comment by bluesurfer** [comment]
@rpkilby 

Yes, Django 1.10.7

**Comment by rpkilby** [comment]
Sorry - I didn't exactly wrap up that thought. Overriding the `django_filters/widgets/multiwidget.html` template has no effect because template-based widget rendering was introduced in the Django 1.11 release. I'd say this can be closed off as expected behavior. The solution is to either:

- Upgrade to Django 1.11+
- Override the [`format_output`](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/widgets.py#L96-L98) method of the widget class.

**Comment by DonExo** [comment]
I'm using Django 3.04 and Django-filter 2.2.0 and I have exactly the same issue. I need that dash to be removed and I'm already pulling my hair out. I believe I can remove it via jQuery, but that would be my last measure of resort.

I have extended the RangeWidget to have custom placeholder for the two inputs and it works fine. The suffixes are also working fine. But the damn template won't be found.

`
from django_filters.widgets import RangeWidget

class MinMaxRangeWidget(RangeWidget):
    template_name = "foo/bar/custom_widget.html"
`

the template foo/bar/custom_widget.html: (just had the dash removed)
`
{% for widget in widget.subwidgets %}{% include widget.template_name %}{% if forloop.first %}{% endif %}{% endfor %}
`

APP_DIRS = True...

**Comment by bluesurfer** [comment]
@DonExo this is what I have done at the time and still using it.

```
import django_filters
from django_filters.widgets import DateRangeWidget


class CustomDateRangeWidget(DateRangeWidget):
    template_name = 'bootstrap4/layout/multiwidget.html'


class OrderFilterSet(django_filters.FilterSet)):
    created = django_filters.DateFromToRangeFilter(widget=CustomDateRangeWidget)

```

**Comment by tubaman** [comment]
Just a note here.  I had a similarly long session of pulling hair out.  [The key[(https://docs.djangoproject.com/en/5.0/ref/forms/renderers/#overriding-built-in-widget-templates) is that you need to set `FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'` in your settings.py.  Then you'll be able to override `django_filters/widgets/multiwidget.html`
