### ISSUE TITLE
Can't pass in callable to ModelChoiceFilter

### ISSUE THREAD

**Issue by jordan9724** [carltongibson/django-filter#748]
I tried following the example the best I could, the example was:

```
def departments(request):
    company = request.user.company
    return company.department_set.all()

class EmployeeFilter(filters.FilterSet):
    department = filters.ModelChoiceFilter(queryset=departments)
    ...
```

My code is as follows:
```
queryset_of_model(request):
    return ModelName.objects.all()

class MyFilter(django_filters.FilterSet):
    my_field = django_filters.ModelChoiceFilter(queryset=queryset_of_model)
    ...
```
When it is set up like this I get the error `'function' object has no attribute 'all'` because it tries to call "all" on the function (this happens elsewhere in the code) rather than using what is returned from the function

**Comment by rpkilby** [comment]
What version of django-filter are you using? Could you provide a traceback?

**Comment by jordan9724** [comment]
Weird how things work when you upgrade them. Thanks for the help!
