### ISSUE TITLE
FilterSet resolved field 'image' with 'exact' lookup to an unrecognized field type ImageField...

### ISSUE THREAD

**Issue by msbt** [carltongibson/django-filter#751]
Hi there!
I know this issue has been addressed [here](https://github.com/carltongibson/django-filter/issues/564) already, but I just can't find a proper solution.

I have a model with a Store class that contains various information about different stores and includes also a field with image = models.ImageField to display when querying for it. 

I tried everything from the docs, but it seems to be ignoring my exlude and also the fields I'm filtering for

```
class StoreFilter(django_filters.FilterSet):
    class Meta:
        model = Store
        exclude = ['image']
        fields = {
            'name': ['exact', 'contains'],
            'created': ['exact', 'year__gt'],
        }
```
This is what I'm trying to filter for and it keeps throwing me that AssertionError, any idea what I might be missing? As soon as I comment the image line in my models.py it works (but it shows all fields, not only name and created which I was filtering for. Any pointers would be appreciated.

Best regards

**Comment by rpkilby** [comment]
Hi @msbt - I'd wager that some information has been left out here. I ran a quick test, and the mentioned `AssertionError` was not raised. As you can see below, no filter for the image fields was created. 

```python
# models
from django.db import models

class Store(models.Model):
    name = models.CharField(max_length=80)
    created = models.DateField()
    image = models.ImageField()


# filters
import django_filters

class StoreFilter(django_filters.FilterSet):
    class Meta:
        model = Store
        exclude = ['image']
        fields = {
            'name': ['exact', 'contains'],
            'created': ['exact', 'year__gt'],
        }


# console output
In [8]: StoreFilter.base_filters
Out[8]: 
OrderedDict([('name', <django_filters.filters.CharFilter at 0x10f2de630>),
             ('name__contains', <django_filters.filters.CharFilter at 0x10f2de6a0>),
             ('created', <django_filters.filters.DateFilter at 0x10f2de6d8>),
             ('created__year__gt', <django_filters.filters.NumberFilter at 0x10df4a6d8>)])
````

Could you provide the full model & filter code? If not, a distilled example that demonstrates the issue would be helpful.

**Comment by msbt** [comment]
Hey, thanks for getting back to me! Give me a bit more time to figure out what I might have done wrong, would be embarassing if it was a rookie mistake ;)

**Comment by rpkilby** [comment]
Hi @msbt - did you ever figure out what was going on, or can this be closed?

**Comment by msbt** [comment]
I don't have time right now, so lets close it up and revisit when I'm trying again and get stuck ;)

**Comment by georgezouq** [comment]
@msbt Any idea about this problem? I have the same one

**Comment by ZigmundVonZaun** [comment]
it was ignoring my overrides since I was using a generic view. this has temporarily solved my problem but my client is bothering me in the specificity of his filters lol. Could you look into this

```
urlpatterns = [
    path('', views.StadiumFilterView.as_view(model=Stadium,
                                             filterset_fields=['name', 'country']), name="stadium_index"),
]
```

**Comment by tamhv** [comment]
fields, exclude, filter_overrides in Meta doesn't solve this `AssertionError` error, when i use `FilterView` + `filter_class = MyFilterSet` , i have to set filter_fields under view to exclude fields,
otherwise `def filter_for_field(cls, f, name, lookup_expr='exact')` will run through all fields
