### ISSUE TITLE
BaseInFilter should prevent query on empty value

### ISSUE THREAD

**Issue by camd** [carltongibson/django-filter#755]
I had a user that submitted the following request:

    /api/jobdetail/?job_id__in=

This ended up returning EVERY jobdetail record which, with the size of our DB, was huge and timed out with a very long running query.  A few of these at a time caused a serious slow-down on our server. 

We are using a filter for this field like so:

    class NumberInFilter(django_filters.filters.BaseInFilter,
                     django_filters.NumberFilter):
        pass

It would be great to have a way to specify you wanted to reject empty values for filters.  I know there is a ``method`` param I could pass, so perhaps that's the intended answer.  But it would be nice to have this built-in.

My solution was to override the ``filter`` function with a check in the ``NumberInFilter`` class above:

    def filter(self, qs, value):
        if value in django_filters.constants.EMPTY_VALUES:
            raise ValueError("Invalid filter on empty value: {}".format(value))
        return super(NumberInFilter, self).filter(self, qs, value)

Or perhaps this should be another filter class that can be added in?  Please advise your preference and I can open a PR.  Thanks!!  :)

**Comment by rpkilby** [comment]
Hi @camd - instantiating the filter with `required=True` should provide the expected behavior.

**Comment by camd** [comment]
In my case, there are several parameters that could be passed in.  Sometimes the user can pass in combinations of them.  So none of them are necessarily required.  But if they're passed, in, we want a valid value.  Perhaps a ``not_empty`` argument would be appropriate for that?

**Comment by carltongibson** [comment]
@camd At this stage I'm inclined towards you creating your own Filters exactly as you have (although validation belong on the `form` so I might move the check there). 

`?job_id__in=` is identical to not providing the value at all — no filtering will occur. This is the intended behaviour. (I'm not at all inclined to change that.)

> This ended up returning EVERY jobdetail record which, with the size of our DB, was huge and timed out with a very long running query. A few of these at a time caused a serious slow-down on our server.

You should **always** `LIMIT` your QuerySets. That's not Django-Filter's responsibility.
