### ISSUE TITLE
OrderingFilter widget select multiple 

### ISSUE THREAD

**Issue by tamhv** [carltongibson/django-filter#756]
I'm trying to use OrderingFilter, it says "Multiple values may be separated by commas." but users can't pick multiple
```
class MyFilter(django_filters.FilterSet):
o = django_filters.OrderingFilter(
        fields=(
            ('pk', 'pk'),
            ('first_name', 'first_name'),
            ('email', 'email')
        ),
        field_labels={
            'pk': 'ID',
            'first_name': 'First name',
            'email': 'Email'
        },
    )
```
<img width="506" alt="screen shot 2017-08-06 at 11 26 19 am" src="https://user-images.githubusercontent.com/5440638/29000669-56e5a5a0-7a9c-11e7-8bfd-67065d9d9c31.png">
I try to override widget `widget=forms.SelectMultiple` but it doesn't work

`'list' object has no attribute 'split'`

**Comment by rpkilby** [comment]
Hi @tamhv. Sorry, the help text is a little misleading here. The quick answer is that you may just want to simply disable the `help_text`. I'm opening a PR that does this. 

The longer answer is that `OrderingFilter` inherits from `BaseCSVFilter` and can accept multiple values separated by commas (eg, `?o=pk,first_name`). However, this value isn't possible to create with standard HTML select widgets. You would need to have client code that constructed this value for you. 

It's also worth noting that `SelectMultiple` doesn't work here, given that the widget is unable to retain selection order.
