### ISSUE TITLE
The app cache isn't ready yet, so if this is an auto-created related field, it won't be available yet.

### ISSUE THREAD

**Issue by AlJohri** [carltongibson/django-filter#758]
I'm running into an issue where if I import a particular file too early, I get this error: `TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: xyz`. This is occurring because the [`MyModel._meta.get_field` method](https://docs.djangoproject.com/en/1.11/_modules/django/db/models/options/#Options.get_field) raises FieldDoesNotExist if the "app cache" isn't ready yet.

snippet:

```python
if not self.apps.models_ready:
    raise FieldDoesNotExist(
        "%s has no field named '%s'. The app cache isn't ready yet, "
        "so if this is an auto-created related field, it won't "
        "be available yet." % (self.object_name, field_name)
    )
```

can django-filter somehow wait until the app cache is ready? I'm pretty unfamiliar with this issue. Unsure if other libraries run into the same thing as well

**Comment by carltongibson** [comment]
@AlJohri There's not enough here to say exactly where your issue is coming up... It looks like you're doing things _too early_ (hence the app cache error) but I couldn't say what. You need to review your code to pin down the exact issue. 

(The general rule is that you can **use** a model at import time.) 

I don't think this is a Django Filter **issue**. I'm happy to look again if you can pin down something concrete with the library.

**Comment by AlJohri** [comment]
I was importing serialzers across apps which were defined in a views.py file, the same file on which the filter sets were defined. By moving the serialzers into their own file, the cross app import worked fine. Thanks for the response @carltongibson

**Comment by DramanSalif** [comment]
Hi,
Can you help me in solving this issue ? I am running my django project in vs code. Although, I''have a field named 'last_name', in my model, I am getting :" django.core.exceptions.FieldDoesNotExist: Customer has no field named 'last_name'. The app cache isn't ready yet, so if this is an auto-created related field, it won't be available yet." each I want run makemigrations.
