### ISSUE TITLE
Form rendering

### ISSUE THREAD

**Issue by frague59** [carltongibson/django-filter#765]
Hi, 

I'm using django-filter with crispy, and I'm trying to use the Meta.form option to a filterset.

+ My filter declaration 

```python
class ManifestationFilter(filter.FilterSet):
    ... some filters ...
    class Meta:
        """ Bind the search form to the filterset  """
        form = search_forms.ManifestationSearchForm
```
+ My form declaration

```python
class ManifestationSearchForm(forms.Form):
    ... some fields ...
    def __init__(self, *args, **kwargs):
        """" Binds the helper to a crispy helper """
        super().__init__(*args, **kwargs)
        self.helper = helpers.ManifestationSearchFormHelper()
```

When I render the form, it is "partially" rendered : I've defined some "label" in the **form fields**, but they are not used in the rendering, the **filter** fields label seems to be rendered instead.

I can set my **label** to the filterset fields, but it seem a bit weird : part of the form display is assumed by the filterset, and another by the form.

**Comment by carltongibson** [comment]
Look at the [`form` property implementation](https://github.com/carltongibson/django-filter/blob/develop/django_filters/filterset.py#L238-L252). If `ManifestationSearchForm` is fully configured you'll want to override this to just instantiate your form and return it, rather than setting fields based on the `FilterSet`.

**Comment by rpkilby** [comment]
Additionally, you may want to look at [`django_filters.rest_framework.FilterSet.form`](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/rest_framework/filterset.py#L25-L42).

**Comment by frague59** [comment]
OK, I've got it... (and thank you for this project !)

I've renamed my fields to match the filterset filter names, aka.:
```python
class ManifestationSearchForm(forms.Form):
    title__icontains = forms.CharField(max_length=255, required=False, label="My pretty localized title")
```
Then I've linked the form to the filterset:
```python
class ManifestationFilter(filter.FilterSet):
    class Meta:
        form = search_forms.ManifestationSearchForm
        fields = {"title": ["icontains"]}
```
I'm not using localization for my strings (big old project, too much work to localize it properly), even if USE_L10N is activated, and LOCALE set to "fr".

When rendered, the field label is now:

**Titre contains**

where "Titre" is the localized (french) name of the field, but "contains" is not.

Any idea ?

**Comment by rpkilby** [comment]
I don't think you can override the form fields in that manner. Basically, the `Meta.form` is subclassed with  fields [derived from filters](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/filterset.py#L223-L228). Your declared `title__icontains` field would simply be overridden.

However, you could override the field's label in the form `__init__`. Something like...

```python
class ManifestationSearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title__icontains'].label = 'My super awesome label'
```


> where "Titre" is the localized (french) name of the field, but "contains" is not.

The form labels are built with the [`label_for_filter`](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/utils.py#L214-L234) utility function, using the lookup expression parts. eg, `title__icontains` becomes "Title contains", and `published__year__gte` becomes "Published year is greater than or equal to". 

There are two potential problems here. 

- Translation isn't working properly in `label_for_filter`. 
- Translation *is* working, but there aren't corresponding translations for the individual [lookup parts](https://github.com/carltongibson/django-filter/blob/develop/django_filters/conf.py#L23-L60).

**Comment by frague59** [comment]
Thanks for your help !

Basically, I'm building a django-tables2 based list view...

I'ld like to display a search form on top of the page, then the table. I'dl like to use crispy to tune the search form display (form layout...), and use django-filter filtering. Finally, I'ld like to use some "special" widgets (select2 / bootstrap3_datetimepicker)

Using a search form to bind the widgets + crispy helper sounded like a good idea... 
I'm a bit confused about linking all those modules together...

**Comment by rpkilby** [comment]
If you're customizing a number of attributes on the filter, it might be simpler to declare the filters instead of relying on `Meta.fields` and overriding `__init__`. The above could be accomplished with:

```python
class ManifestationFilter(filters.FilterSet):
        title__icontains = filters.CharFilter(label="Custom title", widget=...)

    class Meta:
        model = models.Manifestation
        fields = {'other_field': ['lookups', ...]}
```

Any keyword arguments not used by the `Filter` are automatically passed to its form field's constructor.

----

> I'm a bit confused about linking all those modules together...

I'd recommend looking at the django-filter tag on stackoverflow. There have been some questions in the past, asking about integration with these various packages.
