### ISSUE TITLE
[Question] How override DjangoFilterBackend for JSONFields ?

### ISSUE THREAD

**Issue by sergiomb2** [carltongibson/django-filter#768]
Hello ,
I'm trying set filter for json parameters in very esay way , i.e., like all json is one text field . 
I got 
AssertionError: CiTypeFilter resolved field 'parameters' with 'exact' lookup to an unrecognized field type JSONField. 

but if in `class CiTypeFilter(filters.FilterSet):`  add    `parameters = django_filters.CharFilter(lookup_expr=['icontains']) ` it works as I want . 

Now what I want is setting all JSONField as django_filters.CharFilter(lookup_expr=['icontains']) , how I may do that ? 

Thanks

**Comment by rpkilby** [comment]
There are a few options: 
- Use the [`Meta.filter_overrides`](http://django-filter.readthedocs.io/en/develop/ref/filterset.html#filter-overrides) option.
- Subclass and modify the [`FILTER_DEFAULTS`](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/filterset.py#L164) attribute. [`rest_framework.FilterSet`](https://github.com/carltongibson/django-filter/blob/1.0.4/django_filters/rest_framework/filterset.py#L14-L22) is a good example.
- Subclass and override [`FilterSet.filter_for_lookup()`](https://django-filter.readthedocs.io/en/latest/ref/filterset.html#filter-for-lookup) to add handling for `JSONField`s.

**Comment by sergiomb2** [comment]
please exemplify , I already read documentation before made the question you mean : 

class CustonFilterSet(filterset.FilterSet):
FILTER_DEFAULTS= deepcopy(filterset.FILTER_FOR_DBFIELD_DEFAULTS)
FILTER_FOR_DBFIELD_DEFAULTS.update({
    models.JSONField: {'filter_class': something},  
})

where do I have "something"  ? I want modify for all django project not for one model only , that I already done .

**Comment by rpkilby** [comment]
[`Meta.filter_overrides`](http://django-filter.readthedocs.io/en/develop/ref/filterset.html#customise-filter-generation-with-filter-overrides) is simply copied over `FILTER_DEFAULTS` and shares the same format. In your example, you wanted to map JSONFields to a `CharFilter` with an `icontains` lookup. 

```python
class CustonFilterSet(filters.FilterSet):
    FILTER_DEFAULTS= deepcopy(filterset.FILTER_FOR_DBFIELD_DEFAULTS)
    FILTER_FOR_DBFIELD_DEFAULTS.update({
        models.JSONField: {
            'filter_class': filters.CharFilter,
            'extra': lambda f: {'lookup_expr': 'icontains'},
        },
    })
```

**Comment by sergiomb2** [comment]
icontains is under a list to work ! here is my snippet 
Thanks a lot.

```
from copy import deepcopy
from rest_framework import filters
from django_filters import filterset
from django_filters.rest_framework import DjangoFilterBackend
from django_filters.rest_framework.filters import CharFilter
from .models import JSONField

class CustomFilterSet(filters.FilterSet):
    FILTER_DEFAULTS = deepcopy(filterset.FILTER_FOR_DBFIELD_DEFAULTS)
    FILTER_DEFAULTS.update({
        JSONField: {
            'filter_class': CharFilter,
            'extra': lambda f: {'lookup_expr': ['icontains']},
        },
    })

class CustomDjangoFilterBackend(DjangoFilterBackend):
    default_filter_set = CustomFilterSet
```
