### ISSUE TITLE
Missing import django_filters in docs code snippet

### ISSUE THREAD

**Issue by kjschiroo** [carltongibson/django-filter#772]
In [Adding a FilterSet with filter class](https://django-filter.readthedocs.io/en/develop/guide/rest_framework.html#adding-a-filterset-with-filter-class) the code snippet appears to be missing an `import django_filters`

**Comment by carltongibson** [comment]
Hi. 

I think you made the PR against your own repo. Oops. 

More though, I don’t think the import is missing.  It’s the line below the one you added.

**Comment by kjschiroo** [comment]
Yep, I screwed up the PR. I see it now, you aren't necessarily missing an import statement, but something does need to change. Exploring in the shell:
```
In [1]: from django_filters import rest_framework as filters

In [2]: min_price = django_filters.NumberFilter(name="price", lookup_expr='gte')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-d44ca3e674ce> in <module>()
----> 1 min_price = django_filters.NumberFilter(name="price", lookup_expr='gte')

NameError: name 'django_filters' is not defined

In [3]: min_price = filters.NumberFilter(name="price", lookup_expr='gte')
```
