### ISSUE TITLE
`filter_for_lookup` cannot be overriden

### ISSUE THREAD

**Issue by twidi** [carltongibson/django-filter#776]
Summary
------------
`filter_for_lookup`  is a class method, but is called in the metaclass, so when `super` is called, the class does not exist yet.

So, contrary to what is in the documentation, it's not "really" possible to override this method.

You'll find below different important library versions, the steps to reproduce the error, and a temporary workaround

Versions
--------
Python: 2.7.9
Django:1.11.4
django-filter: 1.0.4

Steps to reproduce:
-------------------

This is the simplest example. You can type it in a console and type "enter" at the end, the error will occur.

```python
from django.contrib.auth.models import User
from django_filters import FilterSet

class MyFilter(FilterSet):
    class Meta:
        model = User
        fields = ['username']

    @classmethod
    def filter_for_lookup(cls, f, lookup_type):
        return super(MyFilter, cls).filter_for_lookup(f, lookup_type)
```

This produces  directly, at the time the class is created, this error:

```python
NameError                                 Traceback (most recent call last)
/path/to/local-code
----> 1 class MyFilter(FilterSet):
      2     class Meta:
      3         model = User
      4         fields = ['gender']
      5 

/path/to/django_filters/filterset.pyc in __new__(cls, name, bases, attrs)
     84         new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
     85         new_class._meta = FilterSetOptions(getattr(new_class, 'Meta', None))
---> 86         new_class.base_filters = new_class.get_filters()
     87 
     88         return new_class

/path/to/django_filters/filterset.pyc in get_filters(cls)
    304 
    305                 if field is not None:
--> 306                     filters[filter_name] = cls.filter_for_field(field, field_name, lookup_expr)
    307 
    308         # filter out declared filters

/path/to/django_filters/filterset.pyc in filter_for_field(cls, f, name, lookup_expr)
    328         }
    329 
--> 330         filter_class, params = cls.filter_for_lookup(f, lookup_type)
    331         default.update(params)
    332 

/path/to/local-code in filter_for_lookup(cls, f, lookup_type)
      6     @classmethod
      7     def filter_for_lookup(cls, f, lookup_type):
----> 8         return super(MyFilter, cls).filter_for_lookup(f, lookup_type)
      9 

NameError: global name 'MyFilter' is not defined
```

Workaround
---------

The simplest workaround - but not a clean solution - is to not use `super()` but hard-code the `FilterSet` class (it will of course not work if the filter class inherits from many parents):

```python

    @classmethod
    def filter_for_lookup(cls, f, lookup_type):
        return FilterSet.filter_for_lookup(f, lookup_type)
```

**Comment by rpkilby** [comment]
Interestingly enough, `super(MyFilter, cls)` also fails in python 3.x, but the terser `super()` call *does* work.

My recommendation would be to upgrade to python 3 😉

**Comment by rpkilby** [comment]
For reference:
https://stackoverflow.com/questions/12757468/invoking-super-in-classmethod-called-from-metaclass-new

**Comment by rpkilby** [comment]
One possible workaround that would be python 2 and 3 compatible is to use an intermediate FilterSet. eg, 

```python
class Intermediate(django_filters.FilterSet):
    @classmethod
    def filter_for_lookup(cls, f, lookup_type):
       return super(Intermediate, cls).filter_for_lookup(f, lookup_type)

class MyFilter(Intermediate):
    class Meta:
        model = User
        fields = ['username']
```

**Comment by carltongibson** [comment]
I’m inclined towards “Use Python 3.6+ or do this ⬆️“ here

**Comment by rpkilby** [comment]
Basically, there are three options:
- `super()` w/ python3.6+
- Hardcoded class names in python < 3.6
- Use an intermediate class to define the class methods, which is compatible with all versions

**Comment by twidi** [comment]
The intermediate class is smart. Thanks for all the participation.
