### ISSUE TITLE
Proposal for lookups within several fields with OR 

### ISSUE THREAD

**Issue by nanopony** [carltongibson/django-filter#781]
**Example problem this proposal solves**: Order has relation to UserProfile; user would like to find every order made user, whose `first_name` or `last_name` contains "Xi"

**Solution proposal**: (right now I use this semantics via monkey-patching of `Filter` class)
```
user = django_filters.CharFilter(name=[
        'profile__last_name',
        'profile__first_name',
    ], label="User", lookup_expr = 'icontains')
```
I apologize in advance if similar proposals was made (search resulted in none), or if the semantic looks off; I really would love to have similar functionality in the django-filters and if there's a better semantics, I'd love to contribute making a PR implementing it;

P.S. thank you for this great project :)

**Comment by carltongibson** [comment]
This should be handled using the `method` parameter. You do your OR filtering in the custom method.
