### ISSUE TITLE
Apply filter to nested content in serialized data

### ISSUE THREAD

**Issue by OskarPersson** [carltongibson/django-filter#794]
Say I have a `Product` model that belong to a `Company`, now I want to filter the products and group the results by the company they belong to at `api/companies?product=foo`.

I have set up the following serializer and filter that will list all companies that have at least one product matching the filter, but this will also list **all other** products for each company. How do I apply the filter to the nested serialized data?

```
class CompanyFilter(django_filters.FilterSet):
    product = CharFilter(name="products__name")
    class Meta:
        model = Company
        fields = ['product']

class CompanySerializer(ModelSerializer):
     class Meta:
          model = Company
          fields = ('name', 'products')
```

**Comment by rpkilby** [comment]
This sounds very similar to #740. In short, you need to prefetch the related products based on the filter value. Ultimately, you're trying to construct the following:

```python
products = Product.objecs.filter(name='foo')

Company.objects \
    .filter(product__name='foo') \
    .prefetch_related(Prefetch('products', products))
```

The way to do this is to override the `FilterSet.qs` property and add in the prefetching. You would want to do something like the below. 

```python
class CompanyFilter(django_filters.FilterSet):
    product = CharFilter(name='products__name')
    class Meta:
        model = Company
        fields = ['product']

    def prefetch_products(self, qs):
        product = self.form.cleaned_data.get('product')
        if product:
            products = Product.objects.filter(name=product)
            qs = qs.prefetch_related(Prefetch('products', products))
        return qs

    @property
    def qs(self):
        already_prefetched = hasattr(self, '_qs')
        qs = super().qs

        if self.is_bound and not already_prefetched:
            self._qs = self.prefetch_products(self._qs)

        return self._qs
```

Note that overridding the .qs property is a little awkward, and should be improved in v2.0.

**Comment by OskarPersson** [comment]
That works great, thanks!

Now to find a way to do the same with the [SearchFilter](http://www.django-rest-framework.org/api-guide/filtering/#searchfilter) 🤔

**Comment by carltongibson** [comment]
@OskarPersson _SearchFilter_ — ` WHERE ... ILIKE ... ` (shudder) 

Use a proper search solution, Django's own, or Django Watson (which is great BTW) or...

Then wrap the actual filtering in a function and pass it to CharFilter (say) as the `method`. 

NTS: we should have some patterns for this in the docs at least.

**Comment by Philipp-M** [comment]
> Note that overridding the .qs property is a little awkward, and should be improved in v2.0.

Solution still works great, but as you said, is there now a different way to achieve this?

**Comment by rpkilby** [comment]
Yes. The issue with overriding `.qs` was that the method cached the result and performed a few additional checks. It was very easy to override this method in subtly incorrect ways. 

The filtering portion has since been moved to `filter_queryset`, which is much more straightforward method that just performs filtering. Your code would look something like:
```python
class MyFilterSet(FilterSet):
    def filter_queryset(self, queryset):
        queryset = super().filter_queryset(queryset)
        # perform additional filtering
        return queryset
```

Relevant code is here:

https://github.com/carltongibson/django-filter/blob/7c08deea132686f456df8a646a9c65654cee2712/django_filters/filterset.py#L215-L239
