### ISSUE TITLE
TypeError: get_filter_name() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by danielhers** [carltongibson/django-filter#798]
Using the new 1.1.0 release, I get this error.

See here: https://travis-ci.org/danielhers/UCCA-App/jobs/289970765

**Comment by carltongibson** [comment]
What's this?: 

```
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/rest_framework_filters/filterset.py", line 19, in __new__
    new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
```

I'd guess your issue is there. 

(I'm going to close this. Happy to re-open if there's actually a DF issue.)

**Comment by danielhers** [comment]
Thanks for your response.
So you're saying djangorestframework-filters (latest, 0.10.1) is not compatible with django-filter 1.1.0, because of [this line](https://github.com/philipn/django-rest-framework-filters/blob/master/rest_framework_filters/filterset.py#L19)?

**Comment by carltongibson** [comment]
I'm just looking at the stack trace. That's not my file, so I can't vouch for it. 


(Aside: you should put a bit more effort into your issue descriptions. It helps to review. It's not much fun having to click lots of links and work things out. Especially when it's your issue your looking for help on... 🙂)

**Comment by danielhers** [comment]
Fair enough. Apologies for the terseness and thanks for the help.
