### ISSUE TITLE
How about capturing variables from URLs?

### ISSUE THREAD

**Issue by cicuz** [carltongibson/django-filter#799]
Hello, a quick question:

has it ever been considered to add support for getting search parameters off URL variables?
It doesn't seem to be easily/readily possible now..

**Comment by carltongibson** [comment]
Does `filter.form.cleaned_data.keys()` give you what you want?

**Comment by carltongibson** [comment]
Or even just `request.GET.keys()`?

**Comment by cicuz** [comment]
I think I meant to ask if it exists a filter backend that can handle URL regex-variables, or if it is even possible to write one

**Comment by carltongibson** [comment]
I think you’re going to need to explain you use case more fully. I don’t really know what you’re asking, or trying to do. 

Can you explain what you’d do at the View layer without using Django Filter?  We can go from there.

**Comment by cicuz** [comment]
The view layer is essentially a verbatim ModelViewSet, and I was wondering if it was possible to set a filter_backend to automatically parse search_fields off of URL variables. I tried looking inside `mixins.py` and `filters.py`, but it seems that URL variables are used only for getting a specific object, not for search operations.

**Comment by rpkilby** [comment]
A simple approach would be to modify the `request.query_params` with the URL kwargs, as this is the data that's ultimately used to construct the FilterSet. eg, 

```python
class MyViewSet(..):
    def filter_queryset(self, queryset):
        data = self.request.query_params.copy()
        data.update(self.kwargs)
        self.request.query_params = data

        return super(MyViewSet, self).filter_queryset(queryset)
```

That said, I'd encourage you to restructure your URL to use query params instead of URL kwargs.

**Comment by carltongibson** [comment]
Ah, thanks @rpkilby, now I see what's meant. 

Say you filter by an `id` in the URL, and then further filter by query params, e.g. `?state=open`, or such. 


In that case, I'd put the `id` filtering in `get_queryset` or such. (It's already part of `get_object`, I suppose. But going with the example...) 

This splits the filtering, but the normal use is two-different kinds of restriction... — it's just a matter of style. 

@rpkilby is right: if you want to have the filter set do it, you just need to update the `QueryDict` that gets passed in.
