### ISSUE TITLE
v1.1 tag/release commit is incorrect

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#804]
It's the same as v1.0.4

**Comment by carltongibson** [comment]
Hmmm. 

I've got 1.1 at af6cff84a2ff3e09e94e4b8649cd06a417dd5228
and 1.0.4 at 7e949076a5dec69811d081fd78838999c8abf374

**Comment by carltongibson** [comment]
That seems to match here https://github.com/carltongibson/django-filter/releases

**Comment by rpkilby** [comment]
Oh whoops, I was simply looking at the "27 commits to develop since this release"

**Comment by rpkilby** [comment]
And then assumed that the commits were the same

**Comment by rpkilby** [comment]
Okay, so it looks like develop and master have diverged?

Instead of one release commit, there are two:

- af6cff84a2ff3e09e94e4b8649cd06a417dd5228
- 0148e576798f5142acb776e0915c722e84e40a69

**Comment by carltongibson** [comment]
Yeah. Probably. I'm just reviewing #788. Once that's merged I'm going to merge `develop` into `master` and delete the `develop` branch. Everything after that will happen on `master`.
