### ISSUE TITLE
Link to documentation does not work

### ISSUE THREAD

**Issue by eprikazc** [carltongibson/django-filter#806]
https://django-filter.readthedocs.io/en/develop/ says "SORRY This page does not exist yet"
![readthedocs-page-not-found](https://user-images.githubusercontent.com/161618/31935833-85ff7028-b8b8-11e7-8662-b474275b8ecd.png)

**Comment by rpkilby** [comment]
Yep - the branch structure just changed. It should be "master", not "develop"

**Comment by carltongibson** [comment]
@eprikazc Where did you get that link? (Ta)

**Comment by rpkilby** [comment]
The readme is has two links. One towards the top, and the DRF integration docs towards the bottom

**Comment by carltongibson** [comment]
OK, they're gone. No doubt there'll be more.
