### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by claytondaley** [carltongibson/django-filter#811]
The link found in the error text [here](https://github.com/carltongibson/django-filter/blob/9910ee11af8ab54bd788bcf97a20f3e5c02b92b4/django_filters/filterset.py#L331-L335) doesn't work for me.

Perhaps this is the new link:

http://django-filter.readthedocs.io/en/latest/guide/usage.html#overriding-default-filters

**Comment by carltongibson** [comment]
Works for me...
