### ISSUE TITLE
How to filter with forward relations?

### ISSUE THREAD

**Issue by daredevil82** [carltongibson/django-filter#814]
Lets say I have a model structure like:

```
class Record(models.Model):
    # some fields here

class Link(models.Model):
    record = models.ForeignKey(Record)

class Check(model.Model):
    link = models.ForeignKey(Link)
    comment = models.CharField(max_length = 300)
```

With `django-filter`, how can I filter on `Check.comment` with the `Filter` class implementation mapped to `Link`?  I can easily follow relations from `Link` back to `Record`, but not forward to `Check`.  Ideally, something like 

```
class LinkFilter(filters.FilterSet):
    message = filters.CharFilter(name = 'check__comment', lookup_expr = 'icontains')

     class Meta:
         model = Link
         fields = ('message', )
```

**Comment by rpkilby** [comment]
Hi @daredevil82 - the above looks like it should work. Does the following work?
```python
Link.objects.filter(check__comment__icontains='foo')
```

If so, then your filterset should also work.

**Comment by daredevil82** [comment]
Ack.  OK, the issue was I was making the request to the wrong API endpoint resource, without noticing.  Feel free to close, sorry for the brain fart.
