### ISSUE TITLE
Sorting? 

### ISSUE THREAD

**Issue by DDiran** [carltongibson/django-filter#822]
First of all, awesome work on this plugin, it's very well done.

I'm using it to filter products by attributes in my e-commerce website, which works great. What I'd like to do next is create a dropdown with various sort parameters (eg. By price highest to lowest, viceversa, by date added newest to oldest, viceversa, etc...).

I've scanned through the docs but haven't found anything that mentions this kind of thing. Do you know if it's supported? 

Thanks

**Comment by durdenk** [comment]
You checked below link?
http://django-filter.readthedocs.io/en/latest/ref/filters.html#orderingfilter

**Comment by DDiran** [comment]
Now how did I go ahead and miss something so glaringly obvious? It's exactly what I need!
Thanks!

**Comment by DDiran** [comment]
Now how did I go ahead and miss something so glaringly obvious? It's exactly what I need!
Thanks!
