### ISSUE TITLE
Request not being passed to FilterSet? --> 'NoneType' object has no attribute 'user'

### ISSUE THREAD

**Issue by pascal210** [carltongibson/django-filter#825]
I'm trying to filter the primary .qs (with the current version of django-filter) basically like in the [docs](https://django-filter.readthedocs.io/en/master/guide/usage.html#filtering-the-primary-qs). My filter class:

    class RequirementFilter(django_filters.FilterSet):
        tag = django_filters.ModelMultipleChoiceFilter(queryset=Tag.objects.all())
        requirement_fullText = django_filters.CharFilter(lookup_expr='icontains') 

        @property
        def qs(self):
            parent = super(RequirementFilter, self).qs
            print(getattr(self.request, 'user'))

            return parent.exclude(requirement_isPlaceholder=True)

        o = django_filters.OrderingFilter(
            fields=(
                ('requirement_creationDate', 'requirement_creationDate'),
                ('requirement_votes', 'requirement_votes'),
            ),
            field_labels={
                'requirement_creationDate': 'Datum',
                'requirement_votes': 'Stimmen',
            },
        )
        class Meta:
            model = Requirement
            fields = ['requirement_software', 'requirement_author', "requirement_roadmap_timescale"]

        def __init__(self, *args, **kwargs):
            super(RequirementFilter, self).__init__(*args, **kwargs)
            self.filters['requirement_software'].extra.update(
                {'empty_label': 'Alle Anwendungen'})
            self.filters['requirement_author'].extra.update(
                {'empty_label': 'Alle Autoren'})
            self.filters['o'].extra.update(
                {'empty_label': 'Sortierung'})
            self.filters['requirement_roadmap_timescale'].extra.update(
                {'empty_label': 'Alle Stati'})
            print('Request on init: ', self.request)

The error gets thrown for `print(getattr(self.request, 'user'))`. If I comment this out and leave the `print('Request on init: ', self.request)`, it prints None for the request object.
My view looks as follows:

```
@login_required
def index(request):
	f = RequirementFilter(request.GET)
	context = {
		'requirement_filter': f,
	}
	return render(request, 'req/index.html', context)
```
Any idea what's going wrong here? I can't see the reason the request doesn't reach the FilterSet

**Comment by carltongibson** [comment]
http://django-filter.readthedocs.io/en/latest/guide/usage.html

**Comment by pascal210** [comment]
I have indeed looked at the docs (I also linked them in my post) and set my project up in the same way. However, I still receive the above described error message which is the reason I opened this issue.

**Comment by carltongibson** [comment]
> The FilterSet may be initialized with an optional request argument. If a request object is passed, then you may access the request during filtering.

**Comment by pascal210** [comment]
Isn't that what I'm doing by initializing the Filterset with XyzFilter(request.GET)?

**Comment by carltongibson** [comment]
```
XyzFilter(request.GET, request=request)
```
