### ISSUE TITLE
Getting Django-Filter and Ajax to work together

### ISSUE THREAD

**Issue by DDiran** [carltongibson/django-filter#826]
I have got `django-filter` set up and working as intended on my e-commerce website with a few filters, such filter product by colour (`<input type="checkbox">`) and sort by price (`<select>`). The user chooses and then hits "Submit" to submit the form. 

What I would like to do is make it so that as soon as the user checks the box or selects an option from the dropdown, the products are automatically filtered, without having to hit the "submit" button, which I would like to get rid of.

I'm fairly certain that AJAX is what is needed to achieve this - however looking through the web most tutorials deal with POST forms, not GET. Plus, the actual queryset/filtering logic is handled by `django-filter` and not myself in the views/urls.

Is this functionality supported? If so how would I get it to work exactly? Is there anything in the docs that I missed?

**Comment by carltongibson** [comment]
You'd need to create an API endpoint to return your filtered results and call that from your JavaScript, then updating the available options. 

Whilst django filter would be perfect for the backend filtering part, the rest of it is nothing to do with backend stuff — it's all in the frontend. You'll need to work it out yourself I'm afraid.
