### ISSUE TITLE
Display ManyToMany as checkboxes + customize layout

### ISSUE THREAD

**Issue by ppo** [carltongibson/django-filter#834]
Hi,

What's the easiest way to display a ManyToManyField as checkboxes?
And I want to customize the layout of the checkboxes (either as multi-column list, or the first 10 items with a "more" link, or only the selected ones with a link "more").

Thanks in advance.

**Comment by carltongibson** [comment]
Check the Django docs on [Selector and Checkbox widgets](https://docs.djangoproject.com/en/1.11/ref/forms/widgets/#selector-and-checkbox-widgets). 

Beyond that I'm afraid I can't really offer support on the issue tracker. Good luck.
