### ISSUE TITLE
Submit button in DRF api view

### ISSUE THREAD

**Issue by frague59** [carltongibson/django-filter#845]
Hi, 

First of all, thanks for your great job on data filtering with django !

```
Django (1.11.8)
django-filter (1.1.0)
django-rest-framework  (3.7.3)
django-crispy-forms (1.7.0)
```

I'm using the combo DRF + crispy + django-filter, and I'm using the api (HTML) default view of data.

I'm using the documented method from both DRF and django-filter to implement the data filtering.

For testing / debugging purpose, I do try to filter the data but I do not have a "Submit" button on the displayed form in the API  view.

This bug has been previously reported on DRF (https://github.com/encode/django-rest-framework/issues/3636), and was fixed on it (I think so). While DRF does not support its own filtering backend anymore, the bug is still present in django-filter.

Is there a workarround or a fix about this issue ? Thanks !

**Comment by rpkilby** [comment]
Hi @frague59 Are you importing the correct FilterSet? You should be using:

```python
from django_filters.rest_framework import FilterSet
```

not 

```python
from django_filters import FilterSet
```

**Comment by frague59** [comment]
Arg ! Y've got it ! Thanks !
