### ISSUE TITLE
Boolean fields render at initial

### ISSUE THREAD

**Issue by polrodoreda** [carltongibson/django-filter#848]
I've added some boolean fields to my django filter application. When I access for the first time to the page, the results are rendered using this boolean values, but I've never submited filter form.

```python
class SearchFilter(django_filters.FilterSet):
   class Meta:
        model = Property
        fields = ['lift',]
        filter_overrides = {
            models.BooleanField: {
                'filter_class': django_filters.BooleanFilter,
                'extra': lambda f: {
                    'widget': forms.CheckboxInput,
                },
            },
        }
```

Can I avoid this and show all results before submitting the form?

**Comment by rpkilby** [comment]
I think this can be closed, as this is a usage question. Corresponding question on SO from author: https://stackoverflow.com/questions/47994336/django-filter-boolean-fields
