### ISSUE TITLE
Improve filter naming consistency

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#853]
I'd like to suggest a few naming changes for 2.0:

| Current | 2.0 |
| :--- | :--- |
| `DateTimeFromToRangeFilter` | `DateTimeRangeFilter` |
| `DateFromToRangeFilter` | `DateRangeFilter` |
| `DateRangeFilter` | `DateRangeChoiceFilter` |
| `AllValuesFilter` | `FieldValuesChoiceFilter` |
| `AllValuesMultipleFilter` | `FieldValuesMultipleChoiceFilter` |

On the one hand, I'd argue these names are a little more consistent. On the other, IDK if it's worth the hassle to the community. 

Most of these naming changes would be relatively straightforward (create class alias that raises a deprecation warning), however  `DateRangeFilter` and `DateFromToRangeFilter` can't work automatically, given that the former is replaced by the latter. We could add some kind of temporary flag to suppress the warning, but ech. 

Thoughts?

**Comment by garynobles** [comment]
Related to this pip install django_filter and 'django_filters', in the settings.py makes things confusing, pural or not, but not both. I suggest renaming the package django_filters?

**Comment by rpkilby** [comment]
The [`django-filters`](https://pypi.org/project/django-filters/) package name is already claimed.

**Comment by carltongibson** [comment]
Fixed by #867

**Comment by carltongibson** [comment]
Oh no it wasn't. 

Can't really see the benefit of this one.
