### ISSUE TITLE
Adding custom form to filter gives error: is_valid() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by wroscoe** [carltongibson/django-filter#858]
I'm trying to customize the filter form so I can add a datepicker. When I try to add the form as suggested in the documentation I'm getting an error. Here is what I'm doing:

```python
class FlightListForm(ModelForm):
    min_date = DateField(label='Flight Date (min)', required=False)
    min_date.widget.attrs['class'] = 'datepicker'

    max_date = DateField(label='Flight Date (max)', required=False)
    max_date.widget.attrs['class'] = 'datepicker'

    class Meta:
        model = models.Flight
        fields = ['min_date', 'max_date']

class FlightFilter(django_filters.FilterSet):

    min_date = django_filters.DateTimeFilter(name="date", lookup_expr='gte')
    max_date = django_filters.DateTimeFilter(name="date", lookup_expr='lte')
    form = FlightListForm

    class Meta():
        model = models.Flight
        fields = ['min_date', 'max_date']
```

When I use the filter I'm doing..
```python
f = FlightFilter(request.GET, qs)
render(request, 'web/flight_list.html', filter=f )
```

Here is the error trace...
```python
Traceback (most recent call last):
  File "/home/wroscoe/miniconda3/envs/works/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wroscoe/miniconda3/envs/works/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wroscoe/miniconda3/envs/works/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wroscoe/code/works/web/views.py", line 492, in flight_list
    flights_df = prepare_table(f.qs, columns, links)
  File "/home/wroscoe/miniconda3/envs/works/lib/python3.5/site-packages/django_filters/filterset.py", line 206, in qs
    if not self.form.is_valid():
TypeError: is_valid() missing 1 required positional argument: 'self'

```

**Comment by wroscoe** [comment]
Ok. I figured this out and its as decribed in docs. I just needed an example to understand. Here's what worked.

```python
class FlightFilter(FilterSet):
    min_date = DateTimeFilter(name="date", lookup_expr='gte')
    max_date = DateTimeFilter(name="date", lookup_expr='lte')

    class Meta(web.forms.FlightListForm):
        model = Flight
        fields = ['min_date', 'max_date']
```

**Comment by wroscoe** [comment]
I was wrong. The above did not work. but I can add the datepicker options by doing...

```python
class FlightFilter(FilterSet):
    min_date = DateTimeFilter(name="date", lookup_expr='gte')
    max_date = DateTimeFilter(name="date", lookup_expr='lte')

    def __init__(self, *args,**kwargs):
        super (FlightFilter,self ).__init__(*args,**kwargs) # populates the post
        self.form.fields['min_date'].widget.attrs['class'] = 'datepicker'
        self.form.fields['max_date'].widget.attrs['class'] = 'datepicker'

    class Meta():
        model = Flight
        fields = ['min_date', 'max_date']
```

I'd still like to inherit an existing form.

**Comment by rpkilby** [comment]
Hi @wroscoe. If you want to override the form class, you need to place this in the inner `Meta` class. eg,

```python
class MyFilterset(...):
    class Meta:
        form = MyForm
```

**Comment by wroscoe** [comment]
Thanks for the response but this doesn't work for me. No errors are thrown but the form I give is not used. The input labels are the filter defaults not the ones I used on the form and the datepicker widget is not used. Here's what I'm trying..

```python
class FlightListForm(ModelForm):
    min_date = DateField(label='Flight Date (min)', required=False)
    min_date.widget.attrs['class'] = 'datepicker'
    max_date = DateField(label='Flight Date (max)', required=False)
    max_date.widget.attrs['class'] = 'datepicker'

    class Meta:
        model = models.Flight
        fields = ['min_date', 'max_date']

class FlightFilter(django_filters.FilterSet):
    min_date = django_filters.DateTimeFilter(name="date", lookup_expr='gte')
    max_date = django_filters.DateTimeFilter(name="date", lookup_expr='lte')

    class Meta:
        form = FlightListForm
        model = models.Flight
        fields = ['min_date', 'max_date']
```

Any thoughts?

**Comment by carltongibson** [comment]
https://github.com/carltongibson/django-filter/blob/a88c2bc98d28686b3b0f2ba5ae9528f38c8bb5a6/django_filters/filterset.py#L195-L217

I guess your fields are getting overridden. If you form is fully configured override `get_form_class` to return it directly, rather than using it as a base class.

**Comment by wroscoe** [comment]
Thanks, I've been digging into the repo code a bit but still I can't figure out how to get the attributes from both the custom form and the filter. I can get either the form fields to work or the filter fields. An example in the docs would really help show what's possible and not. 

My solution was to just use the form outside of the filter and keep the field names the same. 

Thanks.

**Comment by rpkilby** [comment]
If you're looking to customize the fields, there are two avenues:

- Modify the form fields in the form's `__init__`.
- Pass the field arguments to the filter. Unrecognized arguments are stored as an `extra` dict on the filter class, which are then used to [construct the underlying form field](https://github.com/carltongibson/django-filter/blob/1.1.0/django_filters/filters.py#L199). eg, 
    ```python
    class FlightFilter(django_filters.FilterSet):
        min_date = django_filters.DateTimeFilter(
            name='date', lookup_expr='gte',
            widget=forms.DateInput(attrs={'class': 'datepicker'}),
        )
    ```

Alternatively, you could override the form `__init__` and automatically update the class for all `DateField`s.

----

> An example in the docs would really help show what's possible and not.

I've added to my list docs TODOs. In general, overhauling the docs is on the list for 2.0

**Comment by diogosimao** [comment]
I followed @rpkilby instructions and I could get everything to work including `'type': 'date'` in `attrs` and then it showed the `datepicker`.

**Comment by ivarandre** [comment]
If you comment out 

model = models.Flight

it works fine.
