### ISSUE TITLE
TypeError: Object of type 'Decimal' is not JSON serializable

### ISSUE THREAD

**Issue by alexanderoskin** [carltongibson/django-filter#868]
We have a field with JSON (PostgeSQL JSONB) where product prices are specified:
{"total": 2400000, "currency": "USD", "per_meter": 3404}

When we try to filter this field with NumberFilter we've got error:
TypeError: Object of type 'Decimal' is not JSON serializable

https://sentry.io/share/issue/43b4eb682bf64562961f12f60b05f9f6/

django 2.0.1
django-filters 1.1.0
rest_framework 3.7.7

**Comment by rpkilby** [comment]
@alexanderoskin - looking at the traceback, django-filter doesn't seem to even be called?

**Comment by alexanderoskin** [comment]
@rpkilby It seems. But why I've posted the issue here. After a few experiments we have the following results:

We have JSONB field in PostgreSQL
`{"total": 2400000, "currency": "USD", "per_meter": 3404}`

###**First variant of filter class**
`
class FlatsFilter(filters.FilterSet):
    price = filters.CharFilter(name="sale__price_rub__total")

    class Meta:
        model = Properties
        fields = [
            'id',
            'place__name'
        ]
`
**As a result no filtering results and no errors.**

###**Second variant of filter class**
`
class FlatsFilter(filters.FilterSet):
    price = filters.NumberFilter(name="sale__price_rub__total")

    class Meta:
        model = Properties
        fields = [
            'id',
            'place__name'
        ]
`
**As a result error "TypeError: Object of type 'Decimal' is not JSON serializable"**

### **Third variant of filter class**
`
class FlatsFilter(filters.FilterSet):
    price = filters.NumberFilter(name="sale__price_rub__total", method='correct_price')

    def correct_price(self, queryset, name, value):
        value = int(value)
        return queryset.filter(**{name: value})

    class Meta:
        model = Properties
        fields = [
            'id',
            'place__name'
        ]
`
**As a result no errors and correct filtering result. Everything is fine.**

But it seems to be error because if we make this field not JSONB, simply integer field with on value, everything will work with simple:
`price = filters.NumberFilter(name="sale__price_rub")`

**Comment by alexanderoskin** [comment]
If we use filtering in query set in a view class everything is fine too. But if you use filtering with FilterSet subclass we got this error.

**Comment by rpkilby** [comment]
That makes sense now. `NumberFilter` validates decimal objects, which is incompatible with the jsonb field. django-filter doesn't have separate filters for integer and float types, but they're simple to create. Just do this instead:


```python
class IntegerFilter(filters.Filter):
    field_class = forms.IntegerField


class FlatsFilter(filters.FilterSet):
    price = filters.IntegerField(name='sale__price_rub__total')

    class Meta:
        model = Properties
        fields = [
            'id',
            'place__name'
        ]
```

**Comment by alexanderoskin** [comment]
@rpkilby it doesn't work. Error 'AttributeError: module 'django_filters.rest_framework' has no attribute 'IntegerField'.

Imports
```
from django_filters import rest_framework as filters
from django import forms
```

**Comment by rpkilby** [comment]
@alexanderoskin - did the updated example work for you?

**Comment by alexanderoskin** [comment]
@rpkilby - yes, it helped us. But now we are trying to use OrderingFilter with values in JSONB fields and unfortunately we have problems.

**Comment by rpkilby** [comment]
@alexanderoskin - the ORM does not support arbitrary transforms into the JSONField, if that's what you're trying to do. This is [addressed in Django 2.1](https://code.djangoproject.com/ticket/24747), but for now you will need to do [something like this](https://stackoverflow.com/questions/36641759/django-1-9-jsonfield-order-by) and override [`get_ordering_value`](https://github.com/carltongibson/django-filter/blob/a88c2bc98d28686b3b0f2ba5ae9528f38c8bb5a6/django_filters/filters.py#L612-L617).

**Comment by eriktelepovsky** [comment]
It would be great if we could override ``field_class`` of the filter field like this:

```Python
price = filters.Filter(name='sale__price_rub__total', field_class=forms.IntegerField)
```

**Comment by carltongibson** [comment]
JSONField takes an encoder: https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/fields/#jsonfield

Other than that this isn't something we're going to address.
