### ISSUE TITLE
Change default choices for BooleanFilter through settings

### ISSUE THREAD

**Issue by emihir0** [carltongibson/django-filter#871]
Currently the `choices` is set to

```
choices = (
    ('1', ugettext_lazy('Unknown')),
    ('2', ugettext_lazy('Yes')),
    ('3', ugettext_lazy('No')),
 )
```
On `BooleanFilter` where the `Unknown` seems very counter-intuitive. Better choice description would be `All` or `Off`. Is it possible to change this globally (through settings)? I know I can simply set it through `choices=(...)` in a custom filter, but that would be quite a lot of redundant work as it would have to be changed in all `ModelFilterSet`s.

**Comment by carltongibson** [comment]
No. Not a setting. Subclass the filter is you need to.
