### ISSUE TITLE
Time Zone warning when filtering on the "past 7 days"

### ISSUE THREAD

**Issue by ukrutt** [carltongibson/django-filter#873]
When requesting data that's filtered on a "Date range" of "last week", I get a warning in the Django console:

    .../.venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1393:
    RuntimeWarning: DateTimeField Asset.date_added received a naive datetime
    (2018-02-08 00:00:00) while time zone support is active.

The reason is that the `_truncate` function removes time zone info.  I am about to open a Pull Request with code that fixes this.

**Comment by carltongibson** [comment]
Hi @ukrutt. Thanks for the report. 

Currently `DateRangeFilter` only really works with `DateField`s. `_truncate` is meant to return a `date`. When that gets converted to a `datetime` you're not going to have `tzinfo`. 

Your change in #874 has `_truncate` return a `datetime`, which is leading to the failure in the filtering for the object create `today` in the week filtering test. (_Exactly_ why that's not giving the right result would be interesting: what's the zero-hour datetime getting converted back to a date as? — but I haven't had a  chance to look at that.) 

There shouldn't be any reason this should work both ways. (Django's ChangeList manages it I think.) So I'd be very happy to look a PR solving the issues here.

**Comment by carltongibson** [comment]
DateRangeFilter was reworked in #852. Happy to review if still an issue (perhaps with a test case demonstrating). But closing otherwise
