### ISSUE TITLE
Is there any way around defining one filterset per model?

### ISSUE THREAD

**Issue by hmpf** [carltongibson/django-filter#876]
I have an abstract model in an all drf site, with two fields that will be filtered on in *all* concrete models, so far 12, and that number is set to rise. One is a char-field, which works fine. The other is an iso datetime with zulu timezone (last_fetched), and I need a gt or gte lookup on the latter, it's so that clients need only fetch fresh data.

What I've been doing is I have a mixin that defines `filter_fields` to lookup the char field. The mixin is inherited by the drf `ViewSet`s and can be overridden there (some concrete children add fields).

Obviously, adding 'last_fetched' to the mixin's `filter_fields` gives an exact match. 'last_fetched__gt' and similar does not work. A FilterSet with Meta.model set to the abstract class does not work.

Will I have to define a new FilterSet class for every single concrete class or am I overlooking something?

**Comment by rpkilby** [comment]
Hi @hmpf `filter_fields` is used to create the `FilterSet`'s `Meta.fields` and shares the same API. If you want to use lookups, you'll need to use the `dict` syntax. eg, 

```
class MyView(...):
    filter_fields = {
        'charfield': ['exact'],
        'datetimefield': ['gt'],
    }
```

The `Meta.fields` list syntax only supports a list of field names, not field names + lookups/transforms

**Comment by hmpf** [comment]
Ooh. I'll test, and then I think there'll be a documentation patch incoming. With what's spread around in drf, here and drf-filters, finding the info needed can be tricky.
