### ISSUE TITLE
RangeField not passing kwargs to child fields

### ISSUE THREAD

**Issue by lukka5** [carltongibson/django-filter#878]
I wan't to pass some args to the underlying form fields. When I pass them using `DateFilter` they work but they don't when using anything that subclass `RangeFilter` (i.e. `DateFromToRangeFilter`).

    # Works
    initial_date = DateFilter(input_formats=['%d/%m/%Y'])

    # Doesn't work
    range_date = DateFromToRangeFilter(input_formats=['%d/%m/%Y'])

    # django_filters/fields.py
    class DateRangeField(RangeField):
        def __init__(self, *args, **kwargs):
            fields = (
                forms.DateField(),  # <- Shouldn't this be forms.DateField(**kwargs) ?
                forms.DateField())  # <- Shouldn't this be forms.DateField(**kwargs) ?
            super(DateRangeField, self).__init__(fields, *args, **kwargs)

Another thoughts. Seems a little hard coded the use of specific fields. Just in case someone wanted to use it's own fields on i.e. a `DateFromToRangeFilter` I think it would be a little difficult. You can't pass a `fields` argument. Maybe something like:

    # django_filters/fields.py
    class DateRangeField(RangeField):
        def __init__(self, fields=None, *args, **kwargs):
            if fields is None:
                fields = (
                    forms.DateField(**kwargs),
                    forms.DateField(**kwargs))
            super(DateRangeField, self).__init__(fields, *args, **kwargs)

P.D.:  Great library!

**Comment by carltongibson** [comment]
I'd happily see a PR exploring this (with tests etc). Yes, to adding flexibility is someone wants to contribute it. (Probably No otherwise.)
