### ISSUE TITLE
Refactor BaseCSVWidget and BaseCSVField

### ISSUE THREAD

**Issue by skarzi** [carltongibson/django-filter#888]
I have some ideas that can probably improve the `django_filter`:

+ add information to `BaseCSVField` docs that value validation is performed
  only by secondary classes that are subclasses of `django.forms.Field`.
  Add tests for scenario when secondary classes do not inherit from `django.forms.Field`.
+ add possibility to `BaseCSVWidget` to set any split delimiter.
+ add possibility to use `request.POST` or `request.data` (DRF) as `FilterSet` input data.

I am eager to contribute to the project, hence even if my ideas are somehow bad,
I can fix some issues and add or refactor the features suggested by authors and
maintainers.

**Comment by carltongibson** [comment]
Happy to review PRs. This isn't really addressable as is.
