### ISSUE TITLE
Filter on model property?

### ISSUE THREAD

**Issue by lggwettmann** [carltongibson/django-filter#889]
Is it possible to filter on model properties? If so, how? 

I know that the filter method of query sets works on the database level, but would be nice to still have that function available via a workaround if needed.

**Comment by carltongibson** [comment]
> Is it possible to filter on model properties?

Not really, no. Each step in the a FilterSet needs to adjust the passed QuerySet in some way. This only really works with QuerySet methods, so unless your property reduced to those you won't be able to use it. 

You could wrap `qs` to perform the in-memory filtering as a last step before returning the result.

This is out of scope for Django Filter.
