### ISSUE TITLE
No default Result on Display

### ISSUE THREAD

**Issue by bobozar** [carltongibson/django-filter#895]
Awesome package!

I don't want all data saved in the database to output in the template on first load or when the user is yet to carry out a search function.  

I want to show results in template only when a user carry out a search function.

```
def search_advance(request):
    profile_list = Profile.objects.all()
    profile_filter = ProfileFilter(request.GET, queryset=profile_list)
    return render(request, 'ad_search.html',{'filter':profile_filter})
```

```
 <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  
  {% if filter %}
  {% for prov in filter.qs %}
    <li>{{ prov.user.username }} - {{ prov.user.get_full_name }}</li>
  {% endfor %}
  </ul>
  {% endif %}  
```

What am I missing?

**Comment by carltongibson** [comment]
This is a usage question rather than an issue... StackOverflow is the best place for that kind of thing. 

You'll need to do something like see if `request.GET` is empty or not. If it's empty do something other than iterate `filter.qs` (i.e. skip it.)

**Comment by bukowa** [comment]
@carltongibson isusing strict = True on View a correct approach? no idea what does this option...

**Comment by bukowa** [comment]
@bobozar this does the trick for me
````python
from django.http import QueryDict
import django_filters

class AdFilterSet(django_filters.FilterSet):
    def __init__(self, *args, **kwargs):
        if kwargs.get('data') is None:
            kwargs['data'] = QueryDict()
        super(AdFilterSet, self).__init__(*args, **kwargs)
````
