### ISSUE TITLE
BaseRangeFilter documentation error ?

### ISSUE THREAD

**Issue by lucas-bremond** [carltongibson/django-filter#896]
Hi there, what an amazing library!

In the documentation (https://django-filter.readthedocs.io/en/1.1.0/ref/filters.html#baserangefilter), there is a great example explaining how to use `BaseRangeFilter`.

However, there may be a small typo.

Shouldn't:

```py
class NumberRangeFilter(BaseInFilter, NumberFilter):
    pass
...
```

be:

```py
class NumberRangeFilter(BaseRangeFilter, NumberFilter):
    pass
...
```

?

Since we're expecting a `range` filter, using `BaseInFilter` would only return items in the list, not between two values.

Best!

**Comment by rpkilby** [comment]
It is indeed a typo
