### ISSUE TITLE
Help request: remove BLANK_CHOICE_DASH from Select widget.

### ISSUE THREAD

**Issue by katsika** [carltongibson/django-filter#899]
Hi,

not really an issue with django-filter, just thought I might ask for help here as I couldn't figure out how to remove BLANK_CHOICE_DASHes from my Select widget within OrderingFilter.

I have:

```
o = django_filters.OrderingFilter(
    fields=(
        ('date', 'date'),
        ('field__name', 'field'),
    ),
    field_labels={
        '-date': 'Latest',
        'date': 'Oldest',
        'field__name': 'A-Z',
        '-field': 'Z-A',

    },
)
```
also in my `get_queryset():` I do `.order_by('-date')`, so I would like to get widget to show `Latest` in  as default option, even if no `?o=…` is present in GET. Instead, now, it shows dashes `---------`.

This is what it looks like:
<img width="142" alt="select" src="https://user-images.githubusercontent.com/796021/39482658-32bc9cea-4d70-11e8-844a-de494a4a0923.png">

Is it possible to remove those dashes and put `Latest` as default option?

(I would also like to change ordering between Oldest and Latest on the drop down menu.

Thanks a lot!

**Comment by rpkilby** [comment]
Hi @katsika.

> I couldn't figure out how to remove BLANK_CHOICE_DASHes from my Select widget

 `OrderingFilter` inherits from `ChoiceFilter` ([docs](https://django-filter.readthedocs.io/en/master/ref/filters.html#choicefilter)), and you can pass `empty_label=None` to disable the empty choice. 

> (I would also like to change ordering between Oldest and Latest on the drop down menu.

By default, fields are sorted by ascending then descending. If you want more explicit control of how fields are presented, you can provide the choices to `OrderingFilter`. eg, 

```python
o = django_filters.OrderingFilter(
    empty_label=None,
    choices=[
        ('-date', 'Latest'),
        ('date', 'Oldest'),
        ('field__name', 'A-Z'),
        ('-field__name', 'Z-A'),
    ],
)
```

**Comment by katsika** [comment]
Thank you! `empty_label` was such a simple solution! Works perfectly.

As for `choices`, I had them set up instead of `fields`, but couldn't figure out how to map them to `field_labels`. With just `choices` I get `?o=field__name` which exposes structure of database. I would like to avoid it.

Is it possible to have such mapping that `field__name` will be presented in URL as `?o=field`, but in Select widget it will appear as `A-Z`, for example?

Once again, thanks!

**Comment by rpkilby** [comment]
I don't remember entirely, but you *should* be able to use `choices` with `fields` to get the desired effect. 

```python
o = django_filters.OrderingFilter(
    empty_label=None,
    choices=[
        ('-date', 'Latest'),
        ('date', 'Oldest'),
        ('param', 'A-Z'),
        ('-param', 'Z-A'),
    ],
    fields={
        'field_name': 'param', 
    }
)
```

**Comment by katsika** [comment]
Perfect, thought they were mutually exclusive. Got the very result I wanted with:

```
o = django_filters.OrderingFilter(
    empty_label=None,
    fields=(
        ('date', 'date'),
        ('field__name', 'field'),
        …,
    ),
    choices=[
        ('-date', 'Latest'),
        ('date', 'Oldest'),
        ('field', 'A-Z'),
        ('-field', 'Z-A'),
        …,
    ],
)
```

Thank you very much for your help on this one!
