### ISSUE TITLE
[DRF] filter_fields ignored with filter_class

### ISSUE THREAD

**Issue by gthieleb** [carltongibson/django-filter#905]
filterset.py:
```
class MiddlewareSpecBaseFilter(FilterSet):
    middleware = filters.CharFilter(label='Middleware', name='middlewarespecification__middleware__name')
    stage = filters.CharFilter(label='Stage', name='middlewarespecification__stage__stage')
    service_level = filters.CharFilter(label='Service Level', name='middlewarespecification__service_level__name')
    tshirt_size = filters.CharFilter(label='Tshirt Size', name='middlewarespecification__tshirt_size__size')


class StageFilter(MiddlewareSpecBaseFilter):

    class Meta:
        model = Stage
        exclude = ('stage',)
```
viewsets.py:
```
class StageViewSet(viewsets.ModelViewSet):
    queryset = Stage.objects.all()
    serializer_class = StageSerializer
    filter_class = StageFilter
    filter_fields = ('middleware',
                     'service_level',
                     'tshirt_size')
```

The exptected result:  filterable fields: `middleware`, `service_level`, `tshirt_size`
The current result: additionally also `stage` is a filterable field. 

`filter_fields` should be obsolete as I already use the `StageFilter._meta.exclude`. Both seems to not work.

**Comment by gthieleb** [comment]
![drf-filtering-2018-05-12](https://user-images.githubusercontent.com/21332468/39958975-15e029cc-560b-11e8-8ff0-0ee1c0c3dae0.png)

**Comment by rpkilby** [comment]
Hi @gthieleb. `filter_class` and `filter_fields` are not intended to be used together. If you're using `filter_class` you should provide the fields to `Meta.fields` directly. eg, `StageFilter` should look like:

```python
class StageFilter(MiddlewareSpecBaseFilter):

    class Meta:
        model = Stage
        fields = ['middleware', 'service_level', 'tshirt_size']
```

That said, the docs and the backend should probably warn the user that the attributes should not be used together.
