### ISSUE TITLE
Allow 'default' behaviour in FilterSet for annotated fields

### ISSUE THREAD

**Issue by Lyalpha** [carltongibson/django-filter#909]
This may be more of a use-case question than issue.

Is it possible to have a FilterSet class automatically handle the default behaviour (widget creation, data handling etc.) for annotated fields? I see this is related to #393, which looks like the ideal scenario. I am able to implement my own custom filters within my `FilterSet` class, however in the `method` I find I am having to deal with converting the `value` and handling exceptions etc.

e.g. I have annotated values of an `Object` model that are derived from a reverse lookup to `Observation` and using the latest one. The annotations are in the `get_queryset` of my view.

```
class MyView(FilterView):
    ...
    model = Object
    filterset_class = ObjectFilter
    def get_queryset(self):
        p = Observation.objects.filter(size_limit=False,
                                      candidate_id=OuterRef("pk"))\
                              .order_by("-obs_date")
        qs = qs.annotate(latest_obs_size=Subquery(p.values("obs_size")[:1]))
        return qs
```

Then in `ObjectFilter` I have a number of filters using fields of `Object` that work fine and handle value conversions, errors etc. on the webpage. I can add a filter for the annotated `latest_obs_size` field but this will not handle errors, and I need to handle conversions etc. for more complicated data types (e.g. dates)

```
class ObjectFilter(FilterSet):
    latest_obs_date = RangeFilter(label="latest observed size is in range",
                                                     lookup_expr="range",
                                                     method="filter_latest_obs_size")

    def filter_latest_size(self, queryset, name, value):
        r = [*map(float, value.split(","))]
        return queryset.filter(latest_size__range=r)

    class Meta:
        model = Object
        fields = {"name": ["icontains"],
                     "score": ["range"],
                     "created_at": ["range"],}
```

Is there any way to 'tell' django-filter to just treat my annotated `latest_obs_date` field as it would normally treat, say, a `FloatField` that needs to be filtered using a range?

I noticed #469 also but confess I did not follow it. I'd rather avoid playing with changing the models directly, if it can be helped. Since I am not following a single relation but rather `SubQuery`ing on a set, I didn't know if the `object__obs_size` style lookup could made to work, in any case.

Thanks, apologies if I've missed something or this is way off.

**Comment by rpkilby** [comment]
> Is it possible to have a FilterSet class automatically handle the default behaviour (widget creation, data handling etc.) for annotated fields? I see this is related to #393, which looks like the ideal scenario.

#393 certainly could be resurrected. However, I haven't because I'm not sure if it's a good idea. A model's fields are always present and can always be inspected. Annotations are only present on the queryset instance, and in order to function correctly, require that the provided queryset to have those annotated fields.

> I am able to implement my own custom filters within my FilterSet class, however in the method I find I am having to deal with converting the value and handling exceptions etc.

This would be preferred approach in my mind. I might even annotate the queryset within the filter method. The issue you're running into is that you're not using the correct range filter, which is why you have to massage the value. There are two parts to this.
- `RangeFilter` isn't type aware. You'd need to use something like `DateFromToRangeFilter`.
- The automatically generated `range` filters from `Meta.fields` are actually using the CSV-based range filter. You can read about it more in the filters API docs.

I kind of briefly whipped up this reply. Let me know if something isn't clear.

**Comment by Lyalpha** [comment]
OK thanks I think I've got it how I wanted it - posting below for completeness (and if you spot any errors!).

I have an existing `Meta.fields` filter similar to ``` "created_at" : ["range"],``` in my template, which renders as a single text box. I then use a daterangepicker to fill in a pair of dates in CSV-style in my locale, e.g.: `26/04/2018, 25/05/2018`.

I am now using a `DateFromToRangeFilter` with `CSVWidget` to try mimic this for my annotated date field. It is handling invalid dates etc. which is great. It however seems to return a slice object with the start and stop dates rather than a list or CSV string as I was expecting. I am thus doing this in my filter's `method`:
```
def filter_created_at(self, queryset, name, value):
       return queryset.filter(created_at__range=(value.start,value.stop))
```

This seems to be working well so far. Thanks for the pointers.
