### ISSUE TITLE
Single query params for all filters (JSON API compatible)

### ISSUE THREAD

**Issue by kacperix** [carltongibson/django-filter#913]
Is it possible to configure django-filter to search for filter values in single query parameter, e.g. `filter`. The url looks like the following: `http://example.com/resource?filter[field]=value&filter[field2]=value`.

If not by configuration, maybe you know some solution/workaround for this?

I'm trying to make filtering compatible with JSON API v1.0 Specification (http://jsonapi.org/format/#fetching-filtering)

**Comment by carltongibson** [comment]
Assuming you're using DRF, the FilterSet is normally instantiated with `request.query_params`. 

https://github.com/carltongibson/django-filter/blob/2b554a50d227999db9e537568af63c64a550f786/django_filters/rest_framework/backends.py#L53

In this case it looks like the dict you want will actually be `request.query_params["filter"]`
So overide, `filter_queryset` in the backend and adjust that.

**Comment by n2ygk** [comment]
@pciacka FYI this is recently implemented here: https://github.com/django-json-api/django-rest-framework-json-api/pull/466 and will be in a soon-to-be-forthcoming 2.6.0 release.

@carltongibson It occurs to me that you might want to keep track of [DJA](https://github.com/django-json-api/django-rest-framework-json-api/) and any other packages that extend DF in a manner similar to the [way DRF does](https://django-rest-framework.readthedocs.io/en/latest/topics/third-party-packages/). 

Perhaps you'd consider accepting a PR to add this functionality to django-filter proper? I'm a bit concerned about how deep into the DF guts [I had to go](https://github.com/django-json-api/django-rest-framework-json-api/tree/master/rest_framework_json_api/django_filters) to extend filter_queryset but understand that you might not want to carry extra baggage.
