### ISSUE TITLE
Modify ``self.form.cleaned_data`` before the queryset evaluates?

### ISSUE THREAD

**Issue by bukowa** [carltongibson/django-filter#916]
From my understanding of the API the ````form.is_valid()```` methods is called on the ````q```` property.
I want to modify the ````self.form.cleaned_data```` values before the queryset evaluates, but after the ````form.is_valid()```` method. I know this can be hacked on the form itself, but maybe theres a way / should be to do this on the ````FilterSet````?

**Comment by rpkilby** [comment]
> I want to modify the `self.form.cleaned_data` values before the queryset evaluates, but after the `form.is_valid()` method.

There are a few places you can override the behavior:

- `FilterSet.is_valid()`
- `FilterSet.filter_queryset()`
- A custom `Form` class

The relevant code:

https://github.com/carltongibson/django-filter/blob/2b554a50d227999db9e537568af63c64a550f786/django_filters/filterset.py#L159-L193

**Comment by rpkilby** [comment]
Ah, right. The latest 'stable' release is `1.1.0`. The referenced codes is from the `2.0.0.dev1` release. You can install it with `pip install --pre`

Either way, your best bet is to override the `Form` class's cleaning behavior, which is the same between both versions.

**Comment by bukowa** [comment]
@rpkilby Thank you, yes i already did the cleaning on the form class, but are there are any important changes to the API in the newest version? Can i find anywhere what did change and is important?

**Comment by bukowa** [comment]
@rpkilby thank you!
