### ISSUE TITLE
Not supplying a model in meta AND not supplying a label in the filter field produces an AttributeError

### ISSUE THREAD

**Issue by awgymer** [carltongibson/django-filter#926]
If you declare a `FilterSet` without a `Meta` class and `model` and do not supply a `label` option to your filters then it throws `AttributeError: 'NoneType' object has no attribute '_meta'` when calling `get_field_parts` to automatically generate a label. 

I may just be using django_filters badly/wrong but this behaviour and need to explicitly define a label in such a case doesn't seem to be documented anywhere that I can see.

**Comment by rpkilby** [comment]
Hi @awgymer. I believe that this may have already been fixed in `2.0.0.dev1`. Would you mind checking?

To install the pre-release, use `pip install -U --pre django-filter`

**Comment by awgymer** [comment]
Indeed, `2.0.0.dev1` does seem to have fixed the issue, once I managed to realise that the `name` parameter is now called `field_name`!

**Comment by rpkilby** [comment]
Thanks for verifying. I think this can be closed then. Development for the 1.x branch has ceased, and the issue has been fixed on the 2.x line.
