### ISSUE TITLE
Filter fields doesn't work on array with GraphQL

### ISSUE THREAD

**Issue by VinayakBagaria** [carltongibson/django-filter#927]
With Graphene, filter fields are specified on a Many-To-May field as <lookup_field>__In : which expects [ID]. See the image below for reference for `color`.

<img width="1275" alt="screen shot 2018-06-11 at 11 27 47 am" src="https://user-images.githubusercontent.com/17192467/41257210-a60092c6-6de9-11e8-9cb5-b8e554c5c1cd.png">

But this query doesn't execute. Here's the stack trace.

<img width="1280" alt="screen shot 2018-06-11 at 9 38 22 pm" src="https://user-images.githubusercontent.com/17192467/41257249-c9647be2-6de9-11e8-84f6-62977fd2b140.png">

Refer [this link](https://github.com/VinayakBagaria/Product-Filter/blob/graphql-django/products/schema.py#L20) for code.

**Comment by rpkilby** [comment]
Hi @VinayakBagaria. This is an issue in django-graphene (see: https://github.com/graphql-python/graphene-django/issues/190). 

In short, django-filter expects a comma separate string value, not a list of individual values. 
Change `color_In: ["Q2hvaWNlTm9kZTox"]` to `color_In: "Q2hvaWNlTm9kZTox"`. 
Or more generally, `field_In: ["a", "b"]` to `field_In: "a,b"`.

**Comment by VinayakBagaria** [comment]
@rpkilby  Doesn't work when then. Throws the same error.  ![](https://i.imgur.com/VTMhAyj.png)

**Comment by rpkilby** [comment]
@VinayakBagaria. It's possible that the implementation has changed, and the solution in https://github.com/graphql-python/graphene-django/issues/190 is outdated. My guess would be that graphene-django is coercing the string to a list containing the string. Regardless. django-filter expects to parse a string, not a list of strings. The root issue lies with graphene-django.

**Comment by VinayakBagaria** [comment]
Yeah.. printed the value of the field in console to see that an array is passed. Thanks for the reference here. :blush:
