### ISSUE TITLE
filter with method, is getting null as a value

### ISSUE THREAD

**Issue by jerzyk** [carltongibson/django-filter#932]
I have a UserFilter:
```
class UserFilter(filterset.FilterSet):
    full_name = filters.CharFilter(method='filter_full_name', lookup_expr=['exact', 'iexact])

    def filter_full_name(self, query, field, name):
        return query
```

calling url?full_name=usr

is calling a filter method, with field parameter containg field name, and name containg a value:
Lookup(value=None, lookup_type='exact')

this is happening because this field is being replaced by LookupTypeField, then added as such to the validation form... and LookupTypeField is expecting 2 variables full_name_0 & full_name_1 but those are not in the .data - nowhere in the code there is a magic sentence, where full_name will be renamed to full_name_0 with value that was passed from request and full_name_1 with value 'exact'

**Comment by rpkilby** [comment]
The `lookup_expr=[...]` behavior is partially described in the docs [here](http://django-filter.readthedocs.io/en/1.1.0/ref/filters.html#lookup-expr). To enable the ability to select the lookup expression from a select, the filter has to use Django's `MultiWidget`. The `_0` and `_1` suffixes are an implementation detail of that widget.

That said, what exactly are you trying to do?

Also worth noting, I created #851 to disable the implicit lookup types feature, instead opting for an explicit `LookupChoiceFilter` that users need to declare.

**Comment by jerzyk** [comment]
I just want to have a method, where I can build my query without reinventing the wheel - in this case, I would like to build a query to do some more advanced search - sentence matching (without going much to the details) - I would expect in sucha case that I'll get field name and value or Value instance as method input, not Value(null)

**Comment by rpkilby** [comment]
To be more direct, what are you expecting to do with the list of `lookup_expr`? Did you intend to give users the ability to select which `lookup_expr` is used, or were you expecting a different behavior there?

**Comment by carltongibson** [comment]
This is expected behaviour. It's now superseded with the changes in #851 introducing `LookupChoiceFilter`. 

I'd suggest updating to 2.0 and reviewing the situation. Happy to consider concrete suggestions from there.
