### ISSUE TITLE
provide validation of whole FilterSet

### ISSUE THREAD

**Issue by backbohne** [carltongibson/django-filter#939]
I have a more complex filerset with field dependencies like:

```
if field1 == 1 and field2 == 2:
    raise ValidationError('combination not possible')
```
Would it been possible to implement a way to validate all filterset fields together?

Regards
Frank

**Comment by carltongibson** [comment]
Specify a form class and [validate the multi-field dependencies in the normal way](https://docs.djangoproject.com/en/2.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other).
