### ISSUE TITLE
More informative warning needed at django_filters/rest_framework/backends.py:93

### ISSUE THREAD

**Issue by estianross** [carltongibson/django-filter#940]
Current warning is simply "{} is not compatible with schema generation".format(view.__class__) while the actual reason for this error is a missing get_queryset() on the appropriate view. Please update this message to be actually informative of the issue.

**Comment by carltongibson** [comment]
Duplicate of #903

**Comment by blueyed** [comment]
@estianross 
Maybe you have some input for https://github.com/carltongibson/django-filter/issues/966 - what is your reason for the exceptions there?  (please follow up in #966).
