### ISSUE TITLE
Invalid syntax error when importing Filterset

### ISSUE THREAD

**Issue by lalzada** [carltongibson/django-filter#942]
```
from .filterset import FilterSet
```

```
File "/python2.7/site-packages/django_filters/filterset.py", line 141
    def __init__(self, data=None, queryset=None, *, request=None, prefix=None):
                                                  ^
SyntaxError: invalid syntax
```

Python 2.7
Django 1.11
django-filter (latest master)

**Comment by lalzada** [comment]
If you need to support Python 2.7 or Django <1.11 use the version 1.1 release.

**Comment by rvernica** [comment]
The metadata for the `2.*` packages should enforce Python `>= 3`. I think should be reopened.

**Comment by rpkilby** [comment]
Hi @rvernica. This has been fixed, just not released. See #953.
