### ISSUE TITLE
Docs out of date (name => field_name)

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#945]
I'm sure a few other API changes have been forgotten.

**Comment by rpkilby** [comment]
https://django-filter.readthedocs.io/en/master/guide/tips.html#filter-name-and-lookup-expr-not-configured

**Comment by carltongibson** [comment]
Hey @rpkilby. Yes quite likely. Happy to take quick fixes for anything you spot here.

**Comment by rpkilby** [comment]
Yep - I'm currently working on/reviewing the docs.

**Comment by carltongibson** [comment]
Right. I did a quick patch up of field name. More importantly I’ve got rtd set up again to build master from the webhook, so if you can have a quick look we can hit the 80:20 straight away. 

Good catch. Thank you!

**Comment by carltongibson** [comment]
I’ll close this as is following #946. No doubt other issues will crop up.
