### ISSUE TITLE
ViewSet.filterset_fields recreates filterset per-request

### ISSUE THREAD

**Issue by rpkilby** [carltongibson/django-filter#947]
This is fairly low priority, but I noticed that the backend `AutoFilterSet` generated for `filterset_fields` is regenerated per-request, which is a bit of a performance hit as you're having to create the filters twice per request instead of once (once for class creation, once for `deepcopy` during initialization). Regular filterset classed only incur the class creation cost on process startup. A few options:

1. Document the issue, although a lot of existing users likely won't be aware of the issue (they'd have to reread the backend/DRF integration docs).
2. Deprecate `filterset_fields` in favor of `filterset_class`. If users don't want to define the filterset elsewhere, they could just..
    ```python
    class MyViewSet:
        class MyFilterSet:
            class Meta:
                ...
        filterset_class = MyFilterSet

    # or even
    class MyViewSet:
        class filterset_class:
            class Meta:
                ...
    ```
3. Set the generated `AutoFilterSet` on the viewset class on the first request. Unless the user is doing something crazy, like making `filterset_fields` a property and dynamically returning differing sets of fields per-request, then this shouldn't be an issue.

I'd opt for either the second, but probably the third option. Thoughts?

**Comment by carltongibson** [comment]
My first thought is to document this, simply stat No the performance characteristics and stating “prefer defining the class”. 

(That’s the way the wind blows anyway right: always towards the explicit definition.)

**Comment by carltongibson** [comment]
I don't really think this is an active issue. Happy to look a PR on the docs, but not sure it's worth it.
