### ISSUE TITLE
No results without Get parameters since 2.0

### ISSUE THREAD

**Issue by lggwettmann** [carltongibson/django-filter#957]
When a user used to go to http://localhost:8000/courses/, he would see the full and unfiltered query set. Just updated to 2.0 and since then, the result query set is empty if there are not get-parameters.
If there are get parameters (e.g. http://localhost:8000/courses/?show_past=on), then the filtered query set is shown.

I didn't read anything about that in the migration guide - is this a bug or a new default behavior? How can I show the full unfiltered query set again?

Thanks for your help.

**Comment by rpkilby** [comment]
The behavior shouldn't have changed. Can you provide a more concrete test case?

**Comment by carltongibson** [comment]
@lggwettmann Can you create a test case that fails on 2.0 and passes on 1.1? If so we can bisect the change and work out what altered.

**Comment by carltongibson** [comment]
Duplicate of #930
