### ISSUE TITLE
Code to clean values for a BooleanFilter is inappropriate 

### ISSUE THREAD

**Issue by jsbueno** [carltongibson/django-filter#959]
django_filter use django-forms to clean the passed in values before actually filtering. However, the code inside django-forms for cleaning up boolean values from whatver was passed in an API call is bound to hardcoded values in the HTML widget, and has nothing to do with actual boolean-meaning values one would pass in an API call.

More objectively, `django_filters.filters.BooleanFilters`  uses `django.forms.NullBooleanField`, which in turn uses the code from `django.forms.widgets.NullBoleanSelect` which in turn has _this_ code to clean up the passed in value:

```
    def value_from_datadict(self, data, files, name):
        value = data.get(name)
        return {
            '2': True,
            True: True,
            'True': True,
            '3': False,
            'False': False,
            False: False,
        }.get(value)
```

 ( https://github.com/django/django/blob/2.1/django/forms/widgets.py#L711 )

**Comment by jsbueno** [comment]
Something along:
```

    def value_from_datadict(self, data, files, name):
        value = data.get(name)
        if value in (True, 'True', 'true', 1, '1'):
            return True
        if value in (False, 'False', 'false', 0, '0'):
            return False
        if value in (None, 'None', 'none', 'null'):
            return None
        raise exceptions.ValidationError("Invalid Bool value '{}'".format(value))
```

would be more sane - but unfortunately, one can't  just add this method there but for monkeypatching, as intermediary `Filter`, `Field` and `Widget` classes have to be in place for the alternate method to be called.

**Comment by carltongibson** [comment]
We provide a BooleanWidget for this. 

https://github.com/carltongibson/django-filter/blob/99ced9ce401f8e08f4ee89a4e1246253640e5b2f/django_filters/widgets.py#L176-L188

If you use the `django_filters.rest_framework.FilterSet`  (as per the [Integrating with DRF docs](https://django-filter.readthedocs.io/en/master/guide/rest_framework.html#integration-with-drf) this will be used automatically. Otherwise you can specify your widget as per normal.
