### ISSUE TITLE
On field ordering

### ISSUE THREAD

**Issue by jomsdev** [carltongibson/django-filter#964]
Since django 1.9 Forms had a [new field](https://docs.djangoproject.com/en/2.1/ref/forms/api/#django.forms.Form.field_order) `field_order` used for determining in which order fields are displayed when `.as_p()`, `.as_ul()` and `.as_table() ` are called in a template.

The `FilterSet` class doesn't seem to allow you override the order in which [fields are displayed](https://github.com/carltongibson/django-filter/blob/master/django_filters/filterset.py#L248).

A possible workaround is using an `OrderedDict` when declaring `fields`
```python
# No control about ordering
class MyClassFilter(django_filters.FilterSet):
    class Meta:
        model = MyClass
        fields = [
            'field_one': ['exact']
            'field_two': ['lt','gt']
            ...
        ]
# Custom Order
class MyClassFilter(django_filters.FilterSet):
    class Meta:
        model = MyClass
        fields = OrderedDict((
            ('field_one', ['exact']), 
            ('field_two', ['lt','gt']),
            ...
            ) )
        ]
```

I think that would be great if django-filter followed the same style as Django Forms and let the user declare `field_order`.

Are PR welcomed :)?

**Comment by jmstp** [comment]
It did, but it was kind of hack (I looked to the code to see how it is implemented and then take advantage of how it is implemented "under the hood") However, my first try was using `field_order` and I was surprise that it did not work.

If other people are happy about using the workaround and you don't see any value changing there is no problem. Just opened the issue because of my own experience

**Comment by jomsdev** [comment]
It did, but it was kind of hack (I looked to the code to see how it is implemented and then take advantage of how it is implemented "under the hood") However, my first try was using `field_order` and I was surprise that it did not work.

If other people are happy about using the workaround and you don't see any value changing there is no problem. Just opened the issue because of my own experience

**Comment by jomsdev** [comment]
Let's leave it.  We can "fix" it if more people complain or need the feature
