### ISSUE TITLE
UserWarning: X is not compatible with schema generation: due to AnonymousUser

### ISSUE THREAD

**Issue by blueyed** [carltongibson/django-filter#966]
I am looking at the UserWarnings I've tried to enhance in https://github.com/carltongibson/django-filter/pull/903 again:

```
…/django-filter/django_filters/rest_framework/backends.py:131: UserWarning: <class 'project.app.views.TermsOfServiceViewSet'> is not compatible with schema generation
  "{} is not compatible with schema generation".format(view.__class__)
```

Those happen mostly because an AnonymousUser is used, which is not compatible with most of our view's `get_queryset()` methods, which assume that the user is authenticated (and has certain methods in particular).

I am using drf_yasg here.

I wonder if there is a way to improve this, e.g. by using an authenticated user for it (would be a drf-yasg issue then probably).

Traceback:

```
../../../Vcs/django-rest-framework/rest_framework/views.py:480: in dispatch
    response = handler(request, *args, **kwargs)
.venv/lib/python3.6/site-packages/drf_yasg/views.py:85: in get
    schema = generator.get_schema(request, self.public)
.venv/lib/python3.6/site-packages/drf_yasg/generators.py:215: in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
.venv/lib/python3.6/site-packages/drf_yasg/generators.py:337: in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
.venv/lib/python3.6/site-packages/drf_yasg/generators.py:379: in get_operation
    operation = view_inspector.get_operation(operation_keys)
.venv/lib/python3.6/site-packages/drf_yasg/inspectors/view.py:30: in get_operation
    query = self.get_query_parameters()
.venv/lib/python3.6/site-packages/drf_yasg/inspectors/view.py:293: in get_query_parameters
    natural_parameters = self.get_filter_parameters() + self.get_pagination_parameters()
.venv/lib/python3.6/site-packages/drf_yasg/inspectors/base.py:336: in get_filter_parameters
    fields += self.probe_inspectors(self.filter_inspectors, 'get_filter_parameters', filter_backend()) or []
.venv/lib/python3.6/site-packages/drf_yasg/inspectors/base.py:71: in probe_inspectors
    result = method(obj, **kwargs)
.venv/lib/python3.6/site-packages/drf_yasg/inspectors/query.py:27: in get_filter_parameters
    fields = filter_backend.get_schema_fields(self.view)
../../../Vcs/django-filter/django_filters/rest_framework/backends.py:131: in get_schema_fields
    "{} is not compatible with schema generation".format(view.__class__)
E   UserWarning: <class 'project.app.views.AffiliationViewSet'> is not compatible with schema generation
```

**Comment by carltongibson** [comment]
Not much we can do **here**. Any method needing to call `get_queryset()` is going to run into this. You basically need to allow that to handle the anonymous case. 

Either way the issue is better addressed as part of DRF's introspection logic. (But there's not a simple answer there yet either.)

**Comment by gunthercox** [comment]
One possible workaround might be to define something like this in the `get_queryset` method of your viewset. Handling the case where `self.request` is `None` seems to do the trick.

```
def get_queryset(self):
    if self.request is None:
        return SomeModel.objects.none()

    return SomeModel.objects.filter(...)
```

**Comment by aaronstephenson** [comment]
Thanks @gunthercox your comment really helped me out. It put me on the path to the solution, but ultimately what worked for me was this:

```
queryset = MyModel.objects.all()

def get_queryset(self):
    if not self.request:
        return MyModel.objects.none()

    if self.request.query_params:
        queryset = self.filter_queryset(self.queryset)
    else:
        queryset = self.queryset

    # ... the rest of the method code ...

    return queryset
```

Hope this helps someone else in a similar situation.

**Comment by ruhan** [comment]
I think that the suggested approach is this one:

```python
def get_queryset(self):
    if getattr(self, "swagger_fake_view", False):
        return Service.objects.none()

    # .... your normal code!
```

I've seen that in this thread: https://github.com/axnsan12/drf-yasg/issues/333

**Comment by nurmukhammaddev** [comment]
def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return Event.objects.none()
        return Event.objects.exclude(slug=self.kwargs["slug"])
        
        
        
     Solved

**Comment by KonstantinosPetrakis** [comment]
I wrote a decorator so DRY principle is followed when using this fix:

```python
from django.db.models import QuerySet


def django_filter_warning(get_queryset_func):
    """
    This decorator is used to fix a warning in django-filter.
    See: https://github.com/carltongibson/django-filter/issues/966
    """

    def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return QuerySet()
        return get_queryset_func(self)

    return get_queryset

class MyCoolView:
    ...
    @django_filter_warning
    def get_queryset(self):
        """
        Returns reports that belong to the current user.
        """

        return self.request.user.reports.all()
```

**Comment by nurmukhammaddev** [comment]
The warning message you've provided appears to be related to some software or code, but it's not specific enough to provide a detailed explanation without additional context. However, I can offer some general insights into what this warning might mean and how to address it.

Context Matters: To better understand the warning, you need to provide more context about the software or code in which this warning is being generated. Knowing the programming language, libraries, and the context in which this message appears can be helpful.

AnonymousUser: The warning message mentions "AnonymousUser." This could be a reference to a user or an object with an anonymous or unspecified identity. It's possible that there is a mismatch or compatibility issue between the data (X) and the schema or requirements of the code or library.

Compatibility Issue: The warning suggests that there is an issue with the compatibility of the data (X) with some schema generation process. This could mean that the data you are using does not conform to the expected format or structure required by the code or library.

Possible Solutions:

Review the code or library documentation: Look for information on how the data should be structured and what requirements need to be met.
Check the data: Ensure that the data you are passing (X) adheres to the expected format and structure.
Debugging: Use debugging tools to trace the source of the warning. Check the code where this warning is generated to understand the specific conditions that trigger it.
Seek help: If you are working with a specific library or framework, consider seeking help on relevant forums, communities, or from colleagues who may have experience with the same issue.
Update Dependencies: Sometimes, updating the software dependencies, libraries, or packages you are using can resolve compatibility issues. If this warning is related to a library, check if there are newer versions available that might have addressed this problem.

To provide more specific guidance, I would need additional information about the context in which this warning is occurring and the relevant code or software involved.
