### ISSUE TITLE
DRF integration does not work for extra viewset actions

### ISSUE THREAD

**Issue by estianross** [carltongibson/django-filter#967]
I have multiple list actions in a single viewset by making use of the @action decorator as described [here](http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing) and have included a FilterSet via filter_class as specified in docs [here](https://django-filter.readthedocs.io/en/master/guide/rest_framework.html#adding-a-filterset-with-filterset-class). The filters are only being applied to the default ViewSet List and Retrieve actions and not any of the custom List or Retrieve actions which is where we actually need the filters.

**Comment by carltongibson** [comment]
Hi @estianross. You need to provide more details if we're going to be able to comment. 

Are you sure your extra actions are calling [`filter_queryset()`](http://www.django-rest-framework.org/api-guide/generic-views/#filter_querysetself-queryset)?

**Comment by estianross** [comment]
They do but I'm fairly sure I'm not using it the way it should be used if that's where the issue is, I've included a simple sample action below to show the basics of what I'm doing in these actions
```
@action(methods=['GET'], detail=False)
def simplelist(self, request, *args, **kwargs):
    serializer = SpecializedModelListSerializer(self.filter_queryset(self.get_queryset()), many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
```

**Comment by carltongibson** [comment]
I suggest you create an [APITestCase](http://www.django-rest-framework.org/api-guide/testing/#example) and plug the url + query parameters you're expecting into it. You'll then be able to make assertions and insert breakpoints as needed to see where things are going wrong for you. 

(I'm afraid that without much more detail it's impossible to be able to advise at all.)

**Comment by estianross** [comment]
I got it working by simply moving the call as follows
```
@action(methods=['GET'], detail=False)
def simplelist(self, request, *args, **kwargs):
    qs = self.filter_queryset(self.get_queryset())
    serializer = SpecializedModelListSerializer(qs, many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)
```
Thanks for the help!!!

**Comment by LyleScott** [comment]
This does not seem to work in most of my cases.

**Comment by felipelerena** [comment]
I think this issue should be reopened. I have the same problem and the proposed solution worked for me.

**Comment by nabeeltariqbhatti** [comment]
@action(methods=['get'], detail=True, url_path='retrieve_by_card_no/(<int:CardNo>)')
    def getByCarNo(self, request, CardNo):
        user = get_object_or_404(employe_model, EmpCardNo=CardNo)
        return Response(serializers.EmployeeInfoSerializer(user).data, status=status.HTTP_200_OK)



I want to search employee by his card no instead of employee id

anyone can help me?

**Comment by Mohammed-Sunasra** [comment]
I think the filter integration works correctly if you pass the query params along with your action in the URL. Below was the action that I had 
```
@action(methods=['GET'], detail=False)
def export(self, request): 
    queryset = self.get_queryset()
    filtered_queryset = self.filter_queryset(queryset)
```

When trying to call the export action from DRF browsable API, the request that was getting sent was
 **/api/viewname/export/** instead it should called like 
**/api/viewname/export/?query_param_1=value1&?query_param_2=value2**

Passing the query params along with the action will call the filterset class and hence you will get a filtered queryset in filtered_queryset variable

**Comment by nabeeltariqbhatti** [comment]
Thank you so much I figured it out
