### ISSUE TITLE
OR statement with ModelMultipleChoiceFilter (M2M relationship)

### ISSUE THREAD

**Issue by Amoki** [carltongibson/django-filter#969]
Hi !
I want to be able to filter with an OR statement. I found multiple resources which explain how to achieve that. Unfortunately, they are many years old and I can't make them work. (https://github.com/carltongibson/django-filter/issues/137 in particular)

```python
class Subject(models.Model):
    name = models.CharField(max_length=255)


class Topic(models.Model):
   subjects = models.ManyToManyField('Subject')
   title = models.CharField(max_length=255)

class TopicFilter(django_filters.FilterSet):
    subjects = django_filters.ModelMultipleChoiceFilter(
        field_name="subjects",
        queryset=Subject.objects.all(),
    )

    class Meta:
        model = Topic
        fields = ["subjects"]

class TopicSerializer(serializers.ModelSerializer):
    class Meta:
        model = Topic
        fields = ("title",)

class TopicsViewSet(viewsets.ModelViewSet):
    serializer_class = TopicSerializer
    queryset = Topic.objects.all()
    filterset_class = TopicFilter
```
I tried with `?subjects=1&subjects=2`, `?subjects=1,2`, tried to play with the `CSVWidget`, without success :cry:. I can make it work with MultipleChoiceFilter (without model relation)

I'm using django 2.1 and django_filters 2.0

**Comment by Amoki** [comment]
My bad, a subtle typo in my code AND in my tests lied to me. Feels like the establishment lying to me :(

**Comment by carltongibson** [comment]
Glad you got it sorted @Amoki.
