### ISSUE TITLE
Ability to provide schema.format and schema.pattern

### ISSUE THREAD

**Issue by danizen** [carltongibson/django-filter#975]
`coreschemas.schemas.String` supports now `format` and `pattern` attributes to allow generation of swagger specifications.   However, django-filter provides no way to implement those without compromising other features.   My current work-around is as follows:

```python
class EnhancedDjangoFilterBackend(filters.DjangoFilterBackend):
    """
    Enhance DjangoFilterBackend to allow filters to provide the format and the pattern to the schema,
    Note that this breaks the ability to instantiate the filterset in the Browseable API, because
    the form type will not understand the attributes "format" and "schema".
    """
    def get_coreschema_field(self, field):
        schema = super().get_coreschema_field(field)
        schema.format = field.extra.get('format', None)
        schema.pattern = field.extra.get('pattern', None)
        return schema
```

The problem with this method is that it makes the application harder to maintain for several reasons:
* Custom filter backend tied to your implementation.
* No ability to switch to the Browsable API if that is desirable.
* No ability to use DRF standard docs generator if that is desirable.
* No ability to use the same filterset class for both a non DRF view and a DRF viewset, e.g. migration is compromised.

My proposal is that `django_filter.filters.Filter` be enhanced to take a `schema` parameter which becomes directly an attribute on the Filter.  `django_filter.rest_framework.backends.DjangoFilterBackend` be enhanced to look for that schema attribute, and generate the schema only if that schema attribute is false, e.g. something like:

```python
    def get_coreschema_field(self, field):
        if field.schema:
            return field.schema
        if isinstance(field, filters.NumberFilter):
            field_cls = compat.coreschema.Number
        else:
            field_cls = compat.coreschema.String
        return field_cls(
            description=str(field.extra.get('help_text', ''))
        )
```

I do not presently have time to implement a pull request, but I may in time.    If you can tell me what else needs to be done - e.g. generation of filterset from other DRF viewset and view attributes, then I may take it on when I have more time.

**Comment by rpkilby** [comment]
Hi @danizen. #819 sounds like it would have at least partially solved this. For now, the PR is on hold, since the next version of coreapi will likely have some significant changes.

**Comment by danizen** [comment]
@rpkilby, I discovered my work-around works only when generating the schema.  The form is still instantiated when I visit the view, but the filterset itself is not instantiated when `drf_yasg` generates the schema.  This may not be the case for the other DRF enhancement libraries that generate a schema.

Here's my inelegant work-around, which works so far.

```python
class SwaggerFilterSet(filters.FilterSet):
    """
    A filterset that removes "format" and "pattern" from filter.extra for actual use.
    The form is not created to introspect the schema below.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, filter in self.filters.items():
            filter.extra.pop('format', None)
            filter.extra.pop('pattern', None)


class EnhancedDjangoFilterBackend(filters.DjangoFilterBackend):
    """
    A DjangoFilterBackend sub-class that allow filters to provide the format and the pattern to the schema.
    This only works properly if the filterset is a SwaggerFilterSet
    """
    def get_coreschema_field(self, field):
        schema = super().get_coreschema_field(field)
        schema.format = field.extra.get('format', None)
        schema.pattern = field.extra.get('pattern', None)
        return schema
```

**Comment by danizen** [comment]
@rpkilby , Can you point me towards the upcoming coreapi/coreschema changes?  Thanks.

**Comment by rpkilby** [comment]
I haven't followed it closely, but it looks like coreapi/coreschema are going to be removed/replaced.

**Comment by carltongibson** [comment]
Yep. DRF 3.9 will support (default even) to OpenAPI directly. What we do here (for a v2.1) will reflect that. Can't say more just yet. ("`[WIP]`" — it's coming.)

**Comment by carltongibson** [comment]
I'm going to close this as is. Enhancing CoreAPI is a dead-end at this point.
