### ISSUE TITLE
Feature request: automatic filter negation/exclusion

### ISSUE THREAD

**Issue by aidanlister** [carltongibson/django-filter#978]
This package supersedes django-rest-framework-filters, but django-rest-framework-filters had a great feature that allows you to do foo!=bar automatically (changes from a filter to an exclude). 

https://github.com/philipn/django-rest-framework-filters#automatic-filter-negationexclusion
https://github.com/philipn/django-rest-framework-filters/pull/43/files

This is a nice saving, all of our filtersets look like this:

```
    text_contains = SearchFilter(fields=['property__name', 'property__client_ref', 'compliancetype__name'], comparison='contains')
    text_excludes = SearchFilter(fields=['property__name', 'property__client_ref', 'compliancetype__name'], comparison='excludes')
    ref_contains = SearchFilter(fields=['property__client_ref'], comparison='contains')
    ref_excludes = SearchFilter(fields=['property__client_ref'], comparison='excludes')
    property_contains = SearchFilter(fields=['property__name'], comparison='contains')
    property_excludes = SearchFilter(fields=['property__name'], comparison='excludes')
    category_contains = SearchFilter(fields=['compliancetype__name'], comparison='contains')
    category_excludes = SearchFilter(fields=['compliancetype__name'], comparison='excludes')
```

Would you accept a PR that included this functionality?

**Comment by zkne** [comment]
This feature is much needed!

**Comment by carltongibson** [comment]
I have no real desire to expand the API of django-filter. (I'm not in favour of automatically extending the filters available: these drive your database, you want to control them.) 

However, as I understand it, django-rest-framework-filters just builds on django-filter, so if you like its features, why not just use it? 

@rpkilby What is the state of play here? (Thanks!)

**Comment by carltongibson** [comment]
Also, looking at the diff from the linked PR there, isn't a `FilterSet` subclass (or decorating class) available without too much effort?

**Comment by rpkilby** [comment]
> What is the state of play here?

It's a little complicated. Automatic negation works for most cases, however it runs into issues with multi-valued relationships (see: https://github.com/philipn/django-rest-framework-filters/issues/217). But in general, django-filter doesn't really handling to-many relationships well (#745, #1077), so maybe it should be considered out-of-scope, punting to drf-filters?

----

> I have no real desire to expand the API of django-filter. 

I would agree against expanding the API of the base `FilterSet`. Automatic negation is a somewhat "magical" feature, and if django-filter were to support it, it should exist as a mixin.

**Comment by carltongibson** [comment]
Okay, thanks @rpkilby. I’m going to close. Don’t mind seeing examples from users but not ready to include, even as a mixin, at this point.
