### ISSUE TITLE
DeprecationWarning on python 3.7

### ISSUE THREAD

**Issue by therefromhere** [carltongibson/django-filter#988]
```
django_filters/widgets.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

see potential fix here: https://github.com/pyparsing/pyparsing/pull/16/files

**Comment by therefromhere** [comment]
Actually since Python 2 support was dropped the fix can be simpler.

**Comment by neostimul** [comment]
warnings.warn("Using or importing the ABCs from 'collections' instead "
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
