### ISSUE TITLE
Limiting/cutoff model choices with DRF

### ISSUE THREAD

**Issue by rrauenza** [carltongibson/django-filter#992]
I have a 'through' model (used for Many to Many) I'm making a DRF endpoint for and I need to be able to filter on the two foreign keys.

When I add the filterset to the DRF view, the API Render of the endpoint in DRF takes a really really long time to render because it is adding all the possible choices to DRF Filter UI's choices field.   I'd like to be able to limit the number of choices (or force it to be just a text box, with no suggested choices for the foreign key.)

Is this possible?

Using django-filter 1.x because Python 2.x :(

**Comment by rpkilby** [comment]
Hi @rrauenza. The model choice fields accept a `queryset` callable that can be used  to limit the choices dynamically. Here are the [guide](https://django-filter.readthedocs.io/en/master/guide/usage.html#filtering-the-related-queryset-for-modelchoicefilter) and [reference](https://django-filter.readthedocs.io/en/master/ref/filters.html#modelchoicefilter) docs for the `queryset` argument.

If you want to go the forms route, they can be customized in two ways:
1. Passing a custom form class to the `Meta.form` option.
2. Passing extra form field arguments to the filter field declaration. For example,

    ```python
    class MyFilterSet(django_filters.FilterSet):
        my_field = django_filters.ChoiceFilter(widget=forms.TextInput)
    ```

    Here, the `widget` argument is not recognized by the filter init, so it is collected in an `extra` arguments dict that is used to initialize its underlying form field.

**Comment by rrauenza** [comment]
Thanks!  I was looking through the code and was about to derive from ModelChoice{Filter,Field} ... I'll try your suggestions tomorrow.

It wasn't clear if limiting the queryset might also limit the *actual* query performed... I've been reading through the code and am still concerned that passing queryset=Foo.objects.all()[0:1000] might also limit results.

**Comment by rrauenza** [comment]
Thank you -- for now I'm using your recommendation of overriding the widget and it works great.  

My use case for the API view is just for discovery / documentation.
